force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>Defines the user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Look up to Account record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Edition Mappings (Account)</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/CC_Status__c.field-meta.xml
<CustomField>
    <fullName>CC_Status__c</fullName>
    <description>Formula field, fetches value from Edition Customer Center status</description>
    <formula>TEXT(Edition__r.Customer_Center_Status__c)</formula>
    <label>CC Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Look up to Contact record</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Not a Customer Center Contact.</errorMessage>
        <filterItems>
            <field>Contact.IOM_Contact_Identifier__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <description>Defines status of account contact relationship</description>
    <label>Relationship Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Director__c.field-meta.xml
<CustomField>
    <fullName>Edition_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Lookup Field store the id of the Edition Director.</description>
    <label>Edition Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Expocad_Event_Code__c.field-meta.xml
<CustomField>
    <fullName>Expocad_Event_Code__c</fullName>
    <description>contains expocad event code which will be used in formula Floorplan url</description>
    <label>Expocad Event Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Edition_Popup__c/Edition_Popup__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Edition. Used to define the Popup properties for a particular Event.</description>
    <label>Edition Popup</label>
    <nameField>
        <displayFormat>EPN-{00000}</displayFormat>
        <label>Edition Popup Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Edition Popups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition_Popup__c/fields/Booth_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Booth_Product_Type__c</fullName>
    <description>Booth Product type are picklist values displayed from global picklist value set of Booth Product Type.</description>
    <label>Booth/Product Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Booth_Product_Type1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition_Popup__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Each Edition can have many Edition Popups. This field helps to select the related Edition for a Pop up.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Edition Popups</relationshipLabel>
    <relationshipName>Edition_Popups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition_Popup__c/fields/Is_Visible__c.field-meta.xml
<CustomField>
    <fullName>Is_Visible__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field helps to control the pop up visibility for the community user by operations admin.</description>
    <label>Is Visible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Edition_Popup__c/fields/Pop_Up_Text__c.field-meta.xml
<CustomField>
    <fullName>Pop_Up_Text__c</fullName>
    <description>This is a rich text area field to store the pop up text to be displayed on pop up on community portal.</description>
    <label>Pop Up Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Edition_Popup__c/fields/Reset_Pop_up_Preferences__c.field-meta.xml
<CustomField>
    <fullName>Reset_Pop_up_Preferences__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To reset the pop up preferences set by a user when there are any changes done in popup by operations admin.</description>
    <inlineHelpText>To reset the pop up preferences set by a user when there are any changes done in popup by operations admin.</inlineHelpText>
    <label>Reset Pop up Preferences</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/Purchase_Data__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It is the transactional information regarding the booth/product purchased.</description>
    <label>Purchase Data</label>
    <nameField>
        <displayFormat>PD-{000000000}</displayFormat>
        <label>Purchase Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Account Record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Booth_Number__c.field-meta.xml
<CustomField>
    <fullName>Booth_Number__c</fullName>
    <description>Booth number Purchased by the Exhibitor</description>
    <label>Booth Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Booth_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Booth_Product_Type__c</fullName>
    <description>Booth Product type are picklist values displayed from global picklist value set of Booth Product Type.</description>
    <label>Booth/Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Booth_Product_Type1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Contact Record</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact Edition mapping</description>
    <label>Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Edition Record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Exhibiting_Name__c.field-meta.xml
<CustomField>
    <fullName>Exhibiting_Name__c</fullName>
    <label>Exhibiting Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Purchase_Status__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Status__c</fullName>
    <description>Lists the purchase status like Active, Inactive</description>
    <label>Purchase Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Quantity_Area__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Area__c</fullName>
    <description>Defines the value of quantity/Area for Product/Booth.</description>
    <label>Quantity/Area</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <description>Defines Transaction status like Active, Inactive</description>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Unit_of_Measurement__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measurement__c</fullName>
    <label>Unit of Measurement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>m</fullName>
                <default>true</default>
                <label>Meter</label>
            </value>
            <value>
                <fullName>ft</fullName>
                <label>Feet</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <description>Defines user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tab_User_Type__c/Tab_User_Type__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will give info on tab will be visible to which user type.</description>
    <label>Tab User Type</label>
    <nameField>
        <displayFormat>UT-{00000}</displayFormat>
        <label>Tab User Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tab User Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tab_User_Type__c/fields/Edition_Popup__c.field-meta.xml
<CustomField>
    <fullName>Edition_Popup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition Popup objects stores the data of the popup to be shown in Community Portal based on User Type.</description>
    <label>Edition Popup</label>
    <referenceTo>Edition_Popup__c</referenceTo>
    <relationshipLabel>Tab User Types</relationshipLabel>
    <relationshipName>Tab_User_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tab_User_Type__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <description>Defines user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/IMCC_GreetingPopup.cls
/*
Created By    : Aishwarya[IMCC-13]
Test Class    : IMCC_GreetingPopup_Test()
Created/Modified By   :  11/10/2021
@description  : The purpose of this class is to populate Greeting popup and error popup on cummuity pages.
Modified By : Shiv Raghav (Ticket No - IMCC-2815 )
@description : Added null check as part of IMCC-2815 ticket
*/
public without sharing class IMCC_GreetingPopup 
{
    /**
    * @description : Get PopUp details on Cummunity pages. 
    * @param eventCode
    * @param accountId
    * @return : WrapperPopupDetail
    **/
    @AuraEnabled(cacheable = false)
    public static WrapperPopupDetail fetchPopupDetails(String eventCode, String accountId) 
    {
        WrapperPopupDetail popupDetails = new WrapperPopupDetail();

        try{
        
        //User u = [SELECT Id,Name,ContactId FROM User WHERE Id =: UserInfo.getUserId() WITH SECURITY_ENFORCED];
        Map<String,Object> mapCEMDetails = IMCC_UtilityMethods.getContactEditionMappings(eventCode, accountId);
        
        List<Contact_Edition_Mapping__c> conEdMapLst = (List<Contact_Edition_Mapping__c>)mapCEMDetails.get('cemList');
        Set<Id> cemIds = (Set<Id>)mapCEMDetails.get('cemIds');

        if(!conEdMapLst.isEmpty()){
            popupDetails.CEM = conEdMapLst[0];
        }
        
        Set<String> setProductTypes = new Set<String>();
        String slist = '';
        String boothProductType = '';
        List<Purchase_Data__c> listPurchaseData = [SELECT Id, Booth_Product_Type__c FROM Purchase_Data__c
         WHERE Contact_Edition_Mapping__c IN:cemIds  WITH SECURITY_ENFORCED];
        
        for(Purchase_Data__c booth : listPurchaseData){                
            if((booth.Booth_Product_Type__c!=null && booth.Booth_Product_Type__c!='') && boothProductType.indexOf('\''+booth.Booth_Product_Type__c+'\'')<0){
                boothProductType += boothProductType==''?String.escapeSingleQuotes(booth.Booth_Product_Type__c):'\',\''+String.escapeSingleQuotes(booth.Booth_Product_Type__c);
            }
        }
        //Added null check as part of IMCC-2815 ticket (!conEdMapLst.isEmpty())
        if(string.isNotBlank(eventCode) && !conEdMapLst.isEmpty()){
            popupDetails.popupText ='';
             
            Set<String> setEditionPopupId = new Set<String>();
            List<Tab_User_Type__c> listTabUserType =[SELECT Edition_Popup__c, User_Type__c FROM Tab_User_Type__c
             WHERE Edition_Popup__r.Edition__r.Edition_Code__c =:eventCode
              AND User_Type__c =:conEdMapLst[0].Access_Type__c WITH SECURITY_ENFORCED];
            
            for(Tab_User_Type__c tuser :listTabUserType){
                setEditionPopupId.add(tuser.Edition_Popup__c);
            }
        
            List<Edition_Popup__c> listEditionPopup = new List<Edition_Popup__c>();
            //Fetch edition popup data
            String squery;                                                                       
            if(Test.isRunningTest()){
                squery = 'Select Id, Booth_Product_Type__c, Edition__c, Is_Visible__c, Pop_Up_Text__c, Reset_Pop_up_Preferences__c FROM Edition_Popup__c WHERE Edition__r.Edition_Code__c=:eventCode AND ID IN: setEditionPopupId';
            }
            else{                
                squery = 'Select Id, Booth_Product_Type__c, Edition__c, Is_Visible__c, Pop_Up_Text__c, Reset_Pop_up_Preferences__c FROM Edition_Popup__c WHERE Is_Visible__c=true AND Id IN: setEditionPopupId AND (Booth_Product_Type__c=\'\' OR Booth_Product_Type__c Includes(\''+boothProductType+'\'))';
            }
            
            system.debug('================='+squery);
            listEditionPopup = Database.query(squery);

            if(!listEditionPopup.IsEmpty()){
                popupDetails.editionPopup = listEditionPopup[0];
                for(Edition_Popup__c edp :listEditionPopup){ 
                    popupDetails.popupText = popupDetails.popupText + '&nbsp;' + edp.Pop_Up_Text__c;
                }
            }            
        } 
        }catch(Exception e) {
            String mesg = String.isNotBlank(e.getMessage()) ? e.getMessage():'';  
            String stackTrace = e.getStackTraceString().substringBefore('\n');             
            throw new AuraHandledException('Message='+mesg+'Stacktrace='+stackTrace); 

        }
        
        return popupDetails;
    }
    
    /**
    * @description : wrapper or Inner class with @AuraEnabled {get;set;} properties*  
    **/  
    public class WrapperPopupDetail
    {
        @AuraEnabled public Edition_Popup__c editionPopup{get;set;}
        @AuraEnabled public String popupText{get;set;}
        @AuraEnabled public Contact_Edition_Mapping__c CEM{get;set;}
        @AuraEnabled public List<Purchase_Data__c> purchaseDtls{get;set;}
         @AuraEnabled public String expocadEventCode{get;set;}
    }
    
    /**
    * @description : Get Stand details based on event code and account id. 
    * @param eventCode
    * @param accountId
    * @return : WrapperPopupDetail
    **/
    @AuraEnabled
    public static WrapperPopupDetail fetchStandDetails(String eventCode, String accountId){
        WrapperPopupDetail wrapBoothData = new WrapperPopupDetail();
        User u;
        if(User.SObjectType.getDescribe().isAccessible()){
            u = [Select id,Name,ContactId from User where Id =: UserInfo.getUserId()];
        }
        try{
            Map<String,Object> mapCEMDetails = IMCC_UtilityMethods.getContactEditionMappings(eventCode, accountId);        
            List<Contact_Edition_Mapping__c> conEdMapLst = (List<Contact_Edition_Mapping__c>)mapCEMDetails.get('cemList');//[SELECT Id,Name,Access_Type__c,Account__c,Account__r.Name,CC_Status__c,Contact__c,Edition__c,Relationship_Status__c FROM Contact_Edition_Mapping__c WHERE Contact__c =: u.ContactId AND Account__c =: accountId AND Relationship_Status__c = 'Active' AND Edition__r.Edition_Code__c =: eventCode WITH SECURITY_ENFORCED];   
            Set<Id> cemIds = (Set<Id>)mapCEMDetails.get('cemIds');
            if(!conEdMapLst.isEmpty()){
                wrapBoothData.expocadEventCode = conEdMapLst[0].Edition__r.Expocad_Event_Code__c;
                wrapBoothData.purchaseDtls = [SELECT Id,Name,Account__r.Name,
                    Contact_Edition_Mapping__c,Booth_Number__c,Booth_Product_Type__c,Purchase_Status__c,Exhibiting_Name__c,
                    Transaction_Status__c,Quantity_Area__c,Unit_of_Measurement__c FROM Purchase_Data__c WHERE Booth_Number__c != '' and Purchase_Status__c='Active' and Transaction_Status__c = 'Active' and Contact_Edition_Mapping__c IN:cemIds WITH SECURITY_ENFORCED];                    
            } 
                  
        }
        catch (Exception e) {
            System.debug('Exception hit ' +e.getMessage());
            //HandleAllCustomException.logException(e,'Purchase_Data__c', 'After Insert');
            String mesg = String.isNotBlank(e.getMessage()) ? e.getMessage():'';  
            String stackTrace = e.getStackTraceString().substringBefore('\n');             
            throw new AuraHandledException('Message='+mesg+'Stacktrace='+stackTrace);                     
        } 
        return wrapBoothData;
    }
    
    /**
    * @description : Update marked as read checkbox on CEM. 
    * @param cemId
    * @return : String
    **/
    //public static Contact_Edition_Mapping__c updateMarkAsRead(String eventCode, String accountId)
    @AuraEnabled(cacheable=false) 
    public static string updateMarkAsRead(String cemId) 
    {
        String message ='';
        User u;
        if(User.SObjectType.getDescribe().isAccessible()){
            u = [Select id,Name,ContactId from User where Id =: UserInfo.getUserId()];
        }
        system.debug('===================1'+cemId);
        Contact_Edition_Mapping__c cem = new Contact_Edition_Mapping__c();
        cem.Id = cemId;
        cem.Popup_Marked_as_Read__c = true;
        try{
            if(Schema.sObjectType.Contact_Edition_Mapping__c.isUpdateable())
            {
                update cem;
                message = 'success';
            }
        }catch (Exception ex) {

            //HandleAllCustomException.logException(ex,'Contact_Edition_Mapping__c', 'After Insert');
            String mesg = String.isNotBlank(ex.getMessage()) ? ex.getMessage():'';  
            String stackTrace = ex.getStackTraceString().substringBefore('\n');             
            throw new AuraHandledException('Message='+mesg+'Stacktrace='+stackTrace); 

        } 
        return message;
     }       
}