force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>Defines the user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Look up to Account record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Edition Mappings (Account)</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/CC_Status__c.field-meta.xml
<CustomField>
    <fullName>CC_Status__c</fullName>
    <description>Formula field, fetches value from Edition Customer Center status</description>
    <formula>TEXT(Edition__r.Customer_Center_Status__c)</formula>
    <label>CC Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Look up to Contact record</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Not a Customer Center Contact.</errorMessage>
        <filterItems>
            <field>Contact.IOM_Contact_Identifier__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <description>Defines status of account contact relationship</description>
    <label>Relationship Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Director__c.field-meta.xml
<CustomField>
    <fullName>Edition_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Lookup Field store the id of the Edition Director.</description>
    <label>Edition Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Tabs__c/Event_Tabs__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Event Setting. Defines the different tabs and tab properties for a particular event.</description>
    <label>Event Tab</label>
    <nameField>
        <displayFormat>ET-{0000000}</displayFormat>
        <label>Event Tabs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Tabs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Tabs__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Used to sort the Event tabs</description>
    <inlineHelpText>Sequence of the Tab in Customer Center</inlineHelpText>
    <label>Sequence</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Tabs__c/fields/Tab_Code__c.field-meta.xml
<CustomField>
    <fullName>Tab_Code__c</fullName>
    <displayFormat>T-{0000}</displayFormat>
    <label>Tab Code</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Order/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition of order.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Q_s_A_s_How_To__c/Q_s_A_s_How_To__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object is used by Ops Admin to define Ques and Ans or &quot;How to&quot; guides/tutorials which will populate on the Customer Portal</description>
    <label>Q’s &amp; A’s/How To</label>
    <nameField>
        <displayFormat>QA - {000000}</displayFormat>
        <label>Q’s &amp; A’s/How To Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Q’s &amp; A’s/How To</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Q_s_A_s_How_To__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines whether it will show on Portal or Not</description>
    <label>Visible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Q_s_A_s_How_To__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <description>Defines Answer set by Ops Admin to show on FAQ Standard Tab</description>
    <label>Answer</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Q_s_A_s_How_To__c/fields/Event_Tab__c.field-meta.xml
<CustomField>
    <fullName>Event_Tab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Defines for which Tab it will show</description>
    <label>Event Tab</label>
    <referenceTo>Event_Tabs__c</referenceTo>
    <relationshipLabel>Q’s &amp; A’s/How To</relationshipLabel>
    <relationshipName>Q_s_A_s_How_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Q_s_A_s_How_To__c/fields/HyperLink__c.field-meta.xml
<CustomField>
    <fullName>HyperLink__c</fullName>
    <description>Ops Admin can defines Urls for &quot;guidelines/How to&quot; which will show on the Customer Portal</description>
    <label>HyperLink</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Q_s_A_s_How_To__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Defines the Label for &quot;How to&quot; Links</description>
    <label>Label</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Q_s_A_s_How_To__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Defines Question set by Ops Admin to show on FAQ Standard Tab</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Q_s_A_s_How_To__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>It Defines the Sequence of QandA or How To Links which will appear accordingly on Community Portal</description>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Q_s_A_s_How_To__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Define which type of data Ops Admin will define to show on Customer Portal</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FAQ</fullName>
            </value>
            <value>
                <fullName>How to</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object use to create form question along with question type and related to Question Group(Section) and Form Questionnaires(junction object)</description>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Question label</description>
    <label>Question Label</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Set a Question Type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TextPlain</fullName>
                <label>Plain Text</label>
            </value>
            <value>
                <fullName>RichText</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
                <label>Number/Currency</label>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
                <label>Information/Instruction</label>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
            <value>
                <fullName>Slider</fullName>
            </value>
            <value>
                <fullName>GPS Location</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Header/Footer</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
                <label>Time Picklist</label>
            </value>
            <value>
                <fullName>Textarea</fullName>
            </value>
            <value>
                <fullName>GPSLocate</fullName>
                <isActive>false</isActive>
                <label>GPS Locate</label>
            </value>
            <value>
                <fullName>MultiSelect</fullName>
                <isActive>false</isActive>
                <label>MultiSelect</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IMCC_FAQCtrl.cls
/**
* Created/Modified By: Girikon(Garima)
* Created On:          19/10/2021
* @description  :      This class is used to fetch List of Ques Ans and How to List details on Customer Portal
* Methods:             fetchQuesAnsDetails,fetchHowToDetails,fetchContentVerId
* Apex Class:          IMCC_FAQCtrl 
* Apex Test Class:     IMCC_FAQCtrl_Test (91%)
* Modified By      :  IBM(Srikanth)
* Modified On      :   16 Sept, 2022
* @description  :      For all Auraenabled methods added try-catch block and threw Aura exception.
**/

/**
* @description : to fetch List of Ques Ans from Q_s_A_s_How_To__c object
* @param : eventcode, accountId,tabId
* @return : List<Q_s_A_s_How_To__c>
**/

public  without sharing class IMCC_FAQCtrl {
    @AuraEnabled
    public static List<Q_s_A_s_How_To__c> fetchQuesAnsDetails(String eventCode, String accountId, String tabId){
        User u;
        List<Q_s_A_s_How_To__c> fAqLst;
        if(User.SObjectType.getDescribe().isAccessible()){
            u = [Select id,Name,ContactId from User where Id =: UserInfo.getUserId()];
        }
        try{
            List<Contact_Edition_Mapping__c> conEdMapLst;
            if(Contact_Edition_Mapping__c.SObjectType.getDescribe().isAccessible()){
                conEdMapLst = [Select Id,Name,Access_Type__c,Account__c,Account__r.Name,CC_Status__c,Contact__c,Edition__c,Relationship_Status__c from Contact_Edition_Mapping__c where Contact__c =: u.ContactId And Account__c =: accountId And Relationship_Status__c = 'Active' And Edition__r.Edition_Code__c =: eventCode];
            }
            if(!conEdMapLst.isEmpty()){
                if(String.isNotBlank(tabId)){
                    if(Q_s_A_s_How_To__c.SObjectType.getDescribe().isAccessible()){
                        fAqLst = [Select Id,Name,Active__c,Event_Tab__c,Type__c,Sequence__c,Question__c,Answer__c from Q_s_A_s_How_To__c where Event_Tab__r.Tab_Code__c =: tabId and Active__c = true and Type__c = 'FAQ' Order By Sequence__c]; 
                    }
                }
            }
            
        }       
        catch (Exception e) {
            System.debug('Exception hit ' +e.getMessage());
          //  HandleAllCustomException.logException(e,'Q_s_A_s_How_To__c', 'After Insert');
            String stackTrace = e.getStackTraceString().substringBefore('\n');
            String mesg = String.isNotBlank(e.getMessage()) ? e.getMessage():''; 
           throw new AuraHandledException('Message='+mesg+'Stacktrace='+stackTrace);
        } 
        return fAqLst;
    }
    
    /**
* @description : to fetch List of How To Details from Q_s_A_s_How_To__c object
* @param : eventcode, accountId,tabId
* @return : List<Q_s_A_s_How_To__c>
**/
    @AuraEnabled
    public static List<Q_s_A_s_How_To__c> fetchHowToDetails(String eventCode, String accountId, String tabId){
        User u;
        List<Q_s_A_s_How_To__c> howToLst;
        if(User.SObjectType.getDescribe().isAccessible()){
            u = [Select id,Name,ContactId from User where Id =: UserInfo.getUserId()];
        }
        try{
            List<Contact_Edition_Mapping__c> conEdMapLst;
            if(Contact_Edition_Mapping__c.SObjectType.getDescribe().isAccessible()){
                conEdMapLst = [Select Id,Name,Access_Type__c,Account__c,Account__r.Name,CC_Status__c,Contact__c,Edition__c,Relationship_Status__c from Contact_Edition_Mapping__c where Contact__c =: u.ContactId And Account__c =: accountId And Relationship_Status__c = 'Active' And Edition__r.Edition_Code__c =: eventCode];
            }
            if(!conEdMapLst.isEmpty()){
                if(String.isNotBlank(tabId)){
                    if(Q_s_A_s_How_To__c.SObjectType.getDescribe().isAccessible()){
                        howToLst = [Select Id,Name,Active__c,Event_Tab__c,Type__c,Sequence__c,HyperLink__c,Label__c from Q_s_A_s_How_To__c where Event_Tab__r.Tab_Code__c =: tabId and Active__c = true and Type__c = 'How to' Order By Sequence__c]; 
                    }
                }
            }
            
        }       
        catch (Exception e) {
            System.debug('Exception hit ' +e.getMessage());
            //HandleAllCustomException.logException(e,'Q_s_A_s_How_To__c', 'After Insert');
            String stackTrace = e.getStackTraceString().substringBefore('\n');
            String mesg = String.isNotBlank(e.getMessage()) ? e.getMessage():''; 
           throw new AuraHandledException('Message='+mesg+'Stacktrace='+stackTrace);
        } 
        return howToLst;
    }
    
    /**
* @description : to fetch content version id 
* @param : howToId
* @return : String
**/
    @AuraEnabled
    public static String fetchContentVerId(String howToId){
        system.debug('howToId ' +howToId);
        String cntVerId;
        try{
            List<ContentDocumentLink> cntnDocLinkLst;
            if(String.isNotBlank(howToId)){
                if(ContentDocumentLink.SObjectType.getDescribe().isAccessible()){
                    cntnDocLinkLst = [SELECT Id, LinkedEntityId, ContentDocumentId, SystemModstamp, Visibility, ShareType FROM ContentDocumentLink where LinkedEntityId =: howToId Order By SystemModstamp desc ];
                    system.debug('cntnDocLinkLst ' +cntnDocLinkLst);
                }
            }
            if(cntnDocLinkLst.size()>0){
                List<ContentVersion> docmList = new List<ContentVersion>();
                if(ContentVersion.SObjectType.getDescribe().isAccessible()){
                    docmList = [select id FROM ContentVersion where contentdocumentid =: cntnDocLinkLst[0].ContentDocumentId and IsLatest = true];
                }
                if(docmList != null && docmList.size()>0){
                    cntVerId = docmList[0].Id;
                }
            }
        }catch(Exception e) {

            String stackTrace = e.getStackTraceString().substringBefore('\n');
            String mesg = String.isNotBlank(e.getMessage()) ? e.getMessage():''; 
           throw new AuraHandledException('Message='+mesg+'Stacktrace='+stackTrace);

        }
        return cntVerId;
    }
    
}