force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Look up to Account record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Edition Mappings (Account)</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Look up to Contact record</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Not a Customer Center Contact.</errorMessage>
        <filterItems>
            <field>Contact.IOM_Contact_Identifier__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contractor_Mapping__c/Contractor_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It Store the details of contractor</description>
    <label>Contractor Mapping</label>
    <nameField>
        <label>Contractor Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contractor Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contractor_Mapping__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contractor Account</description>
    <label>Contractor Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contractor Mappings</relationshipLabel>
    <relationshipName>Contractor_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contractor_Mapping__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contractor Contact</description>
    <label>Contractor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contractor Mappings</relationshipLabel>
    <relationshipName>Contractor_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contractor_Mapping__c/fields/Contractor_CEM__c.field-meta.xml
<CustomField>
    <fullName>Contractor_CEM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contactor Contact Edition Mapping</description>
    <label>Contractor CEM</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Contractor Mappings</relationshipLabel>
    <relationshipName>Contractor_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contractor_Mapping__c/fields/Contractor_Status__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Status__c</fullName>
    <description>Contractor status shows status of contactor to Exhibitor who assigned them to work on their booth</description>
    <label>Contractor Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Contractor Nomination In Review</fullName>
            </value>
            <value>
                <fullName>New Contractor Nomination Rejected</fullName>
            </value>
            <value>
                <fullName>Contractor Nominated</fullName>
            </value>
            <value>
                <fullName>Contractor Accepted Nomination</fullName>
            </value>
            <value>
                <fullName>Contractor Declined Nomination</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Viewed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Pending Sales Approval</fullName>
            </value>
            <value>
                <fullName>Stand Design Rejected/Incomplete</fullName>
            </value>
            <value>
                <fullName>Stand Design Resubmitted</fullName>
            </value>
            <value>
                <fullName>Pending Venue Approval</fullName>
            </value>
            <value>
                <fullName>Tentative Approval</fullName>
            </value>
            <value>
                <fullName>Permission to Build</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contractor_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition for stand</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contractor Mappings</relationshipLabel>
    <relationshipName>Contractor_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contractor_Mapping__c/fields/Is_Self_Managed__c.field-meta.xml
<CustomField>
    <fullName>Is_Self_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Self Managed</description>
    <label>Is Self Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contractor_Mapping__c/fields/Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Reason__c</fullName>
    <description>This field will be used to store the value when ops admin delete an assigned contractor under Stand Contractor</description>
    <label>Rejection Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Director__c.field-meta.xml
<CustomField>
    <fullName>Edition_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Lookup Field store the id of the Edition Director.</description>
    <label>Edition Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Event_Setting__c.field-meta.xml
<CustomField>
    <fullName>Event_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Setting</label>
    <referenceTo>Event_Setting__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Operations_Team__c.field-meta.xml
<CustomField>
    <fullName>Operations_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refer to the operation team managing this event</description>
    <label>Operations Team</label>
    <referenceTo>Operations_Team__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>This field stores the Start date of Edition.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Event_Setting__c/Event_Setting__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child of Edition. This will set the tab visibility on the home page of a particular event.</description>
    <label>Event Setting</label>
    <nameField>
        <label>Event Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operations_Team__c/Operations_Team__c.object-meta.xml
<CustomObject>
    <label>Operations Team</label>
    <nameField>
        <label>Operations Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operations Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operations_Team__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Define the edition of the operation team</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Operations Teams</relationshipLabel>
    <relationshipName>Operations_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/Purchase_Data__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It is the transactional information regarding the booth/product purchased.</description>
    <label>Purchase Data</label>
    <nameField>
        <displayFormat>PD-{000000000}</displayFormat>
        <label>Purchase Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Account Record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Contact Record</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact Edition mapping</description>
    <label>Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Contractor_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used to capture Contractor mapping respect to Stand Details info</description>
    <label>Contractor Mapping</label>
    <referenceTo>Contractor_Mapping__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Edition Record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IMCC_ContractorMappingTrigHandler.cls
/**
* Created By    :   Girikon[Arushi IMCC-83]
* Created On    :   03/02/2021
* @description  :   Trigger on contractor Mapping object to update the task when it is completed.
* Modified By   :   Girikon(Arushi - [IMCC-91]),Girikon(Garima - [IMCC-4202])
* Modified On   :   25 Feb, 2022,19 Aug, 2022
* @description  :   This class will help Customers to submit the stand design for their booths, if they decide to complete stand submission process.
* Test Class    :   IMCC_ContractorMappingTrigHandler_Test(91%)
*/
public with sharing class IMCC_ContractorMappingTrigHandler {
    /**
    * @description update Contractor Status
    * @param  newConMapList
    */
    public static void updateContractorStatus(List<Contractor_Mapping__c> newConMapList){
        Set<Id> cmId = new Set<Id>();
        for(Contractor_Mapping__c cm : newConMapList){
            cmId.add(cm.Id);
        }
        List<Purchase_Data__c> listPd = [SELECT Id,Contractor_Mapping__c,Contact_Edition_Mapping__c FROM Purchase_Data__c WHERE Contractor_Mapping__c IN:cmId WITH SECURITY_ENFORCED];
        Map<Id,Purchase_Data__c> mapPD = new Map<Id,Purchase_Data__c>();
        for(Purchase_Data__c pd : listPd){
            mapPD.put(pd.Contractor_Mapping__c, pd);
        }

        for(Contractor_Mapping__c cm : newConMapList){
            if(cm.Contractor_CEM__c!=null && (mapPD.get(cm.Id)?.Contact_Edition_Mapping__c == cm.Contractor_CEM__c && cm.Contractor_Status__c == 'Contractor Nominated')){
                cm.Contractor_Status__c = 'Contractor Accepted Nomination';
            }
        }
    }
    
    /**
    * @description update Task Status
    * @param  newConMaps
    * @param  oldConMaps
    */
    public static void updateTaskStatus(Map<Id,Contractor_Mapping__c> newConMaps,Map<Id,Contractor_Mapping__c> oldConMaps){
        Set<Id> editionSet = new Set<Id>();
        set<Id> conIds = new set<Id>();
        set<Id> contractorMappingIds = new set<Id>();
        List<Task> taskList = new List<Task>();
        List<Task> taskToBeUpdated = new List<Task>();
        
        try{
            for(Contractor_Mapping__c cm : newConMaps.Values()){
                if(cm.Contractor_Status__c == 'Contractor Accepted Nomination'){
                    contractorMappingIds.add(cm.Id);
                }
            }
            
            List<Purchase_Data__c> pdList  = [SELECT Contact_Edition_Mapping__r.Contact__c,Contact_Edition_Mapping__r.Edition__c FROM Purchase_Data__c WHERE Contractor_Mapping__c IN:contractorMappingIds WITH SECURITY_ENFORCED];
            
            for(Purchase_Data__c pHData : pdList){
                editionSet.add(pHData.Contact_Edition_Mapping__r.Edition__c);
                conIds.add(pHData.Contact_Edition_Mapping__r.Contact__c);
            }
            
            if((!editionSet.isEmpty() && !conIds.isEmpty()) && Schema.sObjectType.Task.isAccessible()){
                taskList = [SELECT Id, WhoId, WhatId, Subject, ActivityDate, Status, Priority,IsHighPriority, OwnerId, ReminderDateTime FROM Task WHERE WhoId IN:conIds AND WhatId IN:editionSet AND Subject='Nominate the Contractor'];
            }
            
            for(Task t : taskList){
                t.status = 'Completed';
                taskToBeUpdated.add(t);
            }

            if(!taskToBeUpdated.isEmpty() && Schema.sObjectType.Task.isUpdateable()){
                update taskToBeUpdated;
            }
        }
        catch (Exception ex) {
            HandleAllCustomException.logException(ex,'Contractor_Mapping__c', 'After Update');
        }
    }
    
    /**
    * @description send Email And Portal Notifications
    * @param  contractorNewMap
    * @param  contractorOldMap
    * @param  isInsert
    */
    public static void sendEmailAndPortalNotifications(List<Contractor_Mapping__c> contractorNewMap,Map<Id,Contractor_Mapping__c> contractorOldMap,boolean isInsert){
        Profile prf = [SELECT Id,Name FROM Profile WHERE Id=:Userinfo.getProfileid() LIMIT 1];
        Set<Id> setIds = new Set<Id>();
        Map<Id,List<String>> mapCMIdEmailTemplate = new Map<Id,List<String>>();
        for(Contractor_Mapping__c cm : contractorNewMap){
            if(!mapCMIdEmailTemplate.containsKey(cm.Id)){
                mapCMIdEmailTemplate.put(cm.Id, new List<String>());
            }
            List<String> lstET =  mapCMIdEmailTemplate.get(cm.Id);
            Contractor_Mapping__c oldCM = isInsert?null:contractorOldMap.get(cm.Id);
            if(!isInsert && cm.Contractor_Status__c == 'Contractor Accepted Nomination' && cm.Contractor_Status__c!=oldCM.Contractor_Status__c){
                lstET.add('Email:Contractor accepted nomination CUS');
                lstET.add('Portal:Contractor accepted nomination CUS');
                setIds.add(cm.Id);
            }
            if(!isInsert && cm.Contractor_Status__c == 'Contractor Declined Nomination' && cm.Contractor_Status__c!=oldCM.Contractor_Status__c){
                lstET.add('Email:Contractor rejected nomination CUS');
                lstET.add('Portal:Contractor rejected nomination CUS');
                setIds.add(cm.Id);
            }
            if(!isInsert && cm.Contractor_Status__c == 'Contractor Nominated' && oldCM.Contractor_Status__c=='New Contractor Nomination In Review'){
                lstET.add('Email:Ops team accepted New contractor CUS');
                lstET.add('Portal:Ops team accepted New contractor CUS');
                lstET.add('Email:Ops team approve a new contractor CON');
                setIds.add(cm.Id);
            }
            if(!isInsert && cm.Contractor_Status__c == 'New Contractor Nomination Rejected' && cm.Contractor_Status__c!=oldCM.Contractor_Status__c){
                lstET.add('Email:Ops team rejected New contractor CUS');
                lstET.add('Portal:Ops team rejected New contractor CUS');
                setIds.add(cm.Id);
            }
            if(isInsert && cm.Contractor_Status__c == 'Contractor Nominated' && prf.Name != 'IM Customer Community Login User'){
                lstET.add('Email:Ops team nominate a contractor CUS');
                setIds.add(cm.Id);
            }
            if(!isInsert && cm.Contractor_Status__c == 'Permission to Build' && cm.Contractor_Status__c!=oldCM.Contractor_Status__c){
                lstET.add('Email:Stand Design Permission to Build CUS');
                lstET.add('Portal:Stand Design Permission to Build CUS');
                lstET.add('Email:Stand Design Permission to Build CON');
                lstET.add('Portal:Permission to Build Con');
                setIds.add(cm.Id);
            }
            if(cm.Contractor_Status__c == 'Contractor Nominated' && (isInsert || cm.Contractor_Status__c!=oldCM.Contractor_Status__c)){
                lstET.add('Email:Contractor nomination for an event CON');
                lstET.add('Portal:Contractor Nominated Con');
                setIds.add(cm.Id);
            }
            if(!isInsert && cm.Contractor_Status__c == 'In Review' && cm.Contractor_Status__c!=oldCM.Contractor_Status__c){
                lstET.add('Email:Stand Design In Review CON');
                lstET.add('Email:Stand Design Submission OPS');
                lstET.add('Portal:In Review Con');
                setIds.add(cm.Id);
            }
            if(!isInsert && cm.Contractor_Status__c == 'Pending Sales Approval' && cm.Contractor_Status__c!=oldCM.Contractor_Status__c){
                lstET.add('Email:Stand Design Pending Sales Approval CON');
                lstET.add('Portal:Pending Sales Approval Con');
                setIds.add(cm.Id);
            }
            if(!isInsert && cm.Contractor_Status__c == 'Stand Design Rejected/Incomplete' && cm.Contractor_Status__c!=oldCM.Contractor_Status__c){
                lstET.add('Email:Stand Design Rejected CON');
                lstET.add('Portal:Stand Design Rejected/Incomplete Con');
                setIds.add(cm.Id);
            }
            if(!isInsert && cm.Contractor_Status__c == 'Stand Design Resubmitted' && cm.Contractor_Status__c!=oldCM.Contractor_Status__c){
                lstET.add('Email:Stand Design Resubmission OPS');
                lstET.add('Email:Stand Design Resubmitted CON');
                lstET.add('Portal:Stand Design Resubmitted Con');
                setIds.add(cm.Id);
            }
            if(!isInsert && cm.Contractor_Status__c == 'Pending Venue Approval' && cm.Contractor_Status__c!=oldCM.Contractor_Status__c){
                lstET.add('Email:Stand Design Pending Venue Approval CON');
                lstET.add('Portal:Pending Venue Approval Con');
                setIds.add(cm.Id);
            }
            if(!isInsert && cm.Contractor_Status__c == 'Tentative Approval' && cm.Contractor_Status__c!=oldCM.Contractor_Status__c){
                lstET.add('Email:Stand Design Tentative Approval CON');
                lstET.add('Portal:Tentative Approval Con');
                setIds.add(cm.Id);
            }
            if(!isInsert && cm.Contractor_Status__c == 'Cancelled' && cm.Contractor_Status__c!=oldCM.Contractor_Status__c){
                lstET.add('Email:Stand Design Cancelled Status CON');
                lstET.add('Portal:Cancelled Con');
                setIds.add(cm.Id);
            }
            if(isInsert && cm.Contractor_Status__c == 'New Contractor Nomination In Review'){
                lstET.add('Email:New Contractor submission OPS');
                setIds.add(cm.Id);
            }
            mapCMIdEmailTemplate.put(cm.Id, lstET);
        }
            
        if(!setIds.isEmpty()){
            String strQuery = 'SELECT Id,Edition__c,Edition__r.Name,Edition__r.Edition_Code__c,Edition__r.Start_Date__c,Rejection_Reason__c,Contractor_Status__c,Contractor_CEM__c,Contractor_CEM__r.Contact__c,Contractor_CEM__r.Account__r.Id,Account__c,Account__r.Id,Edition__r.Event_Setting__c,Edition__r.Operations_Team__c,Is_Self_Managed__c FROM Contractor_Mapping__c WHERE Id In:setIds';
            List<SObject> listSobject = Database.query(strQuery);
            SendEmailOnFormStatusBatch batch = new SendEmailOnFormStatusBatch(listSobject,'Stand Contractor',mapCMIdEmailTemplate);
            Database.executeBatch(batch,1);
        }
    }
}