force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Welcome_Email_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Email_Job_Id__c</fullName>
    <label>Welcome Email Job Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Welcome_Email_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Email_Job_Id__c</fullName>
    <label>Welcome Email Job Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Welcome_Email_Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Email_Job_Status__c</fullName>
    <label>Welcome Email Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IMCC_SendWelcomeEmailBatch.cls
/**
* Created/Modified By    : Girikon(Deepak)
* Created On             : 29-06-2022
* @description           : This batch class is for sending welcome emails in bulk
* Test Class             : IMCC_EditionWelcomeEmailTest
* Code Coverage          : 100%
* Modified by 
**/
public class IMCC_SendWelcomeEmailBatch implements Database.Batchable<sobject>,Database.stateful{

    public List<Contact_Edition_Mapping__c> listCEM = new List<Contact_Edition_Mapping__c>();
    public Boolean isManual = false;
    public Set<Id> editionIds;
    
    /**
    * @description  IMCC_SendWelcomeEmailBatch Constructor
    * @param  listCEM
    * @param  isManual
    */
    public IMCC_SendWelcomeEmailBatch(List<Contact_Edition_Mapping__c> listCEM, Boolean isManual){
        this.listCEM = listCEM;
        this.isManual = isManual;
        this.editionIds = new Set<Id>();
    }
    
    /**
    * @description  IMCC_SendWelcomeEmailBatch Start Method
    * @param  bc
    * @return List<Contact_Edition_Mapping__c>
    */
    public List<Contact_Edition_Mapping__c> start(Database.BatchableContext bc){
        List<Contact_Edition_Mapping__c> listCemUpdate = new List<Contact_Edition_Mapping__c>();
        for(Contact_Edition_Mapping__c cem : this.listCEM){
            listCemUpdate.add(new Contact_Edition_Mapping__c(Id=cem.Id,Welcome_Email_Job_Id__c=bc.getJobId()));
            editionIds.add(cem.Edition__c);
        }
        update listCemUpdate;
        return this.listCEM;
    }

    /**
    * @description  IMCC_SendWelcomeEmailBatch execute Method
    * @param bc
    * @param scope
    */
    public void execute(Database.BatchableContext bc, List<Contact_Edition_Mapping__c> scope){
        IMCC_EditionWelcomeEmail.processWelcomeEmail(scope, this.isManual);
    }

    /**
    * @description  IMCC_SendWelcomeEmailBatch finish Method
    * @param bc
    */
    public void finish(Database.BatchableContext bc){
        List<Edition__c> listEditionUpdate = new List<Edition__c>();
        for(Id edId : editionIds){
            listEditionUpdate.add(new Edition__c(Id=edId,Welcome_Email_Job_Status__c='Completed'));
        }
        if(!listEditionUpdate.isEmpty()){update listEditionUpdate;}
    }
}