force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Allocation__c/Form_Allocation__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Form Setting. It will contain the list of forms and manuals based on user type.</description>
    <label>Form Allocation</label>
    <nameField>
        <label>Form Display Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Allocation__c/fields/Approval_Required__c.field-meta.xml
<CustomField>
    <fullName>Approval_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to check if form is required or not</description>
    <label>Approval Required?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Allocation__c/fields/Form_Entry__c.field-meta.xml
<CustomField>
    <fullName>Form_Entry__c</fullName>
    <label>Form Entry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Multiple Per Account</fullName>
            </value>
            <value>
                <fullName>Multiple Per Booth</fullName>
            </value>
            <value>
                <fullName>One Per Account</fullName>
                <default>true</default>
                <label>One Per Account</label>
            </value>
            <value>
                <fullName>One Per Booth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Data__c/Form_Data__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object stores all the form summary data related to contact edition mapping, form submission and Questionnaire</description>
    <label>Form Data</label>
    <nameField>
        <displayFormat>FD-{0000000}</displayFormat>
        <label>Form Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Data__c/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up field to contact edition mapping to store in form data.</description>
    <label>Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Form Data</relationshipLabel>
    <relationshipName>Form_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Data__c/fields/Forms_Permission__c.field-meta.xml
<CustomField>
    <fullName>Forms_Permission__c</fullName>
    <description>This field refers to the Form Permission.</description>
    <label>Forms Permission</label>
    <referenceTo>Forms_Permission__c</referenceTo>
    <relationshipLabel>Form Data</relationshipLabel>
    <relationshipName>Form_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Form_Data__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Only Active Form Data will be shown to customers</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Data__c/fields/Overall_Status__c.field-meta.xml
<CustomField>
    <fullName>Overall_Status__c</fullName>
    <description>Backend field to support form filter functionality. Do not use on layout or in reports.</description>
    <inlineHelpText>Backend field to support form filter functionality. Do not use on layout or in reports.</inlineHelpText>
    <label>Overall Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agreed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Viewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Data__c/fields/Purchase_Data__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Data</label>
    <referenceTo>Purchase_Data__c</referenceTo>
    <relationshipLabel>Form Data</relationshipLabel>
    <relationshipName>Form_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Data__c/fields/Status1__c.field-meta.xml
<CustomField>
    <fullName>Status1__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agreed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
                <isActive>false</isActive>
                <label>Declined</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Viewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forms_Permission__c/Forms_Permission__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object defines the user access of the form allocation</description>
    <label>Forms Permission</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Forms Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forms_Permission__c/fields/Form_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Form_Allocation__c</fullName>
    <description>This is refer to the lookup of Form Allocation record</description>
    <label>Form Allocation</label>
    <referenceTo>Form_Allocation__c</referenceTo>
    <relationshipLabel>Forms Permissions</relationshipLabel>
    <relationshipName>Forms_Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forms_Permission__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Only Form Data related to Active Form Permissions will be shown to customers</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/Purchase_Data__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It is the transactional information regarding the booth/product purchased.</description>
    <label>Purchase Data</label>
    <nameField>
        <displayFormat>PD-{000000000}</displayFormat>
        <label>Purchase Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Data__c/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact Edition mapping</description>
    <label>Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IMCC_FormData_Trigger_Handler.cls
/**
* Created/Modified By    : Girikon(Deepak)
* Created On             : 06-06-2022
* @description           : This trigger helper class is for updating form data overall status
* Test Class             : FBUtilTest
* Code Coverage          : 85%
* Modified by 
**/
public with sharing class IMCC_FormData_Trigger_Handler {
    /**
    * @description  to update form data overall status
    * @param  listNewFD
    * @param  oldMapFD
    * @param isAfter
    */
    public static void updateFormDataOverallStatus(List<Form_Data__c> listNewFD , Map<Id,Form_Data__c> oldMapFD, Boolean isAfter){
        if(isAfter){
            Set<Id> formPermIds = new Set<Id>();
            Set<Id> cemIds = new Set<Id>();
            for(Form_Data__c fd: listNewFD){
                if(fd.Status1__c != oldMapFD.get(fd.Id).Status1__c && String.isNotBlank(fd.Purchase_Data__c)){
                    formPermIds.add(fd.Forms_Permission__c);
                    cemIds.add(fd.Contact_Edition_Mapping__c);
                }
            }
            List<Form_Data__c> listFD = [SELECT Id,Is_Active__c,Forms_Permission__r.Form_Allocation__c,Forms_Permission__r.Form_Allocation__r.Approval_Required__c,Status1__c,Contact_Edition_Mapping__c FROM Form_Data__c WHERE Forms_Permission__c IN:formPermIds AND Contact_Edition_Mapping__c IN:cemIds AND Forms_Permission__r.Form_Allocation__r.Form_Entry__c IN ('One Per Booth','Multiple Per Booth') WITH SECURITY_ENFORCED];
            Map<String,List<Form_Data__c>> mapKeyListFD = new Map<String,List<Form_Data__c>>();
            Map<String,Boolean> mapFAllocApprovalReq = new Map<String,Boolean>();
            for(Form_Data__c fd : listFD){
                String key = fd.Forms_Permission__r.Form_Allocation__c + '_' + fd.Contact_Edition_Mapping__c;
                List<Form_Data__c> listFD2 = (mapKeyListFD.containsKey(key)?mapKeyListFD.get(key):(new List<Form_Data__c>()));
                if(fd.Is_Active__c){
                    listFD2.add(fd);
                }
                mapKeyListFD.put(key, listFD2);
                mapFAllocApprovalReq.put(fd.Forms_Permission__r.Form_Allocation__c, fd.Forms_Permission__r.Form_Allocation__r.Approval_Required__c);
            }

            List<Form_Data__c> listUpdate = new List<Form_Data__c>();
            for(String key : mapKeyListFD.keySet()){
                String formAllocId = key.split('_').get(0);
                Boolean approvalRequired = mapFAllocApprovalReq.get(formAllocId);
                List<Form_Data__c> listFD2 = mapKeyListFD.get(key);
                String tempStatus = 'Not Started';
                Integer notStarted = 0;
                Integer viewed = 0;
                Integer inProgress = 0;
                Integer inReview = 0;
                Integer approved = 0;
                Integer rejected = 0;
                Integer submitted = 0;
                //system.debug('listFD2 ' +listFD2);
                for(Form_Data__c fd : listFD2){
                    //system.debug('Form Data Status ' +fd.Status1__c);
                    if(fd.Status1__c == 'Not Started'){
                        notStarted++;
                    }
                    if(fd.Status1__c == 'Viewed'){
                        viewed++;
                    }
                    if(fd.Status1__c == 'In Progress'){
                        inProgress++;
                    }
                    if(fd.Status1__c == 'In Review'){
                        inReview++;
                    }
                    if(fd.Status1__c == 'Approved'){
                        approved++;
                    }
                    if(fd.Status1__c == 'Rejected'){
                        rejected++;
                    }
                    if(fd.Status1__c == 'Submitted' || fd.Status1__c == 'Resubmitted'){
                        submitted++;
                    }
                    if(approvalRequired){
                        if(listFD2.size() == notStarted){
                            tempStatus = 'Not Started';
                        }
                        else if(viewed > 0 && inProgress == 0 && inReview == 0 && approved == 0 && rejected == 0 && submitted == 0){
                            tempStatus = 'Viewed';
                        }
                        else if((notStarted > 0 || viewed > 0 )){
                            tempStatus = 'In Progress';
                            system.debug('tempStatus1 ' +tempStatus);
                        }
                        else{
                            tempStatus = 'In Progress';
                            if(inProgress == 0 && inReview > 0 && rejected == 0){
                                tempStatus = 'In Review';
                                //system.debug('tempStatus2 ' +tempStatus);
                            }
                            if(inProgress == 0 && inReview == 0 && rejected == 0 && approved > 0){
                                tempStatus = 'Approved';
                            }
                            if(listFD2.size() == rejected){
                                tempStatus = 'Rejected';
                            }
                        }
                    }
                    else{
                        if(listFD2.size() == notStarted){
                            tempStatus = 'Not Started';
                        }
                        else if(viewed > 0 && inProgress == 0 && inReview == 0 && approved == 0 && rejected == 0 && submitted == 0){
                            tempStatus = 'Viewed';
                        }
                        else{
                            tempStatus = 'In Progress';
                            if(listFD2.size() == submitted){
                                tempStatus = 'Submitted';
                            }
                        }
                    }
                }
                for(Form_Data__c fd : listFD2){
                    listUpdate.add(new Form_Data__c(Id=fd.Id,Overall_Status__c=tempStatus));
                }
            }
            if(!listUpdate.isEmpty()){
                update listUpdate;
            }
        }
        else{
            updateFormDataOverallStatus(listNewFD, oldMapFD);
        }
    }

    /**
    * @description  to update form data overall status Before Insert/Update
    * @param  listNewFD
    * @param  oldMapFD
    */
    public static void updateFormDataOverallStatus(List<Form_Data__c> listNewFD, Map<Id,Form_Data__c> oldMapFD){
        for(Form_Data__c fd: listNewFD){
            if(oldMapFD == null || (fd.Status1__c != oldMapFD.get(fd.Id).Status1__c && String.isBlank(fd.Purchase_Data__c))){
                fd.Overall_Status__c = fd.Status1__c;
            }
        }
    }
}