force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>Defines the user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Look up to Account record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Edition Mappings (Account)</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Look up to Contact record</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Not a Customer Center Contact.</errorMessage>
        <filterItems>
            <field>Contact.IOM_Contact_Identifier__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <description>Defines status of account contact relationship</description>
    <label>Relationship Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Director__c.field-meta.xml
<CustomField>
    <fullName>Edition_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Lookup Field store the id of the Edition Director.</description>
    <label>Edition Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>This field stores the End date of Edition.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>This field stores the Start date of Edition.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ESSOConnectedAppHandler.cls
global class ESSOConnectedAppHandler extends Auth.ConnectedAppPlugin
{
    global override Map<String,String> customAttributes(Id userId, Id connectedAppId, Map<String,String> formulaDefinedAttributes, Auth.InvocationContext context)
    { 
        User u = [SELECT AccountId, Account.Name, ContactId FROM User WHERE Id = :userId];
        
        if (u != null && u.AccountId != null)
        {
            string strJson = '{';
            strJson += '"contactId": "'+ u.ContactId +'","accountId": "' +u.AccountId +'","accountName": "' +u.Account.Name +'","eventEditions": ['; 
            
            list<Contact_Edition_Mapping__c> listCem = [SELECT Access_Type__c,Edition__r.Edition_Code__c,Edition__r.Name,Edition__r.Start_Date__c,Edition__r.End_Date__c FROM Contact_Edition_Mapping__c WHERE 
                                             Account__c =: u.AccountId AND Contact__c =:u.ContactId AND Relationship_Status__c ='Active' ];

            for(Contact_Edition_Mapping__c cem: listCem)
            {
                strJson += '{"accessType": "' +cem.Access_Type__c +'","eventName": "' +cem.Edition__r.Name +'","eventCode": "' +cem.Edition__r.Edition_Code__c+ '","startDate": "' +cem.Edition__r.Start_Date__c +'","endDate": "' +cem.Edition__r.End_Date__c+ '"},';
            }
            if (strJson.endsWith(',')){strJson.left(strJson.length()-1);}
            
            strJson += ']}';
            
            formulaDefinedAttributes.put('exhibitor',  strJson);
        }
            
        return formulaDefinedAttributes;   
    }
}