force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Look up to Account record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Edition Mappings (Account)</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Look up to Contact record</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Not a Customer Center Contact.</errorMessage>
        <filterItems>
            <field>Contact.IOM_Contact_Identifier__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Edition_Status__c.field-meta.xml
<CustomField>
    <fullName>Edition_Status__c</fullName>
    <description>This picklist stores the status of Edition.</description>
    <label>Edition Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Tentative</fullName>
            </value>
            <value>
                <fullName>Cancelled by Finance</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Pending Setup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Form_Setting__c.field-meta.xml
<CustomField>
    <fullName>Form_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Setting</label>
    <referenceTo>Form_Setting__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Allocation__c/Form_Allocation__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Form Setting. It will contain the list of forms and manuals based on user type.</description>
    <label>Form Allocation</label>
    <nameField>
        <label>Form Display Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Allocation__c/fields/Form_Entry__c.field-meta.xml
<CustomField>
    <fullName>Form_Entry__c</fullName>
    <label>Form Entry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Multiple Per Account</fullName>
            </value>
            <value>
                <fullName>Multiple Per Booth</fullName>
            </value>
            <value>
                <fullName>One Per Account</fullName>
                <default>true</default>
                <label>One Per Account</label>
            </value>
            <value>
                <fullName>One Per Booth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Allocation__c/fields/Form_Setting__c.field-meta.xml
<CustomField>
    <fullName>Form_Setting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to Form Setting.</description>
    <label>Form Setting</label>
    <referenceTo>Form_Setting__c</referenceTo>
    <relationshipLabel>Form Allocations</relationshipLabel>
    <relationshipName>Form_Allocations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Data__c/Form_Data__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object stores all the form summary data related to contact edition mapping, form submission and Questionnaire</description>
    <label>Form Data</label>
    <nameField>
        <displayFormat>FD-{0000000}</displayFormat>
        <label>Form Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up field to Account to store in form data.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Form Data</relationshipLabel>
    <relationshipName>Form_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Data__c/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up field to contact edition mapping to store in form data.</description>
    <label>Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Form Data</relationshipLabel>
    <relationshipName>Form_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Data__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up field to Edition to store in form data.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Form Data</relationshipLabel>
    <relationshipName>Form_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Data__c/fields/Forms_Permission__c.field-meta.xml
<CustomField>
    <fullName>Forms_Permission__c</fullName>
    <description>This field refers to the Form Permission.</description>
    <label>Forms Permission</label>
    <referenceTo>Forms_Permission__c</referenceTo>
    <relationshipLabel>Form Data</relationshipLabel>
    <relationshipName>Form_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Form_Data__c/fields/Purchase_Data__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Data</label>
    <referenceTo>Purchase_Data__c</referenceTo>
    <relationshipLabel>Form Data</relationshipLabel>
    <relationshipName>Form_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forms_Permission__c/Forms_Permission__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object defines the user access of the form allocation</description>
    <label>Forms Permission</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Forms Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forms_Permission__c/fields/Form_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Form_Allocation__c</fullName>
    <description>This is refer to the lookup of Form Allocation record</description>
    <label>Form Allocation</label>
    <referenceTo>Form_Allocation__c</referenceTo>
    <relationshipLabel>Forms Permissions</relationshipLabel>
    <relationshipName>Forms_Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forms_Permission__c/fields/Tab_User_Type__c.field-meta.xml
<CustomField>
    <fullName>Tab_User_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field refers to the tab user type</description>
    <label>Tab User Type</label>
    <referenceTo>Tab_User_Type__c</referenceTo>
    <relationshipLabel>Forms Permissions</relationshipLabel>
    <relationshipName>Forms_Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forms_Permission__c/fields/User_Type1__c.field-meta.xml
<CustomField>
    <fullName>User_Type1__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/Purchase_Data__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It is the transactional information regarding the booth/product purchased.</description>
    <label>Purchase Data</label>
    <nameField>
        <displayFormat>PD-{000000000}</displayFormat>
        <label>Purchase Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Account Record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Contact Record</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact Edition mapping</description>
    <label>Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Edition Record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <description>Defines user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tab_User_Type__c/Tab_User_Type__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will give info on tab will be visible to which user type.</description>
    <label>Tab User Type</label>
    <nameField>
        <displayFormat>UT-{00000}</displayFormat>
        <label>Tab User Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tab User Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tab_User_Type__c/fields/Form_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Form_Allocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up field to form allocation object. One form allocation can have many tab user types.</description>
    <label>Form Allocation</label>
    <referenceTo>Form_Allocation__c</referenceTo>
    <relationshipLabel>Tab User Types</relationshipLabel>
    <relationshipName>Tab_User_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tab_User_Type__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <description>Defines user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/IMCC_ManageFormDataRecords.cls
/**
 * @description IMCC_ManageFormDataRecords 
Created By    : Aishwarya[IMCC-616]
Test Class    : IMCC_FormDataHandler_Test()
Created/Modified By   :  21/11/2021
Code Coverage - 92%
*/

public without sharing class IMCC_ManageFormDataRecords{
    /**
    * @description  to handle form permission after update.
    * @param  lstFP 
    */
    public static void handleAfterInsert(List<Forms_Permission__c> lstFP){
        Set<String> setformAllocationIds = new Set<String>();
        Set<Id> setFormSettingIds = new Set<Id>();
        Set<Id> setEditionIds = new Set<Id>();
        Map<Id,Set<Id>> mapFormSettingIdSetEditionId = new Map<Id,Set<Id>>();
        Set<String> setCEMIds = new Set<String>();
        Set<String> setUserType = new Set<String>();
        Map<Id,Form_Allocation__c> mapFormAllocationData = new Map<Id,Form_Allocation__c>();
        List<Purchase_Data__c> listPurchaseData = new List<Purchase_Data__c>();
        List<Form_Data__c> listFormDataInsert = new List<Form_Data__c>();
        List<Form_Data__c> listFormDataUpdate = new List<Form_Data__c>();
        Map<Id,Set<String>> mapFormAllocUserTypes = new Map<Id,Set<String>>();
        
        for(Forms_Permission__c fp : lstFP){
            setformAllocationIds.add(fp.Form_Allocation__c);
            setUserType.add(fp.User_Type1__c);
        }
        
        mapFormAllocationData = new Map<Id,Form_Allocation__c>([SELECT Id, Booth_Product_Types__c, Form_Setting__c, Form_Entry__c, (select Id, User_Type__c, Form_Allocation__c FROM Tab_User_Types__r) FROM Form_Allocation__c WHERE Id IN:setformAllocationIds WITH SECURITY_ENFORCED]);
        
        if(!mapFormAllocationData.isEmpty()){
            for(Form_Allocation__c form : mapFormAllocationData.Values()){
                setFormSettingIds.add(form.Form_Setting__c);
                Set<String> setStr = new Set<String>();
                if(form.Tab_User_Types__r != null){
                    for(Tab_User_Type__c tut : form.Tab_User_Types__r){
                        setStr.add(tut.User_Type__c);
                    }
                }
                mapFormAllocUserTypes.put(form.Id,setStr);
            }
        }

        if(!setFormSettingIds.isEmpty() && Schema.sObjectType.Edition__c.isAccessible()){
            List<Edition__c> listEdition = [SELECT Id, Name, Form_Setting__c, Edition_Status__c FROM Edition__c WHERE Form_Setting__c IN:setFormSettingIds];
            for(Edition__c edition : listEdition){
                setEditionIds.add(edition.Id);
                Set<Id> setStr = (mapFormSettingIdSetEditionId.containsKey(edition.Form_Setting__c)?mapFormSettingIdSetEditionId.get(edition.Form_Setting__c):(new Set<Id>()));
                setStr.add(edition.Id);
                mapFormSettingIdSetEditionId.put(edition.Form_Setting__c,setStr);
            }
        }

        Map<Id,List<Contact_Edition_Mapping__c>> mapEditionIdListCEM = new Map<Id,List<Contact_Edition_Mapping__c>>();
        if(!setEditionIds.isEmpty() && Schema.sObjectType.Contact_Edition_Mapping__c.isAccessible()){
            List<Contact_Edition_Mapping__c> listCEM2 = [SELECT Id, Account__c, Contact__c, Edition__c, CC_Status__c, Access_Type__c FROM Contact_Edition_Mapping__c WHERE Relationship_Status__c = 'Active' AND CC_Status__c IN ('Active', 'In Progress') AND Edition__c IN:setEditionIds AND Access_Type__c IN:setUserType AND isSecondary__c=false];
            for(Contact_Edition_Mapping__c cem : listCEM2){
                setCEMIds.add(cem.Id);
                List<Contact_Edition_Mapping__c> lst = (mapEditionIdListCEM.containsKey(cem.Edition__c)?mapEditionIdListCEM.get(cem.Edition__c):(new List<Contact_Edition_Mapping__c>()));
                lst.add(cem);
                mapEditionIdListCEM.put(cem.Edition__c,lst);
            }
        }
        
        Map<Id,Set<String>> mapCEMIdBoothTypes = new Map<Id,Set<String>>();
        Map<Id,List<Purchase_Data__c>> mapCEMIdListPD = new Map<Id,List<Purchase_Data__c>>();
        if(!setCEMIds.isEmpty() && Schema.sObjectType.Purchase_Data__c.isAccessible()){
            listPurchaseData = [SELECT Id, Booth_Product_Type__c, Contact_Edition_Mapping__c FROM Purchase_Data__c WHERE Contact_Edition_Mapping__c IN:setCEMIds AND Booth_Number__c!=null AND Purchase_Status__c='Active' AND Transaction_Status__c ='Active'];
            for(Purchase_Data__c pd : listPurchaseData){
                Set<String> setStr = (mapCEMIdBoothTypes.containsKey(pd.Contact_Edition_Mapping__c)?mapCEMIdBoothTypes.get(pd.Contact_Edition_Mapping__c):(new Set<String>()));
                setStr.add(pd.Booth_Product_Type__c);
                mapCEMIdBoothTypes.put(pd.Contact_Edition_Mapping__c,setStr);
                
                List<Purchase_Data__c> listPD = (mapCEMIdListPD.containsKey(pd.Contact_Edition_Mapping__c)?mapCEMIdListPD.get(pd.Contact_Edition_Mapping__c):(new List<Purchase_Data__c>()));
                listPD.add(pd);
                mapCEMIdListPD.put(pd.Contact_Edition_Mapping__c,listPD);
            }
        }

        Map<Id,Map<Id,List<Form_Data__c>>> mapCEMIdMapFormPermListFD = new Map<Id,Map<Id,List<Form_Data__c>>>();
        if(!setCEMIds.isEmpty() && Schema.sObjectType.Form_Data__c.isAccessible()){
            List<Form_Data__c> listFD = [SELECT Id, Forms_Permission__c, Forms_Permission__r.Form_Allocation__c, Contact_Edition_Mapping__c,Is_Active__c,Purchase_Data__c FROM Form_Data__c WHERE Contact_Edition_Mapping__c IN:setCEMIds AND Forms_Permission__r.Form_Allocation__c IN:setformAllocationIds];
            for(Form_Data__c fd : listFD){
                Map<Id,List<Form_Data__c>> mapFormPermListFD = (mapCEMIdMapFormPermListFD.containsKey(fd.Contact_Edition_Mapping__c)?mapCEMIdMapFormPermListFD.get(fd.Contact_Edition_Mapping__c):(new Map<Id,List<Form_Data__c>>()));
                List<Form_Data__c> lst = (mapFormPermListFD.containsKey(fd.Forms_Permission__c)?mapFormPermListFD.get(fd.Forms_Permission__c):(new List<Form_Data__c>()));
                lst.add(fd);
                mapFormPermListFD.put(fd.Forms_Permission__c,lst);
                mapCEMIdMapFormPermListFD.put(fd.Contact_Edition_Mapping__c,mapFormPermListFD);
            }
        }
        
        for(Forms_Permission__c fp : lstFP){
            Form_Allocation__c formAlloc = mapFormAllocationData.get(fp.Form_Allocation__c);
            Id formSettingId = formAlloc.Form_Setting__c;
            if(mapFormSettingIdSetEditionId.containsKey(formSettingId)){
                Set<Id> editionIds = mapFormSettingIdSetEditionId.get(formSettingId);
                List<Contact_Edition_Mapping__c> listCEM = new List<Contact_Edition_Mapping__c>();
                for(Id editionId : editionIds){
                    if(mapEditionIdListCEM.containsKey(editionId)){
                        listCEM.addAll(mapEditionIdListCEM.get(editionId));
                    }
                }
                for(Contact_Edition_Mapping__c cem : listCEM){
                    List<Form_Data__c> existingFormData = new List<Form_Data__c>();
                    Map<Id,Form_Data__c> mapExistingFormData = new Map<Id,Form_Data__c>();
                    Set<String> existingBoothProductTypes = new Set<String>();
                    if(mapCEMIdMapFormPermListFD.containsKey(cem.Id)){
                        if(mapCEMIdMapFormPermListFD.get(cem.Id).containsKey(fp.Id)){
                            existingFormData = mapCEMIdMapFormPermListFD.get(cem.Id).get(fp.Id);
                        }
                    }
                    for(Form_Data__c fd : existingFormData){
                        if(String.isNotBlank(fd.Purchase_Data__c)){
                            mapExistingFormData.put(fd.Purchase_Data__c,fd);
                        }
                    }
                    if(mapCEMIdBoothTypes.containsKey(cem.Id)){
                        existingBoothProductTypes = mapCEMIdBoothTypes.get(cem.Id);
                    }
                    if(fp.User_Type1__c == cem.Access_Type__c){
                        String formEntry = formAlloc.Form_Entry__c;
                        List<String> listBoothProductTypes = (String.isBlank(formAlloc.Booth_Product_Types__c)?new List<String>():formAlloc.Booth_Product_Types__c.split(';'));
                        if(formEntry == 'One Per Booth' || formEntry == 'Multiple Per Booth'){
                            
                            List<Purchase_Data__c> listPD = mapCEMIdListPD.containskey(cem.Id)?mapCEMIdListPD.get(cem.Id):new List<Purchase_Data__c>();
                            Set<Id> processedIds = new Set<Id>();
                            for(Purchase_Data__c pd : listPD){
                                processedIds.add(pd.Id);
                                if(listBoothProductTypes.isEmpty() || listBoothProductTypes.contains(pd.Booth_Product_Type__c)){
                                    if(mapExistingFormData.containsKey(pd.Id)){
                                        listFormDataUpdate.add(getFormDataObj(mapExistingFormData.get(pd.Id), cem, fp.Is_Active__c,pd.Id));
                                    }
                                    else{
                                        Form_Data__c newFD = getFormDataObj(new Form_Data__c(), cem, fp.Is_Active__c,pd.Id);
                                        newFD.Forms_Permission__c = fp.Id;
                                        listFormDataInsert.add(newFD);
                                    }
                                }
                                else if(mapExistingFormData.containsKey(pd.Id)){
                                    listFormDataUpdate.add(getFormDataObj(mapExistingFormData.get(pd.Id), cem, false,pd.Id));
                                }
                            }
                            
                            for(Form_Data__c oldFD: mapExistingFormData.Values()){
                                if(!processedIds.contains(oldFD.Purchase_Data__c)){
                                    listFormDataUpdate.add(new Form_Data__c(Id=oldFD.Id,Is_Active__c = false));
                                }
                            }
                        }
                        else{
                            boolean isInsert = existingFormData.isEmpty();
                            boolean isProcess = listBoothProductTypes.isEmpty();
                            for(String str : listBoothProductTypes){
                                if(String.isNotBlank(str) && existingBoothProductTypes.contains(str)){
                                    isProcess = true;
                                }
                            }
                            if(isProcess){
                                if(isInsert){
                                    Form_Data__c newFD = getFormDataObj(new Form_Data__c(), cem, fp.Is_Active__c,null);
                                    newFD.Forms_Permission__c = fp.Id;
                                    listFormDataInsert.add(newFD);
                                    system.debug(LoggingLevel.Debug, 'listFormDataInsert2 ' +listFormDataInsert);
                                }
                                else{
                                    listFormDataUpdate.add(getFormDataObj(existingFormData.get(0), cem, fp.Is_Active__c,null));
                                }
                            }
                            else if(!existingFormData.isEmpty()){
                                listFormDataUpdate.add(getFormDataObj(existingFormData.get(0), cem, false,null));
                            }
                        }
                    }
                }
            }
        }

        if(!listFormDataInsert.isEmpty() && Schema.sObjectType.Form_Data__c.IsCreateable()){
            Database.insert(listFormDataInsert,false);
            //insert listFormDataInsert;
        }
        if(!listFormDataUpdate.isEmpty() && Schema.sObjectType.Form_Data__c.isUpdateable()){
            Database.update(listFormDataUpdate,false);
            //update listFormDataUpdate;
        }
    }

    /**
    * @description  to Insert/Update form data after purchase data After Insert/Update.
    * @param  listPDNew 
    * @param  mapOldPD 
    * @param  isInsert 
    */
    public static void handleAfterInsertAfterUpdatePurchaseData(List<Purchase_Data__c> listPDNew, Map<Id,Purchase_Data__c> mapOldPD, Boolean isInsert){
        Set<Id> setCEMIds = new Set<Id>();
        Set<Id> setEditionIds = new Set<Id>();
        Map<Id,Set<Id>> mapFormSettingIdSetEditionId = new Map<Id,Set<Id>>();
        Map<Id,Form_Allocation__c> mapFormAllocationData = new Map<Id,Form_Allocation__c>();

        for(Purchase_Data__c pd : listPDNew){
            if(isInsert || (pd.Booth_Product_Type__c != mapOldPD.get(pd.Id).Booth_Product_Type__c || pd.Purchase_Status__c != mapOldPD.get(pd.Id).Purchase_Status__c || pd.Transaction_Status__c != mapOldPD.get(pd.Id).Transaction_Status__c)){
                setCEMIds.add(pd.Contact_Edition_Mapping__c);
                setEditionIds.add(pd.Edition__c);
            }
        }

        if(!setEditionIds.isEmpty()){
            List<Edition__c> listEdition = [SELECT Id, Name, Form_Setting__c, Edition_Status__c FROM Edition__c WHERE Id IN:setEditionIds WITH SECURITY_ENFORCED];
            for(Edition__c edition : listEdition){
                if(String.isNotBlank(edition.Form_Setting__c)){
                    Set<Id> setStr = (mapFormSettingIdSetEditionId.containsKey(edition.Form_Setting__c)?mapFormSettingIdSetEditionId.get(edition.Form_Setting__c):(new Set<Id>()));
                    setStr.add(edition.Id);
                    mapFormSettingIdSetEditionId.put(edition.Form_Setting__c,setStr);
                }
            }
        }
        
        Map<Id,List<Form_Allocation__c>> mapFprmSettingIdListFormAlloc = new Map<Id,List<Form_Allocation__c>>();
        if(!mapFormSettingIdSetEditionId.isEmpty()){
            mapFormAllocationData = new Map<Id,Form_Allocation__c>([SELECT Id, Booth_Product_Types__c, Form_Setting__c, Form_Entry__c, (select Id, User_Type__c, Form_Allocation__c FROM Tab_User_Types__r) FROM Form_Allocation__c WHERE Form_Setting__c IN:mapFormSettingIdSetEditionId.keySet() WITH SECURITY_ENFORCED]);
            for(Form_Allocation__c fAlloc : mapFormAllocationData.Values()){
                List<Form_Allocation__c> lst = (mapFprmSettingIdListFormAlloc.containsKey(fAlloc.Form_Setting__c)?mapFprmSettingIdListFormAlloc.get(fAlloc.Form_Setting__c):(new List<Form_Allocation__c>()));
                lst.add(fAlloc);
                mapFprmSettingIdListFormAlloc.put(fAlloc.Form_Setting__c,lst);
            }
        }

        Map<Id,List<Contact_Edition_Mapping__c>> mapEditionIdListCEM = new Map<Id,List<Contact_Edition_Mapping__c>>();
        Set<String> setUserType = new Set<String>();
        if(!setCEMIds.isEmpty()){
            List<Contact_Edition_Mapping__c> listCEM2 = [SELECT Id, Account__c, Contact__c, Edition__c, CC_Status__c, Access_Type__c FROM Contact_Edition_Mapping__c WHERE Relationship_Status__c = 'Active' AND CC_Status__c IN ('Active', 'In Progress') AND Id IN:setCEMIds AND isSecondary__c=false WITH SECURITY_ENFORCED];
            for(Contact_Edition_Mapping__c cem : listCEM2){
                List<Contact_Edition_Mapping__c> lst = (mapEditionIdListCEM.containsKey(cem.Edition__c)?mapEditionIdListCEM.get(cem.Edition__c):(new List<Contact_Edition_Mapping__c>()));
                lst.add(cem);
                mapEditionIdListCEM.put(cem.Edition__c,lst);
                setUserType.add(cem.Access_Type__c);
            }
        }

        Map<Id,Set<String>> mapCEMIdBoothTypes = new Map<Id,Set<String>>();
        Map<Id,List<Purchase_Data__c>> mapCEMIdListPD = new Map<Id,List<Purchase_Data__c>>();
        if(!setCEMIds.isEmpty()){
            List<Purchase_Data__c> listPurchaseData = [SELECT Id, Booth_Product_Type__c, Contact_Edition_Mapping__c FROM Purchase_Data__c WHERE Contact_Edition_Mapping__c IN:setCEMIds AND Booth_Number__c!=null AND Purchase_Status__c='Active' AND Transaction_Status__c ='Active' WITH SECURITY_ENFORCED];
            for(Purchase_Data__c pd : listPurchaseData){
                Set<String> setStr = (mapCEMIdBoothTypes.containsKey(pd.Contact_Edition_Mapping__c)?mapCEMIdBoothTypes.get(pd.Contact_Edition_Mapping__c):(new Set<String>()));
                setStr.add(pd.Booth_Product_Type__c);
                mapCEMIdBoothTypes.put(pd.Contact_Edition_Mapping__c,setStr);
                
                List<Purchase_Data__c> listPD = (mapCEMIdListPD.containsKey(pd.Contact_Edition_Mapping__c)?mapCEMIdListPD.get(pd.Contact_Edition_Mapping__c):(new List<Purchase_Data__c>()));
                listPD.add(pd);
                mapCEMIdListPD.put(pd.Contact_Edition_Mapping__c,listPD);
            }
        }

        Map<Id,Map<Id,List<Form_Data__c>>> mapCEMIdMapFormPermListFD = new Map<Id,Map<Id,List<Form_Data__c>>>();
        if(!setCEMIds.isEmpty()){
            List<Form_Data__c> listFD = [SELECT Id, Forms_Permission__c, Contact_Edition_Mapping__c,Is_Active__c,Purchase_Data__c FROM Form_Data__c WHERE Contact_Edition_Mapping__c IN:setCEMIds WITH SECURITY_ENFORCED];
            for(Form_Data__c fd : listFD){
                Map<Id,List<Form_Data__c>> mapFormPermListFD = (mapCEMIdMapFormPermListFD.containsKey(fd.Contact_Edition_Mapping__c)?mapCEMIdMapFormPermListFD.get(fd.Contact_Edition_Mapping__c):(new Map<Id,List<Form_Data__c>>()));
                List<Form_Data__c> lst = (mapFormPermListFD.containsKey(fd.Forms_Permission__c)?mapFormPermListFD.get(fd.Forms_Permission__c):(new List<Form_Data__c>()));
                lst.add(fd);
                mapFormPermListFD.put(fd.Forms_Permission__c,lst);
                mapCEMIdMapFormPermListFD.put(fd.Contact_Edition_Mapping__c,mapFormPermListFD);
            }
        }


        List<Form_Data__c> listFormDataInsert = new List<Form_Data__c>();
        List<Form_Data__c> listFormDataUpdate = new List<Form_Data__c>();

        List<Forms_Permission__c> lstFP = [SELECT Id,Form_Allocation__c,Is_Active__c,User_Type1__c FROM Forms_Permission__c WHERE Form_Allocation__c IN:mapFormAllocationData.keySet() AND User_Type1__c IN:setUserType WITH SECURITY_ENFORCED];
        
        for(Forms_Permission__c fp : lstFP){
            Form_Allocation__c formAlloc = mapFormAllocationData.get(fp.Form_Allocation__c);
            Id formSettingId = formAlloc.Form_Setting__c;
            if(mapFormSettingIdSetEditionId.containsKey(formSettingId)){
                Set<Id> editionIds = mapFormSettingIdSetEditionId.get(formSettingId);
                List<Contact_Edition_Mapping__c> listCEM = new List<Contact_Edition_Mapping__c>();
                for(Id editionId : editionIds){
                    if(mapEditionIdListCEM.containsKey(editionId)){
                        listCEM.addAll(mapEditionIdListCEM.get(editionId));
                    }
                }
                for(Contact_Edition_Mapping__c cem : listCEM){
                    List<Form_Data__c> existingFormData = new List<Form_Data__c>();
                    Map<Id,Form_Data__c> mapExistingFormData = new Map<Id,Form_Data__c>();
                    Set<String> existingBoothProductTypes = new Set<String>();
                    if(mapCEMIdMapFormPermListFD.containsKey(cem.Id)){
                        if(mapCEMIdMapFormPermListFD.get(cem.Id).containsKey(fp.Id)){
                            existingFormData = mapCEMIdMapFormPermListFD.get(cem.Id).get(fp.Id);
                        }
                    }
                    for(Form_Data__c fd : existingFormData){
                        if(String.isNotBlank(fd.Purchase_Data__c)){
                            mapExistingFormData.put(fd.Purchase_Data__c,fd);
                        }
                    }
                    if(mapCEMIdBoothTypes.containsKey(cem.Id)){
                        existingBoothProductTypes = mapCEMIdBoothTypes.get(cem.Id);
                    }
                    if(fp.User_Type1__c == cem.Access_Type__c){
                        String formEntry = formAlloc.Form_Entry__c;
                        List<String> listBoothProductTypes = (String.isBlank(formAlloc.Booth_Product_Types__c)?new List<String>():formAlloc.Booth_Product_Types__c.split(';'));

                        if(formEntry == 'One Per Booth' || formEntry == 'Multiple Per Booth'){
                            
                            List<Purchase_Data__c> listPD = mapCEMIdListPD.containskey(cem.Id)?mapCEMIdListPD.get(cem.Id):new List<Purchase_Data__c>();
                            Set<Id> processedIds = new Set<Id>();
                            for(Purchase_Data__c pd : listPD){
                                processedIds.add(pd.Id);
                                if(listBoothProductTypes.isEmpty() || listBoothProductTypes.contains(pd.Booth_Product_Type__c)){
                                    if(mapExistingFormData.containsKey(pd.Id)){
                                        listFormDataUpdate.add(getFormDataObj(mapExistingFormData.get(pd.Id), cem, fp.Is_Active__c,pd.Id));
                                    }
                                    else{
                                        Form_Data__c newFD = getFormDataObj(new Form_Data__c(), cem, fp.Is_Active__c,pd.Id);
                                        newFD.Forms_Permission__c = fp.Id;
                                        listFormDataInsert.add(newFD);
                                    }
                                }
                                else if(mapExistingFormData.containsKey(pd.Id)){
                                    listFormDataUpdate.add(getFormDataObj(mapExistingFormData.get(pd.Id), cem, false,pd.Id));
                                }
                            }
                            
                            for(Form_Data__c oldFD: mapExistingFormData.Values()){
                                if(!processedIds.contains(oldFD.Purchase_Data__c)){
                                    listFormDataUpdate.add(new Form_Data__c(Id=oldFD.Id,Is_Active__c = false));
                                }
                            }
                        }
                        else{
                            boolean isInsert2 = existingFormData.isEmpty();
                            boolean isProcess = listBoothProductTypes.isEmpty();
                            for(String str : listBoothProductTypes){
                                if(String.isNotBlank(str) && existingBoothProductTypes.contains(str)){
                                    isProcess = true;
                                }
                            }
                            if(isProcess){
                                if(isInsert2){
                                    Form_Data__c newFD = getFormDataObj(new Form_Data__c(), cem, fp.Is_Active__c,null);
                                    newFD.Forms_Permission__c = fp.Id;
                                    listFormDataInsert.add(newFD);
                                }
                                else{
                                    listFormDataUpdate.add(getFormDataObj(existingFormData.get(0), cem, fp.Is_Active__c,null));
                                }
                            }
                            else if(!existingFormData.isEmpty()){
                                listFormDataUpdate.add(getFormDataObj(existingFormData.get(0), cem, false,null));
                            }
                        }
                    }
                }
            }
        }

        if(!listFormDataInsert.isEmpty() && Schema.sObjectType.Form_Data__c.IsCreateable()){
            Database.insert(listFormDataInsert,false);
        }
        if(!listFormDataUpdate.isEmpty() && Schema.sObjectType.Form_Data__c.isUpdateable()){
            Database.update(listFormDataUpdate,false);
        }
    }

    private static Form_Data__c getFormDataObj(Form_Data__c fData, Contact_Edition_Mapping__c cem, Boolean isActive,String pdId){
        fData.Contact_Edition_Mapping__c = cem.Id;
        fData.Account__c = cem.Account__c;
        fData.Edition__c = cem.Edition__c;
        fData.User_Type1__c = cem.Access_Type__c;
        fData.Is_Active__c = isActive;
        fData.Purchase_Data__c = pdId;
        return fData;
    }
}