force-app/main/default/objects/Custom_Error_Log__c/Custom_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Object for logging exceptions and validations done through custom code</description>
    <label>Custom Error Log</label>
    <nameField>
        <displayFormat>CEL-{0000}</displayFormat>
        <label>Custom Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Error_Log__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>The Apex Class which Generated the Error</description>
    <label>Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Error message generated</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Method of Apex class which generated the error.</description>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/On__c.field-meta.xml
<CustomField>
    <fullName>On__c</fullName>
    <description>On which trigger call is the error generated</description>
    <label>On</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>The Stack Trace of the error.</description>
    <label>StackTrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Error Generated</description>
    <label>Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IMCC_APICallOutVisit.cls
/**
* Created/Modified By    : Girikon(Arushi [IMCC-4862])
* Created On             : 22-Nov-2022
* @description           : Helper class method can be called on demand to make API Callout 
* Test Class             : Imcc_APICallOutVisit_Test
* Code Coverage          : 100%
**/
public with sharing class IMCC_APICallOutVisit {
    /**
    * @description  to make API Callout
    */    
    @future(callOut = True)
    public static void makeGetCallout() {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('callout:Get_Call_Visit_Api2');
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        if(response.getStatusCode() == 200) {
            Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            System.debug(LoggingLevel.DEBUG, results);
        }
        else{
            Custom_Error_Log__c customLog = new Custom_Error_Log__c();
            customLog.Message__c = response.getBody();
            customLog.StackTrace__c = response.getBody();
            customLog.Type__c = response.getStatusCode() + '';
            customLog.Method__c = 'makeGetCallout';
            customLog.Apex_Class__c = 'IMCC_APICallOutVisit';
            customLog.OwnerId = UserInfo.getUserId();
            customLog.On__c = 'On Visit Get API Callout';
            Boolean byPass = true;
            if(byPass || Schema.sObjectType.Custom_Error_Log__c.isCreateable()){
                Database.insert(customLog,false); 
            }
        }
    }
}