force-app/main/default/objects/IOM_Integration_Mapping__mdt/IOM_Integration_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>IOM Integration Mapping Records with CRM Objects to IOM sync nodes</description>
    <label>IOM Integration Mapping</label>
    <pluralLabel>IOM Integration Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/IOM_Integration_Mapping__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>IOM Integration Mapping Active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IOM_Integration_Mapping__mdt/fields/Child_Node__c.field-meta.xml
<CustomField>
    <fullName>Child_Node__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Child Node in Integration Mapping Payload</description>
    <label>Child Node</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IOM_Integration_Mapping__mdt/fields/CRM_Object__c.field-meta.xml
<CustomField>
    <fullName>CRM_Object__c</fullName>
    <description>CRM sObject to map with IOM payload</description>
    <label>CRM Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>IOM_Integration_Mappings</relationshipLabel>
    <relationshipName>IOM_Integration_Mappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/IOM_Integration_Mapping__mdt/fields/CRM_Object_Field__c.field-meta.xml
<CustomField>
    <fullName>CRM_Object_Field__c</fullName>
    <description>CRM Object field API name</description>
    <inlineHelpText>Add field API Name like
For account name from opportunity add Account.Name
&amp; for Edition Name from add Edition__r.Name</inlineHelpText>
    <label>CRM Object Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IOM_Integration_Mapping__mdt/fields/IOM_Node_Data_Length__c.field-meta.xml
<CustomField>
    <fullName>IOM_Node_Data_Length__c</fullName>
    <description>IOM payload Node maximum length</description>
    <label>IOM Node Data Length</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IOM_Integration_Mapping__mdt/fields/IOM_Node_Name__c.field-meta.xml
<CustomField>
    <fullName>IOM_Node_Name__c</fullName>
    <description>IOM JSON Payload node name</description>
    <label>IOM Node Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IOM_Integration_Mapping__mdt/fields/IOM_Node_Type__c.field-meta.xml
<CustomField>
    <fullName>IOM_Node_Type__c</fullName>
    <description>IOM payload node data type</description>
    <label>IOM Node Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Date/Time</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Text Area</fullName>
            </value>
            <value>
                <fullName>Long Text Area</fullName>
            </value>
            <value>
                <fullName>Rich Text Area</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IOM_Integration_Mapping__mdt/fields/Record_Id_Filter_Field__c.field-meta.xml
<CustomField>
    <fullName>Record_Id_Filter_Field__c</fullName>
    <description>Incase of Opportunity/Amendment  use ID , for Opportunity Products &amp; OpportunityContactRole use OpportunityId</description>
    <label>Record Id Filter Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IOM_Integration_Mapping__mdt/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>is node required for OMP payload</description>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IOM_Integration_Mapping__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of IOM Integration</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Sync</fullName>
                <default>true</default>
                <label>Opportunity Sync</label>
            </value>
            <value>
                <fullName>Amendment Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/IOM_BulkUploadMetadata_Test.cls
/**
* File         :   IOM_BulkUploadMetadata_Test 
* Project      :   Order & Billing Plateform
* Created Date :   24th Jan 2022
* Created By   :   Girikon(Ashish)
* ******************************************************************************************************
 @description : Test Class to cover IOM_BulkUploadMetadata
*******************************************************************************************************
* Modification log :
* 1. 
*/
@isTest
private with sharing class IOM_BulkUploadMetadata_Test
{
    @isTest static void testUpdateBulkMetadata()
    {
        String jsonString  = '{"TEST_META001":[{"index":"1","value":"TEST_001"},{"index":"2","value":"My_Test_Node"},{"index":"3","value":"Name"},{"index":"4","value":"Opportunity"},{"index":"5","value":"255"},{"index":"6","value":"Text"},{"index":"7","value":"Id"},{"index":"8","value":"false"},{"index":"9","value":"false"},{"index":"10","value":"Opportunity Sync"},{"index":"11","value":"true"}]}';
        String mappingString = '{"0":{"fieldname":"DeveloperName","datatype":"String"},"1":{"fieldname":"MasterLabel","datatype":"String"},"2":{"fieldname":"IOM_Node_Name__c","datatype":"String"},"3":{"fieldname":"CRM_Object_Field__c","datatype":"String"},"4":{"fieldname":"CRM_Object__c","datatype":"String"},"5":{"fieldname":"IOM_Node_Data_Length__c","datatype":"Double"},"6":{"fieldname":"IOM_Node_Type__c","datatype":"Picklist"},"7":{"fieldname":"Record_Id_Filter_Field__c","datatype":"String"},"8":{"fieldname":"Required__c","datatype":"Boolean"},"9":{"fieldname":"Child_Node__c","datatype":"Boolean"},"10":{"fieldname":"Type__c","datatype":"Picklist"},"11":{"fieldname":"Active__c","datatype":"Boolean"}}';
        String customMetaDataName = 'IOM_Integration_Mapping__mdt';
        String res = IOM_BulkUploadMetadata.updateBulkMetadata(jsonString, mappingString, customMetaDataName);
        System.assertNotEquals(null, res,'Metadata Insert Failed');        
    }
    @isTest static void testGetCustomMetaDataList()
    {        
        List<IOM_BulkUploadMetadata.MdtWrapper> listMetaData = IOM_BulkUploadMetadata.getCustomMetaDataList();
        System.assertNotEquals(0,listMetaData.size(),'Metadata Objcet not found');        
    }
}