force-app/main/default/objects/Case/fields/Category_1__c.field-meta.xml
<CustomField>
    <fullName>Category_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Will consist Level 1 Categories</description>
    <label>Category 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Category__c.Level__c</field>
            <operation>equals</operation>
            <value>L1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Category__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Category_2__c.field-meta.xml
<CustomField>
    <fullName>Category_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Consist level 2 Categories</description>
    <label>Category 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Category__c.Level__c</field>
            <operation>equals</operation>
            <value>L2</value>
        </filterItems>
        <filterItems>
            <field>Case_Category__c.Parent_Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category_1__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Category__c</referenceTo>
    <relationshipLabel>Cases (Sub Category 1)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Category_3__c.field-meta.xml
<CustomField>
    <fullName>Category_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Consist Level 3 Categories</description>
    <label>Category 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Category__c.Level__c</field>
            <operation>equals</operation>
            <value>L3</value>
        </filterItems>
        <filterItems>
            <field>Case_Category__c.Parent_Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category_2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Category__c</referenceTo>
    <relationshipLabel>Cases (Category 3)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Category__c/Case_Category__c.object-meta.xml
<CustomObject>
    <description>Used for Mapping Case Categories</description>
    <label>Case Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Category__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Defines Levels of the Categories</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>L1</fullName>
            </value>
            <value>
                <fullName>L2</fullName>
            </value>
            <value>
                <fullName>L3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Category__c/fields/Parent_Category__c.field-meta.xml
<CustomField>
    <fullName>Parent_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It defines the Parent Category under which the current category will fall</description>
    <label>Parent Category</label>
    <referenceTo>Case_Category__c</referenceTo>
    <relationshipLabel>Case Categories</relationshipLabel>
    <relationshipName>Case_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/caseCategoryMappingCtrl_Test.cls
@isTest
public with sharing class caseCategoryMappingCtrl_Test {
    
     @isTest
     static void testData(){
         
        Case_Category__c objCaseCategory1 = new Case_Category__c(Name = 'Test Category1' , Level__c = 'L1');
        insert objCaseCategory1;
         
        Case_Category__c objCaseCategory2 = new Case_Category__c(Name = 'Test Category2' , Level__c = 'L2' , Parent_Category__c = objCaseCategory1.id);
        insert objCaseCategory2;
         
        Case_Category__c objCaseCategory3 = new Case_Category__c(Name = 'Test Category3' , Level__c = 'L3' , Parent_Category__c = objCaseCategory2.id);
        insert objCaseCategory3;
         
        Case objCase = new Case(Status ='New', Priority = 'Medium', Origin = 'Web',Category_1__c = objCaseCategory1.id ,Category_2__c = objCaseCategory2.id,Category_3__c= objCaseCategory3.id);
        insert objCase;
        System.AssertNotEquals(objCase, null, 'Case must not be null');
         
        LiveChatVisitor visitor = new LiveChatVisitor();
        insert visitor;
         
        LiveChatTranscript chatObj = new LiveChatTranscript(
            chatKey = '123',
            liveChatVisitorId = visitor.id,
            CaseId = objCase.Id
        );

        insert chatObj;
         
         test.startTest();
         CaseCategoryMappingCtrl.getCaseCategoryValues('L1' , null);
         CaseCategoryMappingCtrl.getCategoryValueOnCase(objCase.id);
         CaseCategoryMappingCtrl.getCategoryValueOnCase(chatObj.Id);
         
         test.stopTest();
    }
}