force-app/main/default/objects/Case/fields/Category_1__c.field-meta.xml
<CustomField>
    <fullName>Category_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Will consist Level 1 Categories</description>
    <label>Category 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Category__c.Level__c</field>
            <operation>equals</operation>
            <value>L1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Category__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Category_2__c.field-meta.xml
<CustomField>
    <fullName>Category_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Consist level 2 Categories</description>
    <label>Category 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Category__c.Level__c</field>
            <operation>equals</operation>
            <value>L2</value>
        </filterItems>
        <filterItems>
            <field>Case_Category__c.Parent_Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category_1__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Category__c</referenceTo>
    <relationshipLabel>Cases (Sub Category 1)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Category_3__c.field-meta.xml
<CustomField>
    <fullName>Category_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Consist Level 3 Categories</description>
    <label>Category 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Category__c.Level__c</field>
            <operation>equals</operation>
            <value>L3</value>
        </filterItems>
        <filterItems>
            <field>Case_Category__c.Parent_Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category_2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Category__c</referenceTo>
    <relationshipLabel>Cases (Category 3)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Category__c/Case_Category__c.object-meta.xml
<CustomObject>
    <description>Used for Mapping Case Categories</description>
    <label>Case Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Category__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Defines Levels of the Categories</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>L1</fullName>
            </value>
            <value>
                <fullName>L2</fullName>
            </value>
            <value>
                <fullName>L3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Category__c/fields/Parent_Category__c.field-meta.xml
<CustomField>
    <fullName>Parent_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It defines the Parent Category under which the current category will fall</description>
    <label>Parent Category</label>
    <referenceTo>Case_Category__c</referenceTo>
    <relationshipLabel>Case Categories</relationshipLabel>
    <relationshipName>Case_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseCategoryMappingCtrl.cls
/**
* File			: 	CaseCategoryMappingCtrl
* Project		: 	Service Console Informa
* Created By	: 	Garima Gupta(Girikon)
* Test Class	:  	CaseCategoryMappingCtrl_Test
* Coverage		:  	90%
* Created Date	: 	28th Jan 2021
 ******************************************************************************************************
* @description : class to fetch Categories on Case
 ******************************************************************************************************
* Last Modified By :
*/
public with sharing class CaseCategoryMappingCtrl {


    /**
    * @description : To Fetch Category Value from Case Category Object 
    * @param level
    * @param parentCategoryId
    * @return List<sObject>
    */
    @auraenabled
    public static List<sObject> getCaseCategoryValues(string level, string parentCategoryId) {
         
         string query;
         if(String.isNotBlank(parentCategoryId)){
            query = 'Select id,Name,Level__c,Parent_Category__c from Case_Category__c where level__c = : level and Parent_Category__c =: parentCategoryId ORDER BY Name';
         }
         else{
            query = 'Select id,Name,Level__c,Parent_Category__c from Case_Category__c where level__c = : level and Parent_Category__c =null ORDER BY Name';
         }

         return database.query(query);
    }
    
    
    /**
    * @description : To Fetch Category Value from Case Object 
    * @param recordId
    * @return Case
    */
    @AuraEnabled
    public static Case getCategoryValueOnCase(String recordId){
        Id importRecordId = recordId;
        Id caseId = recordId;
        If( importRecordId.getSObjectType().getDescribe().getName() == 'LiveChatTranscript' && Schema.sObjectType.LiveChatTranscript.isAccessible()){
            
            List<LiveChatTranscript> transcriptLst = new List<LiveChatTranscript>();
            transcriptLst = [Select Id,CaseId from LiveChatTranscript where id =: importRecordId WITH SECURITY_ENFORCED];
            caseId = !transcriptLst.isEmpty() ? transcriptLst[0].CaseId : null;
        }
      

        Case objCase = New Case();
        if (Schema.sObjectType.Case.fields.Category_1__c.isAccessible() && Schema.sObjectType.Case.fields.Category_2__c.isAccessible() && Schema.sObjectType.Case.fields.Category_3__c.isAccessible()) {
        objCase = [Select Id, Category_1__c,Category_2__c,Category_3__c,Category_1__r.Name,Category_2__r.Name,Category_3__r.Name from Case where id =: caseId WITH SECURITY_ENFORCED];
        }
        return objCase;
    }
}