force-app/main/default/objects/Form_Allocation__c/Form_Allocation__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Form Setting. It will contain the list of forms and manuals based on user type.</description>
    <label>Form Allocation</label>
    <nameField>
        <label>Form Display Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Allocation__c/fields/Form_Setting__c.field-meta.xml
<CustomField>
    <fullName>Form_Setting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to Form Setting.</description>
    <label>Form Setting</label>
    <referenceTo>Form_Setting__c</referenceTo>
    <relationshipLabel>Form Allocations</relationshipLabel>
    <relationshipName>Form_Allocations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Setting__c/Form_Setting__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will show list of forms which will be visible to which user type. It contains different form allocations.</description>
    <label>Form Setting</label>
    <nameField>
        <label>Form Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object store form details like name, description, language, category and header info.</description>
    <label>Form Template</label>
    <nameField>
        <label>Form Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IMCC_FormAllocationCtrl_Test.cls
/**
* Created/Modified By: Girikon(Keertiraj)
* Created On:          08th Nov 2021
* @description : This test class covers the apex class : IMCC_FormAllocationCtrl
* Apex Class:    IMCC_FormAllocationCtrl(85%)      
**/

@isTest
public class IMCC_FormAllocationCtrl_Test {
    
    @TestSetUp
    static void testUserData(){
        UserRole userrole = [Select Id, DeveloperName From UserRole Where DeveloperName = 'Administrator' Limit 1];
        User adminUser = [Select Id, UserRoleId From User Where Profile.Name='System Administrator' and IsActive = true Limit 1];
        adminUser.UserRoleId = userrole.Id;
        update adminUser;
    }
    
    public static testMethod void IMCC_FormAllocationCtrlTest(){        
        List<Questionnaire__c> girikonForms = IMCC_TestUtilities.createGirikonForm(250);
        Id girikonFormId = girikonForms[0].Id;
        List<Form_Setting__c> formSettings = IMCC_TestUtilities.createFormSettings(250);
        Id formSettingId = formSettings[0].Id;
        Form_Allocation__c formAlloc = IMCC_TestUtilities.createFormAllocation(girikonFormId,formSettingId);
        Test.startTest();
        try{
        IMCC_FormAllocationCtrl.getFormSubmissions(formAlloc.Id);
        }catch(exception e){}
        Profile p = [Select Id From Profile Where Name='Chatter Free User'];
        User u = new User(Username = 'test@test.com.imcctestclassuserflloc',
                                        FirstName = 'test',
                                        LastName = 'test',
                                        Email = 'test@test.com',
                                        ProfileId = p.Id,
                                        Alias='test',
                                        EmailEncodingKey = 'UTF-8',
                                        LanguageLocaleKey = 'en_US',
                                        LocaleSidKey = 'en_US',
                                        TimeZoneSidKey = 'America/Los_Angeles');
        insert u;
        system.runAs(u){
            try{
            IMCC_FormAllocationCtrl.getFormSubmissions(formAlloc.Id);
            }catch(exception e){}
        }
        Test.stopTest();
        
    }

}