force-app/main/default/objects/Form_Allocation__c/Form_Allocation__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Form Setting. It will contain the list of forms and manuals based on user type.</description>
    <label>Form Allocation</label>
    <nameField>
        <label>Form Display Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Allocation__c/fields/Approval_Required__c.field-meta.xml
<CustomField>
    <fullName>Approval_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to check if form is required or not</description>
    <label>Approval Required?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Allocation__c/fields/Email_To__c.field-meta.xml
<CustomField>
    <fullName>Email_To__c</fullName>
    <description>For adding email ids for whom the form submission response to be sent to.</description>
    <label>Email To</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Form_Allocation__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Girikon form object(Questionnaire object)</description>
    <label>Form</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Form Allocations</relationshipLabel>
    <relationshipName>Form_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Allocation__c/fields/Form_Type__c.field-meta.xml
<CustomField>
    <fullName>Form_Type__c</fullName>
    <description>Placeholder to keep formula field Form Type from Form Object</description>
    <label>Form Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Feature_Category__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>PDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Allocation__c/fields/Send_individual_forms__c.field-meta.xml
<CustomField>
    <fullName>Send_individual_forms__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To control whether to send email to mentioned email ids in the Email To field</description>
    <inlineHelpText>To control whether to send email to mentioned email ids in the Email To field</inlineHelpText>
    <label>Send individual forms</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Data__c/Form_Data__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object stores all the form summary data related to contact edition mapping, form submission and Questionnaire</description>
    <label>Form Data</label>
    <nameField>
        <displayFormat>FD-{0000000}</displayFormat>
        <label>Form Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Data__c/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up field to contact edition mapping to store in form data.</description>
    <label>Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Form Data</relationshipLabel>
    <relationshipName>Form_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Data__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up field to Edition to store in form data.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Form Data</relationshipLabel>
    <relationshipName>Form_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Data__c/fields/Form_Type__c.field-meta.xml
<CustomField>
    <fullName>Form_Type__c</fullName>
    <description>Forms_Permission__r.Form_Allocation__r.Form_Type__c</description>
    <formula>TEXT( Forms_Permission__r.Form_Allocation__r.Form_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Form Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Data__c/fields/Forms_Permission__c.field-meta.xml
<CustomField>
    <fullName>Forms_Permission__c</fullName>
    <description>This field refers to the Form Permission.</description>
    <label>Forms Permission</label>
    <referenceTo>Forms_Permission__c</referenceTo>
    <relationshipLabel>Form Data</relationshipLabel>
    <relationshipName>Form_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Form_Response_Entry__c/Form_Response_Entry__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object is used to save multi response from users.</description>
    <label>Form Response Entry</label>
    <nameField>
        <displayFormat>FormRes-{0000}</displayFormat>
        <label>Form Response Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Response Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Response_Entry__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Approval Status of form whether it is Not Required, In Review, Approved or Rejected</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Response_Entry__c/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Form Response Entries</relationshipLabel>
    <relationshipName>Form_Response_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Response_Entry__c/fields/Content_Version__c.field-meta.xml
<CustomField>
    <fullName>Content_Version__c</fullName>
    <label>Content Version</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Response_Entry__c/fields/Form_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Form_Allocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Form response shown in related tab of form allocation.</description>
    <label>Form Allocation</label>
    <referenceTo>Form_Allocation__c</referenceTo>
    <relationshipLabel>Form Response Entries</relationshipLabel>
    <relationshipName>Form_Response_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Response_Entry__c/fields/Form_Data__c.field-meta.xml
<CustomField>
    <fullName>Form_Data__c</fullName>
    <label>Form Data</label>
    <referenceTo>Form_Data__c</referenceTo>
    <relationshipLabel>Form Response Entries</relationshipLabel>
    <relationshipName>Form_Response_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Form_Response_Entry__c/fields/Form_Type__c.field-meta.xml
<CustomField>
    <fullName>Form_Type__c</fullName>
    <description>It will show the Form type of Form Allocation.</description>
    <formula>TEXT(Form_Data__r.Forms_Permission__r.Form_Allocation__r.Form_Type__c)</formula>
    <label>Form Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object use to create form question along with question type and related to Question Group(Section) and Form Questionnaires(junction object)</description>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Set a Question Type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TextPlain</fullName>
                <label>Plain Text</label>
            </value>
            <value>
                <fullName>RichText</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
                <label>Number/Currency</label>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
                <label>Information/Instruction</label>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
            <value>
                <fullName>Slider</fullName>
            </value>
            <value>
                <fullName>GPS Location</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Header/Footer</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
                <label>Time Picklist</label>
            </value>
            <value>
                <fullName>Textarea</fullName>
            </value>
            <value>
                <fullName>GPSLocate</fullName>
                <isActive>false</isActive>
                <label>GPS Locate</label>
            </value>
            <value>
                <fullName>MultiSelect</fullName>
                <isActive>false</isActive>
                <label>MultiSelect</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Store Response of each questions except Header/Footer and Information type questions.</description>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Response</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response__c/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used to manage uniqueness of the form submitted by user</description>
    <label>Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Question Response</relationshipLabel>
    <relationshipName>Question_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Form_Response_Entry__c.field-meta.xml
<CustomField>
    <fullName>Form_Response_Entry__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Form Response Entry</label>
    <referenceTo>Form_Response_Entry__c</referenceTo>
    <relationshipLabel>Question Response</relationshipLabel>
    <relationshipName>Question_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IMCC_FBUtilsHelper.cls
/*
* Created/Modified By: Girikon(Keertiraj)
* Created On:          10/11/2021
* Modified By:     Girikon(Garima)
* Modified On:          07/03/2022
* @description : This class is used to send form responses in emails.                   
* Test Class: IMCC_FBUtilsHelper_Test(87%)
*/

public with sharing class IMCC_FBUtilsHelper {
    
    public static Id getFormAllocation(Id formRespEntryId){
        List<Form_Response_Entry__c> listFormResp = new List<Form_Response_Entry__c>();
        Id formAllocId;
        
        try{
        If(formRespEntryId!=null){
            listFormResp = [SELECT Form_Data__r.Forms_Permission__r.Form_Allocation__c,Form_Data__r.Forms_Permission__r.Form_Allocation__r.Name,Form_Data__r.Forms_Permission__r.Form_Allocation__r.Form_Type__c FROM Form_Response_Entry__c WHERE Id=:formRespEntryId WITH SECURITY_ENFORCED];
        }

        System.debug(LoggingLevel.Debug, 'listFormResp'+listFormResp);
        
        if(!listFormResp.isEmpty()){
            formAllocId = listFormResp[0].Form_Data__r.Forms_Permission__r.Form_Allocation__c;
        }
        }
        catch (Exception ex) {
            HandleAllCustomException.logException(ex,'Form_Submission_Status__c', 'Form Submission Status');
        }
        return formAllocId;
    }
   
    public static List<String> getEmailIds(Id formAllocId){
        Form_Allocation__c formAlloc = new Form_Allocation__c();
        String emailTo;
        List<String> emailIds = new List<String>();
        List<Form_Allocation__c> formAllocList = new List<Form_Allocation__c>();
        
        try{
        If(formAllocId!=null && Schema.sObjectType.Form_Allocation__c.isAccessible()){
        formAllocList = [SELECT Id, Name, Email_To__c, Send_individual_forms__c, Form__c FROM Form_Allocation__c WHERE Id=:formAllocId];
        }
        if(!formAllocList.isEmpty()){
            formAlloc = formAllocList[0];
            if(formAlloc.Send_individual_forms__c==true){
                emailTo = formAlloc.Email_To__c;
                emailTo = emailTo.replaceAll('\\s+','').replace(';',',');
                emailIds = emailTo.split(',');
                System.debug('emailTo :'+emailTo);
                System.debug('emailIds1231 :'+emailIds);
            }
        }
        }
        catch (Exception ex) {
            HandleAllCustomException.logException(ex,'Form_Allocation__c', 'Form Allocation');
        }
        return emailIds;
    }
    
    public static void sendEmailFormResponse(Id formRespEntryId){
        List<Form_Response_Entry__c> listFormResp = [SELECT Content_Version__c,Form_Data__r.Forms_Permission__r.Form_Allocation__c,Approval_Status__c,Form_Data__r.Forms_Permission__r.Form_Allocation__r.Approval_Required__c,Contact_Edition_Mapping__r.Edition__r.Name,Girikon_Form__c,Girikon_Form__r.Name,Form_Data__r.Forms_Permission__r.Form_Allocation__r.Name,Form_Data__r.Forms_Permission__r.Form_Allocation__r.Form_Type__c FROM Form_Response_Entry__c WHERE Id=:formRespEntryId WITH SECURITY_ENFORCED];
        List<ContentVersion> files = [Select Id,Title,VersionData,FileType,FileExtension From ContentVersion Where Id=: listFormResp[0].Content_Version__c];
        Id formAllocId = getFormAllocation(formRespEntryId);
        List<String> emailIds = getEmailIds(listFormResp.get(0).Form_Data__r.Forms_Permission__r.Form_Allocation__c);

        Id userId = UserInfo.getUserId();
        Id formTemplateId;
        String formName;
        String editionName;
        System.debug(LoggingLevel.Debug, 'formAllocId :'+formAllocId);
        System.debug(LoggingLevel.Debug, 'emailIds :'+emailIds);
        
        try{
            String [] emailsAsArray = new String [emailIds.size()];
            Integer i = 0;
            for (String singleEmail: emailIds) {
                emailsAsArray[i++] = singleEmail;
            }

            if(!listFormResp.isEmpty()){
                editionName = listFormResp.get(0).Contact_Edition_Mapping__r.Edition__r.Name;
                formTemplateId = listFormResp.get(0).Girikon_Form__c;
                formName = listFormResp.get(0).Form_Data__r.Forms_Permission__r.Form_Allocation__r.Name;
            }
            
            if(!emailIds.isEmpty()){
                
                List<Messaging.SingleEmailMessage> mails =  new List<Messaging.SingleEmailMessage>();
                    if(listFormResp.get(0).Form_Data__r.Forms_Permission__r.Form_Allocation__r.Form_Type__c == 'Online'){
                        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                        List<String> quesRespId = new List<String>();
                        List<Attachment> attachLst = new List<Attachment>();
                        Map<String,Attachment> mapAttach = new Map<String,Attachment>();
                        String emailSubject;
                        if(listFormResp.get(0).Form_Data__r.Forms_Permission__r.Form_Allocation__r.Approval_Required__c == true && listFormResp.get(0).Approval_Status__c == 'Approved'){
                            emailSubject = 'Form Approved - '+ formName + ' : '+editionName;
                        }
                        else{
                            emailSubject = 'New form submitted - '+ formName + ' : '+editionName;
                        }
                        
                        String htmlValue = getTableEmailBody(formRespEntryId, userId); 
                        List<Question_Response__c> lst = getQuestionResponse(formRespEntryId,userId);
                        System.debug('List12333 :'+lst);
                        for(Question_Response__c qr : lst){
                            quesRespId.add(qr.Id);
                        }
                        System.debug('quesRespId :'+quesRespId);
                        if(!quesRespId.isEmpty()){
                        attachLst= [Select id,Name,Body,parentId from attachment where parentId IN : quesRespId with security_enforced order by CREATEDDATE ASC];
                        System.debug('attachLst 1:'+attachLst); 
                        for(Attachment attach : attachLst){
                            mapAttach.put(attach.parentId,attach);
                        }
                        System.debug('mapAttach :'+mapAttach);
                        }
                        
                         
                        mail.SetSubject(emailSubject);
                        mail.setHtmlBody(htmlValue);  
                        mail.setToAddresses(emailsAsArray);
                        List<Messaging.EmailFileAttachment> attachments = new List<Messaging.EmailFileAttachment>();
                        for(Attachment file: mapAttach.values()) {
                        Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
                        efa.setContentType('application/pdf');
                        efa.setFileName(file.Name);
                        efa.setBody(file.Body);
                        attachments.add(efa);
                        }
                        mail.setFileAttachments(attachments);
                        mails.add(mail);
                    }
                    else if(listFormResp.get(0).Form_Data__r.Forms_Permission__r.Form_Allocation__r.Form_Type__c == 'PDF'){
                        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                        String emailSubject;
                        if(listFormResp.get(0).Form_Data__r.Forms_Permission__r.Form_Allocation__r.Approval_Required__c == true && listFormResp.get(0).Approval_Status__c == 'Approved'){
                            emailSubject = 'Form Approved - '+ formName + ' : '+editionName; 
                        }
                        else{
                            emailSubject = 'New form submitted - '+ formName + ' : '+editionName;  
                        }
                        String htmlValue = 'Please find the attached Submission';
                        mail.SetSubject(emailSubject);
                        mail.setHtmlBody(htmlValue);
                        mail.setToAddresses(emailsAsArray);
                        List<Messaging.EmailFileAttachment> attachments = new List<Messaging.EmailFileAttachment>();
                        for(ContentVersion file: files) {
                        Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
                        efa.setFileName(file.Title+'.'+file.FileExtension);
                        efa.setBody(file.VersionData);
                        attachments.add(efa);
                        }
                        mail.setFileAttachments(attachments);
                        mails.add(mail);
                        }
                        Messaging.SendEmailResult[] results = Messaging.sendEmail(mails);
                        System.debug(LoggingLevel.Debug, 'results :'+results);
                    }
                
            }
        catch (Exception ex) {
            HandleAllCustomException.logException(ex,'Form_Allocation__c', 'Form Allocation');
        }
           
    }
    
    public static List<Question_Response__c> getQuestionResponse(Id formRespEntryId,Id userId){
        List<String> qestId= new List<String>();
        
        List<Question_Response__c> lst = new List<Question_Response__c>();
        //List<Attachment> attachLst = new List<Attachment>();
        try{
        lst = [SELECT Id,Answer__c, Question__c,Question__r.Label__c,Question__r.Type__c FROM 
                Question_Response__c WHERE Form_Response_Entry__c=:formRespEntryId and Question__r.Type__c NOt IN ('Information','Header/Footer') with security_enforced order by CREATEDDATE ASC];
        System.debug(LoggingLevel.Debug, 'lst1 '+lst);
        // for(Question_Response__c qr : lst){
        //     qestId.add(qr.Question__c);
        // }
        // if(!qestId.isEmpty()){
        //     Map<String,String> optionMap = new Map<String,String>();
        //     for(Question_Option__c  qo : [SELECT Id, Name_Long__c FROM Question_Option__c WHERE Question__c IN :qestId with security_enforced]){
        //         optionMap.put(qo.Id,qo.Name_Long__c);
        //     }
        //     for(Question_Response__c qr : lst){
        //         qr.Answer__c =  optionMap.containsKey(qr.Answer__c)?optionMap.get(qr.Answer__c):qr.Answer__c;
        //     }
        // }
        System.debug(LoggingLevel.Debug, 'lst '+lst);
        }catch (Exception ex) {
            HandleAllCustomException.logException(ex,'Question_Option__c', 'Question Option');
        }
            
        return lst;
    }
    
    public static String getTableEmailBody(Id formRespEntryId, Id userId){
        List<Question_Response__c> lst = getQuestionResponse(formRespEntryId,userId);
        List<String> qestId= new List<String>();
        Map<String,String> optionMap = new Map<String,String>();
        for(Question_Response__c quesRes : lst){
            if(quesRes.Question__r.Type__c == 'Picklist'){
                qestId.add(quesRes.Question__c);
            }
        }
        if(!qestId.isEmpty()){
               
               for(Question_Option__c  qo : [SELECT Id, Name_Long__c,Question__c FROM Question_Option__c WHERE Question__c IN :qestId with security_enforced]){
                    optionMap.put(qo.Id,qo.Name_Long__c);
                 }
                
             }
        String nameOfUser;
        List<User> lstUsr = new List<User>();
        String htmlBody='';
        try{
            if(userId!=null && Schema.sObjectType.User.isAccessible()){
                lstUsr = [Select Id,Name from User WHERE Id =:userId];  
            }     
            if(!lstUsr.isEmpty()){
                nameOfUser = lstUsr[0].Name;   
            }
            
            if(!lst.isEmpty()){
                htmlBody = 'New Form Submission Response from '+nameOfUser+'<br><br>';
                htmlBody += '<table border="1" style="border-collapse:collapse"><tr><th>Question</th><th>Answer</th></tr>';
                for(Question_Response__c qr:lst){
                    String question = qr.Question__r.Label__c;
                    String answer = optionMap.containsKey(qr.Answer__c)?optionMap.get(qr.Answer__c):qr.Answer__c;
                    htmlBody += '<tr><td>'+ question + '</td><td>' + answer + '</td></tr>';
                }
                htmlBody += '</table>';
            
                System.debug('Email Body: '+htmlBody);
            }
        }
        catch (Exception ex) {
            HandleAllCustomException.logException(ex,'Question_Response__c', 'Question Response');
        }
        return htmlBody;   
    }

}