force-app/main/default/objects/Form_Allocation__c/Form_Allocation__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Form Setting. It will contain the list of forms and manuals based on user type.</description>
    <label>Form Allocation</label>
    <nameField>
        <label>Form Display Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Data__c/Form_Data__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object stores all the form summary data related to contact edition mapping, form submission and Questionnaire</description>
    <label>Form Data</label>
    <nameField>
        <displayFormat>FD-{0000000}</displayFormat>
        <label>Form Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Data__c/fields/Form_Type__c.field-meta.xml
<CustomField>
    <fullName>Form_Type__c</fullName>
    <description>Forms_Permission__r.Form_Allocation__r.Form_Type__c</description>
    <formula>TEXT( Forms_Permission__r.Form_Allocation__r.Form_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Form Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Data__c/fields/Forms_Permission__c.field-meta.xml
<CustomField>
    <fullName>Forms_Permission__c</fullName>
    <description>This field refers to the Form Permission.</description>
    <label>Forms Permission</label>
    <referenceTo>Forms_Permission__c</referenceTo>
    <relationshipLabel>Form Data</relationshipLabel>
    <relationshipName>Form_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forms_Permission__c/Forms_Permission__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object defines the user access of the form allocation</description>
    <label>Forms Permission</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Forms Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forms_Permission__c/fields/Form_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Form_Allocation__c</fullName>
    <description>This is refer to the lookup of Form Allocation record</description>
    <label>Form Allocation</label>
    <referenceTo>Form_Allocation__c</referenceTo>
    <relationshipLabel>Forms Permissions</relationshipLabel>
    <relationshipName>Forms_Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/IMCC_CommonTableController_test.cls
/**
* Created By       :   Girikon(Garima)
* Created On       :   02/11/2021
* @description     :   Test class for IMCC_CommonTableController 
**/

@IsTest
public class IMCC_CommonTableController_test {
  @IsTest
    private static void getTest() {
        Test.startTest();
        Account acc = new Account();
        acc.Name='test acc';        
        insert acc;
        System.assertEquals('test acc',acc.Name,'True');
       
        IMCC_CommonTableController.getGenericObjectRecord('false', 'Form_Data__c','Name,Forms_Permission__r.Form_Allocation__r.Form_Type__c,Forms_Permission__r.Form_Allocation__r.Form__r.Id',10.0,true,false,-1,'Name','asc','Forms_Permission__r.Form_Allocation__r.Form_Status__c =\'Visible\'' ,true);
        IMCC_CommonTableController.getGenericObjectRecord('test', 'Form_Data__c','Name,Forms_Permission__r.Form_Allocation__r.Form_Type__c,Forms_Permission__r.Form_Allocation__r.Form__r.Id',10.0,false,false,0,'Name','asc','' ,true);
        Test.stopTest();
    }
    @isTest
    private Static void runMethods(){
        Test.startTest();
        IMCC_CommonTableController.getGenericObjectRecord('test', 'Form_Data__c','Name,Forms_Permission__r.Form_Allocation__r.Form_Type__c,Forms_Permission__r.Form_Allocation__r.Form__r.Id',10.0,true,false,0,'Name','asc','' ,true);
        IMCC_CommonTableController.getAggregateData2('Id!=null','Form_Data__c','Forms_Permission__r.Form_Allocation__r.Form_Provider__c');
        Test.stopTest();
    }
}