force-app/main/default/objects/Form_Allocation__c/Form_Allocation__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Form Setting. It will contain the list of forms and manuals based on user type.</description>
    <label>Form Allocation</label>
    <nameField>
        <label>Form Display Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forms_Permission__c/Forms_Permission__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object defines the user access of the form allocation</description>
    <label>Forms Permission</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Forms Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forms_Permission__c/fields/Form_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Form_Allocation__c</fullName>
    <description>This is refer to the lookup of Form Allocation record</description>
    <label>Form Allocation</label>
    <referenceTo>Form_Allocation__c</referenceTo>
    <relationshipLabel>Forms Permissions</relationshipLabel>
    <relationshipName>Forms_Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forms_Permission__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Only Form Data related to Active Form Permissions will be shown to customers</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forms_Permission__c/fields/Tab_User_Type__c.field-meta.xml
<CustomField>
    <fullName>Tab_User_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field refers to the tab user type</description>
    <label>Tab User Type</label>
    <referenceTo>Tab_User_Type__c</referenceTo>
    <relationshipLabel>Forms Permissions</relationshipLabel>
    <relationshipName>Forms_Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forms_Permission__c/fields/User_Type1__c.field-meta.xml
<CustomField>
    <fullName>User_Type1__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tab_User_Type__c/Tab_User_Type__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will give info on tab will be visible to which user type.</description>
    <label>Tab User Type</label>
    <nameField>
        <displayFormat>UT-{00000}</displayFormat>
        <label>Tab User Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tab User Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tab_User_Type__c/fields/Form_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Form_Allocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up field to form allocation object. One form allocation can have many tab user types.</description>
    <label>Form Allocation</label>
    <referenceTo>Form_Allocation__c</referenceTo>
    <relationshipLabel>Tab User Types</relationshipLabel>
    <relationshipName>Tab_User_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tab_User_Type__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <description>Defines user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Type__c/User_Type__c.object-meta.xml
<CustomObject>
    <label>User Type</label>
    <nameField>
        <label>User Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IMCC_FormDataHandler.cls
/**
@description   IMCC_FormDataHandler
Created By    : Aishwarya[IMCC-]
Test Class    : IMCC_FormDataHandler_Test()
Created/Modified Date   :  21//11/2021
Code Coverage - 95%
*/

public without sharing class IMCC_FormDataHandler{

    /**
    * @description  handle Tab User Type After Insert.
    * @param  lstTabUserType
    */
    public static void handleAfterInsert(List<Tab_User_Type__c> lstTabUserType){
        Set<Id> setTabUserTypeIds = new Set<Id>();
        Set<String> setFormAlocIds = new Set<String>();
        Map<String,Id> setUTypeAndFormFormId = new Map<String,Id>();
        List<Forms_Permission__c> listFormPermissionToInsert = new List<Forms_Permission__c>();
        List<Forms_Permission__c> listFormPermissionToUpdate = new List<Forms_Permission__c>();
        List<Forms_Permission__c> listFormPermission = new List<Forms_Permission__c>();
        
        for(Tab_User_Type__c tUserType : lstTabUserType){
            setTabUserTypeIds.add(tUserType.Id);
            setFormAlocIds.add(tUserType.Form_Allocation__c);
        }
        
        if(!setFormAlocIds.isEmpty()){
            listFormPermission = [SELECT Id, Form_Allocation__c, User_Type1__c, Is_Active__c FROM Forms_Permission__c WHERE Form_Allocation__c IN:setFormAlocIds WITH SECURITY_ENFORCED];
            for(Forms_Permission__c fp : listFormPermission){
                String key = fp.User_Type1__c + '-' + fp.Form_Allocation__c;
                setUTypeAndFormFormId.put(key,fp.Id);
            }
        }
        
        for(Tab_User_Type__c tabUType : lstTabUserType){
            String key = tabUType.User_Type__c +'-'+ tabUType.Form_Allocation__c;
            if(!setUTypeAndFormFormId.containsKey(key))
            {
                // initialize form permission object
                Forms_Permission__c formPermission = new Forms_Permission__c();
                formPermission.Form_Allocation__c = tabUType.Form_Allocation__c;
                formPermission.User_Type1__c = tabUType.User_Type__c;
                formPermission.Tab_User_Type__c = tabUType.Id;
                formPermission.Is_Active__c = true;
                listFormPermissionToInsert.add(formPermission);
            }
            else{
                Forms_Permission__c formPermission = new Forms_Permission__c();
                formPermission.Id = setUTypeAndFormFormId.get(key);
                formPermission.Tab_User_Type__c = tabUType.Id;
                formPermission.Is_Active__c = true;
                listFormPermissionToUpdate.add(formPermission);
            }
        }
        try{
            if(!listFormPermissionToInsert.isEmpty() && Schema.sObjectType.Forms_Permission__c.isCreateable()){
                insert listFormPermissionToInsert; // Insert List
            }
            if(!listFormPermissionToUpdate.isEmpty() && Schema.sObjectType.Forms_Permission__c.isUpdateable()){
                update listFormPermissionToUpdate;
            }
        }catch(exception ex){ex.getMessage();}
     }
     
     /**
    * @description  handle Form Allocation After Update.
    * @param  listFormAllocNew
    * @param  mapOldFormAllocation
    */
    public static void handleAfterFormAllocUpdate(List<Form_Allocation__c> listFormAllocNew, Map<Id,Form_Allocation__c> mapOldFormAllocation){
        //List<Form_Allocation__c> listFormAlloc = new List<Form_Allocation__c>();
        Set<String> setFormAlocIds = new Set<String>();
        List<Forms_Permission__c> listFormPermission = new List<Forms_Permission__c>();
        
        for(Form_Allocation__c formAlloc : listFormAllocNew){
            if(formAlloc.Booth_Product_Types__c != mapOldFormAllocation.get(formAlloc.Id).Booth_Product_Types__c){
                setFormAlocIds.add(formAlloc.Id);
                //listFormAlloc.add(formAlloc);
            }
        }
        
        if(!setFormAlocIds.isEmpty()){
            listFormPermission = [SELECT Id, Form_Allocation__c, User_Type1__c FROM Forms_Permission__c WHERE Form_Allocation__c IN: setFormAlocIds];
        }
        
        try{
            if(!listFormPermission.isEmpty() && Schema.sObjectType.Forms_Permission__c.isUpdateable()){
                Database.update(listFormPermission,false);
            }
         }catch(exception ex){ex.getMessage();}
      }
     
    /**
    * @description  handle Tab User Type After Delete.
    * @param  lstTabUserType
    */
     public static void handleAfterDeleteTabUserType(List<Tab_User_Type__c> lstTabUserType){
        try{
            Set<Id> setFormAllocIds = new Set<Id>();
            List<Forms_Permission__c> listFormPermission = new List<Forms_Permission__c>();
            for(Tab_User_Type__c tUtype : lstTabUserType){
                setFormAllocIds.add(tUtype.Form_Allocation__c);
            }
            
            if(!setFormAllocIds.isEmpty()){
                listFormPermission = [SELECT Id FROM Forms_Permission__c WHERE Form_Allocation__c IN:setFormAllocIds AND Tab_User_Type__c=null WITH SECURITY_ENFORCED];
                for(Forms_Permission__c fp : listFormPermission){
                    fp.Is_Active__c = false;
                }
            }
            
            if(!listFormPermission.isEmpty() && Schema.sObjectType.Forms_Permission__c.isUpdateable()){
                update listFormPermission;
            }
        }catch(exception ex){ex.getMessage();}
     }

     /**
    * @description  handle Tab User Type Before update.
    * @param  lstTabUserType
    * @param  mapOldTabUserType
    */
    public static void handleBeforeUpdateTabUserType(List<Tab_User_Type__c> lstTabUserType, Map<Id,Tab_User_Type__c> mapOldTabUserType){
        for(Tab_User_Type__c tUtype : lstTabUserType){
            if(tUtype.User_Type__c != mapOldTabUserType.get(tUtype.Id).User_Type__c){
                tUtype.addError('Can not update user type.Please delete and insert entry for new user type.');
            }
        }
     }
}