force-app/main/default/objects/Badge_Allocation__c/Badge_Allocation__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Badge settings. Badge allocation defines the number of badges assigned to the customer.</description>
    <label>Badge Allocation</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Badge Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badge Allocation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Badge_Allocation__c/fields/Badge_Setting__c.field-meta.xml
<CustomField>
    <fullName>Badge_Setting__c</fullName>
    <description>Lookup to Badge Setting.</description>
    <label>Badge Setting</label>
    <referenceTo>Badge_Setting__c</referenceTo>
    <relationshipLabel>Badge Allocation</relationshipLabel>
    <relationshipName>Badge_Allocation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Badge_Allocation__c/fields/Booth_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Booth_Product_Type__c</fullName>
    <description>Booth Product type are picklist values displayed from global picklist value set of Booth Product Type.</description>
    <label>Booth/Product Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Booth_Product_Type1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Badge_Allocation__c/fields/Lower__c.field-meta.xml
<CustomField>
    <fullName>Lower__c</fullName>
    <description>Defines the lower limit of quantity/Area for Product/Booth.</description>
    <inlineHelpText>Quantity/Area</inlineHelpText>
    <label>Lower</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Badge_Allocation__c/fields/Unlimited_Badges__c.field-meta.xml
<CustomField>
    <fullName>Unlimited_Badges__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked unlimited badges will be allocated for booth/product.</description>
    <label>Unlimited Badges</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Badge_Allocation__c/fields/Upper__c.field-meta.xml
<CustomField>
    <fullName>Upper__c</fullName>
    <description>Defines the upper limit of quantity/Area for Product/Booth.</description>
    <inlineHelpText>Quantity/Area</inlineHelpText>
    <label>Upper</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Badge_Allocation__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Badge_Setting__c/Badge_Setting__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will define the badge allocations available for a particular event. It will have different badge allocations.</description>
    <label>Badge Setting</label>
    <nameField>
        <label>Badge Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badge Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Unlimited_Badges__c.field-meta.xml
<CustomField>
    <fullName>Unlimited_Badges__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked unlimited badges will be allocated for booth/product.</description>
    <label>Unlimited Badges</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Badge_Setting__c.field-meta.xml
<CustomField>
    <fullName>Badge_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Badge Setting</label>
    <referenceTo>Badge_Setting__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Status__c.field-meta.xml
<CustomField>
    <fullName>Edition_Status__c</fullName>
    <description>This picklist stores the status of Edition.</description>
    <label>Edition Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Tentative</fullName>
            </value>
            <value>
                <fullName>Cancelled by Finance</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Pending Setup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/Purchase_Data__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It is the transactional information regarding the booth/product purchased.</description>
    <label>Purchase Data</label>
    <nameField>
        <displayFormat>PD-{000000000}</displayFormat>
        <label>Purchase Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Data__c/fields/Booth_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Booth_Product_Type__c</fullName>
    <description>Booth Product type are picklist values displayed from global picklist value set of Booth Product Type.</description>
    <label>Booth/Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Booth_Product_Type1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact Edition mapping</description>
    <label>Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Edition Record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Purchase_Status__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Status__c</fullName>
    <description>Lists the purchase status like Active, Inactive</description>
    <label>Purchase Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Quantity_Area__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Area__c</fullName>
    <description>Defines the value of quantity/Area for Product/Booth.</description>
    <label>Quantity/Area</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <description>Defines Transaction status like Active, Inactive</description>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <description>Defines user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Type__c/User_Type__c.object-meta.xml
<CustomObject>
    <label>User Type</label>
    <nameField>
        <label>User Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IMCC_BadgeAllocationTriggerHandler.cls
/**
* Created By     :  Girikon(Shiv[IMCC-4279])
* Created On     :  05/09/2022
* @description   :  This class is used for handle logic - If Unlimited Badges checkbox is checked on Badge_Allocation_c then Unlimited Badges checkbox will be checked on purchase Data 
					on after insert or after update of Badge Allocation. 
* Apex Test Class:  IMCC_BadgeAllocationTriggerHandler_Test(100%)
**/

public class IMCC_BadgeAllocationTriggerHandler {
    
    /**
    * @description This method will update Unlimited Badges checkbox on purchase data 
                    If Unlimited Badges checkbox is checked on Badge_Allocation_c 
    * @param newMap
    * @param oldMap
    */
    public static void handleAfterInsertAfterUpdateBadgeAllocation(Map<Id, Badge_Allocation__c> newMap,Map<Id, Badge_Allocation__c> oldMap){
        Set<Id> bgSettingIds = new Set<Id>();
        Map<Id,Edition__c> editionMap = new Map<Id,Edition__c>();  
        Map<Id,Purchase_Data__c> purchaseDataToUpdate = new Map<Id,Purchase_Data__c>();
        Map<Id,Set<Id>> badgeSettingIdEditionIds = new Map<Id,Set<Id>>();
        Map<String,Map<String,List<Purchase_Data__c>>> purchaseDataQtyMap = new Map<String,Map<String,List<Purchase_Data__c>>>();
        
        try{
            for(Badge_Allocation__c bg : newMap.Values()){
                if((oldMap == null && newMap.get(bg.id).Unlimited_Badges__c == true) || (oldMap.get(bg.id).Unlimited_Badges__c != newMap.get(bg.id).Unlimited_Badges__c)){
                    if(bg.Badge_Setting__c != null){
                        bgSettingIds.add(bg.Badge_Setting__c);
                    }
                }
            } 
            
            if(!bgSettingIds.isEmpty() && (Schema.sObjectType.Edition__c.isAccessible())){
                for(Edition__c editionData : [SELECT Id,Edition_Status__c,Badge_Setting__c FROM Edition__c WHERE Edition_Status__c = 'Confirmed' AND Badge_Setting__c IN: bgSettingIds]){
                    Set<Id> editionIds = (badgeSettingIdEditionIds.ContainsKey(editionData.Badge_Setting__c)?badgeSettingIdEditionIds.get(editionData.Badge_Setting__c):new Set<Id>());
                    editionIds.add(editionData.Id);
                    badgeSettingIdEditionIds.put(editionData.Badge_Setting__c,editionIds);
                    editionMap.put(editionData.Id,editionData);
                }              
            }
            
            if(Schema.sObjectType.Purchase_Data__c.isAccessible()){
                for(Purchase_Data__c pdData : [Select id,Unlimited_Badges__c,Quantity_Area__c,User_Type__c,Purchase_Status__c,Edition__c,Booth_Product_Type__c,Transaction_Status__c,Contact_Edition_Mapping__r.Unlimited_Badges__c from Purchase_Data__c where Edition__c IN: editionMap.keyset() And Purchase_Status__c = 'Active' And Transaction_Status__c ='Active']){
                    Map<String,List<Purchase_Data__c>> mapProdTypePDListTemp = (purchaseDataQtyMap.ContainsKey(pdData.Edition__c)?purchaseDataQtyMap.get(pdData.Edition__c):new Map<String,List<Purchase_Data__c>>());
                    List<Purchase_Data__c> pdDataList = (mapProdTypePDListTemp.ContainsKey(pdData.Booth_Product_Type__c)?mapProdTypePDListTemp.get(pdData.Booth_Product_Type__c):new List<Purchase_Data__c>());
                    pdDataList.add(pdData);
                    mapProdTypePDListTemp.put(pdData.Booth_Product_Type__c,pdDataList);
                    purchaseDataQtyMap.put(pdData.Edition__c,mapProdTypePDListTemp);                 
                }
            }
            
            for(Badge_Allocation__c badgeAllocateData : newMap.Values()){
                Set<String> boothProductTypeSet = new Set<String>();
                if(badgeAllocateData.Booth_Product_Type__c != null && badgeAllocateData.Booth_Product_Type__c !=''){
                    boothProductTypeSet.addAll(badgeAllocateData.Booth_Product_Type__c.split(';'));
                }                
                Set<String> userTypeSet = new Set<String>();
                if(badgeAllocateData.User_Type__c != null && badgeAllocateData.User_Type__c !=''){
                    userTypeSet.addAll(badgeAllocateData.User_Type__c.split(';'));
                }
                Id badgeSettingId = badgeAllocateData.Badge_Setting__c;
                Map<String,List<Purchase_Data__c>> mapProdTypePDList = new Map<String,List<Purchase_Data__c>>(); 
                for(Id editionId : badgeSettingIdEditionIds.get(badgeSettingId)){
                    mapProdTypePDList  = purchaseDataQtyMap.get(editionId);                
                }
                
                for(string boothType : boothProductTypeSet){                   
                    if(mapProdTypePDList != null && mapProdTypePDList.containsKey(boothType)){
                        List<Purchase_Data__c> pHDataList = mapProdTypePDList.get(boothType);
                        for(Purchase_Data__c pH : pHDataList){
                            Boolean cemFieldVal = pH.Contact_Edition_Mapping__r.Unlimited_Badges__c;
                            if(userTypeSet.contains(pH.User_Type__c)){
                                if(badgeAllocateData.Upper__c != null){
                                    if((badgeAllocateData.Lower__c <= pH.Quantity_Area__c) && (pH.Quantity_Area__c <= badgeAllocateData.Upper__c)){
                                        pH.Unlimited_Badges__c = (cemFieldVal?true:badgeAllocateData.Unlimited_Badges__c);
                                        purchaseDataToUpdate.put(pH.Id,pH);
                                    } 
                                }
                                else{
                                    if(badgeAllocateData.Lower__c <= pH.Quantity_Area__c){
                                        pH.Unlimited_Badges__c = (cemFieldVal?true:badgeAllocateData.Unlimited_Badges__c);
                                        purchaseDataToUpdate.put(pH.Id,pH);
                                    } 
                                }
                            }
                        }
                    }
                }                                
            } 
            if(!purchaseDataToUpdate.isEmpty())
            {
                update purchaseDataToUpdate.Values();
            }
        }
        catch (Exception ex) {
            HandleAllCustomException.logException(ex,'Badge_Allocation__c', 'After Update');
        }        
    }
}