force-app/main/default/objects/Announcement__c/Announcement__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - the object uses for the important announcements of each editions if defined</description>
    <label>Announcement</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Announcement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Announcement__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition for which Announcement has been made.</description>
    <label>Event Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Announcements</relationshipLabel>
    <relationshipName>Announcements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Announcement__c/fields/Event_Tab__c.field-meta.xml
<CustomField>
    <fullName>Event_Tab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Internal Link to the announcement if any shows that the user can open the announcement and read in.</description>
    <label>Internal Tab</label>
    <referenceTo>Event_Tabs__c</referenceTo>
    <relationshipLabel>Announcements</relationshipLabel>
    <relationshipName>Announcements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Announcement__c/fields/Link_Type__c.field-meta.xml
<CustomField>
    <fullName>Link_Type__c</fullName>
    <description>Type Of Link to announcement if any show that user can open the announcement and read in.</description>
    <label>Link Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Event_Setting__c.field-meta.xml
<CustomField>
    <fullName>Event_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Setting</label>
    <referenceTo>Event_Setting__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Event_Setting__c/Event_Setting__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child of Edition. This will set the tab visibility on the home page of a particular event.</description>
    <label>Event Setting</label>
    <nameField>
        <label>Event Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Tabs__c/Event_Tabs__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Event Setting. Defines the different tabs and tab properties for a particular event.</description>
    <label>Event Tab</label>
    <nameField>
        <displayFormat>ET-{0000000}</displayFormat>
        <label>Event Tabs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Tabs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Tabs__c/fields/Event_Setting__c.field-meta.xml
<CustomField>
    <fullName>Event_Setting__c</fullName>
    <description>Event setting for which this tabs belongs to.</description>
    <inlineHelpText>Event Setting, this Tab Belongs to</inlineHelpText>
    <label>Event Setting</label>
    <referenceTo>Event_Setting__c</referenceTo>
    <relationshipLabel>Event Tabs</relationshipLabel>
    <relationshipName>Event_Tabs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/IMCC_AnnouncementHandler.cls
/**
* Created By/Modified By     :  Girikon(Arushi[IMCC-2026],[IMCC-4300])
* Created On/Modified On     :  06/4/2022,16/Aug/2022
* @description      :   As an Ops user, I should be able to redirect to internal tab links in the portal from within the announcement description
* Apex Test Class   :   IMCC_AnnouncementHandler_Test(85%)
**/

public class IMCC_AnnouncementHandler {
    
    /**
    * @description : to check if Selected Event tab on Announcement belongs to Selected Edition of Announcement or not
    * @param newAnnouncements
    */
    public Static void checkEventTab(List<Announcement__c> newAnnouncements){
        Set<Id> eveSettingIdSet = new Set<Id>();
        Map<Id,Id> mapEditionEveSetting = new Map<Id,Id>();
        Map<Id,Set<Id>> mapeveSettingTabList = new Map<Id,Set<Id>>();
        
        for(Announcement__c annce : newAnnouncements){
            if(annce.Edition__c != null){
                eveSettingIdSet.add(annce.Edition__c);
            }
        }
        
        //map of edition as key and event setting as value
        if(!eveSettingIdSet.isEmpty()){
            for(Edition__c edition : [SELECT Id, Event_Setting__c FROM Edition__c WHERE Id=:eveSettingIdSet WITH SECURITY_ENFORCED]){
                 mapEditionEveSetting.put(edition.Id,edition.Event_Setting__c);
            } 
        }
        
        //map of event setting as key and its related event tabs list as values
        if(!mapEditionEveSetting.isEmpty()){
            for(Event_Tabs__c eveTab : [SELECT Id, Event_Setting__c FROM Event_Tabs__c WHERE Event_Setting__c IN:mapEditionEveSetting.Values() WITH SECURITY_ENFORCED]){
                Set<Id> eveTabList = (mapeveSettingTabList.ContainsKey(eveTab.Event_Setting__c)?mapeveSettingTabList.get(eveTab.Event_Setting__c):new Set<Id>());
                eveTabList.add(eveTab.Id);
                mapeveSettingTabList.put(eveTab.Event_Setting__c,eveTabList);
            }
        }
        
        for(Announcement__c annce : newAnnouncements){
            if(mapeveSettingTabList.containsKey(mapEditionEveSetting.get(annce.Edition__c)) && (annce.Event_Tab__c !=null && annce.Link_Type__c == 'Internal')){
                Set<Id> listEveTab = mapeveSettingTabList.get(mapEditionEveSetting.get(annce.Edition__c));
                //if listEveTab list does not contain the selected event tab then show the error 
                if(!listEveTab.contains(annce.Event_Tab__c)){
                    annce.addError(System.Label.Event_Tab_Other_Than_Event_Setting_Edition_Error_Message);
                }
            }
        }
    }
}