force-app/main/default/objects/Action_Team__c/Action_Team__c.object-meta.xml
<CustomObject>
    <description>Information about  team that will work on approve/reject/amendment of  Opportunites, Orders and Invoices related to editions of selected series.</description>
    <label>Action Team</label>
    <nameField>
        <displayFormat>AT# - {0000}</displayFormat>
        <label>Action Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Team__c/fields/Series__c.field-meta.xml
<CustomField>
    <fullName>Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Series to which action team belongs.</description>
    <label>Series</label>
    <referenceTo>Series__c</referenceTo>
    <relationshipName>SSC_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Team_Member__c/Action_Team_Member__c.object-meta.xml
<CustomObject>
    <description>Information about individual team members of action team.</description>
    <label>Action Team Member</label>
    <nameField>
        <displayFormat>ATM#-{0000}</displayFormat>
        <label>Action Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Team_Member__c/fields/Action_Team__c.field-meta.xml
<CustomField>
    <fullName>Action_Team__c</fullName>
    <description>Action team relation field to which action team member belongs.</description>
    <label>Action Team</label>
    <referenceTo>Action_Team__c</referenceTo>
    <relationshipLabel>Action Team Members</relationshipLabel>
    <relationshipName>SSC_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Action_Team_Member__c/fields/Action_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Action_Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to user who work as action team member for action team.</description>
    <label>Action Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SSC_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agreement__c/Agreement__c.object-meta.xml
<CustomObject>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agreement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/Change_Request__c.object-meta.xml
<CustomObject>
    <description>To capture details of amendment related to Opportunity/Order/Invoice.</description>
    <label>Amendment</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Salesforce record id</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Amendments (Account)</relationshipLabel>
    <relationshipName>Change_Rquests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Amended_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Amended_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup of amended opportunity.</description>
    <label>Amended Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Change_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Change_Request_Status__c</fullName>
    <description>Amendment Status.</description>
    <label>Change Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Amend Data Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Amendment&apos;s Edition.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Amendments</relationshipLabel>
    <relationshipName>Change_Rquests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity on which the change is being requested</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Amendments (Opportunity)</relationshipLabel>
    <relationshipName>Change_Rquests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/SSC_Notes__c.field-meta.xml
<CustomField>
    <fullName>SSC_Notes__c</fullName>
    <description>Notes from SSC Team.</description>
    <label>SSC Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Edition_Director__c.field-meta.xml
<CustomField>
    <fullName>Edition_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Lookup Field store the id of the Edition Director.</description>
    <label>Edition Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Operations_Team__c.field-meta.xml
<CustomField>
    <fullName>Operations_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refer to the operation team managing this event</description>
    <label>Operations Team</label>
    <referenceTo>Operations_Team__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operations_Team__c/Operations_Team__c.object-meta.xml
<CustomObject>
    <label>Operations Team</label>
    <nameField>
        <label>Operations Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operations Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operations_Team__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Define the edition of the operation team</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Operations Teams</relationshipLabel>
    <relationshipName>Operations_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operations_Team_Member__c/Operations_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Operations Team Member</label>
    <nameField>
        <displayFormat>OTM#-{0000}</displayFormat>
        <label>Operations Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Operations_Team_Member__c/fields/Operations_Team__c.field-meta.xml
<CustomField>
    <fullName>Operations_Team__c</fullName>
    <description>Select the operation team</description>
    <label>Operations Team</label>
    <referenceTo>Operations_Team__c</referenceTo>
    <relationshipLabel>Operations Team Members</relationshipLabel>
    <relationshipName>Operations_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approved_Rejected_At__c.field-meta.xml
<CustomField>
    <fullName>Approved_Rejected_At__c</fullName>
    <description>Datetime of Approval/Rejection by SSC user.</description>
    <label>Approved/Rejected At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approved_Rejected_By__c.field-meta.xml
<CustomField>
    <fullName>Approved_Rejected_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SSC user who Approved/Rejection.</description>
    <label>Approved/Rejected By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Reason__c</fullName>
    <description>Rejection Reason</description>
    <label>Rejection Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Series__c.field-meta.xml
<CustomField>
    <fullName>Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Series to which Opportunity&apos;s Edition belongs.</description>
    <label>Series</label>
    <referenceTo>Series__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of opportunity.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Customer Contacted</fullName>
            </value>
            <value>
                <fullName>Customer Engaged</fullName>
            </value>
            <value>
                <fullName>Proposal Sent</fullName>
            </value>
            <value>
                <fullName>Revised Proposal Sent</fullName>
            </value>
            <value>
                <fullName>Pending Accounting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Payment</fullName>
            </value>
            <value>
                <fullName>Accounting Rejected</fullName>
            </value>
            <value>
                <fullName>AR Cancel / Re-bill</fullName>
            </value>
            <value>
                <fullName>Booth/Sponsorship Cancellation</fullName>
            </value>
            <value>
                <fullName>Digital / Print Cancellation</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
            <value>
                <fullName>Online Booth Form In Review</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Pending Change</fullName>
            </value>
            <value>
                <fullName>Legacy Lost</fullName>
            </value>
            <value>
                <fullName>Legacy Cancelled</fullName>
            </value>
            <value>
                <fullName>Legacy Won</fullName>
            </value>
            <value>
                <fullName>Opportunity Cancelled</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Amended</fullName>
            </value>
            <value>
                <fullName>Customize</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Order/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition of order.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Series__c/Series__c.object-meta.xml
<CustomObject>
    <description>It defines the Series Information. Each year&apos;s Edition will be tied to a particular Series.</description>
    <label>Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Series__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Staus of Series.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SSCDashboardLtngCtrl.cls
/****
Created By    : Sachin CHaudhary
Created On    : 18/02/2020
@description  : This is common class for SSC Dashboard.
Test Class    : SSCDashboardLtngCtrl_Test - 86%
*****/

public with sharing class SSCDashboardLtngCtrl {

    /*
    * @description [This method is used to fetch record of SSC Team Member.]
    * @param       Nothing
    * @return      [List of SSC_Team_Member__c]
    */
    @AuraEnabled(cacheable=true)
    public static list<Action_Team_Member__c> getSSCTeamMember() {
        List<Action_Team_Member__c> getActionTeamRecord = new List<Action_Team_Member__c>();
            getActionTeamRecord = [SELECT Id, Name, Action_Team__c, Action_Team__r.Name, Action_Team__r.Series__c,Action_Team__r.Series__r.Name, Action_Team_Member__c, Action_Team_Member__r.Name 
                                FROM Action_Team_Member__c 
                                WHERE Action_Team_Member__c = : userInfo.getUserId()];
     
        return getActionTeamRecord;
    }
    
    /*
    * @description [This method is used to fetch record of Operation Team Member.]
    * @param       Nothing
    * @return      [List of Operations_Team_Member__c]
    */
    // @AuraEnabled(cacheable=true)
    // public static list<Operations_Team_Member__c> getOperationTeamMember() {
    //     List<Operations_Team_Member__c> getOperationTeamRecordList = new List<Operations_Team_Member__c>();
    //         getOperationTeamRecordList = [SELECT Id,Operations_Team__r.Series__c 
    //                                       FROM Operations_Team_Member__c
    //                                       WHERE User_Name__c = : userInfo.getUserId()];
    //     return getOperationTeamRecordList;
    // }

    /**
    *  @description [isSSCBrazilUser() Method query on user object to check is logged in user role is 'SSC-Brazil']
    *  @param     n/a
    *  @return   [return true if logged in user role is 'SSC-Brazil' otherwize false]
    */
    @AuraEnabled(cacheable=true)     
    public static Boolean isSSCBrazilUser(){
        Boolean isBrazilUser = false;
        List<User> userList = new List<User>();
        if(Schema.sObjectType.User.isAccessible())
        {
            userList = [Select Id from User Where Id=:UserInfo.getUserId() AND UserRole.Name='SSC-Brazil'];
        }
        if(userList.size()>0){
            isBrazilUser = true;
        }
        return isBrazilUser;
    }
  
    /**
    *  @description [getProductBrasilCondition() This method is used to fetch the product brazil table data on the basis od opportunity Id]
    *  @param     Opportunity Id
    *  @return   [return Map of Sting and sObject]
    */
    @AuraEnabled(cacheable=true)
    public static Object getProductBrasilCondition(String oppId){
        return new Map<String,Object>{
            'isShowProductHeader' => isShowProductHeader(oppId),
            'isShowProductAgg_brasil' =>isVisible('001',oppId),
            'isShowProductAgg_brasil1' =>isVisible('002',oppId),
            'isShowProductAgg_brasil2' =>isVisible('003',oppId),
            'isShowProductAgg_brasil3' =>isVisible('004',oppId),
            'isShowProductAgg_brasil4' =>isVisible('005',oppId),
            'isShowProductAgg_brasil5' =>isVisible('006',oppId),
            'isShowProductAgg_brasil6' =>isVisible('007',oppId),
            'isShowProductAgg_brasil7' =>isVisible('008',oppId),
            'isShowProductAgg_brasil8' =>isVisible('009',oppId),
            'isShowProductAgg_brasil10' =>isVisible('010',oppId),
            'isShowProductAgg_brasil11' =>isVisible('011',oppId),
            'isShowProductAgg_brasil12' =>isVisible('012',oppId),
            'isShowProductAgg_brasil13' =>isVisible('013',oppId),
            'isShowProductAgg_brasil14' =>isVisible('014',oppId),
            'isShowProductAgg_brasil15' =>isVisible('015',oppId),
            'isShowProductAgg_brasil16' =>isVisible('016',oppId),
            'isShowProductAgg_brasil17' =>isVisible('017',oppId),
            'isShowProductAgg_brasil18' =>isVisible('018',oppId),
            'isShowProductAgg_brasil19' =>isVisible('019',oppId),
            'isShowProductAgg_brasil20' =>isVisible('020',oppId),
            'isShowProductAgg_brasil21' =>isVisible('021',oppId),
            'isShowProductAgg_brasil22' =>isVisible('022',oppId),
            'isShowProductAgg_brasil23' =>isVisible('023',oppId),
            'isShowProductAgg_brasil24' =>isVisible('024',oppId),
            'isShowProductAgg_brasil25' =>isVisible('025',oppId),
            'isShowProductAgg_brasil26' =>isVisible('026',oppId)
        };
    }
    
    /**
    *  @description [isVisible() This method is used to fetch the list of Quote Line on the basis of codetype and opportunity id]
    *  @param     Code Type and Opportunity Id
    *  @return   [return boolean value]
    */
    @TestVisible
    private static Boolean isVisible(String codeType,String oppId){
        Boolean isVisible = true;
        List<SObject> objList = new List<SObject>();
        if(Schema.sObjectType.SBQQ__QuoteLine__c.isAccessible())
        {
            objList = [SELECT id 
                                 From SBQQ__QuoteLine__c 
                                 WHERE SBQQ__Quote__r.SBQQ__Opportunity2__c=:oppId 
                                 AND SBQQ__Quote__r.SBQQ__Primary__c=true];
        }
        
        if(objList.size()==0){
            isVisible = false;
        }
        return isVisible;
    }
    
    /**
    *  @description [isShowProductHeader() This method is used to fetch the list of Quote Line on the basis of primary checkbox]
    *  @param     N/A
    *  @return   [return boolean value]
    */
  @TestVisible
    private static Boolean isShowProductHeader(String oppId){
        boolean isShowProductHeader = false;
        List<SObject> objList = [SELECT id 
                                 From SBQQ__QuoteLine__c 
                                 WHERE SBQQ__Quote__r.SBQQ__Opportunity2__c=:oppId 
                                 AND SBQQ__Quote__r.SBQQ__Primary__c=true];
        if(objList.size()>0){ isShowProductHeader = false;}
        else{
            isShowProductHeader = true;
        }
        return isShowProductHeader;
    }

    /**
     * @description [Get data from aggrement custom object based on opp id. this method used on pending contract tab on SSC Dashboard]
     * @param  opportunity Id and search key
     * @return   [return List of sObject]
     */
    @AuraEnabled(cacheable=true)
    public static List<SObject> getAgreements(String oppId,String searchValue){
        List<SObject> agreementList;
        if(searchValue=='' && Schema.sObjectType.Agreement__c.isAccessible()){ agreementList = [Select Name,Opportunity__r.Name,LastModifiedDate 
                                              FROM Agreement__c 
                                              WHERE Opportunity__c=:oppId];
        } else{
            agreementList = [Select Name,Opportunity__r.Name,LastModifiedDate 
                             FROM Agreement__c
                             WHERE Opportunity__c=:oppId 
                             AND (Name like:String.escapeSingleQuotes(searchValue) OR Opportunity__r.Name like:String.escapeSingleQuotes(searchValue))];
        }
        return agreementList;
    }
    
    /**
    * approveContract Approved contract
    * @param  oppObj Pass opportunity Object
    */
    @AuraEnabled(cacheable=false)
    public static void approveContract(Opportunity oppObj){
        oppObj.Approved_Rejected_At__c = System.now();
        try{
            upsert oppObj;
        } catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    /**
    * getRejectionOptions get all option of rejection response fields
    * @return   return description
    */
    @AuraEnabled(cacheable=true)
    public static Map<String, SchemaUtils.FieldDto> getRejectionOptions(){
        Map<String,String> objectFieldsMap = new Map<String,String> {               
            'Opportunity.Rejection_Reason__c'=>'Rejection_Reason'
                };
                    Map<String, SchemaUtils.FieldDto> fields = new Map<String, SchemaUtils.FieldDto>();
        
        Map<String, SchemaUtils.FieldDto> describes = SchemaUtils.describeSobjects(objectFieldsMap.keySet());
        for (String fieldPath : describes.keySet()) {
            SchemaUtils.FieldDto field = describes.get(fieldPath);
            fields.put(objectFieldsMap.get(fieldPath), field);
        }
        return fields;
    }
    
    /**
    * getRejectionOptions get all option of rejection response fields
    * @param  sChangedValueJson Pass Updated Opportunity Id
    * @return   return void
    */
    @AuraEnabled(cacheable=false)
    public static string approveRejectAmmendedOpportunit(String sOppId, string sAction, string sSSCNotes, string sReason){
        List<Change_Request__c> listChangeRequest = new List<Change_Request__c>();
        if(Schema.sObjectType.Change_Request__c.isAccessible())
        {
            listChangeRequest = [Select Id, Account__c, Account__r.Name, Name, Edition__c,Edition__r.Name, Opportunity__c,  Opportunity__r.Name, Amended_Opportunity__c,Amended_Opportunity__r.Name,Change_Request_Status__c 
                                                     From Change_Request__c
                                                     Where Amended_Opportunity__c=:sOppId 
                                                     order by LastModifiedDate DESC 
                                                     limit 1];
        }
        Change_Request__c changeRequest = new Change_Request__c();
        if(!listChangeRequest.isEmpty()){ changeRequest=listChangeRequest[0]; }
        Opportunity toUpdateOpportunity = new Opportunity();
        if(Schema.sObjectType.Opportunity.isAccessible())
        {
            toUpdateOpportunity = [Select Id,StageName,Rejection_Reason__c,Approved_Rejected_By__c,SBQQ__PrimaryQuote__c , Approved_Rejected_At__c
                                           from Opportunity 
                                           where Id=:sOppId];
        }
        if(sAction=='Approve'){
            changeRequest.Change_Request_Status__c='Completed';
            toUpdateOpportunity.Approved_Rejected_By__c=UserInfo.getUserId();
            toUpdateOpportunity.Approved_Rejected_At__c=System.now();
        } else if(sAction=='Reject'){
            changeRequest.Change_Request_Status__c='Rejected';
            toUpdateOpportunity.StageName='Customize';
            toUpdateOpportunity.Status__c = 'Accounting Rejected';
            toUpdateOpportunity.Approved_Rejected_By__c=UserInfo.getUserId();            
            toUpdateOpportunity.Approved_Rejected_At__c=System.now();
            //toUpdateOpportunity.SSC_Notes__c=sSSCNotes;
            toUpdateOpportunity.Rejection_Reason__c=sReason;
        }
        try{
            if(!test.isRunningTest() && Schema.sObjectType.Opportunity.isUpdateable() && Schema.sObjectType.Change_Request__c.isUpdateable())
            { 
                update toUpdateOpportunity; 
                update changeRequest; 
            }
            return toUpdateOpportunity.SBQQ__PrimaryQuote__c;
        }
        catch(Exception e){
            system.debug('e.getMessage(): '+e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }        
    }
    
    /**
    * getPickListValuesIntoList get all option of rejection response fields
    * @param  sChangedValueJson Pass Updated Opportunity Id
    * @return   return void
    */
    @auraEnabled (cacheable=true)
    public static List<String> getPickListValuesIntoList(){
        List<String> pickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = Opportunity.Rejection_Reason__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }
        return pickListValuesList;        
    }
    
}