force-app/main/default/objects/Contract/fields/Default_Edition__c.field-meta.xml
<CustomField>
    <fullName>Default_Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup of Edition object.</description>
    <label>Default Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Default_Edition__c.field-meta.xml
<CustomField>
    <fullName>Default_Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Edition of Opportunity</description>
    <label>Default Edition</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Edition__c.Edition_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Contact__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Individual who is working with on this opportunity</description>
    <inlineHelpText>Individual you are working with on this opportunity</inlineHelpText>
    <label>Opportunity Contact</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Opportunity Contact)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Series__c.field-meta.xml
<CustomField>
    <fullName>Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Series to which Opportunity&apos;s Edition belongs.</description>
    <label>Series</label>
    <referenceTo>Series__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Series__c/Series__c.object-meta.xml
<CustomObject>
    <description>It defines the Series Information. Each year&apos;s Edition will be tied to a particular Series.</description>
    <label>Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Series__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/classes/SSCDashboardLtngCtrl_Test.cls
/**
* Created By       :   Girikon(Sachin[IML2R-742])
* Created On       :   Feb 25, 2020
* @description     :   Test class for SSCDashboardLtngCtrl class 80%
* Modified by      :   
**/

@IsTest
public class SSCDashboardLtngCtrl_Test {
     @IsTest
    private static void getTest()
    {
       
        //@Description: Insert Account.
        Account acc = TestDataFactoryUtils.createAccount();
        insert acc;
        System.assertEquals('Test Account', acc.name,'true');
        
       //@Description: Insert Contact.
        Contact ocontact = TestDataFactoryUtils.createContact(acc.Id);
        insert ocontact;
        
        APXTConga4__Conga_Template__c oCongaContractTemp = TestDataFactoryUtils.createCongaContractTemplate();
        insert oCongaContractTemp;
        
        APXTConga4__Conga_Template__c onCongaInv = TestDataFactoryUtils.createCongaInvoiceTemplate();
        insert onCongaInv;
        
        APXTConga4__Conga_Template__c oCongaQuoteTemp = TestDataFactoryUtils.createCongaQuoteTemplate();
        insert oCongaQuoteTemp;
        
        APXTConga4__Conga_Template__c oCongaCNTemp = TestDataFactoryUtils.createCongaCreditNoteTemplate();
        insert oCongaCNTemp;
        
        blng__LegalEntity__c oLegalEntity = TestDataFactoryUtils.createLegalEntity(oCongaContractTemp.Id,onCongaInv.Id,oCongaQuoteTemp.Id,oCongaCNTemp.Id);
        insert oLegalEntity;
        
        Series__c oSeries = TestDataFactoryUtils.createSeries(oLegalEntity.Id);
        insert oSeries;
        
        //@Description: Insert Event Edition.
        Edition__c eventEdition = TestDataFactoryUtils.createEdition(oSeries.Id, oCongaCNTemp.Id, onCongaInv.Id);
        insert eventEdition;
        
        //@Description: Insert Opportunity.
        Opportunity opp = new Opportunity();
        opp.Name = 'Testing Opportunity';
        opp.Default_Edition__c = eventEdition.Id;
        opp.Opportunity_Contact__c = ocontact.Id;
        opp.AccountId = acc.Id;
        opp.CloseDate = Date.Today().addDays(1);
        opp.stagename = 'Closed Won';
        insert opp;
        System.assertEquals('Testing Opportunity', opp.name,'true');
        
        SSCDashboardLtngCtrl.getSSCTeamMember();
        //SSCDashboardLtngCtrl.getOperationTeamMember();
        SSCDashboardLtngCtrl.isSSCBrazilUser();
        SSCDashboardLtngCtrl.getProductBrasilCondition(opp.Id);
        SSCDashboardLtngCtrl.isVisible('abcd',opp.Id);
        SSCDashboardLtngCtrl.isShowProductHeader(opp.Id);
        SSCDashboardLtngCtrl.getAgreements(opp.id,'%Test%');
        SSCDashboardLtngCtrl.approveContract(opp);
        SSCDashboardLtngCtrl.getRejectionOptions();
        SSCDashboardLtngCtrl.approveRejectAmmendedOpportunit(opp.Id,'sAction','Test','No signature on contract');
        SSCDashboardLtngCtrl.getPickListValuesIntoList();
    }
}