force-app/main/default/objects/Contract/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup of Legal Entity object.</description>
    <label>Legal Entity</label>
    <referenceTo>blng__LegalEntity__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Approval_Service_Now_ID__c.field-meta.xml
<CustomField>
    <fullName>Approval_Service_Now_ID__c</fullName>
    <description>Approval - Service Now ID</description>
    <label>Approval - Service Now ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/CC_Emails__c.field-meta.xml
<CustomField>
    <fullName>CC_Emails__c</fullName>
    <description>This field stores all CC Emails.</description>
    <inlineHelpText>Emails to be CC&apos;ed on invoices

Format for multiple emails :

abc@xyz.com,lmn@xyz.com</inlineHelpText>
    <label>CC Emails</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Contract_Template__c.field-meta.xml
<CustomField>
    <fullName>Contract_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Lookup store the id of the associated Contract Template.</description>
    <label>Contract Template</label>
    <referenceTo>APXTConga4__Conga_Template__c</referenceTo>
    <relationshipLabel>Edition (Contract Template)</relationshipLabel>
    <relationshipName>Event_Edition1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/CutoffDate_1__c.field-meta.xml
<CustomField>
    <fullName>CutoffDate_1__c</fullName>
    <description>Cutoff Date 2 for payment schedule.</description>
    <label>Cutoff Date 2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/CutoffDate_2__c.field-meta.xml
<CustomField>
    <fullName>CutoffDate_2__c</fullName>
    <description>Cutoff Date 3 for payment schedule.</description>
    <label>Cutoff Date 3</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/CutoffDate_3__c.field-meta.xml
<CustomField>
    <fullName>CutoffDate_3__c</fullName>
    <description>Cutoff Date 4 for payment schedule.</description>
    <label>Cutoff Date 4</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/CutoffDate__c.field-meta.xml
<CustomField>
    <fullName>CutoffDate__c</fullName>
    <description>Cutoff Date 1 for payment schedule.</description>
    <label>Cutoff Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Edition_Image_URL__c</fullName>
    <description>This Field stores Edition Logo Id.</description>
    <label>Edition Logo Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Status__c.field-meta.xml
<CustomField>
    <fullName>Edition_Status__c</fullName>
    <description>This picklist stores the status of Edition.</description>
    <label>Edition Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Tentative</fullName>
            </value>
            <value>
                <fullName>Cancelled by Finance</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Pending Setup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>This field stores the End date of Edition.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Informa_Logo__c.field-meta.xml
<CustomField>
    <fullName>Informa_Logo__c</fullName>
    <defaultValue>&quot;01550000003Ld8E&quot;</defaultValue>
    <description>Informa Logo</description>
    <inlineHelpText>This logo is located on the top left corner of all Conga Templates</inlineHelpText>
    <label>Informa Logo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Invoice_to_be_issued_before__c.field-meta.xml
<CustomField>
    <fullName>Invoice_to_be_issued_before__c</fullName>
    <description>The field is to be used to drive the invoice start date as per the cut off dates created on the edition. The field will subtract the entered number of days from the Cut off dates and will change the payment plan on contract based on the date on which it gets generated between the Invoicing to Start Date and Cut off Date.</description>
    <inlineHelpText>The field is to be used to drive the invoice start date as per the cut off dates created on the event edition. The field will subtract the entered number of days from the Cut off dates to calculate the Invoicing to Start From Dates.</inlineHelpText>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <description>This field is used to fetch the legal entity name from event series as per ticket no IML2R-135.</description>
    <formula>HYPERLINK(&quot;/&quot;&amp;Part_of_Series__r.Legal_Entity__c,Part_of_Series__r.Legal_Entity__r.Name,&quot;_blank&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field is used to fetch the legal entity name from event series.</inlineHelpText>
    <label>Legal Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Logo_Shape__c.field-meta.xml
<CustomField>
    <fullName>Logo_Shape__c</fullName>
    <label>Logo Shape</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rectangle</fullName>
            </value>
            <value>
                <fullName>Square</fullName>
            </value>
            <value>
                <fullName>Long Rectangle</fullName>
            </value>
            <value>
                <fullName>Small Square</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/fields/No_Invoicing__c.field-meta.xml
<CustomField>
    <fullName>No_Invoicing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>On checking this checkbox true, invoice can&apos;t be created on any associated opportunity.</description>
    <inlineHelpText>On checking this checkbox true, invoice can&apos;t be created on any associated opportunity.</inlineHelpText>
    <label>No Invoicing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/No_Order_Creation__c.field-meta.xml
<CustomField>
    <fullName>No_Order_Creation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>On checking this checkbox true, order cannot be created on any associated opportunity.</description>
    <inlineHelpText>On checking this checkbox true, order cannot be created on any associated opportunity.</inlineHelpText>
    <label>No Order Creation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Order_Creation__c.field-meta.xml
<CustomField>
    <fullName>Order_Creation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Order Creation for this Edition is Automated. If unchecked, a user with the correct permission set will have access to execute this Action</description>
    <inlineHelpText>Order Creation for this Edition is Automated. If unchecked, a user with the correct permission set will have access to execute this Action</inlineHelpText>
    <label>Order Creation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Part_of_Series__c.field-meta.xml
<CustomField>
    <fullName>Part_of_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup store value of series this edition is part of</description>
    <label>Part of Series</label>
    <referenceTo>Series__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Event_Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <description>Payment Schedule</description>
    <label>Payment Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Schedule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Quote_Template__c.field-meta.xml
<CustomField>
    <fullName>Quote_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Lookup store the id of the associated Quote Template.</description>
    <label>Quote Template</label>
    <referenceTo>APXTConga4__Conga_Template__c</referenceTo>
    <relationshipLabel>Edition (Quote Template)</relationshipLabel>
    <relationshipName>Event_Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>This field stores the Start date of Edition.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <description>This Field store the venue of Edition.</description>
    <label>Venue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the legal entity.</description>
    <inlineHelpText>This legal entity will be the default one for the quote</inlineHelpText>
    <label>Legal Entity</label>
    <referenceTo>blng__LegalEntity__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <description>This picklist provides options for all payment schedules available</description>
    <inlineHelpText>This picklist provides options for all payment schedules available</inlineHelpText>
    <label>Payment Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Schedule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Series__c.field-meta.xml
<CustomField>
    <fullName>Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Series to which Opportunity&apos;s Edition belongs.</description>
    <label>Series</label>
    <referenceTo>Series__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>First Due date</description>
    <inlineHelpText>First Due date</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Series__c/Series__c.object-meta.xml
<CustomObject>
    <description>It defines the Series Information. Each year&apos;s Edition will be tied to a particular Series.</description>
    <label>Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Series__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Legal Entity for Series.</description>
    <label>Legal Entity</label>
    <referenceTo>blng__LegalEntity__c</referenceTo>
    <relationshipLabel>Series</relationshipLabel>
    <relationshipName>Event_Series</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataFactoryUtils.cls
/**
* File:          TestDataFactoryUtils
* Project:       Greenfield 
* Created Date:  30 Jan 2020
* Created By:    Prashant(Girikon)
* *******************************************************************************************************
* @description : This class is used as a Test Data Factory for all test classes.
* *******************************************************************************************************
* History:       Yash Gupta(3/26/2020), Remove Event_Type__c, Invoice_Template__c, Credit_Note_Template__c field from edition obj inst.
*/

public with sharing class TestDataFactoryUtils {

    /**
    * @description Made a wrapper to get all the parameters required for Opportunity.
    */ 
    public class WrapperOpportunity
    {
        /**
        * @description For getting Account Id for Opportunity
        */
        public Id accountId{get;set;}
        /**
        * @description For getting Series Id for Opportunity
        */
        public Id seriesId{get;set;}
        /**
        * @description For getting Edition Id for Opportunity
        */
        public Id editionId{get;set;}
        /**
        * @description For getting Contact Id for Opportunity
        */
        public Id contactId{get;set;}
    }

    /**
    * @description Method is used for creating Account
    * @return Account
    */
    public static Account createAccount(){
        Account testAccount = new Account();
        testAccount.Name = 'Test Account';
        testAccount.CurrencyIsoCode = 'USD';
        testAccount.Phone = '2423122323';
        testAccount.BillingCountry='India';
        testAccount.BillingPostalCode='121212';
        testAccount.BillingCity='Noida';
        testAccount.BillingState='Uttar Pradesh';
        testAccount.BillingStreet='ABC';
        return testAccount;
    }

    /**
    * @description Method is used for creating Contact
    * @param accountId
    * @return Contact
    */
    public static Contact createContact(Id accountId){
        Contact testContact = new Contact();
        testContact.LastName = 'Test Contact';
        testContact.Email = 'test@test.com';
        testContact.AccountId = accountId;
        testContact.MailingStreet = 'Test';
        testContact.MailingCity = 'Test';
        testContact.MailingState = '';
        testContact.MailingCountry = 'India';
        testContact.Phone = '2423122323';
        testContact.AssistantPhone = '2423122323';
        testContact.HomePhone = '2121212121';
        testContact.MobilePhone = '2121212145';
        testContact.OtherPhone = '2154215421';
        return testContact;
    }

    /**
    * @description Method is used for creating Conga Contract Template
    * @return APXTConga4__Conga_Template__c
    */
    public static APXTConga4__Conga_Template__c createCongaContractTemplate() {
        APXTConga4__Conga_Template__c congaTemp = new APXTConga4__Conga_Template__c();
        congaTemp.APXTConga4__Name__c = 'Test Contract';
        congaTemp.APXTConga4__Template_Group__c = 'Contract';
        congaTemp.APXTConga4__Template_Type__c = 'Document';
        return congaTemp;
    }

    /**
    * @description Method is used for creating Conga Invoice Template
    * @return APXTConga4__Conga_Template__c
    */
    public static APXTConga4__Conga_Template__c createCongaInvoiceTemplate() {
        APXTConga4__Conga_Template__c congaTemp = new APXTConga4__Conga_Template__c();
        congaTemp.APXTConga4__Name__c = 'Test Invoice';
        congaTemp.APXTConga4__Template_Group__c = 'Invoice';
        congaTemp.APXTConga4__Template_Type__c = 'Document';
        return congaTemp;
    }

    /**
    * @description Method is used for creating Conga Quote Template
    * @return APXTConga4__Conga_Template__c
    */
    public static APXTConga4__Conga_Template__c createCongaQuoteTemplate() {
        APXTConga4__Conga_Template__c congaTemp = new APXTConga4__Conga_Template__c();
        congaTemp.APXTConga4__Name__c = 'Test Quote';
        congaTemp.APXTConga4__Template_Group__c = 'Quote';
        congaTemp.APXTConga4__Template_Type__c = 'Document';
        return congaTemp;
    }

    /**
    * @description Method is used for creating Conga Credit Note Template
    * @return APXTConga4__Conga_Template__c
    */
    public static APXTConga4__Conga_Template__c createCongaCreditNoteTemplate() {
        APXTConga4__Conga_Template__c congaTemp = new APXTConga4__Conga_Template__c();
        congaTemp.APXTConga4__Name__c = 'Test QCredit Noteuote';
        congaTemp.APXTConga4__Template_Group__c = 'Credit Note';
        congaTemp.APXTConga4__Template_Type__c = 'Document';
        return congaTemp;
    }

    /**
    * @description Method is used for creating Legal Entity
    * @param congaContractTemplId
    * @param congaInvoiceTemplId
    * @param congaQuoteTemplId
    * @param congaCreditNoteTemplId
    * @return blng__LegalEntity__c
    */
    public static blng__LegalEntity__c createLegalEntity(Id congaContractTemplId, Id congaInvoiceTemplId, Id congaQuoteTemplId, Id congaCreditNoteTemplId) {
        blng__LegalEntity__c legalEntity = new blng__LegalEntity__c();
        legalEntity.Name = 'Test Legal';
        legalEntity.blng__Active__c=true; 
        legalEntity.blng__Country__c='USA';
        legalEntity.Contract_Template__c = congaContractTemplId;
        legalEntity.Invoice_Template__c = congaInvoiceTemplId;
        legalEntity.Quote_Template__c = congaQuoteTemplId;
        legalEntity.Credit_Note_Template__c = congaCreditNoteTemplId;
        return legalEntity;
    }

    /**
    * @description Method is used for creating Series
    * @param legalEntityId
    * @return Series__c
    */
    public static Series__c createSeries(Id legalEntityId){

        Series__c testSeries = new Series__c();
        testSeries.Name = 'Arab Health';
        testSeries.CurrencyISOCode = 'USD';
        testSeries.Legal_Entity__c = LegalEntityId;
        return testSeries;
    }

    /**
    * @description Method is used for creating Edition
    * @param seriesId
    * @param congaCreditNoteTemplId
    * @param congaInvoiceTemplId
    * @return Edition__c
    */
    public static Edition__c createEdition(Id seriesId, Id congaCreditNoteTemplId, Id congaInvoiceTemplId){
        Edition__c testEdition = new Edition__c(Name = 'Arab Health 2020');        
        testEdition.Approval_Service_Now_ID__c = '123';
        testEdition.CurrencyIsoCode = 'USD';
        testEdition.Edition_Code__c = 'KDB,KDB2';     
        testEdition.Part_Of_Series__c = seriesId;
        testEdition.Start_Date__c = Date.today();
        testEdition.End_Date__c = Date.today()+ 30;
        testEdition.Invoice_to_be_issued_before__c = '30';
        testEdition.Venue__c = 'abc';
        testEdition.Payment_Schedule__c = '25-25-25-25';
        testEdition.CutoffDate__c = Date.today();
        testEdition.CutoffDate_1__c = Date.today()+30;
        testEdition.CutoffDate_2__c = Date.today()+60;
        testEdition.CutoffDate_3__c = Date.today()+90;
        testEdition.CC_Emails__c = 'test@test.com';
        testEdition.Informa_Logo__c = 'testLogo';
        testEdition.Edition_Image_URL__c = 'testImage';
        testEdition.Logo_Shape__c = 'Rectangle';
        testEdition.Edition_Status__c  = 'Active';
        testEdition.No_Order_Creation__c = false;
        testEdition.Order_Creation__c = false;
        testEdition.Order_Creation__c = false;
        //testEdition.No_Invoicing__c = false;
        testEdition.Invoice_Creation__c = false;
        testEdition.Edition_Type__c = 'Conference';
        return testEdition;
    }

    /**
    * @description Method is used for creating Opportunity
    * @param opp
    * @return Opportunity
    */
    public static Opportunity createOpportunity(WrapperOpportunity opp){

        Opportunity testOpportunity = new Opportunity();
        testOpportunity.Name = 'Test Opportunity';
        testOpportunity.CloseDate = Date.today();
        testOpportunity.StageName = 'Proposal';
        testOpportunity.Default_Edition__c = opp.editionId;
        testOpportunity.Series__c = opp.seriesId;
        testOpportunity.AccountId = opp.accountId;
        testOpportunity.Billing_Contact__c = opp.contactId;
        testOpportunity.Bill_To_Account__c = opp.accountId;
        testOpportunity.Address_Status__c = 'Valid';
        return testOpportunity;
    }
}