force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <description>This field is used to fetch the legal entity name from event series as per ticket no IML2R-135.</description>
    <formula>HYPERLINK(&quot;/&quot;&amp;Part_of_Series__r.Legal_Entity__c,Part_of_Series__r.Legal_Entity__r.Name,&quot;_blank&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field is used to fetch the legal entity name from event series.</inlineHelpText>
    <label>Legal Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Part_of_Series__c.field-meta.xml
<CustomField>
    <fullName>Part_of_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup store value of series this edition is part of</description>
    <label>Part of Series</label>
    <referenceTo>Series__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Event_Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Default_Edition__c.field-meta.xml
<CustomField>
    <fullName>Default_Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Edition of Opportunity</description>
    <label>Default Edition</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Edition__c.Edition_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the legal entity.</description>
    <inlineHelpText>This legal entity will be the default one for the quote</inlineHelpText>
    <label>Legal Entity</label>
    <referenceTo>blng__LegalEntity__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Series__c/Series__c.object-meta.xml
<CustomObject>
    <description>It defines the Series Information. Each year&apos;s Edition will be tied to a particular Series.</description>
    <label>Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Series__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Legal Entity for Series.</description>
    <label>Legal Entity</label>
    <referenceTo>blng__LegalEntity__c</referenceTo>
    <relationshipLabel>Series</relationshipLabel>
    <relationshipName>Event_Series</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityLegalEntityUpdate_Trig.cls
/**
* File:          OpportunityLegalEntityUpdate_Trig
* Project:       GAP
* Created Date:  12/10/2019
* Created By:    Sachin Chaudhary
* Modified By:   Trusha
* Modified Date: 01/13/2020 
* Test Class:   OpportunityLegalEntityUpdate_Trig_Test
* Test Coverage: 100%
* *******************************************************************************************************
* @description : Sharing Class to update the Legal Entity, Tax Jurisdiction on opportunity.
*/

public with sharing class OpportunityLegalEntityUpdate_Trig implements TriggerInterface_Opportunity.Runnable {

    /*
    * @description [Variable Declarations]
    */
    Set<String> setOpportunityEdition = new Set<String>();

    /**
    * @description [Call Interface Class to fetch the new list and old map of opportunity]
    * @param trig [fetch the trigger new list and old map]
    */
    public void run(TriggerInterface_Opportunity.Trig trig) {
        if(trig.isBefore && (trig.isInsert || trig.isUpdate)){
            opportunityLegalEntityUpdate(trig.newList);
        }
    }
    
    /**
    * @description [this method is used to Update Legal Entity & Tax Jurisdiction on affected Opportunities]
    * @param lstOpportunity [list of opportunity]
    */
    public void opportunityLegalEntityUpdate ( List <Opportunity> lstOpportunity) {
        for(Opportunity opp : lstOpportunity){
            if(opp.Default_Edition__c != null && opp.Legal_Entity__c == null){
                setOpportunityEdition.add(opp.Default_Edition__c);
            }
        }
        
        if(!setOpportunityEdition.isEmpty() &&  Schema.sObjectType.Edition__c.isAccessible()){
            Map<Id,Edition__c> mapEditionAndSeries = new  Map<Id,Edition__c>([SELECT Id, Part_of_Series__r.Legal_Entity__c FROM Edition__c WHERE ID IN: setOpportunityEdition]);
            for(Opportunity opp : lstOpportunity){
                if(mapEditionAndSeries.containsKey(opp.Default_Edition__c)){
                    //Updating Legal Entity on Opportunity.
                    opp.Legal_Entity__c = mapEditionAndSeries.get(opp.Default_Edition__c).Part_of_Series__r?.Legal_Entity__c;
                }
            }
        }
    }
}