force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <description>This field is used to fetch the legal entity name from event series as per ticket no IML2R-135.</description>
    <formula>HYPERLINK(&quot;/&quot;&amp;Part_of_Series__r.Legal_Entity__c,Part_of_Series__r.Legal_Entity__r.Name,&quot;_blank&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field is used to fetch the legal entity name from event series.</inlineHelpText>
    <label>Legal Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition_Setting__mdt/Edition_Setting__mdt.object-meta.xml
<CustomObject>
    <description>IOM/IE Edition Settings  [IE-27/28]</description>
    <label>IOM Edition Setting</label>
    <pluralLabel>IOM Edition Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Edition_Setting__mdt/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition_Setting__mdt/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Legacy CRM Instance</description>
    <label>Legacy CRM Instance</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Penton</fullName>
            </value>
            <value>
                <fullName>Payment Portal</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition_Setting__mdt/fields/Set_Override_Billing_Date_to_OrderDate__c.field-meta.xml
<CustomField>
    <fullName>Set_Override_Billing_Date_to_OrderDate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true the FI order should be produced at the same date as the order date.-[IE-192]</description>
    <label>Set Override Billing Date to OrderDate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition of order.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Legacy CRM Instance</description>
    <label>Legacy CRM Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legacy_CRM_Instance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Legal Entity is set from the Quote</description>
    <label>Legal Entity</label>
    <referenceTo>blng__LegalEntity__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Product_Count__c.field-meta.xml
<CustomField>
    <fullName>Order_Product_Count__c</fullName>
    <description>Count of Order Products.</description>
    <label>Order Product Count</label>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Bill_at_Start_of_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Bill_at_Start_of_Campaign__c</fullName>
    <description>Bill at Start of Campaign</description>
    <formula>SBQQ__QuoteLine__r.Bill_at_Start_of_Campaign__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill at Start of Campaign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order - Opportunity - Default Edition  [IOM-221]</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <description>Only related to the Print Magazine Advert Issue Product.</description>
    <inlineHelpText>Issue Date for a Magazine Issue</inlineHelpText>
    <label>Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Set_Override_Next_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Set_Override_Next_Billing_Date__c</fullName>
    <description>Set the override next billing date field based on the End Date automatically If true [IOM-1458]</description>
    <formula>Product2.Set_Override_Next_Billing_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Set Override Next Billing Date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateFieldsOnOrderItem_Helper.cls
/**
* File:         UpdateFieldsOnOrderItem_Helper
* Project:      PoC SFDC Informa 
* Test Class:   UpdateFieldsOnOrderItem_Test
* Coverage:     100%
* *******************************************************************************************************
* @description : Helper Class to set the Legal Entity From Order , Hold Billing , Invoice Run  Processing Status on the order Item
* 				 
* @author: Ayoub Ouarti (aouarti@salesforce.com)
* @date: 07/02/2020
* *******************************************************************************************************
History
-------
VERSION         AUTHOR              DATE            DETAIL
1.0         Ayoub Ouarti        05/12/2019      Initial Dev
2.0         Girikon(Ashish)     05 May 2022     IOM-1458  - Set the override next billing date field based on the End Date automatically for specific products
* *******************************************************************************************************/
public class UpdateFieldsOnOrderItem_Helper implements Queueable{
    public Set<Id> setOrderIds  ;
    List<OrderItem> listOrderProduct;
    
    /**
* @description [This method is constructor for UpdateFieldsOnOrderItem_Helper class]
* @param setOrderIds set Order Ids
* @param listOrderProduct List Order Products
*/
    public UpdateFieldsOnOrderItem_Helper(Set<Id> setOrderIds, List<OrderItem> listOrderProduct){
        this.setOrderIds = setOrderIds;
        this.listOrderProduct = listOrderProduct;
    }
    
    /**
* @description [This method is execute for UpdateFieldsOnOrderItem_Helper Class]
* @param context List Order
*/
    public void execute(QueueableContext context) {
        updateFieldsOnOrderProduct(this.setOrderIds, this.listOrderProduct);
    }
    
    /**
* @description [This method is for updating order line items]
* @param setOrderIds List Order
* @param listOrderProduct List Order Products
*/
    public static void updateFieldsOnOrderProduct(Set<Id> setOrderIds, List<OrderItem> listOrderProduct){
        List<Order> listOrder = Database.query('SELECT Id ,Legal_Entity__c,Order_Product_Count__c from Order where id IN :setOrderIds');
        
        Map<Id,Order> mapOrders = new Map<Id,Order>(listOrder);
        Map<Id,OrderItem> mapOrderItem = new Map<Id,OrderItem>();
        Set<Id> orderIds = new Set<Id>();
        Boolean isCalculateTax = false;
        
        Map<Id,Boolean> orderAllOrverRideNextBillDtFlagMap = getOrderAllOrverRideNextBillDtFlagMap(mapOrders);
        Map<Id,Order> orderMap = new Map<Id,Order>([SELECT Id,Edition__c,Edition__r.Edition_Code__c,Legacy_CRM_Instance__c FROM Order WHERE Id in:setOrderIds WITH SECURITY_ENFORCED]);
        // MAP of Edtion Code & Legacy CRM With Edition Settings
        Map<String,Edition_Setting__mdt> mapEditionSt = InvoiceTaxApiSynchronization_Trig.getEditionSettingsMapOnEditionCodeLegacyCRM();
        
        for(OrderItem oi : listOrderProduct){
            string key = orderMap.get(oi.OrderId).Edition__r.Edition_Code__c+'_'+orderMap.get(oi.OrderId).Legacy_CRM_Instance__c;
            
            Boolean orderSetBillingDate =  String.isNotBlank(key) && mapEditionSt.containsKey(key)?(mapEditionSt.get(key)?.Set_Override_Billing_Date_to_OrderDate__c):false;
            
            OrderItem orderItem = new OrderItem();
            orderItem.Id = oi.Id;
            orderItem.Edition__c = orderMap.get(oi.OrderId).Edition__c;
            if(oi.blng__LegalEntity__c == null ){
                orderItem.blng__LegalEntity__c = mapOrders.get(oi.OrderId).Legal_Entity__c; 
                mapOrderItem.put(orderItem.id, orderItem);
                isCalculateTax = true;
                orderIds.add(oi.OrderId);
            }
            if(oi.Issue_Date__c != null){
                orderItem.blng__HoldBilling__c = 'Yes';
                mapOrderItem.put(orderItem.id,orderItem);
            }
            if(oi.Quantity < 0){
                orderItem.blng__InvoiceRunProcessingStatus__c = 'Will Not Invoice';
                mapOrderItem.put(orderItem.id,orderItem);
            }
            // [IOM-1458] - On Insert only
            //Set the override next billing date field based on the End Date automatically for specific products
            if(orderSetBillingDate && oi.Set_Override_Next_Billing_Date__c){
                orderItem.blng__OverrideNextBillingDate__c = Date.today();
                system.debug('if'+orderItem.blng__OverrideNextBillingDate__c);
                mapOrderItem.put(orderItem.id,orderItem);
            }else if(oi.Set_Override_Next_Billing_Date__c
               && !oi.Bill_at_Start_of_Campaign__c
               && orderAllOrverRideNextBillDtFlagMap.containsKey(oi.OrderId) 
               && orderAllOrverRideNextBillDtFlagMap.get(oi.OrderId)
               && oi.EndDate != null)
            {
                orderItem.blng__OverrideNextBillingDate__c = oi.EndDate.addDays(1);
                system.debug('elseif'+orderItem.blng__OverrideNextBillingDate__c);
                mapOrderItem.put(orderItem.id,orderItem);
            }
        }
        
        upsert mapOrderItem.values();
        
        if(!orderIds.isEmpty() && isCalculateTax){CalculateTaxOnOrderItemUpdate_Trig.processOrderTax(orderIds);}
    }
    
    /**
* @description : This method is for geting a map of Order Id and a Flag value which is True id All OLI is set for Override Next Billing Date from Product [IOM-1458]
* @param orderMap Order Map key = OrderId ,value = Order data 
* @return Map<Id,Boolean> - Id - Order Id , val - Flag to Change Next Over Ride DT.
*/
    public static Map<Id,Boolean> getOrderAllOrverRideNextBillDtFlagMap(Map<Id,Order> orderMap)
    {
        Map<Id,Boolean> orderAllOrverRideNextBillDtFlagMap = new Map<Id,Boolean>();
        for (AggregateResult ar :  [SELECT OrderId,Count(Id) FROM OrderItem WHERE OrderId IN:orderMap.keySet() AND Set_Override_Next_Billing_Date__c = true GROUP BY OrderId])  
        {
            Id orderID =  (Id)ar.get('OrderId');
            Integer overRideNextBDtOLICount = (Integer)ar.get('expr0');
            Boolean orFlag = (orderMap.get(orderID).Order_Product_Count__c == overRideNextBDtOLICount) ? true:false;
            orderAllOrverRideNextBillDtFlagMap.put(orderID, orFlag);
        }
        return orderAllOrverRideNextBillDtFlagMap;
    }
}