force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition of order.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order - Opportunity - Default Edition  [IOM-221]</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <description>Payment Term of Product</description>
    <label>Product Edition Payment Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Invoice_property__c.field-meta.xml
<CustomField>
    <fullName>Product_Invoice_property__c</fullName>
    <description>Invoice property of Product</description>
    <label>Product Edition Invoice property</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Edition__c/Product_Edition__c.object-meta.xml
<CustomObject>
    <description>Junction object between products and editions to allow users to sell products to specific events</description>
    <label>Product Edition</label>
    <nameField>
        <displayFormat>PE-{00000}</displayFormat>
        <label>Product Edition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Editions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Edition__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Product Editions</relationshipLabel>
    <relationshipName>Product_Editions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Edition__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__PaymentTerm</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Edition__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Editions</relationshipLabel>
    <relationshipName>Product_Editions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Edition__c/fields/Product_Invoice_property__c.field-meta.xml
<CustomField>
    <fullName>Product_Invoice_property__c</fullName>
    <description>The field on a product-Edition level to influence the billing schedules on the order product.

&quot;Pay in Full”: then it’s one billing transaction with 100 % irrespective of payment schedule on Event edition/quote/oppty and with the &quot;Billing Target date&quot; = today ().

&quot;Pay as per Invoice Plan”: this is just paying as per event cut-off dates (overridden dates during oppty /quote)

&quot;Pay in Full as per the first invoice schedule&quot;: then it’s one billing transaction with 100 % with the &quot;Billing Target date&quot; of First Schedule cut-off date - number of days that customer has to pay (Net30).

&quot;Pay in Full as per the second invoice schedule”, then it’s one billing transaction with 100 % with the &quot;Billing Target date&quot; of second Schedule cut-off date - number of days that customer has to pay (Net30)</description>
    <label>Product Invoice property</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invoice as per Invoice Plan</fullName>
            </value>
            <value>
                <fullName>Invoice in Full</fullName>
            </value>
            <value>
                <fullName>Invoice in Full as per the first invoice schedule</fullName>
            </value>
            <value>
                <fullName>Invoice in Full as per the second invoice schedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentTermAndProdInvoProp_Trig.cls
/**
* File:         PaymentTermAndProdInvoProp_Trig
* Project:      PoC SFDC Informa 
* Test Class:   PaymentTermAndProdInvoProp_Test
* Coverage:     100%
* *******************************************************************************************************
* @description : Trigger Hundler on OrderItem to set the Product Invoice property & the Payement term on the order Item 
*          From Edition Product
* @author: Ayoub Ouarti (aouarti@salesforce.com)
* @date: 17/12/2019
* *******************************************************************************************************
History
-------
VERSION         AUTHOR              DATE            DETAIL
1.0         Ayoub Ouarti      17/12/2019      Initial Dev

* *******************************************************************************************************/
public class PaymentTermAndProdInvoProp_Trig implements TriggerInterface_OrderItem.Runnable{
    public void run(TriggerInterface_OrderItem.Trig trig) {
        if (trig.isBefore && trig.isInsert ) {
            
            if (trig.triggerSize > 0) {                
                Set<Id> productIds = new Set<Id>();
                Set<Id> editionIds = new Set<Id>();
                for(OrderItem oi : trig.newList){
                    productIds.add(oi.Product2Id);
                    editionIds.add(oi.Edition__c);
                }
                
                List<Product_Edition__c > listProductEdition = Database.query('SELECT Product__c ,Edition__c ,Product_Invoice_property__c , Payment_Term__c from Product_Edition__c  where Product__c IN :productIds AND  Edition__c IN :editionIds');
                for(OrderItem eachOrderItem : trig.newList){
                    for(Product_Edition__c eachProductEdition :listProductEdition ){
                        if(eachOrderItem.Edition__c == eachProductEdition.Edition__c && eachOrderItem.Product2Id == eachProductEdition.Product__c ){
                            System.Debug('INFO: Update Product_Invoice_property__c  and Payment_Term__c');
                            eachOrderItem.Product_Invoice_property__c =eachProductEdition.Product_Invoice_property__c;
                            eachOrderItem.Payment_Term__c =eachProductEdition.Payment_Term__c;
                            break;
                        }  
                    } 
                }
            }
        }
    }
}