force-app/main/default/objects/API_Synchronization_Item__c/API_Synchronization_Item__c.object-meta.xml
<CustomObject>
    <description>object will contain actual information of sync status of account and contact.</description>
    <label>API Synchronization Item</label>
    <nameField>
        <displayFormat>ASI-{0000}</displayFormat>
        <label>API Synchronization Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Synchronization Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Synchronization_Item__c/fields/API_Synchronization_Transaction__c.field-meta.xml
<CustomField>
    <fullName>API_Synchronization_Transaction__c</fullName>
    <description>API Synchronization Transaction</description>
    <label>API Synchronization Transaction</label>
    <referenceTo>API_Synchronization_Transaction__c</referenceTo>
    <relationshipLabel>API Synchronization Items</relationshipLabel>
    <relationshipName>API_Synchronization_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>API Synchronization Items</relationshipLabel>
    <relationshipName>API_Synchronization_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/External_Tax_System__c.field-meta.xml
<CustomField>
    <fullName>External_Tax_System__c</fullName>
    <description>External Tax System</description>
    <label>External Tax System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>External_Tax_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>API Synchronization Item Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Re-Queued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Transaction__c/API_Synchronization_Transaction__c.object-meta.xml
<CustomObject>
    <description>Object to track syncing of data &amp; this will help in tracking errors while Sync</description>
    <label>API Synchronization Transaction</label>
    <nameField>
        <displayFormat>AST-{0000}</displayFormat>
        <label>API Synchronization Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Synchronization Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Synchronization_Transaction__c/fields/External_Tax_System__c.field-meta.xml
<CustomField>
    <fullName>External_Tax_System__c</fullName>
    <description>Name of the external system for Tax</description>
    <label>External Tax System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>External_Tax_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the transaction. Some status will be dependent on status of related line items. The default value will be Queued.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Completed With Errors</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Requeue for Erroneous records</fullName>
            </value>
            <value>
                <fullName>Requeue All</fullName>
            </value>
            <value>
                <fullName>Requeue for Successful records</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/External_Relationship__c.field-meta.xml
<CustomField>
    <fullName>External_Relationship__c</fullName>
    <defaultValue>false</defaultValue>
    <description>External Relationship avalible</description>
    <label>External Relationship</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/External_Status__c.field-meta.xml
<CustomField>
    <fullName>External_Status__c</fullName>
    <description>External System Status</description>
    <label>External Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/fields/External_Tax_System__c.field-meta.xml
<CustomField>
    <fullName>External_Tax_System__c</fullName>
    <description>External Tax System</description>
    <label>External Tax System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>External_Tax_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition of order.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EditionReQueueAPIItems_Trig.cls
/**
* File         : EditionReQueueAPIItems_Trig
* Project      : Order & Billing Plateform
* Created Date : 5th October 2021
* Created By   : Girikon(Deepak)[OPB-401] 
* Test Class   : EditionReQueueAPIItems_Trig_Test
* Coverage     : 96%    
*
* *******************************************************************************************************
* @description : Class for  If API sync transaction is created in Paused state and user update the Edition then paused state API Sync Transaction should be Queued automatically.
* *******************************************************************************************************
* History:
*/

public with sharing class EditionReQueueAPIItems_Trig implements TriggerInterface_Edition.Runnable{
    /**
    * @description [Call Interface Class to fetch the new list and old map of Edition]
    * @param trig [fetch the trigger new list and old map]
    */
    public void run(TriggerInterface_Edition.Trig trig){
        if(trig.isAfter && trig.isUpdate) 
        {
            getAllEditionsForApiSynchItems(trig.newList, trig.oldMap);
        }
    }

    /**
    * @description [method to get All Editions for checking if ApiSynch]
    * @param editionList 
    * @param oldEditionMap
    */
    private void getAllEditionsForApiSynchItems(List<Edition__c> editionList, Map<Id, Edition__c> oldEditionMap)
    {
        Set<Id> setEditionForApiSynchItemsids = new set<Id>();  
        for(Edition__c edition : editionList)
        {
            if(edition.External_Status__c == GlobalConstants.ACTIVE && edition.External_Relationship__c == true && edition.External_Tax_System__c == GlobalConstants.ONESOURCE)
            {   
                if(oldEditionMap.get(edition.Id).External_Relationship__c != edition.External_Relationship__c || oldEditionMap.get(edition.Id).External_Status__c != edition.External_Status__c || oldEditionMap.get(edition.Id).External_Tax_System__c != edition.External_Tax_System__c)
                {
                    setEditionForApiSynchItemsids.add(edition.Id); 
                }
            }  
        }

        if(!setEditionForApiSynchItemsids.isEmpty())
        {
            updateApiSynchItem(setEditionForApiSynchItemsids);
        }
    }


    /**
    * @description [method to update API sync Items to Paused state  (OBP-401)]
    * @param setEditionIdsForApiSynchItems
    */
    private void updateApiSynchItem(Set<Id> setEditionIdsForApiSynchItems)
    {
        List<API_Synchronization_Item__c> lstApiSynchItems = new List<API_Synchronization_Item__c>();
        Map<Id,API_Synchronization_Transaction__c> mapApiSynchTrans = new Map<Id,API_Synchronization_Transaction__c>();
        try
        {
            for(API_Synchronization_Item__c apiSynchItm : [SELECT Id,Status__c,API_Synchronization_Transaction__c FROM API_Synchronization_Item__c WHERE Edition__c IN:setEditionIdsForApiSynchItems AND Status__c=:GlobalConstants.PAUSED WITH SECURITY_ENFORCED])
            {
                apiSynchItm.Status__c = GlobalConstants.QUEUED;
                lstApiSynchItems.add(apiSynchItm);
                API_Synchronization_Transaction__c apiSyncTrans = new API_Synchronization_Transaction__c(Id=apiSynchItm.API_Synchronization_Transaction__c, Status__c = GlobalConstants.QUEUED);
                mapApiSynchTrans.put(apiSynchItm.API_Synchronization_Transaction__c,apiSyncTrans);
            }

            if(!lstApiSynchItems.isEmpty() && Schema.sObjectType.API_Synchronization_Item__c.isUpdateable())
            {
                update lstApiSynchItems;
            }

            if(!mapApiSynchTrans.isEmpty() && Schema.sObjectType.API_Synchronization_Transaction__c.isUpdateable())
            {
                update mapApiSynchTrans.values();
            }
        }
        catch(Exception e){System.debug(logginglevel.DEBUG,'Error in Finish --> '+e.getMessage() +' At Line' + e.getLineNumber());}
    }
}