force-app/main/default/objects/API_Synchronization_Item__c/API_Synchronization_Item__c.object-meta.xml
<CustomObject>
    <description>object will contain actual information of sync status of account and contact.</description>
    <label>API Synchronization Item</label>
    <nameField>
        <displayFormat>ASI-{0000}</displayFormat>
        <label>API Synchronization Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Synchronization Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>API Synchronization Items</relationshipLabel>
    <relationshipName>API_Synchronization_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Amendment_Request__c.field-meta.xml
<CustomField>
    <fullName>Amendment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Amendment Request</description>
    <label>Amendment Request</label>
    <referenceTo>Change_Request__c</referenceTo>
    <relationshipLabel>API Synchronization Items</relationshipLabel>
    <relationshipName>API_Synchronization_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/API_Synchronization_Transaction__c.field-meta.xml
<CustomField>
    <fullName>API_Synchronization_Transaction__c</fullName>
    <description>API Synchronization Transaction</description>
    <label>API Synchronization Transaction</label>
    <referenceTo>API_Synchronization_Transaction__c</referenceTo>
    <relationshipLabel>API Synchronization Items</relationshipLabel>
    <relationshipName>API_Synchronization_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Credit_Note__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Credit Note</description>
    <label>Credit Note</label>
    <referenceTo>blng__CreditNote__c</referenceTo>
    <relationshipLabel>API Synchronization Items</relationshipLabel>
    <relationshipName>API_Synchronization_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>API Synchronization Items</relationshipLabel>
    <relationshipName>API_Synchronization_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/External_Tax_System__c.field-meta.xml
<CustomField>
    <fullName>External_Tax_System__c</fullName>
    <description>External Tax System</description>
    <label>External Tax System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>External_Tax_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Invoice</description>
    <label>Invoice</label>
    <referenceTo>blng__Invoice__c</referenceTo>
    <relationshipLabel>API Synchronization Items</relationshipLabel>
    <relationshipName>API_Synchronization_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>API Synchronization Items</relationshipLabel>
    <relationshipName>API_Synchronization_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>API Synchronization Items</relationshipLabel>
    <relationshipName>API_Synchronization_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>API Synchronization Item Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Re-Queued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/X3rd_Party_ERP_System__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_ERP_System__c</fullName>
    <description>External 3rd Party ERP System</description>
    <label>3rd Party ERP System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X3rd_Party_ERP_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Transaction__c/API_Synchronization_Transaction__c.object-meta.xml
<CustomObject>
    <description>Object to track syncing of data &amp; this will help in tracking errors while Sync</description>
    <label>API Synchronization Transaction</label>
    <nameField>
        <displayFormat>AST-{0000}</displayFormat>
        <label>API Synchronization Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Synchronization Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Synchronization_Transaction__c/fields/External_Tax_System__c.field-meta.xml
<CustomField>
    <fullName>External_Tax_System__c</fullName>
    <description>Name of the external system for Tax</description>
    <label>External Tax System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>External_Tax_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the transaction. Some status will be dependent on status of related line items. The default value will be Queued.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Completed With Errors</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Requeue for Erroneous records</fullName>
            </value>
            <value>
                <fullName>Requeue All</fullName>
            </value>
            <value>
                <fullName>Requeue for Successful records</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Transaction__c/fields/X3rd_Party_ERP_System__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_ERP_System__c</fullName>
    <description>Name of external system for API sync.</description>
    <label>3rd Party ERP System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X3rd_Party_ERP_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Change_Request__c/Change_Request__c.object-meta.xml
<CustomObject>
    <description>To capture details of amendment related to Opportunity/Order/Invoice.</description>
    <label>Amendment</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Salesforce record id</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Amendments (Account)</relationshipLabel>
    <relationshipName>Change_Rquests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Amendment&apos;s Edition.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Amendments</relationshipLabel>
    <relationshipName>Change_Rquests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Invoice</description>
    <inlineHelpText>Invoice</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>blng__Invoice__c</referenceTo>
    <relationshipName>Amendments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity on which the change is being requested</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Amendments (Opportunity)</relationshipLabel>
    <relationshipName>Change_Rquests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/External_Tax_System__c.field-meta.xml
<CustomField>
    <fullName>External_Tax_System__c</fullName>
    <description>External Tax System</description>
    <label>External Tax System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>External_Tax_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/fields/X3rd_Party_ERP_System__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_ERP_System__c</fullName>
    <description>External 3rd Party System Name</description>
    <label>3rd Party ERP System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X3rd_Party_ERP_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of opportunity.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Customer Contacted</fullName>
            </value>
            <value>
                <fullName>Customer Engaged</fullName>
            </value>
            <value>
                <fullName>Proposal Sent</fullName>
            </value>
            <value>
                <fullName>Revised Proposal Sent</fullName>
            </value>
            <value>
                <fullName>Pending Accounting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Payment</fullName>
            </value>
            <value>
                <fullName>Accounting Rejected</fullName>
            </value>
            <value>
                <fullName>AR Cancel / Re-bill</fullName>
            </value>
            <value>
                <fullName>Booth/Sponsorship Cancellation</fullName>
            </value>
            <value>
                <fullName>Digital / Print Cancellation</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
            <value>
                <fullName>Online Booth Form In Review</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Pending Change</fullName>
            </value>
            <value>
                <fullName>Legacy Lost</fullName>
            </value>
            <value>
                <fullName>Legacy Cancelled</fullName>
            </value>
            <value>
                <fullName>Legacy Won</fullName>
            </value>
            <value>
                <fullName>Opportunity Cancelled</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Amended</fullName>
            </value>
            <value>
                <fullName>Customize</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Order/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition of order.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateApiSyncRecords.cls
/**
* File         :   CreateApiSyncRecords 
* Project      :   Order & Billing Plateform
* Created Date :   21 Sept 2021
* Created By   :   Girikon(Deepak)
* Test Class   :   SynchronousAPICallController_Test(93%),CreditNotesOrderHub_Trig_Test(80&) -(95%),CreateAPISyncItemsforAccount_Trig_Test(70-90%),APISynchronization_Test(70%),AmendmentUtils_Test(70%)
* ******************************************************************************************************
* @description : For Creating Records to API Synchronization transaction and its associated API Synchronization Items.
********************************************************************************************************
* Modification log :
    1. Girikon (Suresh) [OBP-342] 28 Sep 2021 : Create a functionality to POST the created Credit Notes into the Order Hub
    2. Girikon (Ashish) [OBP-423] 12 Oct 2021 : control Item Status as a pram 
    3. Girikon (Ashish) [IOM-521] 01 Feb 2022 : Account Credit Status Update to MuleSoft
    4. Girikon (Ashish) [IOM-775] 23 Feb 2022 : Amendment/Opportunity Data Update to MuleSoft
    5. Girikon (Ashish) [IE-10]   10 Aug 2022 : Added Logic for INV payment Tras
    6. Girikon (Ashish) [IE-150]  09 SEP 2022 : Added Logic for CN payment Tras
*/
public with sharing class CreateApiSyncRecords{
   
    /**
    * @description  map objet name and edition field name
    */
    private static Map<String,String> sobjNameEditionFieldName = new Map<String,String>{'Order' => 'Edition__c', 'blng__Invoice__c' => '', 'blng__CreditNote__c' => '','account' => ''};

    /**
    * @description  Wrapper Class For creating Api Sync Records
    */
    public class ApiSyncRecordsWrapper
    {
        /**
        * @description For edition Ids after validation check
        */
        public Map<Id,Boolean> editionValidations = New Map<Id,Boolean>();
        /** @description For sobj id and sobj name
        */
        public Map<String,String> sobjIdSobjName = New Map<String,String>();
        /** @description For sobj id and Edition Id
        */
        public Map<String,String> sobjIdEditionId = New Map<String,String>();
        /**
        * @description For checking the record is for update,Create or GET
        */
        public String type;
        /**
        * @description For Checking where this trigger is started from
        */
        public String startedFrom;
        /**
        * @description list of sobject
        */
        public List<SObject> listSObject = New List<SObject>();
        /**
        * @description For checking whether the record is created for direct sync or can take some time.
        */
        public String requestType;
        /**
        * @description For api Call Type
        */
        public String apiCallType;
        /**
        * @description For item Type
        */
        public String itemType;
        /**
        * @description For All item Status
        */
        public String itemStatus;
        /**
        * @description For checking the transaction status
        */
        public String transactionStatus;
        /**
        * @description For third Party Relation Name.
        */
        public String thirdPartyERPSystem;
        /**
        * @description For third Party Relation Name.
        */
        public String externalTaxSystem;
        /**
        * @description to include one extra item in trasnsaction for Amendment Complete Tras;
        */
        public Boolean addAmendmentCompleteApiItem = false;
    }

    /**
    * @description  Creation of All API Sync items and their transactions records.
    * @param  apiSyncWrap
    * @return  Id API Transaction
    */
    public static Id insertAllAPISyncItem(ApiSyncRecordsWrapper apiSyncWrap)
    {
        List<API_Synchronization_Transaction__c> lstApiSyncTran = new List<API_Synchronization_Transaction__c>();
        List<API_Synchronization_Item__c> lstApiSyncItem = new List<API_Synchronization_Item__c>();
        Id syncTranId;
        String triggerOn;
        Boolean checkAllStatus = false;
        try{
            Set<Id> editionIds = new Set<Id>();
            for(SObject sobj : apiSyncWrap.listSObject)
            {
                Id sobjId = Id.valueOf(String.valueOf(sobj.get('Id')));
                String sobjIdStartString = String.valueOf(sobjId).left(3);
                if(!apiSyncWrap.sobjIdSobjName.containsKey(sobjIdStartString)){
                    String sObjName = sobjId.getSObjectType().getDescribe().getName();
                    apiSyncWrap.sobjIdSobjName.put(sobjIdStartString, sObjName);
                }
                String objectName = apiSyncWrap.sobjIdSobjName.get(sobjIdStartString);
                String editionFieldName = (sobjNameEditionFieldName.containsKey(objectName)?sobjNameEditionFieldName.get(objectName):'');
                if(String.isNotBlank(editionFieldName)){
                    String editionId = OneSourceAPIWrapper.getSObjectValue(sobj, editionFieldName);
                    editionIds.add(editionId);
                    apiSyncWrap.sobjIdEditionId.put(sobjId, editionId);
                }
            }
            apiSyncWrap.editionValidations = new Map<Id,Boolean>(fieldsValidationOnEdition(editionIds));
            if(!apiSyncWrap.listSObject.isEmpty())
            {
                lstApiSyncItem = insertAPISyncItems(apiSyncWrap);
            }
            API_Synchronization_Transaction__c apiSyncTran = new API_Synchronization_Transaction__c();            
            for(API_Synchronization_Item__c item : lstApiSyncItem){
                if((String.isNotBlank(item.Invoice__c) || String.isNotBlank(item.Credit_Note__c) || (String.isNotBlank(item.Order__c) || String.isNotBlank(item.Account__C) || String.isNotBlank(item.Opportunity__c) || String.isNotBlank(item.Amendment_Request__c) )&& GlobalConstants.QUEUED.equalsIgnoreCase(item.Status__c)))
                {
                    checkAllStatus = true;
                }                
            }
            apiSyncWrap.transactionStatus = (checkAllStatus?GlobalConstants.QUEUED:GlobalConstants.PAUSED);
            apiSyncTran.Status__c = GlobalConstants.PAUSED;

            apiSyncTran.External_Tax_System__c = apiSyncWrap.externalTaxSystem;
            apiSyncTran.X3rd_Party_ERP_System__c = apiSyncWrap.thirdPartyERPSystem;
            apiSyncTran.Started_From__c = apiSyncWrap.startedFrom;
            apiSyncTran.Type__c = apiSyncWrap.type;
            apiSyncTran.Request_Type__c = (apiSyncWrap.requestType==GlobalConstants.SYNCHRONOUS?GlobalConstants.SYNCHRONOUS:GlobalConstants.ASYNCHRONOUS);
            lstApiSyncTran.add(apiSyncTran);

           syncTranId =  insertAllRecords(lstApiSyncTran, lstApiSyncItem, apiSyncWrap);            
        }
        catch(Exception e) 
        {
            triggerOn = apiSyncWrap.type;
            //HandleAllCustomException.LogException(e,'',triggerOn);
            System.debug(LoggingLevel.DEBUG, triggerOn);
            System.debug(logginglevel.DEBUG,'Error in Finish --> '+e.getMessage() +' At Line' + e.getLineNumber());
        }
        return syncTranId;
    }

    /**
    * @description  Creation of All API Sync items if triggered from Account Edition object.
    * @param  apiSyncWrap
    * @return  lstApiSyncItem
    */
    public static List<API_Synchronization_Item__c> insertAPISyncItems(ApiSyncRecordsWrapper apiSyncWrap)
    {
        final string NOTES = 'blng__Notes__c';

        List<API_Synchronization_Item__c> lstApiSyncItem = new List<API_Synchronization_Item__c>();
        Map<Id,Edition__c> mapEdition = new Map<Id,Edition__c>();
        if(Schema.sObjectType.Edition__c.isAccessible())
        {
            mapEdition = new Map<Id,Edition__c>([SELECT Id,Edition_Status__c FROM Edition__c WHERE Id In:apiSyncWrap.editionValidations.keySet()]);
        }        
        Set<Id> sObjectIds = new Set<Id>();
        for(SObject sobj : apiSyncWrap.listSObject)
        {
            Id sobjId = Id.valueOf(String.valueOf(sobj.get('Id')));           
            sObjectIds.add(sobjId);
        }
        Set<String> setStatuses = new Set<String>{GlobalConstants.PAUSED,GlobalConstants.QUEUED,GlobalConstants.PROCESSING};
        Set<String> existingItems = new Set<String>();
        
        List<API_Synchronization_Item__c> existingAPIItems = [SELECT Id,Invoice__c,Order__c,Credit_Note__c,Account__c,Opportunity__c,Amendment_Request__c FROM API_Synchronization_Item__c WHERE (Invoice__c IN:sObjectIds OR Order__c IN:sObjectIds OR Credit_Note__c IN:sObjectIds OR Account__c IN:sObjectIds OR Amendment_Request__c IN:sObjectIds OR Opportunity__c IN:sObjectIds) AND Status__c IN:setStatuses AND Type__c=:apiSyncWrap.itemType WITH SECURITY_ENFORCED];
        for(API_Synchronization_Item__c item : existingAPIItems){
            if(String.isNotBlank(item.Invoice__c)){existingItems.add(item.Invoice__c);}
            if(String.isNotBlank(item.Order__c)){existingItems.add(item.Order__c);}
            if(String.isNotBlank(item.Credit_Note__c)){existingItems.add(item.Credit_Note__c);}
            if(String.isNotBlank(item.Account__c)){existingItems.add(item.Account__c);}
            if(String.isNotBlank(item.Opportunity__c)){existingItems.add(item.Opportunity__c);}
            if(String.isNotBlank(item.Amendment_Request__c)){existingItems.add(item.Amendment_Request__c);}
        }
        
        for(SObject sobj : apiSyncWrap.listSObject)
        {
            Id sobjId = Id.valueOf(String.valueOf(sobj.get('Id')));
            String sobjIdStartString = String.valueOf(sobjId).left(3);
            String objectName = apiSyncWrap.sobjIdSobjName.get(sobjIdStartString);
            API_Synchronization_Item__c apiSyncItems = new API_Synchronization_Item__c();
            apiSyncItems.External_Tax_System__c = apiSyncWrap.externalTaxSystem;
            apiSyncItems.X3rd_Party_ERP_System__c = apiSyncWrap.thirdPartyERPSystem;
            apiSyncItems.API_Call_Type__c = apiSyncWrap.apiCallType;
            apiSyncItems.Type__c = apiSyncWrap.itemType;

            if(objectName == 'blng__Invoice__c' && !existingItems.contains(sobjId)){
                apiSyncItems.Invoice__c = sobjId;
                apiSyncItems.Status__c =  String.isNotBlank(apiSyncWrap.itemStatus) ? apiSyncWrap.itemStatus : String.isNotBlank(apiSyncWrap.itemStatus) ? apiSyncWrap.itemStatus : GlobalConstants.QUEUED;
                lstApiSyncItem.add(apiSyncItems);
                // Add Logic to create API Syc Items for Payment Transactions [IE-10]
                if(sobj.isSet(NOTES) && (string)sobj.get(NOTES) == GlobalConstants.POST_PAYMENT_TRANSACTIONS)
                {
                    API_Synchronization_Item__c apiSyncItem2 = new API_Synchronization_Item__c();
                    apiSyncItem2 =  (API_Synchronization_Item__c)JSON.deserialize(JSON.serialize(apiSyncItems), Sobject.class);
                    apiSyncItem2.Type__c = GlobalConstants.POST_PAYMENT_TRANSACTIONS;
                    lstApiSyncItem.add(apiSyncItem2);
                }
            }

            if(objectName == 'Order' && !checkEditionStatus(apiSyncWrap.sobjIdEditionId.get(sobjId),mapEdition) && !existingItems.contains(sobjId)){
                apiSyncItems.Order__c = sobjId;
                apiSyncItems.Edition__c = apiSyncWrap.sobjIdEditionId.get(sobjId);
                apiSyncItems.Status__c = (apiSyncWrap.editionValidations.get(apiSyncWrap.sobjIdEditionId.get(sobjId))?GlobalConstants.QUEUED:GlobalConstants.PAUSED);
                lstApiSyncItem.add(apiSyncItems);
            }

            //This is for CreditNotes OBP-342
            if(objectName == 'blng__CreditNote__c' && !existingItems.contains(sobjId)){
                apiSyncItems.Credit_Note__c = sobjId;
                apiSyncItems.Status__c = String.isNotBlank(apiSyncWrap.itemStatus) ? apiSyncWrap.itemStatus : GlobalConstants.QUEUED;
                lstApiSyncItem.add(apiSyncItems);
                // Add Logic to create API Syc Items for Payment Transactions [IE-150]
                if(sobj.isSet(NOTES) && (string)sobj.get(NOTES) == GlobalConstants.POST_PAYMENT_TRANSACTIONS)
                {
                    API_Synchronization_Item__c apiSyncItem2 = new API_Synchronization_Item__c();
                    apiSyncItem2 =  (API_Synchronization_Item__c)JSON.deserialize(JSON.serialize(apiSyncItems), Sobject.class);
                    apiSyncItem2.Type__c = GlobalConstants.POST_PAYMENT_TRANSACTIONS;
                    lstApiSyncItem.add(apiSyncItem2);
                }
            }

            //This is for Account IOM-521
            if(objectName == 'Account' && !existingItems.contains(sobjId)){
                apiSyncItems.Account__c = sobjId;
                apiSyncItems.Status__c = String.isNotBlank(apiSyncWrap.itemStatus) ? apiSyncWrap.itemStatus : GlobalConstants.QUEUED;
                lstApiSyncItem.add(apiSyncItems);
            }
            // Amendment Request  Approved/Rejected [IOM-775]
            if(objectName == 'Change_Request__c' && !existingItems.contains(sobjId)){
                apiSyncItems.Amendment_Request__c = sobjId;
                apiSyncItems.Type__c = sobj.isSet('Comments__c')? (String)sobj.get('Comments__c'):apiSyncWrap.itemType;
                apiSyncItems.Status__c = String.isNotBlank(apiSyncWrap.itemStatus) ? apiSyncWrap.itemStatus : GlobalConstants.QUEUED;
                lstApiSyncItem.add(apiSyncItems);
                // Add Amendment Completed Item [IOM-572]
                if(apiSyncWrap.addAmendmentCompleteApiItem){
                    API_Synchronization_Item__c apiSyncItem2 = new API_Synchronization_Item__c();
                    apiSyncItem2 =  (API_Synchronization_Item__c)JSON.deserialize(JSON.serialize(apiSyncItems), Sobject.class);
                    apiSyncItem2.Type__c = GlobalConstants.CHANGE_REQUEST_COMPLETED;
                    lstApiSyncItem.add(apiSyncItem2);
                }
            }
            // For Opportunity  [IOM-775]
            if(objectName == 'Opportunity' && !existingItems.contains(sobjId)){
                apiSyncItems.Opportunity__c = sobjId;
                apiSyncItems.Status__c = String.isNotBlank(apiSyncWrap.itemStatus) ? apiSyncWrap.itemStatus : GlobalConstants.QUEUED;
                lstApiSyncItem.add(apiSyncItems);
            }  
        }
        return lstApiSyncItem;
    }

    /**
    * @description  Insert All API Sync Records.
    * @param  lstApiSyncTran
    * @param  lstApiSyncItem
    * @param  apiSyncWrap
    * @return apiSyncTranId
    */
    public static Id insertAllRecords(List<API_Synchronization_Transaction__c> lstApiSyncTran, List<API_Synchronization_Item__c> lstApiSyncItem, ApiSyncRecordsWrapper apiSyncWrap)
    {
        Id apiSyncTranId;
        if(!lstApiSyncTran.isEmpty() && !lstApiSyncItem.isEmpty())
        {
            if(Schema.sObjectType.API_Synchronization_Transaction__c.isCreateable())
            {
                insert lstApiSyncTran;
            }
            apiSyncTranId = lstApiSyncTran[0].Id;
            
            for(API_Synchronization_Item__c apiSyncItm : lstApiSyncItem)
            {
                apiSyncItm.API_Synchronization_Transaction__c = lstApiSyncTran[0].Id;
            }

            if(Schema.sObjectType.API_Synchronization_Item__c.isCreateable())
            {
                insert lstApiSyncItem;
            }

            if(Schema.sObjectType.API_Synchronization_Transaction__c.isUpdateable())
            {
                lstApiSyncTran[0].Status__c = apiSyncWrap.transactionStatus;
                update lstApiSyncTran;
            }
        }
        return apiSyncTranId;
    }

    /**
    * @description  Check if edition completed or cancelled.
    * @param  editionId
    * @param  mapEdition
    * @return boolean edition status
    */
    public static boolean checkEditionStatus(Id editionId, Map<Id,Edition__c> mapEdition)
    {
        Edition__c ed = mapEdition.get(editionId);
        String labelVal = ',Completed,Cancelled,Cancelled by Finance,';
        String editionStatus = ((ed.Edition_Status__c == null || ed.Edition_Status__c == '')?'':(','+ed.Edition_Status__c+','));
        return (editionStatus==''?false:labelVal.contains(editionStatus));
    }

    /**
    * @description  This method is for evaluating all condition which must be checked on edition record before inserting data in API Sync Objects ofr syncronisation with MYS.
    * @param  editionIds
    * @return  allEditionValidation
    */
    
    public static Map<Id,Boolean> fieldsValidationOnEdition(Set<Id> editionIds)
    {
        Map<Id,Boolean> allEditionValidation = new Map<Id,Boolean>();
        for(Edition__c edition : [SELECT Id,External_Relationship__c,External_Status__c,External_Tax_System__c FROM Edition__c WHERE id IN:editionIds WITH SECURITY_ENFORCED])
        {
            allEditionValidation.put(edition.Id,false);
            if(edition.External_Tax_System__c == GlobalConstants.ONESOURCE && edition.External_Relationship__c == true && edition.External_Status__c == GlobalConstants.ACTIVE)
            {
                allEditionValidation.put(edition.Id,true);
            }
        }
        return allEditionValidation;
    }
}