force-app/main/default/objects/API_Synchronization_Item__c/API_Synchronization_Item__c.object-meta.xml
<CustomObject>
    <description>object will contain actual information of sync status of account and contact.</description>
    <label>API Synchronization Item</label>
    <nameField>
        <displayFormat>ASI-{0000}</displayFormat>
        <label>API Synchronization Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Synchronization Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Synchronization_Item__c/fields/API_Call_Type__c.field-meta.xml
<CustomField>
    <fullName>API_Call_Type__c</fullName>
    <description>Type of action which will API callout perform in the external system.</description>
    <label>API Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/API_Synchronization_Transaction__c.field-meta.xml
<CustomField>
    <fullName>API_Synchronization_Transaction__c</fullName>
    <description>API Synchronization Transaction</description>
    <label>API Synchronization Transaction</label>
    <referenceTo>API_Synchronization_Transaction__c</referenceTo>
    <relationshipLabel>API Synchronization Items</relationshipLabel>
    <relationshipName>API_Synchronization_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>API Synchronization Items</relationshipLabel>
    <relationshipName>API_Synchronization_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/External_Tax_System__c.field-meta.xml
<CustomField>
    <fullName>External_Tax_System__c</fullName>
    <description>External Tax System</description>
    <label>External Tax System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>External_Tax_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>API Synchronization Item Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Re-Queued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Transaction__c/API_Synchronization_Transaction__c.object-meta.xml
<CustomObject>
    <description>Object to track syncing of data &amp; this will help in tracking errors while Sync</description>
    <label>API Synchronization Transaction</label>
    <nameField>
        <displayFormat>AST-{0000}</displayFormat>
        <label>API Synchronization Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Synchronization Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Synchronization_Transaction__c/fields/External_Tax_System__c.field-meta.xml
<CustomField>
    <fullName>External_Tax_System__c</fullName>
    <description>Name of the external system for Tax</description>
    <label>External Tax System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>External_Tax_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Transaction__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>This Field tells whether transaction is created from Account/Contact(Synchronous) or any other way(Asynchronous).</description>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asynchronous</fullName>
                <default>true</default>
                <label>Asynchronous</label>
            </value>
            <value>
                <fullName>Synchronous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Transaction__c/fields/Started_From__c.field-meta.xml
<CustomField>
    <fullName>Started_From__c</fullName>
    <description>The object from where this transaction has been initiated.</description>
    <label>Started From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Amendment Request</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the transaction. Some status will be dependent on status of related line items. The default value will be Queued.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Completed With Errors</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Requeue for Erroneous records</fullName>
            </value>
            <value>
                <fullName>Requeue All</fullName>
            </value>
            <value>
                <fullName>Requeue for Successful records</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Edition__c/fields/External_Relationship__c.field-meta.xml
<CustomField>
    <fullName>External_Relationship__c</fullName>
    <defaultValue>false</defaultValue>
    <description>External Relationship avalible</description>
    <label>External Relationship</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/External_Status__c.field-meta.xml
<CustomField>
    <fullName>External_Status__c</fullName>
    <description>External System Status</description>
    <label>External Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/fields/External_Tax_System__c.field-meta.xml
<CustomField>
    <fullName>External_Tax_System__c</fullName>
    <description>External Tax System</description>
    <label>External Tax System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>External_Tax_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition of order.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trigger__c/Trigger__c.object-meta.xml
<CustomObject>
    <label>Trigger</label>
    <nameField>
        <label>Trigger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger__c/fields/After_Update__c.field-meta.xml
<CustomField>
    <fullName>After_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Execution_Order__c.field-meta.xml
<CustomField>
    <fullName>Execution_Order__c</fullName>
    <label>Execution Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>This trigger runs against which object?</inlineHelpText>
    <label>Object</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Recursive_Execution_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Recursive_Execution_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recursive Execution Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Run_for_Recordypes__c.field-meta.xml
<CustomField>
    <fullName>Run_for_Recordypes__c</fullName>
    <label>Run for Recordypes</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Trigger_Name_Unique__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Name_Unique__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Trigger Name Unique</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/EditionReQueueAPIItems_Trig_Test.cls
/**
* File			: 	EditionReQueueAPIItems_Trig_Test
* Project      	:   Order & Billing Plateform
* Created By	: 	Deepak(Girikon)
* Created Date	: 	5th October 2021
* ******************************************************************************************************
* @description : Test Class to provide code covrage to classes - EditionReQueueAPIItems_Trig(96%)
* Last Modified By :
*/

@isTest
private with sharing class EditionReQueueAPIItems_Trig_Test {
    // @description : Setting up all test data
    @testsetup
    static void testData(){
        
        Trigger__c trig = new Trigger__c(Name = 'EditionReQueueAPIItems_Trig' , Trigger_Name_Unique__c='EditionReQueueAPIItems_Trig',Enabled__c=true,Object__c='Edition__c',Run_for_Recordypes__c='All',Recursive_Execution_Allowed__c=true,Execution_Order__c=1,After_Update__c=true);
        Insert trig;

        // create list of edition to be used on the quote
        List<Edition__c> listOfEditions = new List<Edition__c>();
        Edition__c edition = new Edition__c();
        for(Integer i=0;i<500;i++)
        {
            edition =  new Edition__c();
            edition.Name = 'testEdition'+i;
            edition.External_Tax_System__c = GlobalConstants.ONESOURCE;
            edition.External_Relationship__c = true; 
            edition.Edition_Code__c = 'testEdition'+i;
            listOfEditions.add(edition);
        }
        insert listOfEditions;

        Map<Id,API_Synchronization_Transaction__c> mapEdtIdApiTrans = new Map<Id,API_Synchronization_Transaction__c>();
        Map<Id,List<API_Synchronization_Item__c>> mapEdtIdistApiItem = new Map<Id,List<API_Synchronization_Item__c>>();
        for(Edition__c edt : listOfEditions){
            API_Synchronization_Transaction__c apiSyncroTrs = new API_Synchronization_Transaction__c();
            apiSyncroTrs.External_Tax_System__c = GlobalConstants.ONESOURCE;
            apiSyncroTrs.Request_Type__c = GlobalConstants.ASYNCHRONOUS;
            apiSyncroTrs.Started_From__c = 'Order';
            apiSyncroTrs.Status__c = GlobalConstants.PAUSED;
            mapEdtIdApiTrans.put(edt.Id,apiSyncroTrs);

            for(Integer i=0;i<5;i++){
                API_Synchronization_Item__c item = new API_Synchronization_Item__c();
                item.API_Call_Type__c = GlobalConstants.POST;
                item.Status__c = GlobalConstants.PAUSED;
                item.External_Tax_System__c = GlobalConstants.ONESOURCE;
                item.Edition__c = edt.Id;
                List<API_Synchronization_Item__c> listAPIItems = (mapEdtIdistApiItem.containsKey(edt.Id)?mapEdtIdistApiItem.get(edt.Id):new List<API_Synchronization_Item__c>());
                listAPIItems.add(item);
                mapEdtIdistApiItem.put(edt.Id,listAPIItems);
            }
        }

        insert mapEdtIdApiTrans.values();

        List<API_Synchronization_Item__c> listApiItemInsert = new List<API_Synchronization_Item__c>();
        for(Id edtId : mapEdtIdApiTrans.keySet()){
            API_Synchronization_Transaction__c apiSyncroTrs = mapEdtIdApiTrans.get(edtId);
            for(API_Synchronization_Item__c item : mapEdtIdistApiItem.get(edtId)){
                item.API_Synchronization_Transaction__c = apiSyncroTrs.Id;
                listApiItemInsert.add(item);
            }
        }
        insert listApiItemInsert;
    }
    
    // @description : test class is used to create order.
    
    @isTest 
    static void testgetAllEditionsForApiSynchItems()
    {
        Test.startTest();
        List<Edition__c> listEditions = [SELECT Id FROM Edition__c];
        for(Edition__c edt : listEditions){
            edt.External_Status__c = GlobalConstants.ACTIVE;
        }
        update listEditions;
        List<API_Synchronization_Item__c> itemsPaused = [SELECT Id FROM API_Synchronization_Item__c WHERE Status__c=:GlobalConstants.PAUSED];
        List<API_Synchronization_Transaction__c> apiTransPaused = [SELECT Id FROM API_Synchronization_Transaction__c WHERE Status__c=:GlobalConstants.PAUSED];
        List<API_Synchronization_Item__c> itemsQueued = [SELECT Id FROM API_Synchronization_Item__c WHERE Status__c=:GlobalConstants.QUEUED];
        List<API_Synchronization_Transaction__c> apiTransQueued = [SELECT Id FROM API_Synchronization_Transaction__c WHERE Status__c=:GlobalConstants.QUEUED];
        System.assertEquals(0, itemsPaused.size(),'All Items Not Queued.');
        System.assertEquals(0, apiTransPaused.size(),'All API Transactions Not Queued.');
        System.assertEquals(2500, itemsQueued.size(),'All Items Not Queued.');
        System.assertEquals(500, apiTransQueued.size(),'All API Transactions Not Queued.');
        Test.stopTest();
    }
}