force-app/main/default/objects/API_Synchronization_Transaction__c/API_Synchronization_Transaction__c.object-meta.xml
<CustomObject>
    <description>Object to track syncing of data &amp; this will help in tracking errors while Sync</description>
    <label>API Synchronization Transaction</label>
    <nameField>
        <displayFormat>AST-{0000}</displayFormat>
        <label>API Synchronization Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Synchronization Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Synchronization_Transaction__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>This Field tells whether transaction is created from Account/Contact(Synchronous) or any other way(Asynchronous).</description>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asynchronous</fullName>
                <default>true</default>
                <label>Asynchronous</label>
            </value>
            <value>
                <fullName>Synchronous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the transaction. Some status will be dependent on status of related line items. The default value will be Queued.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Completed With Errors</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Requeue for Erroneous records</fullName>
            </value>
            <value>
                <fullName>Requeue All</fullName>
            </value>
            <value>
                <fullName>Requeue for Successful records</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APISynchronizationSchedule.cls
/**
* File         :   APISynchronizationSchedule 
* Project      :   Order & Billing Plateform
* Created Date :   31 march 2023
* Created By   :   Girikon(Deepak)
* Test Class   :   APISynchronizationSchedule_Test
* Coverage     :   100%
* *******************************************************************************************************
* @description : to process record using APISynchronizationBatch after specified frequency(GECI-1326)
* *******************************************************************************************************
* Modification log :   
*/
public without sharing class APISynchronizationSchedule implements Schedulable {
    /**
    * @description : implement execute method for Schedulable interface.
    * @param  sc
    */
    public void execute(SchedulableContext sc)
    {
        List<String> integrationUsers = GlobalConstants.getValue('Integration_Automation_Users').split(',');
        
        Map<Id,API_Synchronization_Transaction__c> mapAPISyncTrans = new Map<Id,API_Synchronization_Transaction__c>([SELECT Id FROM API_Synchronization_Transaction__c WHERE Status__c=:GlobalConstants.Queued AND Request_Type__c=:GlobalConstants.ASYNCHRONOUS AND LastModifiedBy.Name NOT IN:integrationUsers WITH SECURITY_ENFORCED]);
        if(!mapAPISyncTrans.isEmpty()){
            APISynchronizationBatch obj = new APISynchronizationBatch(mapAPISyncTrans.keySet());
            Database.executeBatch(obj,1);
        }
    }
}

/*
Integer interval = 5;
Integer count = (60/interval);
for(Integer i = 0; i < count; i++){
	String sch = '0 ' + String.valueOf(i*interval).leftPad(2,'0') + ' * * * ?';
	APISynchronizationSchedule obj = new APISynchronizationSchedule();
	System.schedule('API Synchronization Processing Job - ' + String.valueOf(i*interval).leftPad(2,'0'), sch, obj);
}
*/