force-app/main/default/objects/Account/fields/Accounting_Credit_Hold__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Credit_Hold__c</fullName>
    <description>Contains the status of credit hold for an account. Can be set to varying values. Should be restricted to only show for accounting and admins.</description>
    <inlineHelpText>Credit status of the account. OK - account is current, no restrictions. Warning - account has been flagged because it may be past due. Credit Hold - cannot sell to this customer without executive approval.</inlineHelpText>
    <label>Accounting Credit Hold</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
                <default>true</default>
                <label>OK</label>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <description>This field is used to fetch the legal entity name from event series as per ticket no IML2R-135.</description>
    <formula>HYPERLINK(&quot;/&quot;&amp;Part_of_Series__r.Legal_Entity__c,Part_of_Series__r.Legal_Entity__r.Name,&quot;_blank&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field is used to fetch the legal entity name from event series.</inlineHelpText>
    <label>Legal Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Part_of_Series__c.field-meta.xml
<CustomField>
    <fullName>Part_of_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup store value of series this edition is part of</description>
    <label>Part of Series</label>
    <referenceTo>Series__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Event_Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Default_Edition__c.field-meta.xml
<CustomField>
    <fullName>Default_Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Edition of Opportunity</description>
    <label>Default Edition</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Edition__c.Edition_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the legal entity.</description>
    <inlineHelpText>This legal entity will be the default one for the quote</inlineHelpText>
    <label>Legal Entity</label>
    <referenceTo>blng__LegalEntity__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Series__c.field-meta.xml
<CustomField>
    <fullName>Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Series to which Opportunity&apos;s Edition belongs.</description>
    <label>Series</label>
    <referenceTo>Series__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of opportunity.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Customer Contacted</fullName>
            </value>
            <value>
                <fullName>Customer Engaged</fullName>
            </value>
            <value>
                <fullName>Proposal Sent</fullName>
            </value>
            <value>
                <fullName>Revised Proposal Sent</fullName>
            </value>
            <value>
                <fullName>Pending Accounting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Payment</fullName>
            </value>
            <value>
                <fullName>Accounting Rejected</fullName>
            </value>
            <value>
                <fullName>AR Cancel / Re-bill</fullName>
            </value>
            <value>
                <fullName>Booth/Sponsorship Cancellation</fullName>
            </value>
            <value>
                <fullName>Digital / Print Cancellation</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
            <value>
                <fullName>Online Booth Form In Review</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Pending Change</fullName>
            </value>
            <value>
                <fullName>Legacy Lost</fullName>
            </value>
            <value>
                <fullName>Legacy Cancelled</fullName>
            </value>
            <value>
                <fullName>Legacy Won</fullName>
            </value>
            <value>
                <fullName>Opportunity Cancelled</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Amended</fullName>
            </value>
            <value>
                <fullName>Customize</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Series__c/Series__c.object-meta.xml
<CustomObject>
    <description>It defines the Series Information. Each year&apos;s Edition will be tied to a particular Series.</description>
    <label>Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Series__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of Series</description>
    <label>Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Series__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Legal Entity for Series.</description>
    <label>Legal Entity</label>
    <referenceTo>blng__LegalEntity__c</referenceTo>
    <relationshipLabel>Series</relationshipLabel>
    <relationshipName>Event_Series</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Series__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Staus of Series.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger__c/Trigger__c.object-meta.xml
<CustomObject>
    <label>Trigger</label>
    <nameField>
        <label>Trigger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger__c/fields/Before_Insert__c.field-meta.xml
<CustomField>
    <fullName>Before_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Before_Update__c.field-meta.xml
<CustomField>
    <fullName>Before_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Execution_Order__c.field-meta.xml
<CustomField>
    <fullName>Execution_Order__c</fullName>
    <label>Execution Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>This trigger runs against which object?</inlineHelpText>
    <label>Object</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <description>Use this format: Param1=Value1;Param2=Value2</description>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Run_for_Recordypes__c.field-meta.xml
<CustomField>
    <fullName>Run_for_Recordypes__c</fullName>
    <label>Run for Recordypes</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Trigger_Name_Unique__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Name_Unique__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Trigger Name Unique</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trigger_Recordtype__c/Trigger_Recordtype__c.object-meta.xml
<CustomObject>
    <label>Trigger Recordtype</label>
    <nameField>
        <label>Recordtype Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Recordtypes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Recordtype__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Enabled for this particular recordtype, but only if the Trigger is also enabled.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Recordtype__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <inlineHelpText>Use this format: Param1=Value1;Param2=Value2</inlineHelpText>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trigger_Recordtype__c/fields/Recordtype_Id__c.field-meta.xml
<CustomField>
    <fullName>Recordtype_Id__c</fullName>
    <inlineHelpText>18 character id of the recordtype</inlineHelpText>
    <label>Recordtype Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Recordtype__c/fields/Trigger__c.field-meta.xml
<CustomField>
    <fullName>Trigger__c</fullName>
    <label>Trigger</label>
    <referenceTo>Trigger__c</referenceTo>
    <relationshipLabel>Trigger Recordtypes</relationshipLabel>
    <relationshipName>Trigger_Recordtypes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OpportunityLegalEntityUpdate_Trig_Test.cls
/**
* File:         OpportunityLegalEntityUpdate_Trig_Test
* Project:      GreenField
* Created Date: 12/10/2019
* Created By:   Sachin Chaudhary
* *******************************************************************************************************
* @description : Test Class for Trigger_Opportunity, TriggerInterface_Opportunity, OpportunityLegalEntityUpdate_Trig
*/

@istest
private class OpportunityLegalEntityUpdate_Trig_Test {
    @isTest static void test() {
        //Create Trigger test record 
        Trigger__c trig = new Trigger__c(Name = 'OpportunityLegalEntityUpdate_Trig' , Trigger_Name_Unique__c='OpportunityLegalEntityUpdate_Trig',Enabled__c=true,Object__c='Opportunity',Run_for_Recordypes__c='All',Description__c='my test',Execution_Order__c=1,Before_Insert__c=true,Before_Update__c=true);
        Insert trig;
        
        Trigger_Recordtype__c rt = new Trigger_Recordtype__c(Enabled__c=true,Recordtype_Id__c=trig.Id,Trigger__c=trig.Id,Parameters__c='param=1;param=2');    
        Insert rt;   
        
        //Call account  trigger interface
        TriggerInterface_Opportunity obj = new TriggerInterface_Opportunity();
        System.debug(LoggingLevel.DEBUG, obj);

        String recTypeId = [SELECT Id FROM RecordType WHERE sObjectType IN ('opportunity') LIMIT 1].Id;

        TriggerInterfaceHelper.runTrigger('OpportunityLegalEntityUpdate_Trig','Opportunity',5, 'bi', recTypeId,null,'All'); 
        
         //Account Insert
        Account acc2 = new Account ();
        acc2.Name = 'Account2';
        acc2.BillingCity='test';
        acc2.BillingPostalCode='12342';
        acc2.BillingStateCode='UP';
        acc2.BillingCountryCode='IN';
        acc2.BillingStreet ='street2';
        acc2.Accounting_Credit_Hold__c ='OK';
        insert acc2;
        
        //Insert Legal Entity
        blng__LegalEntity__c entityObj = new blng__LegalEntity__c();
        entityObj.Name = 'TestLegal';
        entityObj.blng__Active__c = true;
        insert entityObj;
        
        //Insert Series
        Series__c seriesObj = new Series__c();
        seriesObj.Name = 'testSeries';
        seriesObj.Status__c = 'Active';
        seriesObj.Legal_Entity__c = entityObj.Id;
        insert seriesObj;
        
        //Insert Edition
        Edition__c editionObj = new Edition__c();
        editionObj.Name = 'testEdition';
        editionObj.Part_of_Series__c = seriesObj.Id;
        insert editionObj;
        
        system.assertNotEquals(null, editionObj, 'Edition cannot be null');

        Test.startTest();     
        // Creates second opportunity
        Opportunity oppt2 = new Opportunity(Name ='New mAWS Deal2',Default_Edition__c = editionObj.Id, AccountID = acc2.ID, StageName = 'Qualification',CloseDate = System.today());
        insert oppt2;
        Test.stopTest();
    }
}