force-app/main/default/objects/Account/fields/Accounting_Credit_Hold__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Credit_Hold__c</fullName>
    <description>Contains the status of credit hold for an account. Can be set to varying values. Should be restricted to only show for accounting and admins.</description>
    <inlineHelpText>Credit status of the account. OK - account is current, no restrictions. Warning - account has been flagged because it may be past due. Credit Hold - cannot sell to this customer without executive approval.</inlineHelpText>
    <label>Accounting Credit Hold</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
                <default>true</default>
                <label>OK</label>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Address_Status__c.field-meta.xml
<CustomField>
    <fullName>Address_Status__c</fullName>
    <defaultValue>&quot;Invalid&quot;</defaultValue>
    <description>Status to indicate if Address is valid against checks done by Mulesoft against LOV to ensure address is ERP compliant.</description>
    <label>Address Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
                <default>true</default>
                <label>Invalid</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Consist Source Org name from where the data is migrated from</description>
    <label>Legacy CRM Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legacy_CRM_Instance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Legacy CRM Instance</description>
    <label>Legacy CRM Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legacy_CRM_Instance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomLookupLwcCtrl_Test.cls
/**
* File			: CustomLookupLwcCtrl_Test
* Project		: Order & Billing Plateform  [GECI-236]
* Created Date	: 15th Dec 2022
* Created By   	: Girikon(Ashish)  
*****************************************************************************************************
@description : Test Class for CustomLookupLwcCtrl
******************************************************************************************************
* Modification log :
*/

@istest
private class CustomLookupLwcCtrl_Test {
	@isTest
    static void testAccountCreditStatusHold() {        
        // Create a test account
        Account acc = new Account ();
        acc.Name = 'My Test Account';
        acc.currencyisocode='USD';
        acc.BillingStreet ='street2';
        acc.BillingCity='test';
        acc.BillingStateCode='UP';
        acc.BillingCountryCode='IN';
        acc.BillingPostalCode='12342';
        acc.Accounting_Credit_Hold__c = 'Hold';
        acc.Address_Status__c = 'Valid';
        insert acc;
        
        Account acc2 = new Account ();
        acc2.Name = 'Account2';
        acc2.currencyisocode='USD';
        acc2.BillingStreet ='street2';
        acc2.BillingCity='test';
        acc2.BillingStateCode='UP';
        acc2.BillingCountryCode='IN';
        acc2.BillingPostalCode='12342';
        acc2.Accounting_Credit_Hold__c = 'Ok';
        acc2.Legacy_CRM_Instance__c = 'Penton';
        insert acc2;
        System.assertEquals('Account2', acc2.name,'true');
		
        CustomLookupLwcCtrl.fetchDefaultRecord(acc.Id,'Account');
        string reqJSON = '{"sObjectApiName":"Account","labelFieldAPI":"Name","filterCondition":"","otherSearchFields":"Type"}';
		list<sObject> listAccs =  CustomLookupLwcCtrl.fetchLookupData('Account',reqJSON);
        system.assertEquals(listAccs.Size(),2,'No Account Record Found!');
    }
}