force-app/main/default/objects/Account/fields/Accounting_Credit_Hold__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Credit_Hold__c</fullName>
    <description>Contains the status of credit hold for an account. Can be set to varying values. Should be restricted to only show for accounting and admins.</description>
    <inlineHelpText>Credit status of the account. OK - account is current, no restrictions. Warning - account has been flagged because it may be past due. Credit Hold - cannot sell to this customer without executive approval.</inlineHelpText>
    <label>Accounting Credit Hold</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
                <default>true</default>
                <label>OK</label>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Address_Status__c.field-meta.xml
<CustomField>
    <fullName>Address_Status__c</fullName>
    <defaultValue>&quot;Invalid&quot;</defaultValue>
    <description>Status to indicate if Address is valid against checks done by Mulesoft against LOV to ensure address is ERP compliant.</description>
    <label>Address Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
                <default>true</default>
                <label>Invalid</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Address_Status__c.field-meta.xml
<CustomField>
    <fullName>Address_Status__c</fullName>
    <defaultValue>&quot;Invalid&quot;</defaultValue>
    <description>Address Verification Status from SAP Status</description>
    <inlineHelpText>Address Verification Status from SAP Status</inlineHelpText>
    <label>Address Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invalid</fullName>
                <default>true</default>
                <label>Invalid</label>
            </value>
            <value>
                <fullName>Valid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is an explicit field for Bill To Account.</description>
    <label>Bill To Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Accounting_Credit_Hold__c</field>
            <operation>notEqual</operation>
            <value>Hold</value>
        </filterItems>
        <filterItems>
            <field>Account.Accounting_Credit_Hold__c</field>
            <operation>notEqual</operation>
            <value>Warning</value>
        </filterItems>
        <infoMessage>Account Credit Status is On Hold/Warning.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Bill To Account)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/BannerCtrl.cls
/**
*RA, 06/02/2020
*@description controller class for Banner lightning Component
*/
public  with sharing class BannerCtrl {

    /**
   *@description method to retrieve Account record
   *@param recId record Id
   *@return Account  
   */
    @AuraEnabled
    public static Account getAccRecord(String recId){
        String accRecId;
        Account acc;
        Id sId = (Id)recId;
        String sobjectType = sId.getSObjectType().getDescribe().getName();
        
        if(sobjectType == 'Account'){
            accRecId = recId;
        }
        if(sobjectType == 'Contact' && Schema.sObjectType.Contact.isAccessible()){
            Contact cnt = [Select Id, Name, AccountId from Contact Where Id =:recId ];
            accRecId = cnt.AccountId;
        }
        if(sobjectType == 'Opportunity' && Schema.sObjectType.Opportunity.isAccessible()){
            Opportunity opp = [Select Id, Name, Bill_To_Account__c from Opportunity Where Id =:recId ];
          accRecId = opp.Bill_To_Account__c;
        }
        if(accRecId != null && Schema.sObjectType.Account.isAccessible()){
             acc =  [Select Id, Name, Address_Status__c, Accounting_Credit_Hold__c from Account Where Id =:accRecId ];
        }
        return acc;
    }
}