force-app/main/default/objects/Account/fields/Accounting_Credit_Hold__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Credit_Hold__c</fullName>
    <description>Contains the status of credit hold for an account. Can be set to varying values. Should be restricted to only show for accounting and admins.</description>
    <inlineHelpText>Credit status of the account. OK - account is current, no restrictions. Warning - account has been flagged because it may be past due. Credit Hold - cannot sell to this customer without executive approval.</inlineHelpText>
    <label>Accounting Credit Hold</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
                <default>true</default>
                <label>OK</label>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Address_Status__c.field-meta.xml
<CustomField>
    <fullName>Address_Status__c</fullName>
    <defaultValue>&quot;Invalid&quot;</defaultValue>
    <description>Status to indicate if Address is valid against checks done by Mulesoft against LOV to ensure address is ERP compliant.</description>
    <label>Address Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
                <default>true</default>
                <label>Invalid</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Consist Source Org name from where the data is migrated from</description>
    <label>Legacy CRM Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legacy_CRM_Instance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Bypass__c/Application_Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to bypass validation rules, etc. in applications or integrations</description>
    <label>Application Bypass</label>
</CustomObject>

force-app/main/default/objects/Application_Bypass__c/fields/Bypass_Validation_Rules__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Validation_Rules__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Using $Setup.Application_Bypass__c.Bypass_Validation_Rules__c will ignore/bypass validation rules</inlineHelpText>
    <label>Bypass_Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Source CRM name from where Contact is created.</description>
    <label>Legacy CRM Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legacy_CRM_Instance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a field which will derive value from Order.</description>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Bill To Account)</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup of Contact object.</description>
    <label>Billing/Invoice Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Default_Edition__c.field-meta.xml
<CustomField>
    <fullName>Default_Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup of Edition object.</description>
    <label>Default Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Approval_Service_Now_ID__c.field-meta.xml
<CustomField>
    <fullName>Approval_Service_Now_ID__c</fullName>
    <description>Approval - Service Now ID</description>
    <label>Approval - Service Now ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Event_Code__c.field-meta.xml
<CustomField>
    <fullName>Event_Code__c</fullName>
    <label>Expocad Event Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Part_of_Series__c.field-meta.xml
<CustomField>
    <fullName>Part_of_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup store value of series this edition is part of</description>
    <label>Part of Series</label>
    <referenceTo>Series__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Event_Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Address_Status__c.field-meta.xml
<CustomField>
    <fullName>Address_Status__c</fullName>
    <defaultValue>&quot;Invalid&quot;</defaultValue>
    <description>Address Verification Status from SAP Status</description>
    <inlineHelpText>Address Verification Status from SAP Status</inlineHelpText>
    <label>Address Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invalid</fullName>
                <default>true</default>
                <label>Invalid</label>
            </value>
            <value>
                <fullName>Valid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is an explicit field for Bill To Account.</description>
    <label>Bill To Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Accounting_Credit_Hold__c</field>
            <operation>notEqual</operation>
            <value>Hold</value>
        </filterItems>
        <filterItems>
            <field>Account.Accounting_Credit_Hold__c</field>
            <operation>notEqual</operation>
            <value>Warning</value>
        </filterItems>
        <infoMessage>Account Credit Status is On Hold/Warning.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Bill To Account)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Billing Contact.</description>
    <label>Billing/Invoice Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Default_Edition__c.field-meta.xml
<CustomField>
    <fullName>Default_Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Edition of Opportunity</description>
    <label>Default Edition</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Edition__c.Edition_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Consist Source Org name from where the data originated (Source CRM)</description>
    <label>Legacy CRM Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legacy_CRM_Instance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Main_Contract__c.field-meta.xml
<CustomField>
    <fullName>Main_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Main Contract that is being changed by this opportunity.</description>
    <inlineHelpText>Main Contract that is being changed by this opportunity.</inlineHelpText>
    <label>Main Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities (Main Contract)</relationshipLabel>
    <relationshipName>ContractOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Contact__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Individual who is working with on this opportunity</description>
    <inlineHelpText>Individual you are working with on this opportunity</inlineHelpText>
    <label>Opportunity Contact</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Opportunity Contact)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Series__c.field-meta.xml
<CustomField>
    <fullName>Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Series to which Opportunity&apos;s Edition belongs.</description>
    <label>Series</label>
    <referenceTo>Series__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <description>Expiry Date of Product.</description>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Series__c/Series__c.object-meta.xml
<CustomObject>
    <description>It defines the Series Information. Each year&apos;s Edition will be tied to a particular Series.</description>
    <label>Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Series__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of Series</description>
    <label>Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger__c/Trigger__c.object-meta.xml
<CustomObject>
    <label>Trigger</label>
    <nameField>
        <label>Trigger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger__c/fields/Before_Insert__c.field-meta.xml
<CustomField>
    <fullName>Before_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Before_Update__c.field-meta.xml
<CustomField>
    <fullName>Before_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Execution_Order__c.field-meta.xml
<CustomField>
    <fullName>Execution_Order__c</fullName>
    <label>Execution Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>This trigger runs against which object?</inlineHelpText>
    <label>Object</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Run_for_Recordypes__c.field-meta.xml
<CustomField>
    <fullName>Run_for_Recordypes__c</fullName>
    <label>Run for Recordypes</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Trigger_Name_Unique__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Name_Unique__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Trigger Name Unique</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Cls_amendContract_Test.cls
/**
* File:            Cls_amendContract_Test
* Project:         GAP
* Code Coverage:   89%
* Date:            Dec 31, 2019
* Created By:      Sachin Chaudhary
* *************************************************************************
* Description:     Test class for cls_amendContract.
* *************************************************************************
* History:
*/

@isTest(seeAlldata = false)
public class Cls_amendContract_Test {
    
    static testMethod void amendTest() {
        
        
        Trigger__c trig = new Trigger__c(Name = 'OpportunityNameUpdate_Trig' , Trigger_Name_Unique__c='OpportunityNameUpdate_Trig',Enabled__c=true,Object__c='Opportunity',Run_for_Recordypes__c='All',Description__c='my test',Execution_Order__c=1,Before_Insert__c=true,Before_Update__c=true);
        Insert trig;
        
        Application_Bypass__c oAB = new Application_Bypass__c(SetupOwnerId=UserInfo.getOrganizationId(), Bypass_Validation_Rules__c = True);
        Insert oAB ;
        
        Account oAccount = new Account();
        oAccount.Name='Expocad Account';
        oAccount.CurrencyIsoCode = 'USD';
        oAccount.Address_Status__c = 'Valid';
        oAccount.Name = 'Account2';
        oAccount.BillingCity='test';
        oAccount.Legacy_CRM_Instance__c = 'Penton';
        oAccount.BillingPostalCode='12342';
        oAccount.BillingStateCode='UP';
        oAccount.BillingCountryCode='IN';
        oAccount.BillingStreet ='street2';
        oAccount.Accounting_Credit_Hold__c ='OK';
        insert oAccount;
        
        System.assertEquals('Account2' , oAccount.Name, 'true');
        Contact oCon = new Contact(LastName='ContTest1', Legacy_CRM_Instance__c = 'Penton', Email='test1contact@duptest.com', AccountId = oAccount.Id, MailingStreet = 'Test',MailingCity ='Test',MailingState='',MailingCountry='India');
        insert oCon;
        
        User oUser = [SELECT Id FROM User WHERE Id = : UserInfo.getUserId()];
        
        Series__c oEventseries = new Series__c(Name = 'World Of Concrete', CurrencyISOCode = 'USD');
        insert oEventseries;
        
        Edition__c oEvent = new Edition__c(Name = 'World of Concrete 2017',Part_of_Series__c=oEventseries.Id,Approval_Service_Now_ID__c = '123', CurrencyIsoCode = 'USD', Event_Code__c = 'KDB,KDB2');
        insert oEvent;
        
        System.assertEquals('World of Concrete 2017' , oEvent.Name, 'true');
        
        Opportunity oOpportunity = new Opportunity(Name = 'Test Opp', CloseDate = Date.newInstance(2019, 11, 5),StageName = 'Proposal',Address_Status__c = 'Valid', Default_Edition__c = oEvent.Id, Series__c = oEventseries.Id, AccountId = oAccount.Id, Opportunity_Contact__c= oCon.Id,Bill_To_Account__c = oAccount.Id,Billing_Contact__c = oCon.Id);
        insert oOpportunity;
        
        SBQQ__Quote__c oQuote = new SBQQ__Quote__c(CurrencyIsoCode = 'USD', SBQQ__Status__c = 'Draft', SBQQ__Type__c = 'Quote', SBQQ__Opportunity2__c = oOpportunity.Id, SBQQ__Account__c = oAccount.Id, SBQQ__Primary__c = true);
        insert oQuote;
        
        Id pricebookId = Test.getStandardPricebookId();
        Product2 prd1 = new Product2(Name = 'Post Draw Indoor Booth',Family = 'Booth', Expiry_Date__c = Date.today());
        insert prd1;
        Pricebook2 customPB = new Pricebook2(Name='ICRE', isActive=true);
        insert customPB;
        PricebookEntry stndrdPrice1 = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = prd1.Id,UnitPrice = 100, IsActive = true);
        insert stndrdPrice1;
        PricebookEntry iCREPrice1 = new PricebookEntry(Pricebook2Id = customPB.Id, Product2Id = prd1.Id,UnitPrice = 200, IsActive = true);
        insert iCREPrice1;
        
        SBQQ__QuoteLine__c oQuoteLine = new SBQQ__QuoteLine__c(SBQQ__Quote__c = oQuote.Id, SBQQ__Product__c = prd1.Id, SBQQ__Quantity__c = 2, SBQQ__Number__c = 1, Line_Description__c = 'Test', Booth_Number__c = 'TESTBN3', Booth__c = True);
        insert oQuoteLine ;
        
        Contract oContract = new Contract(AccountId = oAccount.id,CustomerSignedId =oCon.Id ,StartDate = Date.today(), ContractTerm = 12, SBQQ__Opportunity__c = oOpportunity.id, SBQQ__Quote__c = oQuote.Id);
        insert oContract;
        
        Test.StartTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(oOpportunity);
        Apexpages.currentpage().getparameters().put('oppId' , oOpportunity.id);
        Cls_amendContract oAmendContract = new Cls_amendContract(sc);
        oAmendContract.amendContract();
        
        oOpportunity.StageName = 'Closed Won';
        oOpportunity.Main_Contract__c = null;
        update oOpportunity;
        oAmendContract.amendContract();
        
        
        oOpportunity.Main_Contract__c = oContract.id;
        update oOpportunity;
        oAmendContract.amendContract();
        
        oOpportunity.SBQQ__AmendedContract__c = oContract.id;
        update oOpportunity;
        oAmendContract.amendContract();
        
        oAmendContract.redirectOppty();
        Test.StopTest();
    }
}