force-app/main/default/objects/Account/fields/Accounting_Credit_Hold__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Credit_Hold__c</fullName>
    <description>Contains the status of credit hold for an account. Can be set to varying values. Should be restricted to only show for accounting and admins.</description>
    <inlineHelpText>Credit status of the account. OK - account is current, no restrictions. Warning - account has been flagged because it may be past due. Credit Hold - cannot sell to this customer without executive approval.</inlineHelpText>
    <label>Accounting Credit Hold</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
                <default>true</default>
                <label>OK</label>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/CutoffDate_1__c.field-meta.xml
<CustomField>
    <fullName>CutoffDate_1__c</fullName>
    <description>Cutoff Date 2 for payment schedule.</description>
    <label>Cutoff Date 2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/CutoffDate__c.field-meta.xml
<CustomField>
    <fullName>CutoffDate__c</fullName>
    <description>Cutoff Date 1 for payment schedule.</description>
    <label>Cutoff Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Part_of_Series__c.field-meta.xml
<CustomField>
    <fullName>Part_of_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup store value of series this edition is part of</description>
    <label>Part of Series</label>
    <referenceTo>Series__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Event_Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <description>Payment Schedule</description>
    <label>Payment Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Schedule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Show_Deliverables__c.field-meta.xml
<CustomField>
    <fullName>Show_Deliverables__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Uncheck the checkbox to hide deliverables on the quote/contract template.</description>
    <inlineHelpText>Uncheck the checkbox to hide deliverables on the quote/contract template.</inlineHelpText>
    <label>Show Deliverables</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Edition__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Default_Edition__c.field-meta.xml
<CustomField>
    <fullName>Default_Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Edition of Opportunity</description>
    <label>Default Edition</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Edition__c.Edition_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <description>This picklist provides options for all payment schedules available</description>
    <inlineHelpText>This picklist provides options for all payment schedules available</inlineHelpText>
    <label>Payment Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Schedule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Series__c.field-meta.xml
<CustomField>
    <fullName>Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Series to which Opportunity&apos;s Edition belongs.</description>
    <label>Series</label>
    <referenceTo>Series__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Payment_Schedule__c/Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This object is used to stores the payment schedule datas into their respective fields.</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Payment Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Series__c/Series__c.object-meta.xml
<CustomObject>
    <description>It defines the Series Information. Each year&apos;s Edition will be tied to a particular Series.</description>
    <label>Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Series__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of Series</description>
    <label>Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Series__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Trigger__c/Trigger__c.object-meta.xml
<CustomObject>
    <label>Trigger</label>
    <nameField>
        <label>Trigger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger__c/fields/Before_Insert__c.field-meta.xml
<CustomField>
    <fullName>Before_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Execution_Order__c.field-meta.xml
<CustomField>
    <fullName>Execution_Order__c</fullName>
    <label>Execution Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>This trigger runs against which object?</inlineHelpText>
    <label>Object</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <description>Use this format: Param1=Value1;Param2=Value2</description>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Run_for_Recordypes__c.field-meta.xml
<CustomField>
    <fullName>Run_for_Recordypes__c</fullName>
    <label>Run for Recordypes</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Trigger_Name_Unique__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Name_Unique__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Trigger Name Unique</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trigger_Recordtype__c/Trigger_Recordtype__c.object-meta.xml
<CustomObject>
    <label>Trigger Recordtype</label>
    <nameField>
        <label>Recordtype Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Recordtypes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Recordtype__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Enabled for this particular recordtype, but only if the Trigger is also enabled.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Recordtype__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <inlineHelpText>Use this format: Param1=Value1;Param2=Value2</inlineHelpText>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trigger_Recordtype__c/fields/Recordtype_Id__c.field-meta.xml
<CustomField>
    <fullName>Recordtype_Id__c</fullName>
    <inlineHelpText>18 character id of the recordtype</inlineHelpText>
    <label>Recordtype Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Recordtype__c/fields/Trigger__c.field-meta.xml
<CustomField>
    <fullName>Trigger__c</fullName>
    <label>Trigger</label>
    <referenceTo>Trigger__c</referenceTo>
    <relationshipLabel>Trigger Recordtypes</relationshipLabel>
    <relationshipName>Trigger_Recordtypes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OpportunityAccountTaxNumber_Trig_Test.cls
/**
* File:         OpportunityAccountTaxNumber_Trig_Test
* Project:      GreenField
* Created Date: 11/15/2019
* Created By:   Yash Gupta
* *******************************************************************************************************
* @description : Test Class for Trigger_Opportunity, TriggerInterface_Opportunity, OpportunityAccountTaxNumber_Trig
* *******************************************************************************************************
* History:    Modified By Yash Gupta [11/27/2019], Increase code coverage.
*/

@istest
public class OpportunityAccountTaxNumber_Trig_Test {
    public static testMethod void test() {
        //Create Trigger test record 
        Trigger__c trig = new Trigger__c(Name = 'OpportunityAccountTaxNumber_Trig' , Trigger_Name_Unique__c='OpportunityAccountTaxNumber_Trig',Enabled__c=true,Object__c='Opportunity',Run_for_Recordypes__c='All',Description__c='my test',Execution_Order__c=1,Before_Insert__c=true);
        Insert trig;
        
        Trigger_Recordtype__c rt = new Trigger_Recordtype__c(Enabled__c=true,Recordtype_Id__c=trig.Id,Trigger__c=trig.Id,Parameters__c='param=1;param=2');    
        Insert rt;   
        
        //Call account  trigger interface
        TriggerInterface_Opportunity obj = new TriggerInterface_Opportunity();
        
        //Call trigger app handler for insert event
       // string accountOnHoldID = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Opportunity_Account_Unhold').getRecordTypeId();
       // system.debug('accountOnHoldID: '+accountOnHoldID);
        string recTypeId = [Select Id From RecordType Where sObjectType IN ('opportunity') LIMIT 1].Id;
        system.debug('recTypeId:'+recTypeId);
        TriggerInterfaceHelper.runTrigger('OpportunityAccountTaxNumber_Trig','Opportunity',5, 'bi', recTypeId,null,'All'); 
        
        //Account Insert
        Account acc2 = new Account ();
        acc2.Name = 'Account2';
        acc2.BillingCity='test';
        acc2.BillingPostalCode='12342';
        acc2.BillingStateCode='UP';
        acc2.BillingCountryCode='IN';
        acc2.BillingStreet ='street2';
        acc2.Accounting_Credit_Hold__c ='OK';
        insert acc2;
        System.assertNotEquals(null, acc2, 'Account Name and Billing Address cannot be null');

        Contact oCon = new Contact(LastName='ContTest1', Email='test1contact@duptest.com', AccountId = acc2.Id);
        insert oCon;
        
        Series__c oESeries = new Series__c(name='World of Concrete');
        insert oEseries;
        
        Edition__c ee = new Edition__c();
        ee.Name = 'TestEvent';
        ee.Part_of_Series__c = oEseries.Id;
        ee.Show_Deliverables__c = true;
        ee.Payment_Schedule__c = '50-50';
        ee.CutoffDate__c = date.today();
        ee.CutoffDate_1__c = date.today().addDays(1);
        insert ee;
             
        // Creates second opportunity
        Opportunity oppt2 = new Opportunity(Name ='New mAWS Deal2', AccountID = acc2.ID, StageName = 'Closed won',CloseDate = System.today(), Default_Edition__c =ee.Id );
        insert oppt2;
    }
}