force-app/main/default/objects/Account/fields/Accounting_Credit_Hold__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Credit_Hold__c</fullName>
    <description>Contains the status of credit hold for an account. Can be set to varying values. Should be restricted to only show for accounting and admins.</description>
    <inlineHelpText>Credit status of the account. OK - account is current, no restrictions. Warning - account has been flagged because it may be past due. Credit Hold - cannot sell to this customer without executive approval.</inlineHelpText>
    <label>Accounting Credit Hold</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
                <default>true</default>
                <label>OK</label>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IM_Account_No__c.field-meta.xml
<CustomField>
    <fullName>IM_Account_No__c</fullName>
    <description>Informa Markets Customer facing Account Number and will be sent to the ERP’s</description>
    <formula>IF( ISBLANK(Account_Number_Text__c) , Account_Number__c, Account_Number_Text__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Informa Markets Customer facing Account Number and will be sent to the ERP’s</inlineHelpText>
    <label>IM Account No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/One_Invoice_Per_Contract__c.field-meta.xml
<CustomField>
    <fullName>One_Invoice_Per_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It will control the creation of single Invoice created on opportunity.</description>
    <inlineHelpText>It will control the creation of single Invoice created on opportunity.</inlineHelpText>
    <label>One Invoice Per Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <description>Payment term for Account.</description>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Due on Receipt</fullName>
            </value>
            <value>
                <fullName>Net 15</fullName>
            </value>
            <value>
                <fullName>Net 30</fullName>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountRESTService_Test.cls
/**
* File      	:   AccountRESTService_Test
* Project       : 	Informa Order Management 
* Created By  	:   Girikon(Ashish)
* Created Date  :   03rd Feb 2022
******************************************************************************************************
* @description : Test Class to provide code covrage to classes - AccountCreditStatusRESTService
******************************************************************************************************
* Last Modified By :
*/
@istest
private class AccountRESTService_Test {
    @testSetup 
    static void setup() 
    {
        // Create an account
        Account acc = new Account ();
        acc.Name = 'TESTACC';
        acc.currencyisocode='USD';
        acc.BillingStreet ='street2';
        acc.BillingCity='test';
        acc.BillingCity='Alaska';
        acc.BillingState='tamil nadu';
        acc.BillingCountryCode='IN';
        acc.BillingPostalCode='12342';
        acc.One_Invoice_Per_Contract__c = true;
        acc.Payment_Term__c='Net 10';
        insert acc;
    }

    @isTest
    private static void  testAccountCreditStatusRESTService()
    {
        Account acc = [Select Id,IM_Account_No__c from Account limit 1];
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/accountcreditstatus'; 
        req.httpMethod = 'Patch';
        req.addHeader('Content-Type', 'application/json'); 
        RestContext.request = req;
        RestContext.response = res; 
        
        Test.startTest();
            AccountCreditStatusRESTService.updateCreditStatusOnAccount(acc.IM_Account_No__c,'Hold');
        Test.stopTest();

        Account accafter = [Select Id,Accounting_Credit_Hold__c from Account limit 1];
        System.assertEquals('Hold', accafter.Accounting_Credit_Hold__c, 'Accounting Credit Status updated successfully');
    }
}