force-app/main/default/objects/Account/fields/Account_Number_Text__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Text__c</fullName>
    <description>Used to record IM Account Number. Used to preserve Account ID’s when Salesforce Account are merged.</description>
    <inlineHelpText>Used to record IM Account Number. Used to preserve Account ID’s when Salesforce Account are merged.</inlineHelpText>
    <label>Account Number Text</label>
    <length>130</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legacy_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Account_Id__c</fullName>
    <description>18 digits Account Id of Source Org</description>
    <label>Legacy Account Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Consist Source Org name from where the data is migrated from</description>
    <label>Legacy CRM Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legacy_CRM_Instance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountFieldUpdate_Trig.cls
/**
* File			: 	AccountFieldUpdate_Trig
* Project       :   GE-CRM-IOM [GECI-763]
* Created By	: 	Girikon(Ansh)
* Created Date	: 	17th Mar 2023
* Test Class    :   
* **************************************************************************************
* @description : Helper class to update account fields
****************************************************************************************
* Modification log :
* 1.
*/
public with sharing class AccountFieldUpdate_Trig implements TriggerInterface_Account.Runnable{
    public static final string ACCOUNTLEGACYCRMINSTANCE = 'AccountLegacyCRMInstance';
    /*
    * @description [Call Interface Class to fetch the new list and old map of account]
    * @param TriggerInterface_Account [fetch the trigger new list and old map]
    */
    public void run(TriggerInterface_Account.Trig trig)
    {
        if(trig.isBefore && (trig.isInsert || trig.isUpdate)) 
        {   
            updateIOMAccount(trig);
        }
    }
    /*
    * @description [method to update account fields]
    * @param TriggerInterface_Account [fetch the trigger new list and old map]
    */
    public static void updateIOMAccount(TriggerInterface_Account.Trig trig){
        String legacyCRMValuesCSV = GlobalConstants.getValue(ACCOUNTLEGACYCRMINSTANCE);

        List<String> legacyCRMValues = legacyCRMValuesCSV.split(',');
		
        Set<Id> accountIdsToUpdate = new Set<Id>();
        for (Account acc : trig.newList) {
            Account oldacc = trig.isUpdate ? trig.oldMap.get(acc.Id):new Account();
            if (String.isNotBlank(acc.Legacy_CRM_Instance__c) && legacyCRMValues.contains(acc.Legacy_CRM_Instance__c)) {
                if((trig.isUpdate && 
                    (acc.Legacy_CRM_Instance__c != oldacc.Legacy_CRM_Instance__c ||
                     acc.Legacy_Account_Id__c != oldacc.Legacy_Account_Id__c))
                     || (trig.isInsert))
                {
                    acc.Account_Number_Text__c = acc.Legacy_Account_Id__c;
                }
            }
        }
    }
}