force-app/main/default/objects/Account/fields/Address_Status__c.field-meta.xml
<CustomField>
    <fullName>Address_Status__c</fullName>
    <defaultValue>&quot;Invalid&quot;</defaultValue>
    <description>Status to indicate if Address is valid against checks done by Mulesoft against LOV to ensure address is ERP compliant.</description>
    <label>Address Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
                <default>true</default>
                <label>Invalid</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To mark account as active/inactive based on status in ERP System.</description>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IOM_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>IOM_Sync_Status__c</fullName>
    <description>Sync Status of Account while sending Account to IOM From CRM.</description>
    <label>IOM Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IOM_Sync_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Contact</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Operations Contact</fullName>
            </value>
            <value>
                <fullName>Invoice Contact</fullName>
            </value>
            <value>
                <fullName>Accounting Contact</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Booth Logistics</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Editorial Contact</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Health and Safety Contact</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing Services</fullName>
            </value>
            <value>
                <fullName>Primary Booth Contact</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Show Coordinator</fullName>
            </value>
            <value>
                <fullName>Booth Contact</fullName>
            </value>
            <value>
                <fullName>Nota Fiscal</fullName>
            </value>
            <value>
                <fullName>Stand Contractor</fullName>
            </value>
            <value>
                <fullName>Agreement Contact</fullName>
            </value>
            <value>
                <fullName>MarkitMkr</fullName>
            </value>
            <value>
                <fullName>Operation Contact 2</fullName>
            </value>
            <value>
                <fullName>Local Representative</fullName>
            </value>
            <value>
                <fullName>Legal Representative 1</fullName>
            </value>
            <value>
                <fullName>Legal Representative 2</fullName>
            </value>
            <value>
                <fullName>Witness</fullName>
            </value>
            <value>
                <fullName>No Revenue</fullName>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To mark contact as active/inactive based on status in ERP System.</description>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IOM_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>IOM_Sync_Status__c</fullName>
    <description>Sync Status of Account while sending Contact to IOM From CRM.</description>
    <label>IOM Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IOM_Sync_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/IOM_Application_Bypass__c/IOM_Application_Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>To prevention deletion of Account, Opportunity and Contact records.</description>
    <label>IOM Application Bypass</label>
</CustomObject>

force-app/main/default/objects/IOM_Application_Bypass__c/fields/Bypass_Account_Deletion__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Account_Deletion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If an entry exist with this field checked then user will be able to delete Account.</description>
    <label>Bypass Account Deletion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Address_Status__c.field-meta.xml
<CustomField>
    <fullName>Address_Status__c</fullName>
    <defaultValue>&quot;Invalid&quot;</defaultValue>
    <description>Address Verification Status from SAP Status</description>
    <inlineHelpText>Address Verification Status from SAP Status</inlineHelpText>
    <label>Address Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invalid</fullName>
                <default>true</default>
                <label>Invalid</label>
            </value>
            <value>
                <fullName>Valid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IOM_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>IOM_Sync_Status__c</fullName>
    <description>Sync staus of sending opportunity to IOM for billing</description>
    <label>IOM Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IOM_Sync_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/IOM_ObjectValidation_Test.cls
/**
* File      :   IOM_ObjectValidation_Test
* Project        : Informa Order Management 
* Created By  :   Suresh(Girikon)
* Created Date  :   28th Dec 2021
* ******************************************************************************************************
* @description : Test Class to provide code covrage to classes - IOM_ObjectValidation() 
* Last Modified By :
*/
@isTest
public with sharing class IOM_ObjectValidation_Test {

    @isTest
    public static void testPreventAccDel() {
        
        insert new IOM_Application_Bypass__c(SetupOwnerId=UserInfo.getUserId(), Bypass_Account_Deletion__c=false);
        
        Account acc1 = new Account();
        acc1.Name='acc1';
        acc1.BillingCity ='Delhi' ;
        acc1.BillingCountry='india';
        acc1.BillingPostalCode='600075';
        acc1.BillingState='Delhi';
        acc1.IOM_Sync_Status__c = 'Complete';
        acc1.BillingStreet='water well street';              
        insert acc1;

        try{
            delete acc1;
        }catch(DMLexception e){
            system.assert(e.getMessage().contains('You are not allowed to delete Account records!'),'You are not allowed to delete Account records!');                       
        }
    }
    @isTest
    public static void testPreventOppDel() {
        
        insert new IOM_Application_Bypass__c(SetupOwnerId=UserInfo.getUserId(), Bypass_Account_Deletion__c=false);
        
        Account acc1 = new Account();
        acc1.Name='acc1';
        acc1.BillingCity ='Delhi' ;
        acc1.BillingCountry='india';
        acc1.BillingPostalCode='600075';
        acc1.BillingState='Delhi';
        acc1.BillingStreet='water well street';              
        insert acc1;
        
        Opportunity opp = new Opportunity(
            CloseDate =Date.newInstance(2019, 11, 5),
            StageName ='Proposal',
            Name ='TESTOPP',Address_Status__c = 'Valid',
            IOM_Sync_Status__c = 'Complete',
            AccountId=acc1.Id);
        insert opp;

        try{
            delete opp;
        }catch(DMLexception e){
            system.assert(e.getMessage().contains('You are not allowed to delete Opportunity records!'),'You are not allowed to delete Opportunity records!');                       
        }
    }
    @isTest
    public static void testPreventConDel() {
        
        insert new IOM_Application_Bypass__c(SetupOwnerId=UserInfo.getUserId(), Bypass_Account_Deletion__c=false);
        
        Account acc1 = new Account();
        acc1.Name='acc1';
        acc1.BillingCity ='Delhi' ;
        acc1.BillingCountry='india';
        acc1.BillingPostalCode='600075';
        acc1.BillingState='Delhi';
        acc1.BillingStreet='water well street';              
        insert acc1;
        
        Contact oCon1 = new Contact();
        oCon1.FirstName = 'test';
        oCon1.Contact_Type__c = 'Invoice Contact';
        oCon1.LastName = 'ContTest11';
        oCon1.Email = 'abcd1@gmail.com';
        oCon1.AccountId = acc1.Id;
        oCon1.MailingStreet = 'Test1';
        oCon1.IOM_Sync_Status__c = 'Complete';
        oCon1.MailingCity = 'Test1';
        oCon1.MailingState='';
        oCon1.MailingCountry='India';
        oCon1.Phone = '+12345564788'; 
        oCon1.Inactive__c = false;
        oCon1.AssistantPhone = '+12445567788'; 
        oCon1.HomePhone = '+12345567388'; 
        oCon1.MobilePhone = '+12335567788'; 
        oCon1.OtherPhone = '+12346567788';
        insert oCon1;

        try{
            delete oCon1;
        }catch(DMLexception e){
            system.assert(e.getMessage().contains('You are not allowed to delete Contact records!'),'You are not allowed to delete Contact records!');                       
        }
    }
}