force-app/main/default/objects/Account/fields/Address_Verified__c.field-meta.xml
<CustomField>
    <fullName>Address_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Status of the address verified check.</description>
    <label>Address Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Consist Source Org name from where the data is migrated from</description>
    <label>Legacy CRM Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legacy_CRM_Instance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <description>Account Tax Id in ERP(SAP).</description>
    <label>Tax ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Address_Verified__c.field-meta.xml
<CustomField>
    <fullName>Address_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Checked means Address is verified from ERP System.</description>
    <label>Address Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Source CRM name from where Contact is created.</description>
    <label>Legacy CRM Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legacy_CRM_Instance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is an explicit field for Bill To Account.</description>
    <label>Bill To Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Accounting_Credit_Hold__c</field>
            <operation>notEqual</operation>
            <value>Hold</value>
        </filterItems>
        <filterItems>
            <field>Account.Accounting_Credit_Hold__c</field>
            <operation>notEqual</operation>
            <value>Warning</value>
        </filterItems>
        <infoMessage>Account Credit Status is On Hold/Warning.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Bill To Account)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Billing Contact.</description>
    <label>Billing/Invoice Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Consist Source Org name from where the data originated (Source CRM)</description>
    <label>Legacy CRM Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legacy_CRM_Instance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Contact__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Individual who is working with on this opportunity</description>
    <inlineHelpText>Individual you are working with on this opportunity</inlineHelpText>
    <label>Opportunity Contact</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Opportunity Contact)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/AccountRelatedAccountValidation_Test.cls
/**
* File:        AccountRelatedAccountValidation_Test
* Date:        13 jan 2020
* Created By : Girikon(Ashish)
* Apex Class : AccountRelatedAccountValidation
* *************************************************************************
* @description: This test class test the AccountRelatedAccountValidation
* *************************************************************************
* History: 
*/

@isTest
public class AccountRelatedAccountValidation_Test {
    
    @testSetup static void createSetup( ) {
                Account acc = new Account( );
        acc.name              = 'TestAccount';
        acc.BillingStreet     = '456 Zepplin Avenue';
        acc.BillingCity       = 'Las Vegas';
        acc.BillingState      = 'Delhi';
        acc.BillingPostalCode = '110025';
        acc.BillingCountry    = 'India';
        acc.Legacy_CRM_Instance__c = 'Penton';
        acc.Phone             = '1234567890';
        acc.Fax               = '1234567890';
        insert acc;
        
        Contact con = new Contact( );
        con.Email             = 'test.test@gmail.com';
        con.Phone             = '1234567890';
        con.Title             = 'Mr.';
        con.Legacy_CRM_Instance__c = 'Penton';
        con.FirstName         = 'TestFN';
        con.LastName          = 'testLN';
        con.AccountId         = acc.Id;
        con.MailingStreet     = 'TestStreet';
        con.MailingCity       = 'Las Vegas';
        con.MailingPostalCode = '89131';
        con.MailingState      = 'Delhi';
        con.MailingCountry    = 'India';
        con.Fax               = '1234567890';
        insert con;
        
        // Create an Oppty
        Opportunity opp = new Opportunity(           
            CloseDate =Date.newInstance(2019, 11, 5),
            StageName ='Proposal',
            Name ='TESTOPP',  
            AccountId=acc.Id,Bill_To_Account__c=acc.Id,Opportunity_Contact__c=con.Id,Billing_Contact__c=con.Id);
        insert opp;     
    }
    @isTest static void testAccntValidation() 
    {    
        map<Id,Contact> mapCon = new map<Id,Contact>();
         Opportunity opp = Database.query('SELECT Id,Opportunity_Contact__c,Name FROM Opportunity WHERE Name = \'TESTOPP\'');
         System.assertEquals('TESTOPP' , opp.Name, 'true');
        for(Contact con:[select id,AccountId,Email, Phone, Title, Name, FirstName, LastName,MailingStreet, MailingCity, MailingPostalCode, MailingState, MailingCountry, Fax,Address_Verified__c  from Contact where id = : opp.Opportunity_Contact__c])
        {
            mapCon.put(con.AccountId,con);
        } 
        List<Account> aScopeList = new List<Account> ([SELECT Id, Name, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, Phone, Fax, blng__BillToContact__c, Tax_Id__c, BillingCountryCode, BillingStateCode FROM Account WHERE ID IN : mapCon.keyset()]); 
        Test.startTest();
        PageReference pg = Page.ValidateBlngContactAccntBlngAdd;
        Test.setCurrentPage( pg );
        pg.getParameters().put( 'Id', String.valueOf(opp.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);            
        AccountRelatedAccountValidationCtrl ctrl = new AccountRelatedAccountValidationCtrl(sc);
        
        Database.BatchableContext     bc;
        AccountRelatedAccountValidationCtrl ctrl2 = new AccountRelatedAccountValidationCtrl(mapCon.keySet(),mapCon,opp.Id);
        Test.setMock(HttpCalloutMock.class, new AccountRelatedAccountValidationMock());
        ctrl.validateAccountBillingAddress();
        ctrl2.execute(bc, aScopeList);
        ctrl2.finish(bc);
        ctrl.validateAccountBillingAddress();
        ctrl.back2opportunity();
        //ctrl.batchProcessId = opp.Id;
        //ctrl.batchStatus ='Start';
        ctrl.batchProcess();
        
        Test.stopTest();
    }
    @isTest static void testAccntValidation2() 
    { 
        Opportunity opp = Database.query('SELECT Id,Opportunity_Contact__c FROM Opportunity WHERE Name = \'TESTOPP\'');
        opp.Opportunity_Contact__c = null;
        update opp;
        System.assertNotEquals(null,opp.id,'opp update failed');
         Test.startTest();
        PageReference pg = Page.ValidateBlngContactAccntBlngAdd;
        Test.setCurrentPage( pg );
        pg.getParameters().put( 'Id', String.valueOf(opp.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);            
        AccountRelatedAccountValidationCtrl ctrl = new AccountRelatedAccountValidationCtrl(sc);
        ctrl.validateAccountBillingAddress();
        Test.stopTest();
    }
    @isTest static void testAccntValidation3() 
    { 
        Opportunity opp = Database.query('SELECT Id,Opportunity_Contact__c FROM Opportunity WHERE Name = \'TESTOPP\'');
        opp.Billing_Contact__c = null;
        update opp;
        System.assertNotEquals(null,opp.id,'opp update failed');
         Test.startTest();
        PageReference pg = Page.ValidateBlngContactAccntBlngAdd;
        Test.setCurrentPage( pg );
        pg.getParameters().put( 'Id', String.valueOf(opp.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);            
        AccountRelatedAccountValidationCtrl ctrl = new AccountRelatedAccountValidationCtrl(sc);
        ctrl.validateAccountBillingAddress();
        Test.stopTest();
    }
}