force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description>Field to identify Branch</description>
    <label>Brand (s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa Health</fullName>
            </value>
            <value>
                <fullName>Arab Health</fullName>
            </value>
            <value>
                <fullName>Channel Partners</fullName>
            </value>
            <value>
                <fullName>Channel Partners Cloud Insights</fullName>
            </value>
            <value>
                <fullName>Channel Partners Conference &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Channel Partners Evolution</fullName>
            </value>
            <value>
                <fullName>Channel Partners Store</fullName>
            </value>
            <value>
                <fullName>China Beauty Expo</fullName>
            </value>
            <value>
                <fullName>EndoNurse Institute</fullName>
            </value>
            <value>
                <fullName>Fispal Cafe</fullName>
            </value>
            <value>
                <fullName>Fispal Tecnologia Expo</fullName>
            </value>
            <value>
                <fullName>Greenbuild Int&apos;l Conf &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Infection Control Today</fullName>
            </value>
            <value>
                <fullName>Ingredient Marketplace Global Expo&amp;Conf</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Developers Conf</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Executive Symposium</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Store</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage World Expo</fullName>
            </value>
            <value>
                <fullName>Interior Design Show</fullName>
            </value>
            <value>
                <fullName>National Tanning Training Institute</fullName>
            </value>
            <value>
                <fullName>Natural Products INSIDER</fullName>
            </value>
            <value>
                <fullName>Petfood 2.0 Conference &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Self-Storage Talk</fullName>
            </value>
            <value>
                <fullName>Self-Storage Training Institute</fullName>
            </value>
            <value>
                <fullName>SupplySide</fullName>
            </value>
            <value>
                <fullName>SupplySide Animal Nutrition Insights</fullName>
            </value>
            <value>
                <fullName>SupplySide Beverage Insights</fullName>
            </value>
            <value>
                <fullName>SupplySide Fispal Brazil Expo</fullName>
            </value>
            <value>
                <fullName>SupplySide Health Technology Insights</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>It defines the Brand Information. A series can belong to a particular brand.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>user type</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>x_1st Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>Defines the user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Look up to Account record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Edition Mappings (Account)</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Look up to Contact record</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Not a Customer Center Contact.</errorMessage>
        <filterItems>
            <field>Contact.IOM_Contact_Identifier__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <description>Defines status of account contact relationship</description>
    <label>Relationship Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Templates__c/Email_Templates__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object will be used a Global Email Templates.</description>
    <label>Email Template</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Series__c/Series__c.object-meta.xml
<CustomObject>
    <description>It defines the Series Information. Each year&apos;s Edition will be tied to a particular Series.</description>
    <label>Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Series__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Brand of Series</description>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Series</relationshipLabel>
    <relationshipName>Event_Series</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IMCC_EditionWelcomeEmailTest.cls
/**
* Created/Modified By: Girikon(Keertiraj)
* Created On:          24th Oct 2021
* @description : This test class covers the apex class : IMCC_EditionWelcomeEmail
* Apex Class:    IMCC_EditionWelcomeEmail(94%) and IMCC_UtilityMethod_Handler(93%) 
**/

@isTest
private class IMCC_EditionWelcomeEmailTest {
    
    @testSetUp
    static void testUserData(){
        UserRole userrole = [Select Id, DeveloperName From UserRole Where DeveloperName = 'Administrator' Limit 1];
        User adminUser = [Select Id, UserRoleId From User Where Profile.Name='System Administrator' and IsActive = true Limit 1];
        adminUser.UserRoleId = userrole.Id;
        update adminUser;

        List<Account> accts = new List<Account>();
        List<String> accountNames = (new List<String>{'Airtel Payments Bank Ltd','Arabi Company','ASEAN Super 8 Virtual Connect','chandras','Edge Communications','Facebook','Girikon Inc.','Global Partners','Google','IBM Corporation','IM Acc1','IM Acc2','IM Acc3','Infosys Public Services Inc','IPL','Maruti Suzuki India Ltd','Microsoft','Naveen& Sons','Pfizer Middle East','pixla12','pixla2','Polystat','Raidu Cement Private Limited','RenewX','salesforce.com','Test Acc CC 2','Test Account 2','Trebing & Himstedt Prozessautomation GmbH & Co.KG','Wipro Technologies Inc','Yahoo Farm'});
        for(String s: accountNames){
            Account a = new Account(Name=s);
            accts.add(a);
        }
        insert accts;

        List<String> firstNames = (new List<String>{'Jack','liam'});
        List<String> lastNames = (new List<String>{'Warner','walter'});           
        Integer emailCounter = 0;
        List<Contact> conList = new List<Contact>();
        for(Account a : accts){
            for(integer i=0;i<2;i++){
                conList.add(new Contact(firstname=firstNames[i]+emailCounter,lastname=lastNames[i]+emailCounter,
                                    AccountId=a.Id,Email='FirstName'+emailCounter+'@test.com')); 
                emailCounter++;
            }
        }
        insert conList;

        List<Brand__c> brand  = IMCC_TestUtilities.createBrand(1);
        List<Series__c> series  = IMCC_TestUtilities.createEventSeries(brand[0].Id, 1);
        List<Document> doc  = IMCC_TestUtilities.createDocument(1);
        List<Edition__c> edition = IMCC_TestUtilities.createEventEdition(series[0].Id,doc[0].Id,1);
        List<Contact_Edition_Mapping__c> listCEM = new List<Contact_Edition_Mapping__c>();
        for(Contact con : conList){
            listCEM.add(new Contact_Edition_Mapping__c(Contact__c=con.Id,Edition__c=edition[0].Id,Relationship_Status__c='Active',Account__c=con.AccountId,Access_Type__c ='Exhibitor'));
        }
        insert listCEM;
    }
    
    @isTest
    static void editionWelcomeEmailTest(){
        Test.startTest();
        Contact_Edition_Mapping__c cemObj2 = [SELECT Id,Access_Type__c FROM Contact_Edition_Mapping__c LIMIT 1];
        cemObj2.Access_Type__c ='Reseller';
        update cemObj2;
        
        Edition__c edition = [SELECT Id FROM Edition__c LIMIT 1];
        List<Email_Templates__c> listEmailTemp = IMCC_TestUtilities.createEmailTemplateWelcome(); 
        IMCC_TestUtilities.createEditionEmailTemplate(edition.Id,listEmailTemp.get(0).Id, new List<String>{'WELNew'});
        IMCC_EditionWelcomeEmail.getContactEditionMappings(edition.Id,'Test','ContactName','asc','All','All');
        IMCC_EditionWelcomeEmail.getContactEditionMappings(edition.Id,'Test','AccountName','desc','All','All');
        IMCC_EditionWelcomeEmail.getContactEditionMappings(edition.Id,'Test','ContactEmail','desc','All','All');
        IMCC_EditionWelcomeEmail.getContactEditionMappings(edition.Id,'Test','IsEmailSent','desc','All','All');
        IMCC_EditionWelcomeEmail.getContactEditionMappings(edition.Id,'Test','EmailSentDate','desc','All','All');
        IMCC_EditionWelcomeEmail.getContactEditionMappings(edition.Id,'Test','FirstLoginDateTime','desc','All','All');
        List<Contact_Edition_Mapping__c> listCEM = IMCC_EditionWelcomeEmail.getContactEditionMappings(edition.Id,'','UserType','desc','Who logged in','Received Email');
        System.assert(listCEM.size()>0, 'No CEM Found');
        List<Contact_Edition_Mapping__c> listCEM2 = [SELECT Id,Access_Type__c FROM Contact_Edition_Mapping__c LIMIT 20];
        IMCC_EditionWelcomeEmail.sendWelcomeEmail(listCEM2);
        List<Contact_Edition_Mapping__c> listCEM3 = [SELECT Id,Access_Type__c FROM Contact_Edition_Mapping__c LIMIT 40];
        IMCC_EditionWelcomeEmail.sendWelcomeEmail(listCEM3);
        IMCC_EditionWelcomeEmail.checkSendWelcomeEmailStatus(edition.Id);
        Test.stopTest();
    }
}