force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description>Field to identify Branch</description>
    <label>Brand (s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa Health</fullName>
            </value>
            <value>
                <fullName>Arab Health</fullName>
            </value>
            <value>
                <fullName>Channel Partners</fullName>
            </value>
            <value>
                <fullName>Channel Partners Cloud Insights</fullName>
            </value>
            <value>
                <fullName>Channel Partners Conference &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Channel Partners Evolution</fullName>
            </value>
            <value>
                <fullName>Channel Partners Store</fullName>
            </value>
            <value>
                <fullName>China Beauty Expo</fullName>
            </value>
            <value>
                <fullName>EndoNurse Institute</fullName>
            </value>
            <value>
                <fullName>Fispal Cafe</fullName>
            </value>
            <value>
                <fullName>Fispal Tecnologia Expo</fullName>
            </value>
            <value>
                <fullName>Greenbuild Int&apos;l Conf &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Infection Control Today</fullName>
            </value>
            <value>
                <fullName>Ingredient Marketplace Global Expo&amp;Conf</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Developers Conf</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Executive Symposium</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Store</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage World Expo</fullName>
            </value>
            <value>
                <fullName>Interior Design Show</fullName>
            </value>
            <value>
                <fullName>National Tanning Training Institute</fullName>
            </value>
            <value>
                <fullName>Natural Products INSIDER</fullName>
            </value>
            <value>
                <fullName>Petfood 2.0 Conference &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Self-Storage Talk</fullName>
            </value>
            <value>
                <fullName>Self-Storage Training Institute</fullName>
            </value>
            <value>
                <fullName>SupplySide</fullName>
            </value>
            <value>
                <fullName>SupplySide Animal Nutrition Insights</fullName>
            </value>
            <value>
                <fullName>SupplySide Beverage Insights</fullName>
            </value>
            <value>
                <fullName>SupplySide Fispal Brazil Expo</fullName>
            </value>
            <value>
                <fullName>SupplySide Health Technology Insights</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Announcement__c/Announcement__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - the object uses for the important announcements of each editions if defined</description>
    <label>Announcement</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Announcement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Announcement__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition for which Announcement has been made.</description>
    <label>Event Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Announcements</relationshipLabel>
    <relationshipName>Announcements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Announcement__c/fields/Event_Tab__c.field-meta.xml
<CustomField>
    <fullName>Event_Tab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Internal Link to the announcement if any shows that the user can open the announcement and read in.</description>
    <label>Internal Tab</label>
    <referenceTo>Event_Tabs__c</referenceTo>
    <relationshipLabel>Announcements</relationshipLabel>
    <relationshipName>Announcements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>x_1st Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Completed_Purchase_Summaries__c.field-meta.xml
<CustomField>
    <fullName>Completed_Purchase_Summaries__c</fullName>
    <description>Purchase Summaries Completed by Customer</description>
    <inlineHelpText>Purchase Summaries Completed by Customer</inlineHelpText>
    <label>Completed Purchase Summaries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Purchase_Summary_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Company_Profile_Submission_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Company_Profile_Submission_Due_Date__c</fullName>
    <label>Company Profile Submission Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Event_Setting__c.field-meta.xml
<CustomField>
    <fullName>Event_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Setting</label>
    <referenceTo>Event_Setting__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Event_Tabs__c/Event_Tabs__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Event Setting. Defines the different tabs and tab properties for a particular event.</description>
    <label>Event Tab</label>
    <nameField>
        <displayFormat>ET-{0000000}</displayFormat>
        <label>Event Tabs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Tabs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Tabs__c/fields/Event_Setting__c.field-meta.xml
<CustomField>
    <fullName>Event_Setting__c</fullName>
    <description>Event setting for which this tabs belongs to.</description>
    <inlineHelpText>Event Setting, this Tab Belongs to</inlineHelpText>
    <label>Event Setting</label>
    <referenceTo>Event_Setting__c</referenceTo>
    <relationshipLabel>Event Tabs</relationshipLabel>
    <relationshipName>Event_Tabs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/Purchase_Data__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It is the transactional information regarding the booth/product purchased.</description>
    <label>Purchase Data</label>
    <nameField>
        <displayFormat>PD-{000000000}</displayFormat>
        <label>Purchase Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Data__c/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact Edition mapping</description>
    <label>Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Edition Record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Summary__c/Purchase_Summary__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Purchase Summary detail to show on event landing page.</description>
    <label>Purchase Summary</label>
    <nameField>
        <label>Purchase Summary Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Summary__c/fields/Event_Setting__c.field-meta.xml
<CustomField>
    <fullName>Event_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Setting</label>
    <referenceTo>Event_Setting__c</referenceTo>
    <relationshipLabel>Purchase Summaries</relationshipLabel>
    <relationshipName>Purchase_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Summary__c/fields/Event_Tab__c.field-meta.xml
<CustomField>
    <fullName>Event_Tab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>IMCC Tab for stand contractor/Purchase Summary Information.</description>
    <inlineHelpText>IMCC Tab for stand contractor/Purchase Summary Information.</inlineHelpText>
    <label>Select Internal Page Tab</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Event_Tabs__c.Event_Setting__c</field>
            <operation>equals</operation>
            <valueField>$Source.Event_Setting__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event_Tabs__c</referenceTo>
    <relationshipLabel>Purchase Summaries</relationshipLabel>
    <relationshipName>Purchase_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Series__c/Series__c.object-meta.xml
<CustomObject>
    <description>It defines the Series Information. Each year&apos;s Edition will be tied to a particular Series.</description>
    <label>Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Series__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Brand of Series</description>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Series</relationshipLabel>
    <relationshipName>Event_Series</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Series__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Tab_User_Type__c/Tab_User_Type__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will give info on tab will be visible to which user type.</description>
    <label>Tab User Type</label>
    <nameField>
        <displayFormat>UT-{00000}</displayFormat>
        <label>Tab User Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tab User Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tab_User_Type__c/fields/Announcement__c.field-meta.xml
<CustomField>
    <fullName>Announcement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Announcement</label>
    <referenceTo>Announcement__c</referenceTo>
    <relationshipLabel>Tab User Types</relationshipLabel>
    <relationshipName>Tab_User_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tab_User_Type__c/fields/Event_Tab__c.field-meta.xml
<CustomField>
    <fullName>Event_Tab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Event Tab</description>
    <label>Event Tab</label>
    <referenceTo>Event_Tabs__c</referenceTo>
    <relationshipLabel>Tab User Types</relationshipLabel>
    <relationshipName>Tab_User_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IMCC_HomeCtrl_Test.cls
@IsTest
public with sharing class IMCC_HomeCtrl_Test {
    @TestSetUp
    static void testUserData(){
        UserRole userrole = [Select Id, DeveloperName From UserRole Where DeveloperName = 'Administrator' Limit 1];
        User adminUser = [Select Id, UserRoleId From User Where Profile.Name='System Administrator' and IsActive = true Limit 1];
        adminUser.UserRoleId = userrole.Id;
        update adminUser;
        
        // Setup Test Data 
        User userObj;
        Id contactId;
        Id accId;
        
        System.runAs(adminUser){
            List<Account> accObj  = IMCC_TestUtilities.createAccount(1);
            accId = accObj[0].Id;
            List<Contact> contObj = IMCC_TestUtilities.createContact(accId, 1);
            contactId = contObj[0].Id;
            userObj = IMCC_TestUtilities.createCommunityUser(contactId);
            System.assertEquals(userObj.ContactID,contactId, 'Same contact');
        }
        List<Document> docObj  = IMCC_TestUtilities.createDocument(1);
        Id docObjId = docObj[0].Id;
        List<Brand__c> brandObj  = IMCC_TestUtilities.createBrand(1);
        Id brandObjId = brandObj[0].Id;
        List<Series__c> serviceObj  = IMCC_TestUtilities.createEventSeries(brandObjId, 1);
        Id serviceObjId = serviceObj[0].Id;
        List<Event_Setting__c> eveSettingObj = IMCC_TestUtilities.createEventSetting(1);
        Id eveSettingObjId = eveSettingObj[0].Id;
        List<Edition__c> editionObj = IMCC_TestUtilities.createEventEditionWithEveSetting(serviceObjId,docObjId,eveSettingObjId,1);
        editionObj[0].Company_Profile_Submission_Due_Date__c = System.Today();
        Update editionObj[0];
        Id editionObjId = editionObj[0].Id;
        
        //System.assertEquals(editionObj[0].Edition_Code__c,'TEV21', 'Event Code');
        
        Contact_Edition_Mapping__c cemObj = IMCC_TestUtilities.createContactEditionMapping(contactId,accId,editionObjId);
        
        cemObj.Completed_Purchase_Summaries__c = 'Badge';
        update cemObj;
        
        IMCC_TestUtilities.createEditionWebsites(editionObjId, 1);
        
        IMCC_TestUtilities.createPurchaseData3(contactId,editionObjId,accId);        
        
        Announcement__c announcement = IMCC_TestUtilities.createAnnouncementData(editionObjId);
        //List<Tab_User_Type__c> tabUserLst = IMCC_TestUtilities.createTabUserTypeForAnnouncement(announcement.Id,'Exhibitor');
        //System.assertEquals(tabUserLst.Size(),2, 'Tab User List size should be 2');
        
        List<Event_Tabs__c> eventTabs = IMCC_TestUtilities.createEventTabs(eveSettingObjId,1,10,null,'Custom','HTML',null);
        List<Event_Tabs__c> eventTabs1 = IMCC_TestUtilities.createEventTabs(eveSettingObjId,1,20,null,'Standard','Forms',null);
        List<Tab_User_Type__c> tabUserLst1 = IMCC_TestUtilities.createTabUserType(eventTabs1[0].Id,1,'Exhibitor');
        tabUserLst1[0].Announcement__c = announcement.Id;
        update tabUserLst1;
        System.assertEquals(tabUserLst1.Size(),1, 'Tab User List size should be 1');
        
        IMCC_TestUtilities.createContentVer(1);
        
        List<ContentDocument> documents = [SELECT Id FROM ContentDocument LIMIT 1];
        IMCC_TestUtilities.createContentDocLink(documents[0].Id,eventTabs[0].Id,1);
        
        List<Purchase_Summary__c> listPS = new List<Purchase_Summary__c>();
        Purchase_Summary__c ps = new  Purchase_Summary__c();
        ps.Event_Setting__c = eveSettingObjId;
        ps.Event_Tab__c = eventTabs.get(0).Id;
        ps.Name='Test';
        ps.Purchase_Summary_Type__c = 'Badge';
        ps.External_Link__c='https://test.com';
        ps.External_Link_Label__c='test link';
        ps.Information_Label__c='test';
        ps.Order__c = 10;
        ps.Is_Active__c = true;
        listPS.add(ps);
        
        ps = new  Purchase_Summary__c();
        ps.Event_Setting__c = eveSettingObjId;
        ps.Event_Tab__c = eventTabs.get(0).Id;
        ps.Name='Test';
        ps.Purchase_Summary_Type__c = 'Virtual Event';
        ps.External_Link__c='https://test.com';
        ps.External_Link_Label__c='test link';
        ps.Information_Label__c='test';
        ps.Order__c = 20;
        ps.Is_Active__c = true;
        listPS.add(ps);
        Insert listPS;
        
        List<Purchase_Data__c> purchaseList = IMCC_TestUtilities.createPurchaseData(cemObj.Id,accId,1);
        System.assertEquals(purchaseList.Size(),1, 'Purchase Data List size should be 1');
    } 
    
    @isTest
    public static void testAnnouncement(){
        User userObj = [SELECT Id FROM User WHERE Profile.Name='IM Customer Community Login User' AND Email='davidjones@test.com' LIMIT 1];
        Account acc = [SELECT Id FROM Account Limit 1];
        List<Contact_Edition_Mapping__c> cemObjs = [SELECT Id FROM Contact_Edition_Mapping__c];
        Edition__c edition = [SELECT Id,Edition_Code__c FROM Edition__c Limit 1];
        Test.startTest();
        System.runAs(userObj) {
            IMCC_HomeCtrl.getAnnouncements(edition.Edition_Code__c,acc.Id);
            IMCC_HomeCtrl.getTabContext(edition.Edition_Code__c,acc.Id,null);
            IMCC_HomeCtrl.getPurchaseSummary(edition.Edition_Code__c,acc.Id);
            IMCC_HomeCtrl.getEventSummary(edition.Edition_Code__c,acc.Id);
            IMCC_HomeCtrl.updatePurchaseSummary('Badge',cemObjs[0].Id);
            Event_Tabs__c et = [SELECT Tab_Code__c FROM Event_Tabs__c LIMIT 1];
            String str = IMCC_HomeCtrl.getHtml(et.Tab_Code__c);
            System.assertEquals('Some Text', str, 'Incorrect String');
            
            IMCC_HomeCtrl.getTabId(edition.Edition_Code__c,acc.Id);
        }
        Test.stopTest();
    } 
    
    @isTest
    private static void testForException()
    {
        Account acc = [SELECT Id FROM Account Limit 1];
        IMCC_HomeCtrl.getAnnouncements(null,acc.Id);
        
        IMCC_HomeCtrl.getTabContext(null,acc.Id,null);
        try{IMCC_HomeCtrl.getPurchaseSummary(null,null);}
        catch(Exception e){
          System.assertEquals('System.AuraHandledException',e.getTypeName(),'Exception is different');
        }
        
        IMCC_HomeCtrl.getBadges(null,null);
        
        try{IMCC_HomeCtrl.updatePurchaseSummary(null,null);}
        catch(Exception e){
          System.assertEquals('System.AuraHandledException',e.getTypeName(),'Exception is different');
        } 
        
        try{IMCC_HomeCtrl.getEventSummary(null,null);}
        catch(Exception e){
          System.assertEquals('System.AuraHandledException',e.getTypeName(),'Exception is different');
        } 
        
        IMCC_HomeCtrl.getHtml(null);
        IMCC_HomeCtrl.getTabId(null,null);
    }
}