force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description>Field to identify Branch</description>
    <label>Brand (s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa Health</fullName>
            </value>
            <value>
                <fullName>Arab Health</fullName>
            </value>
            <value>
                <fullName>Channel Partners</fullName>
            </value>
            <value>
                <fullName>Channel Partners Cloud Insights</fullName>
            </value>
            <value>
                <fullName>Channel Partners Conference &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Channel Partners Evolution</fullName>
            </value>
            <value>
                <fullName>Channel Partners Store</fullName>
            </value>
            <value>
                <fullName>China Beauty Expo</fullName>
            </value>
            <value>
                <fullName>EndoNurse Institute</fullName>
            </value>
            <value>
                <fullName>Fispal Cafe</fullName>
            </value>
            <value>
                <fullName>Fispal Tecnologia Expo</fullName>
            </value>
            <value>
                <fullName>Greenbuild Int&apos;l Conf &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Infection Control Today</fullName>
            </value>
            <value>
                <fullName>Ingredient Marketplace Global Expo&amp;Conf</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Developers Conf</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Executive Symposium</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Store</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage World Expo</fullName>
            </value>
            <value>
                <fullName>Interior Design Show</fullName>
            </value>
            <value>
                <fullName>National Tanning Training Institute</fullName>
            </value>
            <value>
                <fullName>Natural Products INSIDER</fullName>
            </value>
            <value>
                <fullName>Petfood 2.0 Conference &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Self-Storage Talk</fullName>
            </value>
            <value>
                <fullName>Self-Storage Training Institute</fullName>
            </value>
            <value>
                <fullName>SupplySide</fullName>
            </value>
            <value>
                <fullName>SupplySide Animal Nutrition Insights</fullName>
            </value>
            <value>
                <fullName>SupplySide Beverage Insights</fullName>
            </value>
            <value>
                <fullName>SupplySide Fispal Brazil Expo</fullName>
            </value>
            <value>
                <fullName>SupplySide Health Technology Insights</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>x_1st Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contractor_Mapping__c/Contractor_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It Store the details of contractor</description>
    <label>Contractor Mapping</label>
    <nameField>
        <label>Contractor Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contractor Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contractor_Mapping__c/fields/Contractor_Status__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Status__c</fullName>
    <description>Contractor status shows status of contactor to Exhibitor who assigned them to work on their booth</description>
    <label>Contractor Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Contractor Nomination In Review</fullName>
            </value>
            <value>
                <fullName>New Contractor Nomination Rejected</fullName>
            </value>
            <value>
                <fullName>Contractor Nominated</fullName>
            </value>
            <value>
                <fullName>Contractor Accepted Nomination</fullName>
            </value>
            <value>
                <fullName>Contractor Declined Nomination</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Viewed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Pending Sales Approval</fullName>
            </value>
            <value>
                <fullName>Stand Design Rejected/Incomplete</fullName>
            </value>
            <value>
                <fullName>Stand Design Resubmitted</fullName>
            </value>
            <value>
                <fullName>Pending Venue Approval</fullName>
            </value>
            <value>
                <fullName>Tentative Approval</fullName>
            </value>
            <value>
                <fullName>Permission to Build</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contractor_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition for stand</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contractor Mappings</relationshipLabel>
    <relationshipName>Contractor_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contractor_Mapping__c/fields/Is_Self_Managed__c.field-meta.xml
<CustomField>
    <fullName>Is_Self_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Self Managed</description>
    <label>Is Self Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Event_Setting__c.field-meta.xml
<CustomField>
    <fullName>Event_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Setting</label>
    <referenceTo>Event_Setting__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Email_Template_Types_Mapping__mdt/Email_Template_Types_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Email Template Types Mapping</description>
    <label>Email Template Types Mapping</label>
    <pluralLabel>Email Template Types Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Email_Template_Types_Mapping__mdt/fields/Email_Template_Code__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Code__c</fullName>
    <label>Email Template Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/Purchase_Data__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It is the transactional information regarding the booth/product purchased.</description>
    <label>Purchase Data</label>
    <nameField>
        <displayFormat>PD-{000000000}</displayFormat>
        <label>Purchase Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Data__c/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact Edition mapping</description>
    <label>Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Contractor_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used to capture Contractor mapping respect to Stand Details info</description>
    <label>Contractor Mapping</label>
    <referenceTo>Contractor_Mapping__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Edition Record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Series__c/Series__c.object-meta.xml
<CustomObject>
    <description>It defines the Series Information. Each year&apos;s Edition will be tied to a particular Series.</description>
    <label>Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Series__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Brand of Series</description>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Series</relationshipLabel>
    <relationshipName>Event_Series</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Series__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Stand_Detail__c/Stand_Detail__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center -  This object defines about Stand detail for a stand</description>
    <label>Stand Detail</label>
    <nameField>
        <displayFormat>SD-{0000}</displayFormat>
        <label>Stand Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stand Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stand_Detail__c/fields/Contractor_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contractor Stand detail Mapping</description>
    <label>Contractor Mapping</label>
    <referenceTo>Contractor_Mapping__c</referenceTo>
    <relationshipLabel>Stand Details</relationshipLabel>
    <relationshipName>Stand_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stand_Detail__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relate Stand Detail with Edition object</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Stand Details</relationshipLabel>
    <relationshipName>Stand_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IMCC_ContractorMappingTrigHandler_Test.cls
@isTest
public class IMCC_ContractorMappingTrigHandler_Test {
    @TestSetUp
    static void testUserData(){
        UserRole userrole = [Select Id, DeveloperName From UserRole Where DeveloperName = 'Administrator' Limit 1];
        User adminUser = [Select Id, UserRoleId From User Where Profile.Name='System Administrator' and IsActive = true Limit 1];
        adminUser.UserRoleId = userrole.Id;
        update adminUser;
        
        // Setup Test Data 
        //User adminUser = [Select Id, UserRoleId From User Where Profile.Name='System Administrator' and IsActive = true and UserRole.Name = 'Administrator' Limit 1];
        Contact con = new Contact();
        User userObj;
        Id contactId;
        Id contact2Id;
        Id accId;
        
        System.runAs(adminUser){
            List<Account> accObj  = IMCC_TestUtilities.createAccount(250);
            accId = accObj[0].Id;
            List<Contact> contObj = IMCC_TestUtilities.createContact(accId, 250);
            contactId = contObj[0].Id;
            contact2Id = contObj[1].Id;
            con = contObj[0];
            userObj = IMCC_TestUtilities.createCommunityUser(contactId);
            System.assertEquals(userObj.ContactID,contactId, 'Same contact');
        }
        List<Document> docObj  = IMCC_TestUtilities.createDocument(250);
        Id docObjId = docObj[0].Id;
        List<Brand__c> brandObj  = IMCC_TestUtilities.createBrand(250);
        Id brandObjId = brandObj[0].Id;
        List<Series__c> serviceObj  = IMCC_TestUtilities.createEventSeries(brandObjId, 250);
        Id serviceObjId = serviceObj[0].Id;
        List<Event_Setting__c> eveSettingObj = IMCC_TestUtilities.createEventSetting(250);
        Id eveSettingObjId = eveSettingObj[0].Id;
        List<Edition__c> editionObj = IMCC_TestUtilities.createEventEditionWithEveSetting2(serviceObjId,docObjId,eveSettingObjId,2);
        Id editionObjId = editionObj[0].Id;
        IMCC_TestUtilities.createEventTabs(eveSettingObjId,1,10,null,'Standard','Stand Contractors',null);
        IMCC_TestUtilities.createEventTabs(eveSettingObjId,1,20,null,'Standard','Stand Design',null);
        
        //System.assertEquals(editionObj[0].Edition_Code__c,'TEV21', 'Event Code');
        Contact_Edition_Mapping__c cemObj = IMCC_TestUtilities.createContactEditionMapping(contactId,accId,editionObjId);
        IMCC_TestUtilities.createContactEditionMapping(contact2Id,accId,editionObjId);
        IMCC_TestUtilities.createContactEditionMapping(contactId,accId,editionObjId);
        IMCC_TestUtilities.createEditionWebsites(editionObjId, 250);
        
        List<Purchase_Data__c> boothObj = IMCC_TestUtilities.createPurchaseData4(cemObj.Id,editionObjId,1);
        Id boothObjId = boothObj[0].Id;
        IMCC_TestUtilities.createContractorMappingData(accId,contactId,cemObj.Id,boothObjId,'Contractor Nominated',editionObjId,'',1);
        
        List<Email_Templates__c> listEmailTemp = IMCC_TestUtilities.createEmailTemplate();
        Map<String,Email_Template_Types_Mapping__mdt> mapETTTM = Trig_UpdateStatusOnFormData_Handler.getEmailTemplateTypesByModule('Stand Contractor');
        List<String> codes = new List<String>();
        List<String> listEmailTypes = new List<String>();
        for(String s : mapETTTM.keySet()){
            codes.add(mapETTTM.get(s).Email_Template_Code__c);
            listEmailTypes.add('Email:'+s);
        }
        IMCC_TestUtilities.createEditionEmailTemplate(editionObjId,listEmailTemp[0].Id,codes);
    }
    
    @isTest
    public static void testContractorMapping(){
        List<Contractor_Mapping__c> cmObj = [SELECT Id,Is_Self_Managed__c,Contractor_Status__c FROM Contractor_Mapping__c];
        User userObj = [SELECT Id FROM User WHERE Profile.Name='IM Customer Community Login User' AND Email='davidjones@test.com' LIMIT 1];
        Test.startTest();
        System.runAs(userObj) {
            cmObj[0].Contractor_Status__c = 'Contractor Accepted Nomination';
            cmObj[0].Is_Self_Managed__c = false;
            update cmObj[0];
            cmObj[0].Contractor_Status__c = 'Contractor Declined Nomination';
            update cmObj[0];
            System.assertEquals('Contractor Declined Nomination', cmObj[0].Contractor_Status__c,'Status Mismatch');
        }
        Test.stopTest();
    }
    
    @isTest
    public static void testContractorMapping2(){
        List<Contractor_Mapping__c> cmObj = [SELECT Id,Is_Self_Managed__c,Contractor_Status__c FROM Contractor_Mapping__c];
        Test.startTest();
        cmObj[0].Contractor_Status__c = 'New Contractor Nomination In Review';
        update cmObj[0];
        cmObj[0].Contractor_Status__c = 'Contractor Nominated';
        update cmObj[0];
        cmObj[0].Contractor_Status__c = 'New Contractor Nomination In Review';
        update cmObj[0];
        cmObj[0].Contractor_Status__c = 'New Contractor Nomination Rejected';
        update cmObj[0];
        System.assertEquals('New Contractor Nomination Rejected', cmObj[0].Contractor_Status__c,'Status Mismatch');
        Test.stopTest();
    }
    
    @isTest
    public static void testContractorMapping3(){
        List<Contractor_Mapping__c> cmObj = [SELECT Id,Is_Self_Managed__c,Contractor_Status__c FROM Contractor_Mapping__c];
        Test.startTest();
        cmObj[0].Contractor_Status__c = 'Permission to Build';
        update cmObj[0];
        cmObj[0].Contractor_Status__c = 'In Review';
        update cmObj[0];
        cmObj[0].Contractor_Status__c = 'Pending Sales Approval';
        update cmObj[0];
        cmObj[0].Contractor_Status__c = 'Stand Design Rejected/Incomplete';
        Stand_Detail__c standDetail = new Stand_Detail__c();
        standDetail.Contractor_Mapping__c = cmObj[0].Id;
        standDetail.Stand_Detail_Status__c='In Progress';
        standDetail.Current_Step__c='1';
        IMCC_StandDesignSubmissionCtrl.saveStandDetail(standDetail);
        update cmObj[0];
        cmObj[0].Contractor_Status__c = 'Stand Design Resubmitted';
        update cmObj[0];
        cmObj[0].Contractor_Status__c = 'Pending Venue Approval';
        update cmObj[0];
        cmObj[0].Contractor_Status__c = 'Tentative Approval';
        update cmObj[0];
        cmObj[0].Contractor_Status__c = 'Cancelled';
        update cmObj[0];
        System.assertEquals('Cancelled', cmObj[0].Contractor_Status__c,'Status Mismatch');
        Test.stopTest();
    }
}