force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description>Field to identify Branch</description>
    <label>Brand (s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa Health</fullName>
            </value>
            <value>
                <fullName>Arab Health</fullName>
            </value>
            <value>
                <fullName>Channel Partners</fullName>
            </value>
            <value>
                <fullName>Channel Partners Cloud Insights</fullName>
            </value>
            <value>
                <fullName>Channel Partners Conference &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Channel Partners Evolution</fullName>
            </value>
            <value>
                <fullName>Channel Partners Store</fullName>
            </value>
            <value>
                <fullName>China Beauty Expo</fullName>
            </value>
            <value>
                <fullName>EndoNurse Institute</fullName>
            </value>
            <value>
                <fullName>Fispal Cafe</fullName>
            </value>
            <value>
                <fullName>Fispal Tecnologia Expo</fullName>
            </value>
            <value>
                <fullName>Greenbuild Int&apos;l Conf &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Infection Control Today</fullName>
            </value>
            <value>
                <fullName>Ingredient Marketplace Global Expo&amp;Conf</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Developers Conf</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Executive Symposium</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Store</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage World Expo</fullName>
            </value>
            <value>
                <fullName>Interior Design Show</fullName>
            </value>
            <value>
                <fullName>National Tanning Training Institute</fullName>
            </value>
            <value>
                <fullName>Natural Products INSIDER</fullName>
            </value>
            <value>
                <fullName>Petfood 2.0 Conference &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Self-Storage Talk</fullName>
            </value>
            <value>
                <fullName>Self-Storage Training Institute</fullName>
            </value>
            <value>
                <fullName>SupplySide</fullName>
            </value>
            <value>
                <fullName>SupplySide Animal Nutrition Insights</fullName>
            </value>
            <value>
                <fullName>SupplySide Beverage Insights</fullName>
            </value>
            <value>
                <fullName>SupplySide Fispal Brazil Expo</fullName>
            </value>
            <value>
                <fullName>SupplySide Health Technology Insights</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>It defines the Brand Information. A series can belong to a particular brand.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>x_1st Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Series__c/Series__c.object-meta.xml
<CustomObject>
    <description>It defines the Series Information. Each year&apos;s Edition will be tied to a particular Series.</description>
    <label>Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Series__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Brand of Series</description>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Series</relationshipLabel>
    <relationshipName>Event_Series</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IMCC_UserLoginCtrl_Test.cls
/**
* Created/Modified By: Girikon(Aishwarya)
* Created On:          07/9/2021
* @description  :      This class covers the code coverage of the class IMCC_UserLoginCtrl
* Methods:             loginCtrlDataInsert
* Apex Class:          IMCC_UserLoginCtrl(92%) 
**/

@isTest
private class IMCC_UserLoginCtrl_Test {
    @TestSetUp
    static void testUserData(){
        UserRole userrole = [Select Id, DeveloperName From UserRole Where DeveloperName = 'Administrator' Limit 1];
        User adminUser = [Select Id, UserRoleId From User Where Profile.Name='System Administrator' and IsActive = true Limit 1];
        adminUser.UserRoleId = userrole.Id;
        update adminUser;

        Id contactId;
        Id accId;
        User userObj;
        System.runAs(adminUser){
            List<Account> accObj  = IMCC_TestUtilities.createAccount(1);
            accId = accObj[0].Id;
            List<Contact> contObj = IMCC_TestUtilities.createContact(accId, 1);
            contactId = contObj[0].Id;
            userObj = IMCC_TestUtilities.createCommunityUser(contactId);
            System.assertEquals(userObj.ContactID,contactId, 'Same contact');
        }       
        
        List<Document> docObj  = IMCC_TestUtilities.createDocument(1);
        Id docObjId = docObj[0].Id;
        List<Brand__c> brandObj  = IMCC_TestUtilities.createBrand(1);
        Id brandObjId = brandObj[0].Id;
        List<Series__c> serviceObj  = IMCC_TestUtilities.createEventSeries(brandObjId, 1);
        Id serviceObjId = serviceObj[0].Id;
        List<Edition__c> editionObj = IMCC_TestUtilities.createEventEdition(serviceObjId,docObjId,1);
        Id editionObjId = editionObj[0].Id;
        IMCC_TestUtilities.createContactEditionMapping(contactId,accId,editionObjId);
    }

    @isTest
    public static void loginCtrlDataInsert()
    {
        Test.StartTest();
        List<Edition__c> editionObj = [SELECT Id,Edition_Code__c FROM Edition__c];
        User userObj = [SELECT Id,Username FROM User WHERE Email='davidjones@test.com'];
        
        System.runAs(userObj){
            ApexPages.currentPage().getHeaders().put('Host','');
            PageReference pageRef = new PageReference('/IMCC_UserLogin');
            Test.setCurrentPage(pageRef);
            apexpages.currentpage().getparameters().put('edcode','');
            apexpages.currentpage().getparameters().put('reset','1');
            
            IMCC_UserLoginCtrl oLoginCtrl6 = new IMCC_UserLoginCtrl(); 
            oLoginCtrl6.iirislogin();       
            oLoginCtrl6.username = 'Test@testorg.com';
            oLoginCtrl6.password ='Test12345';     
            oLoginCtrl6.login();
            oLoginCtrl6.getOrgId();
            oLoginCtrl6.eventSet = null;
            oLoginCtrl6.eventEditionCode = null;
            oLoginCtrl6.brandingColor = null;
            oLoginCtrl6.imageURL = null;
            
            pageRef = new PageReference('/IMCC_UserLogin?startURL=%2FCustomerProfile%3Feventcode%3DTEV210');
            Test.setCurrentPage(pageRef);
            
            apexpages.currentpage().getparameters().put('er','iunp');
            IMCC_UserLoginCtrl oLoginCtrl = new IMCC_UserLoginCtrl();

            apexpages.currentpage().getparameters().put('er','iufte');
            IMCC_UserLoginCtrl oLoginCtrl1 = new IMCC_UserLoginCtrl();
            System.debug(LoggingLevel.DEBUG, oLoginCtrl1);

            apexpages.currentpage().getparameters().put('er','iu');
            IMCC_UserLoginCtrl oLoginCtrl2 = new IMCC_UserLoginCtrl();
            System.debug(LoggingLevel.DEBUG, oLoginCtrl2);

            apexpages.currentpage().getparameters().put('edcode','');
            IMCC_UserLoginCtrl oLoginCtrl4 = new IMCC_UserLoginCtrl();
            System.debug(LoggingLevel.DEBUG, oLoginCtrl4);

            apexpages.currentpage().getparameters().put('edcode','TEV211');
            IMCC_UserLoginCtrl oLoginCtrl5 = new IMCC_UserLoginCtrl();
            System.debug(LoggingLevel.DEBUG, oLoginCtrl5);

            oLoginCtrl5.getSiteURL();
            System.debug(LoggingLevel.DEBUG, JSON.serialize(userObj));
            oLoginCtrl.username = userObj.Username;
            oLoginCtrl.password ='Test12345';
            System.assertEquals(oLoginCtrl.username, 'davidjones@test.com', 'both values should equal');
            System.assertEquals(oLoginCtrl.password, 'Test12345', 'Password should equal to Test12345');        
            apexpages.currentpage().getparameters().put('edcode',editionObj[0].Edition_Code__c);
            oLoginCtrl.login();
            oLoginCtrl.forgotPassword();
            oLoginCtrl.backToSignIn();
            oLoginCtrl.resetPassword();
            oLoginCtrl.iirislogin();
        }
        Test.stopTest();        
    }   
    
    @isTest
    public static void loginCtrlDataInsert2()
    {
        Test.StartTest();
        List<Edition__c> editionObj = [SELECT Id,Edition_Code__c FROM Edition__c];
        User userObj = [SELECT Id,Username FROM User WHERE Email='davidjones@test.com'];
        
        System.runAs(userObj){
            ApexPages.currentPage().getHeaders().put('Host','');
            PageReference pageRef = new PageReference('/IMCC_UserLogin');
            Test.setCurrentPage(pageRef);
            pageRef = new PageReference('/IMCC_UserLogin?startURL=%2FCustomerProfile%3Feventcode%3DTEV210');
            Test.setCurrentPage(pageRef);
            
            apexpages.currentpage().getparameters().put('er','iunp');
            IMCC_UserLoginCtrl oLoginCtrl = new IMCC_UserLoginCtrl();
            oLoginCtrl.username = userObj.Username+'123';
            oLoginCtrl.password ='Test12345';
            System.assertEquals(oLoginCtrl.username, 'davidjones@test.com123', 'both values should equal');
            System.assertEquals(oLoginCtrl.password, 'Test12345', 'Password should equal to Test12345');        
            apexpages.currentpage().getparameters().put('edcode',editionObj[0].Edition_Code__c);
            oLoginCtrl.login();
            oLoginCtrl.forgotPassword();
            oLoginCtrl.backToSignIn();
            oLoginCtrl.resetPassword();
        }
        Test.stopTest();        
    } 
    
    @isTest
    public static void loginCtrlDataInsert3()
    {
        Test.StartTest();
        List<Edition__c> editionObj = [SELECT Id,Edition_Code__c FROM Edition__c];
        User userObj = [SELECT Id,Username FROM User WHERE Email='davidjones@test.com'];
        delete [Select Id FROM Contact_Edition_Mapping__c];
        
        System.runAs(userObj){
            ApexPages.currentPage().getHeaders().put('Host','');
            PageReference pageRef = new PageReference('/IMCC_UserLogin');
            Test.setCurrentPage(pageRef);
            pageRef = new PageReference('/IMCC_UserLogin?startURL=%2FCustomerProfile%3Feventcode%3DTEV210');
            Test.setCurrentPage(pageRef);
            
            apexpages.currentpage().getparameters().put('er','iunp');
            IMCC_UserLoginCtrl oLoginCtrl = new IMCC_UserLoginCtrl();
            oLoginCtrl.username = userObj.Username;
            oLoginCtrl.password ='Test12345';
            System.assertEquals(oLoginCtrl.username, 'davidjones@test.com', 'both values should equal');
            System.assertEquals(oLoginCtrl.password, 'Test12345', 'Password should equal to Test12345');        
            apexpages.currentpage().getparameters().put('edcode',editionObj[0].Edition_Code__c);
            oLoginCtrl.login();
            oLoginCtrl.forgotPassword();
            oLoginCtrl.backToSignIn();
            oLoginCtrl.username = '';
            oLoginCtrl.resetPassword();
            oLoginCtrl.iirislogin();
        }
        Test.stopTest();        
    }
}