force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description>Field to identify Branch</description>
    <label>Brand (s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa Health</fullName>
            </value>
            <value>
                <fullName>Arab Health</fullName>
            </value>
            <value>
                <fullName>Channel Partners</fullName>
            </value>
            <value>
                <fullName>Channel Partners Cloud Insights</fullName>
            </value>
            <value>
                <fullName>Channel Partners Conference &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Channel Partners Evolution</fullName>
            </value>
            <value>
                <fullName>Channel Partners Store</fullName>
            </value>
            <value>
                <fullName>China Beauty Expo</fullName>
            </value>
            <value>
                <fullName>EndoNurse Institute</fullName>
            </value>
            <value>
                <fullName>Fispal Cafe</fullName>
            </value>
            <value>
                <fullName>Fispal Tecnologia Expo</fullName>
            </value>
            <value>
                <fullName>Greenbuild Int&apos;l Conf &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Infection Control Today</fullName>
            </value>
            <value>
                <fullName>Ingredient Marketplace Global Expo&amp;Conf</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Developers Conf</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Executive Symposium</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Store</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage World Expo</fullName>
            </value>
            <value>
                <fullName>Interior Design Show</fullName>
            </value>
            <value>
                <fullName>National Tanning Training Institute</fullName>
            </value>
            <value>
                <fullName>Natural Products INSIDER</fullName>
            </value>
            <value>
                <fullName>Petfood 2.0 Conference &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Self-Storage Talk</fullName>
            </value>
            <value>
                <fullName>Self-Storage Training Institute</fullName>
            </value>
            <value>
                <fullName>SupplySide</fullName>
            </value>
            <value>
                <fullName>SupplySide Animal Nutrition Insights</fullName>
            </value>
            <value>
                <fullName>SupplySide Beverage Insights</fullName>
            </value>
            <value>
                <fullName>SupplySide Fispal Brazil Expo</fullName>
            </value>
            <value>
                <fullName>SupplySide Health Technology Insights</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>It defines the Brand Information. A series can belong to a particular brand.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>user type</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>x_1st Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsTestUser__c.field-meta.xml
<CustomField>
    <fullName>IsTestUser__c</fullName>
    <defaultValue>false</defaultValue>
    <description>to check If the contact is test user</description>
    <label>IsTestUser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>Defines the user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/isTestUser__c.field-meta.xml
<CustomField>
    <fullName>isTestUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isTestUser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Event_Setting__c.field-meta.xml
<CustomField>
    <fullName>Event_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Setting</label>
    <referenceTo>Event_Setting__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Edition_Popup__c/Edition_Popup__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Edition. Used to define the Popup properties for a particular Event.</description>
    <label>Edition Popup</label>
    <nameField>
        <displayFormat>EPN-{00000}</displayFormat>
        <label>Edition Popup Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Edition Popups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition_Popup__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Each Edition can have many Edition Popups. This field helps to select the related Edition for a Pop up.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Edition Popups</relationshipLabel>
    <relationshipName>Edition_Popups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_Templates__c/Email_Templates__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object will be used a Global Email Templates.</description>
    <label>Email Template</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Setting__c/Event_Setting__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child of Edition. This will set the tab visibility on the home page of a particular event.</description>
    <label>Event Setting</label>
    <nameField>
        <label>Event Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Tabs__c/Event_Tabs__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Event Setting. Defines the different tabs and tab properties for a particular event.</description>
    <label>Event Tab</label>
    <nameField>
        <displayFormat>ET-{0000000}</displayFormat>
        <label>Event Tabs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Tabs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Tabs__c/fields/Event_Setting__c.field-meta.xml
<CustomField>
    <fullName>Event_Setting__c</fullName>
    <description>Event setting for which this tabs belongs to.</description>
    <inlineHelpText>Event Setting, this Tab Belongs to</inlineHelpText>
    <label>Event Setting</label>
    <referenceTo>Event_Setting__c</referenceTo>
    <relationshipLabel>Event Tabs</relationshipLabel>
    <relationshipName>Event_Tabs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Series__c/Series__c.object-meta.xml
<CustomObject>
    <description>It defines the Series Information. Each year&apos;s Edition will be tied to a particular Series.</description>
    <label>Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Series__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Brand of Series</description>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Series</relationshipLabel>
    <relationshipName>Event_Series</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Series__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Tab_User_Type__c/Tab_User_Type__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will give info on tab will be visible to which user type.</description>
    <label>Tab User Type</label>
    <nameField>
        <displayFormat>UT-{00000}</displayFormat>
        <label>Tab User Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tab User Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tab_User_Type__c/fields/Edition_Popup__c.field-meta.xml
<CustomField>
    <fullName>Edition_Popup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition Popup objects stores the data of the popup to be shown in Community Portal based on User Type.</description>
    <label>Edition Popup</label>
    <referenceTo>Edition_Popup__c</referenceTo>
    <relationshipLabel>Tab User Types</relationshipLabel>
    <relationshipName>Tab_User_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IMCC_CreateViewTestDataCTRLTest.cls
/**
* Created/Modified By :(Arushi [IMCC-5107])
* Created On:          28/03/2023
* @description  :      As an Ops User, I should be able to easily create Test Accounts to validate In Progress events
* Methods:             getEixstingTestData,testDataCreated,cancelInvitation,sendEmailInvite
* Apex Class:          IMCC_CreateViewTestDataCTRL
**/
@isTest
public class IMCC_CreateViewTestDataCTRLTest {
    
    public static testMethod void headerDataInsert()
    {
        UserRole userrole = [Select Id, DeveloperName From UserRole Where DeveloperName = 'Administrator' Limit 1];
        User adminUser = [Select Id, UserRoleId From User Where Profile.Name='System Administrator' and IsActive = true Limit 1];
        adminUser.UserRoleId = userrole.Id;
        update adminUser;
        // Setup Test Data 
        // User adminUser = [Select Id, UserRoleId From User Where Profile.Name='System Administrator' and IsActive = true and UserRole.Name = 'Administrator' Limit 1];
        User userObj;
        Id contactId;
        Id accId;
        System.runAs(adminUser){
            List<Account> accObj  = IMCC_TestUtilities.createAccount(250);
            accId = accObj[0].Id;
            List<Contact> contObj = IMCC_TestUtilities.createContact(accId, 250);
            contactId = contObj[0].Id;
            contObj[0].IsTestUser__c = True;
            contObj[0].Access_Type__c = 'Agent';
            update contObj[0];
            
            userObj = IMCC_TestUtilities.createCommunityUser2(contactId);
            System.assertEquals(userObj.ContactID,contactId, 'Same contact');
            
            List<Document> docObj  = IMCC_TestUtilities.createDocument(250);
            Id docObjId = docObj[0].Id;
            
            List<Brand__c> brandObj  = IMCC_TestUtilities.createBrand(250);
            Id brandObjId = brandObj[0].Id;
            
            List<Series__c> serviceObj  = IMCC_TestUtilities.createEventSeries(brandObjId, 250);
            Id serviceObjId = serviceObj[0].Id;
            
            List<Event_Setting__c> eveSettingObj = IMCC_TestUtilities.createEventSetting(250);
            Id eveSettingObjId = eveSettingObj[0].Id;
            
            List<Edition__c> editionObj = IMCC_TestUtilities.createEventEditionWithEveSetting(serviceObjId,docObjId,eveSettingObjId,250);
            Id editionObjId = editionObj[0].Id;
            
            //System.assertEquals(editionObj[0].Edition_Code__c,'TEV21', 'Event Code'); 
            
            List<Edition_Popup__c> listEditionPopup = IMCC_TestUtilities.createEditionPopupData(editionObj[0].Id,200);
            
            List<Event_Tabs__c> evntTabsLst = IMCC_TestUtilities.createEventTabListData(eveSettingObj[0].Id,200);
            
            System.assertEquals(evntTabsLst.Size(),200, 'evntTabsLst size should be 200');
            
            List<Tab_User_Type__c> evntTabUserTypeList = IMCC_TestUtilities.createEventntTabUserTypeData(evntTabsLst[0].Id,listEditionPopup[0].Id,200);
            
            Contact_Edition_Mapping__c cemObj = IMCC_TestUtilities.createContactEditionMapping(contactId,accId,editionObjId);
            List<Email_Templates__c> lisEmailTemp = IMCC_TestUtilities.createEmailTemplateWelcomeTestUser();
            
            Test.startTest();
            IMCC_CreateViewTestDataCTRL.getEixstingTestData(editionObjId);
            IMCC_CreateViewTestDataCTRL.testDataCreated(editionObjId, 'Agent', 'Space Only');
            IMCC_CreateViewTestDataCTRL.sendEmailInvite(cemObj.Id, 'abc@test.com');
            
            Test.stopTest();
        }
        
    }   
    
    public static testMethod void headerDataInsert2()
    {
        UserRole userrole = [Select Id, DeveloperName From UserRole Where DeveloperName = 'Administrator' Limit 1];
        User adminUser = [Select Id, UserRoleId From User Where Profile.Name='System Administrator' and IsActive = true Limit 1];
        adminUser.UserRoleId = userrole.Id;
        update adminUser;
        // Setup Test Data 
        // User adminUser = [Select Id, UserRoleId From User Where Profile.Name='System Administrator' and IsActive = true and UserRole.Name = 'Administrator' Limit 1];
        User userObj;
        Id contactId;
        Id accId;
        System.runAs(adminUser){
            List<Account> accObj  = IMCC_TestUtilities.createAccount(250);
            accId = accObj[0].Id;
            List<Contact> contObj = IMCC_TestUtilities.createContact(accId, 250);
            contactId = contObj[0].Id;
            contObj[0].IsTestUser__c = True;
            contObj[0].Access_Type__c = 'Agent';
            update contObj[0];
            
            userObj = IMCC_TestUtilities.createCommunityUser2(contactId);
            System.assertEquals(userObj.ContactID,contactId, 'Same contact');
            
            List<Document> docObj  = IMCC_TestUtilities.createDocument(250);
            Id docObjId = docObj[0].Id;
            
            List<Brand__c> brandObj  = IMCC_TestUtilities.createBrand(250);
            Id brandObjId = brandObj[0].Id;
            
            List<Series__c> serviceObj  = IMCC_TestUtilities.createEventSeries(brandObjId, 250);
            Id serviceObjId = serviceObj[0].Id;
            
            List<Event_Setting__c> eveSettingObj = IMCC_TestUtilities.createEventSetting(250);
            Id eveSettingObjId = eveSettingObj[0].Id;
            
            List<Edition__c> editionObj = IMCC_TestUtilities.createEventEditionWithEveSetting(serviceObjId,docObjId,eveSettingObjId,250);
            Id editionObjId = editionObj[0].Id;
            
            //System.assertEquals(editionObj[0].Edition_Code__c,'TEV21', 'Event Code'); 
            
            List<Edition_Popup__c> listEditionPopup = IMCC_TestUtilities.createEditionPopupData(editionObj[0].Id,200);
            
            List<Event_Tabs__c> evntTabsLst = IMCC_TestUtilities.createEventTabListData(eveSettingObj[0].Id,200);
            
            System.assertEquals(evntTabsLst.Size(),200, 'evntTabsLst size should be 200');
            
            List<Tab_User_Type__c> evntTabUserTypeList = IMCC_TestUtilities.createEventntTabUserTypeData(evntTabsLst[0].Id,listEditionPopup[0].Id,200);
            
            Contact_Edition_Mapping__c cemObj = IMCC_TestUtilities.createContactEditionMapping2(contactId,accId,editionObjId);
            
            Test.startTest();
            IMCC_CreateViewTestDataCTRL.getEixstingTestData(editionObjId);
            IMCC_CreateViewTestDataCTRL.testDataCreated(editionObjId, 'Agent', 'Space Only');
            IMCC_CreateViewTestDataCTRL.cancelInvitation(cemObj.Id);
            
            Test.stopTest();
        }
        
    }    

}