force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description>Field to identify Branch</description>
    <label>Brand (s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa Health</fullName>
            </value>
            <value>
                <fullName>Arab Health</fullName>
            </value>
            <value>
                <fullName>Channel Partners</fullName>
            </value>
            <value>
                <fullName>Channel Partners Cloud Insights</fullName>
            </value>
            <value>
                <fullName>Channel Partners Conference &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Channel Partners Evolution</fullName>
            </value>
            <value>
                <fullName>Channel Partners Store</fullName>
            </value>
            <value>
                <fullName>China Beauty Expo</fullName>
            </value>
            <value>
                <fullName>EndoNurse Institute</fullName>
            </value>
            <value>
                <fullName>Fispal Cafe</fullName>
            </value>
            <value>
                <fullName>Fispal Tecnologia Expo</fullName>
            </value>
            <value>
                <fullName>Greenbuild Int&apos;l Conf &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Infection Control Today</fullName>
            </value>
            <value>
                <fullName>Ingredient Marketplace Global Expo&amp;Conf</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Developers Conf</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Executive Symposium</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage Store</fullName>
            </value>
            <value>
                <fullName>Inside Self-Storage World Expo</fullName>
            </value>
            <value>
                <fullName>Interior Design Show</fullName>
            </value>
            <value>
                <fullName>National Tanning Training Institute</fullName>
            </value>
            <value>
                <fullName>Natural Products INSIDER</fullName>
            </value>
            <value>
                <fullName>Petfood 2.0 Conference &amp; Expo</fullName>
            </value>
            <value>
                <fullName>Self-Storage Talk</fullName>
            </value>
            <value>
                <fullName>Self-Storage Training Institute</fullName>
            </value>
            <value>
                <fullName>SupplySide</fullName>
            </value>
            <value>
                <fullName>SupplySide Animal Nutrition Insights</fullName>
            </value>
            <value>
                <fullName>SupplySide Beverage Insights</fullName>
            </value>
            <value>
                <fullName>SupplySide Fispal Brazil Expo</fullName>
            </value>
            <value>
                <fullName>SupplySide Health Technology Insights</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Badge_Allocation__c/Badge_Allocation__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Badge settings. Badge allocation defines the number of badges assigned to the customer.</description>
    <label>Badge Allocation</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Badge Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badge Allocation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Badge_Allocation__c/fields/Badge_Setting__c.field-meta.xml
<CustomField>
    <fullName>Badge_Setting__c</fullName>
    <description>Lookup to Badge Setting.</description>
    <label>Badge Setting</label>
    <referenceTo>Badge_Setting__c</referenceTo>
    <relationshipLabel>Badge Allocation</relationshipLabel>
    <relationshipName>Badge_Allocation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Badge_Allocation__c/fields/Upper__c.field-meta.xml
<CustomField>
    <fullName>Upper__c</fullName>
    <description>Defines the upper limit of quantity/Area for Product/Booth.</description>
    <inlineHelpText>Quantity/Area</inlineHelpText>
    <label>Upper</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Badge_Allocation__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Badge_Setting__c/Badge_Setting__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will define the badge allocations available for a particular event. It will have different badge allocations.</description>
    <label>Badge Setting</label>
    <nameField>
        <label>Badge Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badge Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>It defines the Brand Information. A series can belong to a particular brand.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>x_1st Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contractor_Mapping__c/Contractor_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It Store the details of contractor</description>
    <label>Contractor Mapping</label>
    <nameField>
        <label>Contractor Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contractor Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contractor_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition for stand</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contractor Mappings</relationshipLabel>
    <relationshipName>Contractor_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Badge_Setting__c.field-meta.xml
<CustomField>
    <fullName>Badge_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Badge Setting</label>
    <referenceTo>Badge_Setting__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Stand_Setting__c.field-meta.xml
<CustomField>
    <fullName>Stand_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LookUp for Stand Setting</description>
    <label>Stand Setting</label>
    <referenceTo>Stand_Setting__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/Purchase_Data__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It is the transactional information regarding the booth/product purchased.</description>
    <label>Purchase Data</label>
    <nameField>
        <displayFormat>PD-{000000000}</displayFormat>
        <label>Purchase Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Data__c/fields/Addition_Badge_Count__c.field-meta.xml
<CustomField>
    <fullName>Addition_Badge_Count__c</fullName>
    <description>adding new badges by the exhibitor</description>
    <label>Addition Badge Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact Edition mapping</description>
    <label>Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Contractor_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used to capture Contractor mapping respect to Stand Details info</description>
    <label>Contractor Mapping</label>
    <referenceTo>Contractor_Mapping__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Edition Record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <description>Defines user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Series__c/Series__c.object-meta.xml
<CustomObject>
    <description>It defines the Series Information. Each year&apos;s Edition will be tied to a particular Series.</description>
    <label>Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Series__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Brand of Series</description>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Series</relationshipLabel>
    <relationshipName>Event_Series</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stand_Setting__c/Stand_Setting__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child of Edition. This will set the stand visibility on the home page of a particular event.</description>
    <label>Stand Setting</label>
    <nameField>
        <label>Stand Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stand Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Type__c/User_Type__c.object-meta.xml
<CustomObject>
    <label>User Type</label>
    <nameField>
        <label>User Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IMCC_SyncBadgeNumbersBulkCtrl_Test.cls
/**
* Created/Modified By: Girikon(Arushi[IMCC-58])
* Created On    :      23/12/2021
* @description  :      This class is used to fetch the badge Allocation records to update the purchase data field with the current badge numbers in bulk
* Methods:             getData
* Apex Class:          IMCC_SyncBadgeNumbersBulkCtrl, IMCC_PurchaseDataTriggerHandler 
* Apex Test Class:     IMCC_SyncBadgeNumbersBulkCtrl_Test(84%), IMCC_PurchaseDataTriggerHandler(86%)
**/

@isTest
private class IMCC_SyncBadgeNumbersBulkCtrl_Test {

    @isTest
    private static void syncBadgeNumbersBulkMethod1(){
        Id contactId;
        Id accId;
        
        List<Account> accObj  = IMCC_TestUtilities.createAccount(1);
        accId = accObj[0].Id;
        List<Contact> contObj = IMCC_TestUtilities.createContact(accId, 1);
        contactId = contObj[0].Id;
        
        List<Document> docObj  = IMCC_TestUtilities.createDocument(1);
        Id docObjId = docObj[0].Id;
        List<Brand__c> brandObj  = IMCC_TestUtilities.createBrand(1);
        Id brandObjId = brandObj[0].Id;
        List<Series__c> serviceObj  = IMCC_TestUtilities.createEventSeries(brandObjId, 1);
        Id serviceObjId = serviceObj[0].Id;
        List<Badge_Setting__c> badgeSettingObj  = IMCC_TestUtilities.createBadgeSetting(1);
        Id badgeSettingObjId = badgeSettingObj[0].Id;
        List<Badge_Allocation__c> badgeAllocateObj  = IMCC_TestUtilities.createBadgeAllocationSetting(badgeSettingObjId,'Shell Scheme',4);
        badgeAllocateObj[0].User_Type__c = 'Exhibitor';
        badgeAllocateObj[1].User_Type__c = 'Exhibitor';
        badgeAllocateObj[2].User_Type__c = 'Exhibitor';
        badgeAllocateObj[3].User_Type__c = 'Exhibitor';
        update badgeAllocateObj;
        List<Edition__c> editionObj = IMCC_TestUtilities.createEventEditionWithBadgeSetting(serviceObjId,docObjId,badgeSettingObjId,1);
        Id editionObjId = editionObj[0].Id;
        Contact_Edition_Mapping__c cemObj = IMCC_TestUtilities.createContactEditionMapping(contactId,accId,editionObjId);
        List<Purchase_Data__c> purchaseDataObj  = IMCC_TestUtilities.createPurchaseData2(cemObj.Id,editionObjId,2);
        purchaseDataObj[0].User_Type__c = 'Exhibitor';
        purchaseDataObj[1].User_Type__c = 'Exhibitor';
        update purchaseDataObj;
        Test.startTest();
        List<Purchase_Data__c> purchaseDataObj2  = [SELECT Id FROM Purchase_Data__c];
        System.assertEquals(2, purchaseDataObj2.size(),'mismatch');
        IMCC_SyncBadgeNumbersBulkCtrl.getData(badgeSettingObjId);
        Test.stopTest();
        
    }
    
    @isTest
    private static void syncBadgeNumbersBulkMethod2(){
        Id contactId;
        Id accId;
        
        List<Account> accObj  = IMCC_TestUtilities.createAccount(1);
        accId = accObj[0].Id;
        List<Contact> contObj = IMCC_TestUtilities.createContact(accId, 1);
        contactId = contObj[0].Id;
        
        List<Document> docObj  = IMCC_TestUtilities.createDocument(1);
        Id docObjId = docObj[0].Id;
        List<Brand__c> brandObj  = IMCC_TestUtilities.createBrand(1);
        Id brandObjId = brandObj[0].Id;
        List<Series__c> serviceObj  = IMCC_TestUtilities.createEventSeries(brandObjId, 1);
        Id serviceObjId = serviceObj[0].Id;
        List<Stand_Setting__c> standSettingObj = IMCC_TestUtilities.createStandSetting(250);
        Id standSettingObjId = standSettingObj[0].Id;
        
        List<Edition__c> editionObj = IMCC_TestUtilities.createEventEditionWithStandSetting(serviceObjId,docObjId,standSettingObjId,250,system.today(),system.today());
        Id editionObjId = editionObj[0].Id;
         Test.startTest();
        Contact_Edition_Mapping__c cemObj = IMCC_TestUtilities.createContactEditionMapping(contactId,accId,editionObjId);
        List<Purchase_Data__c> booth = IMCC_TestUtilities.createPurchaseData4(cemObj.Id,editionObjId,2);
        List<Contractor_Mapping__c> cmObj = IMCC_TestUtilities.createContractorMappingData(accId,contactId,cemObj.Id,booth[0].Id,'Contractor Nominated',editionObjId,null,1);
        System.assertEquals(1, cmObj.size(),'mismatch');
       
       Test.stopTest();
        
    }
    
    @isTest
    private static void syncBadgeNumbersBulkMethod3(){
        Id contactId;
        Id accId;
        
        List<Account> accObj  = IMCC_TestUtilities.createAccount(1);
        accId = accObj[0].Id;
        List<Contact> contObj = IMCC_TestUtilities.createContact(accId, 1);
        contactId = contObj[0].Id;
        
        List<Document> docObj  = IMCC_TestUtilities.createDocument(1);
        Id docObjId = docObj[0].Id;
        List<Brand__c> brandObj  = IMCC_TestUtilities.createBrand(1);
        Id brandObjId = brandObj[0].Id;
        List<Series__c> serviceObj  = IMCC_TestUtilities.createEventSeries(brandObjId, 1);
        Id serviceObjId = serviceObj[0].Id;
        List<Badge_Setting__c> badgeSettingObj  = IMCC_TestUtilities.createBadgeSetting(1);
        Id badgeSettingObjId = badgeSettingObj[0].Id;
        List<Badge_Allocation__c> badgeAllocateObj  = IMCC_TestUtilities.createBadgeAllocationSetting(badgeSettingObjId,'Shell Scheme',4);
        badgeAllocateObj[0].User_Type__c = 'Exhibitor';
        badgeAllocateObj[1].User_Type__c = 'Exhibitor';
        badgeAllocateObj[2].User_Type__c = 'Exhibitor';
        badgeAllocateObj[2].Upper__c = null;
        badgeAllocateObj[3].User_Type__c = 'Exhibitor';
        badgeAllocateObj[3].Upper__c = null;
        update badgeAllocateObj;
        List<Edition__c> editionObj = IMCC_TestUtilities.createEventEditionWithBadgeSetting(serviceObjId,docObjId,badgeSettingObjId,1);
        Id editionObjId = editionObj[0].Id;
        Contact_Edition_Mapping__c cemObj = IMCC_TestUtilities.createContactEditionMapping(contactId,accId,editionObjId);
        List<Purchase_Data__c> purchaseDataObj  = IMCC_TestUtilities.createPurchaseData2(cemObj.Id,editionObjId,2);
        purchaseDataObj[0].User_Type__c = 'Exhibitor';
        purchaseDataObj[1].User_Type__c = 'Co-Exhibitor';
        update purchaseDataObj;
        Test.startTest();
        IMCC_SyncBadgeNumbersBulkCtrl.getData(badgeSettingObjId);
        List<Purchase_Data__c> purchaseDataObj2  = [SELECT Id FROM Purchase_Data__c];
        System.assertEquals(2, purchaseDataObj2.size(),'mismatch');
        Test.stopTest();
        
    }
    
    @isTest
    private static void syncBadgeNumbersBulkMethod4(){
        Id contactId;
        Id accId;
        
        List<Account> accObj  = IMCC_TestUtilities.createAccount(1);
        accId = accObj[0].Id;
        List<Contact> contObj = IMCC_TestUtilities.createContact(accId, 1);
        contactId = contObj[0].Id;
        
        List<Document> docObj  = IMCC_TestUtilities.createDocument(1);
        Id docObjId = docObj[0].Id;
        List<Brand__c> brandObj  = IMCC_TestUtilities.createBrand(1);
        Id brandObjId = brandObj[0].Id;
        List<Series__c> serviceObj  = IMCC_TestUtilities.createEventSeries(brandObjId, 1);
        Id serviceObjId = serviceObj[0].Id;
        List<Badge_Setting__c> badgeSettingObj  = IMCC_TestUtilities.createBadgeSetting(1);
        Id badgeSettingObjId = badgeSettingObj[0].Id;
        List<Badge_Allocation__c> badgeAllocateObj  = IMCC_TestUtilities.createBadgeAllocationSetting(badgeSettingObjId,'Shell Scheme',4);
        badgeAllocateObj[0].User_Type__c = 'Exhibitor';
        badgeAllocateObj[1].User_Type__c = 'Exhibitor';
        badgeAllocateObj[2].User_Type__c = 'Exhibitor';
        badgeAllocateObj[2].Upper__c = null;
        badgeAllocateObj[3].User_Type__c = 'Exhibitor';
        badgeAllocateObj[3].Upper__c = null;
        update badgeAllocateObj;
        List<Edition__c> editionObj = IMCC_TestUtilities.createEventEditionWithBadgeSetting(serviceObjId,docObjId,badgeSettingObjId,1);
        Id editionObjId = editionObj[0].Id;
        Contact_Edition_Mapping__c cemObj = IMCC_TestUtilities.createContactEditionMapping(contactId,accId,editionObjId);
        List<Purchase_Data__c> purchaseDataObj  = IMCC_TestUtilities.createPurchaseData2(cemObj.Id,editionObjId,2);
        purchaseDataObj[0].User_Type__c = 'Exhibitor';
        purchaseDataObj[1].User_Type__c = 'Reseller';
        update purchaseDataObj;
        purchaseDataObj[1].User_Type__c = 'Exhibitor';
        purchaseDataObj[1].Addition_Badge_Count__c = null;
        update purchaseDataObj;
        Test.startTest();
        IMCC_SyncBadgeNumbersBulkCtrl.getData(badgeSettingObjId);
        List<Purchase_Data__c> purchaseDataObj2  = [SELECT Id FROM Purchase_Data__c];
        System.assertEquals(2, purchaseDataObj2.size(),'mismatch');
        Test.stopTest();
        
    }
}