force-app/main/default/objects/Account/fields/Facebook__c.field-meta.xml
<CustomField>
    <fullName>Facebook__c</fullName>
    <description>Facebook URL of Company</description>
    <label>Facebook</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Linkedin__c.field-meta.xml
<CustomField>
    <fullName>Linkedin__c</fullName>
    <description>Linkedin URL of Company</description>
    <label>Linkedin</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Twitter__c.field-meta.xml
<CustomField>
    <fullName>Twitter__c</fullName>
    <description>Twitter URL of Company</description>
    <label>Twitter</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Look up to Contact record</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Not a Customer Center Contact.</errorMessage>
        <filterItems>
            <field>Contact.IOM_Contact_Identifier__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Background_Colour__c.field-meta.xml
<CustomField>
    <fullName>Background_Colour__c</fullName>
    <description>Define the branding color of the background of Footer</description>
    <inlineHelpText>Define the branding color of the background of Footer</inlineHelpText>
    <label>Background Colour</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Description__c.field-meta.xml
<CustomField>
    <fullName>Edition_Description__c</fullName>
    <description>Used to display content in footer at customer portal.</description>
    <inlineHelpText>Define the content in footer at customer portal.</inlineHelpText>
    <label>Edition Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Director__c.field-meta.xml
<CustomField>
    <fullName>Edition_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Lookup Field store the id of the Edition Director.</description>
    <label>Edition Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Edition_Image_URL__c</fullName>
    <description>This Field stores Edition Logo Id.</description>
    <label>Edition Logo Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Status__c.field-meta.xml
<CustomField>
    <fullName>Edition_Status__c</fullName>
    <description>This picklist stores the status of Edition.</description>
    <label>Edition Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Tentative</fullName>
            </value>
            <value>
                <fullName>Cancelled by Finance</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Pending Setup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>This field stores the End date of Edition.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Event_Setting__c.field-meta.xml
<CustomField>
    <fullName>Event_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Setting</label>
    <referenceTo>Event_Setting__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/FaceBook__c.field-meta.xml
<CustomField>
    <fullName>FaceBook__c</fullName>
    <description>Define the facebook URL on facebook icon on customer portal.</description>
    <inlineHelpText>Define the Facebook URL.</inlineHelpText>
    <label>FaceBook</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/LinkedIn__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn__c</fullName>
    <description>Define the LinkedIn Url on LinkedIn icon on customer portal</description>
    <inlineHelpText>Define the LinkedIn URL.</inlineHelpText>
    <label>LinkedIn</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Show_Hours__c.field-meta.xml
<CustomField>
    <fullName>Show_Hours__c</fullName>
    <description>Using on customer portal footer to display show timing.</description>
    <inlineHelpText>Using on customer portal footer to display show timing.</inlineHelpText>
    <label>Show Hours</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Text_Colour__c.field-meta.xml
<CustomField>
    <fullName>Text_Colour__c</fullName>
    <description>Define the branding color of the text of footer</description>
    <inlineHelpText>Define the branding color of the text of footer</inlineHelpText>
    <label>Text Colour</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Twitter__c.field-meta.xml
<CustomField>
    <fullName>Twitter__c</fullName>
    <description>Define redirect URL for the Twitter icon on customer portal.</description>
    <inlineHelpText>Define the Twitter URL.</inlineHelpText>
    <label>Twitter</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/YouTube__c.field-meta.xml
<CustomField>
    <fullName>YouTube__c</fullName>
    <description>Define redirect URL for the you tube icon on customer portal.</description>
    <inlineHelpText>Define the You Tube URL.</inlineHelpText>
    <label>YouTube</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Edition__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Edition_Websites__c/Edition_Websites__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child Object of Edition. It contains the websites name and link records to be shown on the footer after login to Customer Center</description>
    <label>Edition Websites</label>
    <nameField>
        <label>Edition Websites Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition Websites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition_Websites__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Edition Websites</relationshipLabel>
    <relationshipName>Edition_Websites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Edition_Websites__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Defines the order of Websites shown on Footer</description>
    <label>Sequence</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Edition_Websites__c/fields/Website_Label__c.field-meta.xml
<CustomField>
    <fullName>Website_Label__c</fullName>
    <description>Defines the label for your website link</description>
    <label>Website Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition_Websites__c/fields/Website_Link__c.field-meta.xml
<CustomField>
    <fullName>Website_Link__c</fullName>
    <description>Contains the Website link url</description>
    <label>Website Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Event_Setting__c/Event_Setting__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child of Edition. This will set the tab visibility on the home page of a particular event.</description>
    <label>Event Setting</label>
    <nameField>
        <label>Event Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition of order.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IMCC_UserLoginCtrl.cls
/**
* Created/Modified By: Girikon(Garima)
* Created On:          6/9/2021
* @description  : This class provides following functionalities:
*                      If community url is having event code then display event data on login page i.e. event name & log
*                      Allow login to valid user (with or without event code) else show proper error message
*                      Allow valid user to put the request for new password.
* Methods:             GetUserData, getEventCode, login 
* Apex Class:          IMCC_UserLoginCtrl 
* Apex Test Class:     IMCC_UserLoginCtrl_Test (92%)
**/

public without sharing class IMCC_UserLoginCtrl{
    /**@description username */
    public string username {get;set;}
    /**@description password */
    public string password {get;set;}
    /**@description errMsg */
    public string errMsg{get;set;}
    /**@description username */
    public string successMsg{get;set;}
    
    /**@description event */
    public Edition__c event{get;set;}
    /**@description eventSet */
    public Event_Setting__c eventSet{get;set;}
    /**@description editionWeb */
    public List<Edition_Websites__c> editionWeb{get;set;}
    /**@description eventEditionCode */
    public String eventEditionCode{get;set;}
    /**@description brandingColor */
    public String brandingColor{get;set;}  
    /**@description editionDescription */
    public String editionDescription{get;set;} 
    /**@description showHours */
    public String showHours{get;set;}
    /**@description backgroundColor */
    public String backgroundColor{get;set;}
    /**@description textColor */
    public String textColor{get;set;}
    /**@description imageURL */
    public String imageURL{get;set;}  
    /**@description facebook */
    public String facebook{get;set;}
    /**@description twitter */
    public String twitter{get;set;}
    /**@description youtube */
    public String youtube{get;set;}
    /**@description linkedin */
    public String linkedin{get;set;}
     
    
    /**@description log */
    public String log{get;set;}

    /**
    * @description : Get site url
    * @return : SiteURL
    */
    public String getSiteURL() 
    {
        return System.URL.getSalesforceBaseURL().toExternalForm();   
    }
    
    /**
    * @description : get Current Org ID
    * @return :  Org ID
    */
    public String getOrgId() 
    {
        return UserInfo.getOrganizationId();
    }
    
    /**
    * @description : Class constructor
    */
    public IMCC_UserLoginCtrl()
    {  
        log =  JSON.serialize(ApexPages.currentPage().getparameters());
        successMsg = '';        
        try
        {     
            string errorCode= apexpages.currentpage().getparameters().get('er');
            System.Debug(LoggingLevel.DEBUG,'ErrorCode: '+errorCode);
            
            //Display proper error message as per errorcode
            if(string.isNotBlank(errorCode))
            {
                if(ErrorCode.equalsIgnoreCase('iunp'))
                {
                    errMsg='Invalid Username/Password';
                }
                else if(ErrorCode.equalsIgnoreCase('iufte'))
                {
                    errMsg='Invalid user for this event.';
                }
                else if(ErrorCode.equalsIgnoreCase('iu'))
                {
                    errMsg='Invalid Username/Password';            
                }
            }
            
            //Get event code from to get event details to display on login page
            string eventCode= apexpages.currentpage().getparameters().get('edcode');
            if(eventCode !=null)
            {
                if(string.isBlank(EventCode))
                {
                    eventCode = getEventCode();
                }
                
                if(string.isNotBlank(eventCode))
                {
                    List<Edition__c> eves;
                    if(Edition__c.SObjectType.getDescribe().isAccessible()){
                        eves = [SELECT id,Name,End_Date__c,Edition_Image_URL__c,Edition_Description__c,Background_Colour__c,Text_Colour__c,Show_Hours__c,FaceBook__c,LinkedIn__c,Twitter__c,YouTube__c FROM Edition__c WHERE Edition_Code__c =:eventCode AND Edition_Status__c='Confirmed'];
                    }
                    
                    if(eves!=null && eves.size()>0)
                    {
                        event=eves[0];
                        if(Edition_Websites__c.SObjectType.getDescribe().isAccessible()){
                            editionWeb = [Select Edition__c,Website_Label__c,Website_Link__c,Sequence__c from Edition_Websites__c where Edition__c =: event.Id Order By Sequence__c asc];
                        }
                        backgroundColor= event.Background_Colour__c;
                        textColor= event.Text_Colour__c;
                        editionDescription = event.Edition_Description__c;
                        showHours = event.Show_Hours__c;
                        facebook = event.FaceBook__c;
                        twitter = event.Twitter__c;
                        youtube = event.YouTube__c;
                        linkedin = event.LinkedIn__c; 
                    }
                    else{
                        errMsg='Either invalid event code OR event has been ended.';
                    }
                }
            }
            System.debug(LoggingLevel.DEBUG,'errMsg: '+errMsg);
        }
        catch(Exception ex)
        {
            System.Debug(LoggingLevel.DEBUG,'Error : '+ex.getMessage());
            HandleAllCustomException.logException(ex,'Edition__c', 'After Insert');   
        }
    } 

    /**
    * @description : Method to get user data & redirect user to respective page
    * @param eventCode
    * @return PageReference
    */
    public PageReference getUserData(string eventCode)
    {
        PageReference pageRef;
        try{
            username = username.trim();
            System.debug(LoggingLevel.DEBUG,'username: '+username);
            
            List<User> usr = [SELECT Id,ContactId FROM User WHERE Username=:username AND IsActive=True];
            System.debug(LoggingLevel.DEBUG,'User: '+usr);
            if(!usr.isEmpty() && usr[0].ContactId!=null){
                string strQuery='select id,Edition__r.Edition_Code__c from Contact_Edition_Mapping__c where Contact__c =\''+ String.escapeSingleQuotes(usr[0].ContactId)+'\'';
                strQuery +=' AND Edition__r.Edition_Code__c != null';
                if(string.isNotBlank(EventCode)){
                    strQuery +=' AND Edition__r.Edition_Code__c =\''+String.escapeSingleQuotes(EventCode)+'\'';
                }    
                List<Contact_Edition_Mapping__c> conEdMap = Database.query(strQuery);
                
                if(conEdMap!=null && conEdMap.size()>0){
                    String u = (eventCode!=null && eventCode!='') ? 'edcode='+eventCode:'';                    
                    String communityURL ='/s/accountselection?'+u;
                    pageRef = Site.login(username, password, communityURL);
                    if(pageRef == null){        
                        u = (eventCode!=null && eventCode!='') ? '&edcode='+eventCode:'';             
                        pageRef=new PageReference('/apex/IMCC_UserLogin?er=iunp'+u);
                        pageRef.setRedirect(true);
                    }
                }
                else if(string.isNotBlank(EventCode)){
                    pageRef=new PageReference('/apex/IMCC_UserLogin?er=iufte&edcode='+EventCode);
                    pageRef.setRedirect(true);
                }
            }
            else{
                pageRef=new PageReference('/apex/IMCC_UserLogin?&er=iu'+(String.isNotBlank(eventCode)?('&edcode='+eventCode):''));
                pageRef.setRedirect(true);
            }
        }
        catch(exception e){
            HandleAllCustomException.logException(e,'Account', 'After Insert');
        }
        return pageRef;
    }
    
    /**
    * @description : Get event code from encoded url
    * @return : EventCode
    */
    public string getEventCode()
    {
        string eventCode = '';
        string url='';
        try{
            string headerdata= ApexPages.currentPage().getHeaders().get('Host');
            string urlvalue=Apexpages.currentPage().getUrl(); 
            string currentURL ='https://' + headerdata+ urlvalue;
            String encoded = EncodingUtil.urlDecode(currentURL, 'UTF-8');
            string[] strArr=encoded.split('\\?');
            
            if(strArr!=null && strArr.size()>0)
            {
                URL=strArr[1];
                if(strArr.size()>2)
                {
                    EventCode=strArr[2];
                }                    
                string[] strURLArr=URL.split('=');
                if(strURLArr!=null && strURLArr.size()>1)
                {
                    URL=strURLArr[1];
                    URL=URL.remove('\'');
                }
                string[] strparamArr;
                if(String.IsNotBlank(EventCode))
                {
                    strparamArr=EventCode.split('=');
                }                
                if(strparamArr!=null && strparamArr.size()>0)
                {
                    EventCode=strparamArr[1];
                }
            }
        }
        catch(exception e){
            HandleAllCustomException.logException(e,'Account', 'After Insert');
        }
        return EventCode;
    }

    /**
    * @description : Login functionality with or without event code
    * @return : pageRef
    */
    public PageReference login(){
        PageReference pageRef;
        string eventCode= apexpages.currentpage().getparameters().get('edcode');
        if(EventCode!=null && string.isBlank(EventCode)){
            EventCode = getEventCode();
        }
        pageRef=getUserData(EventCode);
        
        return pageRef;
    }
    
    /**
    * @description : Show forgot password panel
    * @return : pageRef
    */
    public PageReference forgotPassword(){
        errMsg='';
        PageReference pageRef = new PageReference('/apex/IMCC_ForgotPassword');
        pageRef.setRedirect(true);
        return pageRef;
    }
    /* End*/
    
    /**
    * @description : Back to login page
    * @return : pageRef
    */
    public PageReference backToSignIn(){
        errMsg='';        
        PageReference pageRef = new PageReference('/apex/IMCC_UserLogin');
        pageRef.setRedirect(true);
        return pageRef;
    }
    
    /**
    * @description : Processing for reset password
    * @return : pageRef
    */
    public PageReference resetPassword(){
        successMsg='';
        if(username != null && username != ''){
            username = username.trim();
            List<user> listbs = [SELECT Username,Email FROM user WHERE Username=:username LIMIT 1];
            if(!listbs.isEmpty()){
                string str = listbs[0].Email;
                
                boolean success = Site.forgotPassword(username);
                if(success){
                    successMsg = 'Password reset link has been sent to '+ str;
                    username = '';
                    errMsg = '';
                }
                else{
                    errMsg = 'Something went wrong, Please try again later.';
                }
            } 
            else{
                System.debug(LoggingLevel.DEBUG,'No record');
                errMsg= 'Invalid user name';
            }
        }
        else{
            System.debug(LoggingLevel.DEBUG,'Outside username');
            errMsg = 'Please enter user name!' ;
        }
        return null;
    }

    /**
    * @description : Login Using IIRIS External Auth. Provider
    * @return : pageRef
    */
    public PageReference iirislogin(){
        PageReference pageRef;
        string eventCode = apexpages.currentpage().getparameters().get('edcode');
        if(EventCode!=null && string.isBlank(EventCode)){
            EventCode = getEventCode();
        }
        String u = ((eventCode!=null && eventCode!='')?'edcode='+eventCode:'');                    
        String startURL ='/s?'+u;
        String startURL2 = apexpages.currentpage().getparameters().get('startURL');
        if(String.isNotBlank(startURL2)){startURL = EncodingUtil.urlDecode(startURL2,'UTF-8');}
        Id networkId = Network.getNetworkId();
        Auth.AuthConfiguration authConfig = new Auth.AuthConfiguration(networkId,null);
        List<AuthProvider> authPrvs = authConfig.getAuthProviders();
        if(!authPrvs.isEmpty()){
            for(AuthProvider provider : authPrvs){
                if(provider.DeveloperName == Label.IMCC_IIRIS_Auth_Provider){
                    System.debug(LoggingLevel.Debug, 'sso===' + getSiteURL()+'/IMCC/services/auth/sso/'+provider.DeveloperName+'?startURL='+ EncodingUtil.urlEncode(startUrl,'UTF-8'));
                    pageRef = new PageReference(getSiteURL()+'/IMCC/services/auth/sso/'+provider.DeveloperName+'?startURL='+ EncodingUtil.urlEncode(startUrl,'UTF-8'));
                }
            }
        }
        return pageRef;
    }
    /* End*/
}