force-app/main/default/objects/Account/fields/IOM_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>IOM_Sync_Status__c</fullName>
    <description>Sync Status of Account while sending Account to IOM From CRM.</description>
    <label>IOM Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IOM_Sync_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/IOM_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>IOM_Sync_Status__c</fullName>
    <description>Sync Status of Account while sending Contact to IOM From CRM.</description>
    <label>IOM Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IOM_Sync_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/IOM_Application_Bypass__c/IOM_Application_Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>To prevention deletion of Account, Opportunity and Contact records.</description>
    <label>IOM Application Bypass</label>
</CustomObject>

force-app/main/default/objects/IOM_Application_Bypass__c/fields/Bypass_Account_Deletion__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Account_Deletion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If an entry exist with this field checked then user will be able to delete Account.</description>
    <label>Bypass Account Deletion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IOM_Application_Bypass__c/fields/Bypass_Contact_Deletion__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Contact_Deletion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If an entry exist with this field checked then user will be able to delete Contact.</description>
    <label>Bypass Contact Deletion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IOM_Application_Bypass__c/fields/Bypass_Opportunity_Deletion__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Opportunity_Deletion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If an entry exist with this field checked then user will be able to delete Opportunity.</description>
    <label>Bypass Opportunity Deletion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IOM_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>IOM_Sync_Status__c</fullName>
    <description>Sync staus of sending opportunity to IOM for billing</description>
    <label>IOM Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IOM_Sync_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/IOM_ObjectValidation.cls
/**
* File			: 	IOM_ObjectValidation
* Project       :   Informa Order Management
* Created By	: 	Suresh(Girikon)
* Created Date	: 	28th Dec 2021
* Test Class   :    IOM_ObjectValidation_Test(100%)
* ***************************************************************************
* @description : Class to prevent user from deleting opportunity,account and Contact
*****************************************************************************
* Last Modified By :
*/
public with sharing class IOM_ObjectValidation {
    
    public static IOM_Application_Bypass__c abpUser = IOM_Application_Bypass__c.getInstance(UserInfo.getUserId());
/**
* @description  This method is used to prevent user from deleting opportunities
* @param opplist opportunity list
* @param oppmap map of opportunity
*/
    public static void oppValidate(List<Opportunity> opplist, Map<Id,Opportunity> oppmap) 
    {
        for(Opportunity opp : opplist){
            if(opp.IOM_Sync_Status__c == IOM_GlobalConstantsData.getValue('IOM_Sync_Status') &&
              abpUser.Bypass_Opportunity_Deletion__c != true){
                opp.addError('You are not allowed to delete Opportunity records!');
            }
        }
        
    }
    
/**
* @description  This method is used to prevent user from deleting accounts
* @param acclist opportunity list
* @param accmap map of opportunity
*/
    public static void accValidate(List<Account> acclist, Map<Id,Account> accmap) 
    {
        for(Account acc : acclist){
            if(acc.IOM_Sync_Status__c == IOM_GlobalConstantsData.getValue('IOM_Sync_Status') &&
              abpUser.Bypass_Account_Deletion__c != true){
                acc.addError('You are not allowed to delete Account records!');
            }
        }
        
    }
/**
* @description  This method is used to prevent user from deleting contacts
* @param conlist opportunity list
* @param conmap map of opportunity
*/
    public static void conValidate(List<Contact> conlist, Map<Id,Contact> conmap) 
    {
        for(Contact con : conlist){
            if(con.IOM_Sync_Status__c == IOM_GlobalConstantsData.getValue('IOM_Sync_Status') &&
              abpUser.Bypass_Contact_Deletion__c != true){
                con.addError('You are not allowed to delete Contact records!');
            }
        }
        
    }    
}