force-app/main/default/objects/Account/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Consist Source Org name from where the data is migrated from</description>
    <label>Legacy CRM Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legacy_CRM_Instance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Source CRM name from where Contact is created.</description>
    <label>Legacy CRM Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legacy_CRM_Instance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Part_of_Series__c.field-meta.xml
<CustomField>
    <fullName>Part_of_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup store value of series this edition is part of</description>
    <label>Part of Series</label>
    <referenceTo>Series__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Event_Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is an explicit field for Bill To Account.</description>
    <label>Bill To Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Accounting_Credit_Hold__c</field>
            <operation>notEqual</operation>
            <value>Hold</value>
        </filterItems>
        <filterItems>
            <field>Account.Accounting_Credit_Hold__c</field>
            <operation>notEqual</operation>
            <value>Warning</value>
        </filterItems>
        <infoMessage>Account Credit Status is On Hold/Warning.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Bill To Account)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Billing Contact.</description>
    <label>Billing/Invoice Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Default_Edition__c.field-meta.xml
<CustomField>
    <fullName>Default_Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Edition of Opportunity</description>
    <label>Default Edition</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Edition__c.Edition_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Consist Source Org name from where the data originated (Source CRM)</description>
    <label>Legacy CRM Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legacy_CRM_Instance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Series__c.field-meta.xml
<CustomField>
    <fullName>Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Series to which Opportunity&apos;s Edition belongs.</description>
    <label>Series</label>
    <referenceTo>Series__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Order/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition of order.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Legacy CRM Instance</description>
    <label>Legacy CRM Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legacy_CRM_Instance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Booth_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Booth_Product_Type__c</fullName>
    <description>Type of booth product (e.g. Space, Shell Scheme etc.)</description>
    <label>Booth Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Booth_Product_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Booth_Type__c.field-meta.xml
<CustomField>
    <fullName>Booth_Type__c</fullName>
    <description>Type of booth (e.g. Island, Inline etc.)</description>
    <label>Booth Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Indoor</fullName>
            </value>
            <value>
                <fullName>Outdoor</fullName>
            </value>
            <value>
                <fullName>Corner</fullName>
            </value>
            <value>
                <fullName>Island</fullName>
            </value>
            <value>
                <fullName>Inline</fullName>
            </value>
            <value>
                <fullName>Peninsula</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/IM_ProductCode__c.field-meta.xml
<CustomField>
    <fullName>IM_ProductCode__c</fullName>
    <description>Informa Markets product code.</description>
    <displayFormat>IM-{00000}</displayFormat>
    <label>IM ProductCode</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Series__c/Series__c.object-meta.xml
<CustomObject>
    <description>It defines the Series Information. Each year&apos;s Edition will be tied to a particular Series.</description>
    <label>Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AddCPQQuoteLines_Test.cls
/**
* File      	:   AddCPQQuoteLines_Test
* Project       : 	Informa Order Management 
* Created By  	:   Deepak(Girikon)
* Created Date  :   2nd Feb 2022
* ******************************************************************************************************
* @description : Test Class to provide code covrage to classes - AddCPQQuoteLines,CPQAPIUtils,CPQCallbackCls
* Last Modified By :
*/
@istest
private class AddCPQQuoteLines_Test {
    @testSetup 
    static void testSetupData() 
    {

        // Create Account
        Account oAccount = new Account(Name = 'Expocad Account', CurrencyIsoCode = 'USD',
        Phone = '2423122323');
        oAccount.BillingCity = 'Dubai';
        oAccount.BillingCountry = 'India';
        oAccount.BillingPostalCode = '00000';
        oAccount.Legacy_CRM_Instance__c = 'Penton';
        oAccount.BillingState = 'Delhi';
        oAccount.BillingStreet = 'Dubai Test Centre, Building No. 4 - Happiness St';        
        insert oAccount;

        // Create Contact
        Contact oCon = new Contact(LastName = 'ContTest1', Legacy_CRM_Instance__c = 'Penton', Email = 'test1contact@duptest.com', 
        AccountId = oAccount.Id, MailingStreet = 'Test', MailingCity = 'Test', MailingState = '', 
        MailingCountry = 'India', Phone = '2423122323', AssistantPhone = '2423122323', 
        HomePhone = '2121212121', MobilePhone = '2121212145', OtherPhone = '2154215421');
        insert oCon;

        Series__c oSeries = new Series__c(Name = 'Arab Health', CurrencyISOCode = 'USD');
        insert oSeries;

        /**  Package Product Setup **/
        Id pricebookId = Test.getStandardPricebookId(); // StandardPricebook
        
        Edition__c oEdition = new Edition__c(Name = 'Arab Health Exhibition and Congress Test',
        CurrencyIsoCode = 'USD', Edition_Code__c = 'arabh19',Part_of_Series__c = oSeries.id);
        insert oEdition;

        Product2 childPrd = new Product2(Name = 'Raw Space', Booth_Product_Type__c = 'Space Only', 
        Booth_Type__c = 'esc', Family = 'Booth',SBQQ__SubscriptionTerm__c=1,CurrencyIsoCode = 'USD');
        insert childPrd;    // Child product-1 of main Bundle (Stand Alone Type)

        PricebookEntry pbStndrdPriceP1 = new PricebookEntry(Pricebook2Id = pricebookId, 
        Product2Id = childPrd.Id, UnitPrice = 100, IsActive = true,CurrencyIsoCode = 'USD');
        insert pbStndrdPriceP1;  // Child product-1 Standard Pricebook entry

        Product2 childPrd2 = new Product2(Name = 'Admin Fee',Family = 'Booth', Booth_Type__c = 'esc',SBQQ__SubscriptionTerm__c=1,CurrencyIsoCode = 'USD');
        insert childPrd2;       // Child product-2 of main Bundle (Package Type)

        PricebookEntry pbStndrdPriceP2 = new PricebookEntry(Pricebook2Id = pricebookId, 
        Product2Id = childPrd2.Id, UnitPrice = 100, IsActive = true,CurrencyIsoCode = 'USD');
        insert pbStndrdPriceP2;      // Child product-2 Standard Pricebook entry
        /**  Product Set Up - End  **/

        Opportunity oOpportunity = new Opportunity(Name = 'Expocad Opportunity',
        Default_Edition__c =oEdition.Id ,CloseDate = Date.today(), StageName = 'Proposal', 
        AccountId = oAccount.Id, Billing_Contact__c = oCon.Id, Bill_To_Account__c = oAccount.Id,CurrencyIsoCode = 'USD');
        insert oOpportunity;

        SBQQ__Quote__c oQuote = new SBQQ__Quote__c(CurrencyIsoCode = 'USD', SBQQ__Status__c = 'Quote Sent', 
        SBQQ__Type__c = 'Quote', SBQQ__Opportunity2__c = oOpportunity.Id, SBQQ__Account__c = oAccount.Id, 
        SBQQ__Primary__c = true);
        insert oQuote;
    }

    /** @description : testRest*/
    @isTest
    private static void  testRest(){
        Test.startTest();
        SBQQ__Quote__c qt = [SELECT Id,Name FROM SBQQ__Quote__c LIMIT 1];
        List<Product2> listProduct = [SELECT Id,IM_ProductCode__c FROM Product2];

        List<AddCPQQuoteLines.QuoteLineModelWrapper> quoteLines = new List<AddCPQQuoteLines.QuoteLineModelWrapper>();
        AddCPQQuoteLines.QuoteLineModelWrapper wrap = new AddCPQQuoteLines.QuoteLineModelWrapper();
        wrap.imProductCode = listProduct.get(0).IM_ProductCode__c;
        wrap.quantity = 1;
        wrap.unitPrice = 105;
        wrap.startDate = date.newinstance(2022, 2, 1);
        wrap.endDate = date.newinstance(2022, 2, 28);
        quoteLines.add(wrap);

        wrap = new AddCPQQuoteLines.QuoteLineModelWrapper();
        wrap.imProductCode = listProduct.get(0).IM_ProductCode__c;
        wrap.quantity = 1;
        wrap.unitPrice = 100;
        wrap.startDate = date.newinstance(2022, 3, 1);
        wrap.endDate = date.newinstance(2022, 3, 31);
        quoteLines.add(wrap);

        AddCPQQuoteLines.QuoteModelWrapper wrap2 = new AddCPQQuoteLines.QuoteModelWrapper();
        wrap2.lines = quoteLines;
        wrap2.quoteId = qt.Id;
        wrap2.currencyISOcode = 'USD';
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/insertquotelineitems'; 
        req.httpMethod = 'Post';
        req.addHeader('Content-Type', 'application/json');
        req.requestBody = Blob.valueOf(JSON.serialize(wrap2)); 
        RestContext.request = req;
        RestContext.response = res;
        
        AddCPQQuoteLines.ResponseData resWrap = AddCPQQuoteLines.addQLI();
        System.assertEquals('Success', resWrap.status, 'Success');
        Test.stopTest();
    }
    
    /** @description : testRestNegative*/
    @isTest
    private static void  testRestNegative(){
        Test.startTest();
        SBQQ__Quote__c qt = [SELECT Id,Name FROM SBQQ__Quote__c LIMIT 1];

        List<AddCPQQuoteLines.QuoteLineModelWrapper> quoteLines = new List<AddCPQQuoteLines.QuoteLineModelWrapper>();
        AddCPQQuoteLines.QuoteLineModelWrapper wrap = new AddCPQQuoteLines.QuoteLineModelWrapper();
        wrap.imProductCode = 'IM-00089';
        wrap.quantity = 1;
        wrap.unitPrice = 105;
        wrap.startDate = date.newinstance(2022, 2, 1);
        wrap.endDate = date.newinstance(2022, 2, 28);
        quoteLines.add(wrap);

        wrap = new AddCPQQuoteLines.QuoteLineModelWrapper();
        wrap.imProductCode = 'IM-00089';
        wrap.quantity = 1;
        wrap.unitPrice = 100;
        wrap.startDate = date.newinstance(2022, 3, 1);
        wrap.endDate = date.newinstance(2022, 3, 31);
        quoteLines.add(wrap);

        AddCPQQuoteLines.QuoteModelWrapper wrap2 = new AddCPQQuoteLines.QuoteModelWrapper();
        wrap2.lines = quoteLines;
        wrap2.quoteId = qt.Id;
        wrap2.currencyISOcode = 'USD';
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/insertquotelineitems'; 
        req.httpMethod = 'Post';
        req.addHeader('Content-Type', 'application/json');
        req.requestBody = Blob.valueOf(JSON.serialize(wrap2)); 
        RestContext.request = req;
        RestContext.response = res;
        
        AddCPQQuoteLines.ResponseData resWrap = AddCPQQuoteLines.addQLI();
        System.assertEquals('Error', resWrap.status, 'Error');
        try{
            CPQAPIUtils oCPQreader  = new CPQAPIUtils();
            oCPQreader.dynamicGetAllFieldsQuery('Account');
            CPQAPIUtils.ConfigurationModel obj = new CPQAPIUtils.ConfigurationModel();
            System.debug(LoggingLevel.DEBUG, obj);
            oCPQreader.saveQuoteModel(new CPQAPIUtils.QuoteModel());
        }catch(Exception e){System.debug(LoggingLevel.DEBUG,e);}
        Test.stopTest();
    }
}