force-app/main/default/objects/Account/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Consist Source Org name from where the data is migrated from</description>
    <label>Legacy CRM Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legacy_CRM_Instance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Source CRM name from where Contact is created.</description>
    <label>Legacy CRM Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legacy_CRM_Instance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Part_of_Series__c.field-meta.xml
<CustomField>
    <fullName>Part_of_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup store value of series this edition is part of</description>
    <label>Part of Series</label>
    <referenceTo>Series__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Event_Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Invoice_to_be_issued_before_in_Days__c.field-meta.xml
<CustomField>
    <fullName>Invoice_to_be_issued_before_in_Days__c</fullName>
    <description>The field is to be used to drive the invoice start date as per the cut off dates created on the edition. The field will subtract the entered number of days from the Cut off dates and will change the payment plan on contract based on the date on which it gets generated between the Invoicing to Start Date and Cut off Date.</description>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Legacy_CRM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Instance__c</fullName>
    <description>Consist Source Org name from where the data originated (Source CRM)</description>
    <label>Legacy CRM Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legacy_CRM_Instance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Term_Code__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term_Code__c</fullName>
    <description>Payment Term Code for ERP[Oracle] ,It is set on the basis of payment Schedule selected from Edition</description>
    <label>Payment Term Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Series__c.field-meta.xml
<CustomField>
    <fullName>Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Series to which Opportunity&apos;s Edition belongs.</description>
    <label>Series</label>
    <referenceTo>Series__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Payment_Term_Code__c/Payment_Term_Code__c.object-meta.xml
<CustomObject>
    <description>The mapping of the Payment Term codes, Description, payment split% based on Edition</description>
    <label>Payment Term Code</label>
    <nameField>
        <displayFormat>PTC-{000000}</displayFormat>
        <label>Payment Term Code ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Term Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Term_Code__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Payment Term Codes</relationshipLabel>
    <relationshipName>Payment_Term_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Term_Code__c/fields/Payment_Split_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Payment_Split_Percentage__c</fullName>
    <description>Payment Split Percentage</description>
    <label>Payment Split Percentage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Schedule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Term_Code__c/fields/Payment_Term_Code__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term_Code__c</fullName>
    <description>Payment Term Code</description>
    <label>Payment Term Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Series__c/Series__c.object-meta.xml
<CustomObject>
    <description>It defines the Series Information. Each year&apos;s Edition will be tied to a particular Series.</description>
    <label>Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Series__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of Series</description>
    <label>Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Series__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Trigger__c/Trigger__c.object-meta.xml
<CustomObject>
    <label>Trigger</label>
    <nameField>
        <label>Trigger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger__c/fields/After_Update__c.field-meta.xml
<CustomField>
    <fullName>After_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Before_Insert__c.field-meta.xml
<CustomField>
    <fullName>Before_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Execution_Order__c.field-meta.xml
<CustomField>
    <fullName>Execution_Order__c</fullName>
    <label>Execution Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>This trigger runs against which object?</inlineHelpText>
    <label>Object</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <description>Use this format: Param1=Value1;Param2=Value2</description>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Run_for_Recordypes__c.field-meta.xml
<CustomField>
    <fullName>Run_for_Recordypes__c</fullName>
    <label>Run for Recordypes</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Trigger_Name_Unique__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Name_Unique__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Trigger Name Unique</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trigger_Recordtype__c/Trigger_Recordtype__c.object-meta.xml
<CustomObject>
    <label>Trigger Recordtype</label>
    <nameField>
        <label>Recordtype Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Recordtypes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Recordtype__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Enabled for this particular recordtype, but only if the Trigger is also enabled.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Recordtype__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <inlineHelpText>Use this format: Param1=Value1;Param2=Value2</inlineHelpText>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trigger_Recordtype__c/fields/Recordtype_Id__c.field-meta.xml
<CustomField>
    <fullName>Recordtype_Id__c</fullName>
    <inlineHelpText>18 character id of the recordtype</inlineHelpText>
    <label>Recordtype Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Recordtype__c/fields/Trigger__c.field-meta.xml
<CustomField>
    <fullName>Trigger__c</fullName>
    <label>Trigger</label>
    <referenceTo>Trigger__c</referenceTo>
    <relationshipLabel>Trigger Recordtypes</relationshipLabel>
    <relationshipName>Trigger_Recordtypes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OpportunityBillToAccount_Trig_Test.cls
/**
* File:         OpportunityBillToAccount_Trig_Test
* Project:      GAP
* Created Date: 24 Feb 2020
* Created By:   Girikon(Garima Gupta)
* *******************************************************************************************************
* @description : Test Class for TriggerInterface_Opportunity, OpportunityBillToAccount_Trig
*/

@isTest
public with sharing class OpportunityBillToAccount_Trig_Test {
    
    // @description : Setting up all test data
    public static testMethod void test(){
        
        
        //Create Trigger test record 
        Trigger__c trig = new Trigger__c(Name = 'OpportunityBillToAccount_Trig' , Trigger_Name_Unique__c='OpportunityBillToAccount_Trig',Enabled__c=true,Object__c='Opportunity',Run_for_Recordypes__c='All',Description__c='my test',Execution_Order__c=1,Before_Insert__c=true,After_Update__c=true);
        Insert trig;
        
        Trigger_Recordtype__c rt = new Trigger_Recordtype__c(Enabled__c=true,Recordtype_Id__c=trig.Id,Trigger__c=trig.Id,Parameters__c='param=1;param=2');    
        Insert rt;   
        
        //Call account  trigger interface
        TriggerInterface_Opportunity obj = new TriggerInterface_Opportunity();
        
        //Call trigger app handler for insert event
       // string accountOnHoldID = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Opportunity_Account_Unhold').getRecordTypeId();
       // system.debug('accountOnHoldID: '+accountOnHoldID);
        string recTypeId = [Select Id From RecordType Where sObjectType IN ('SBQQ__Quote__c') LIMIT 1].Id;
        system.debug('recTypeId:'+recTypeId);
        TriggerInterfaceHelper.runTrigger('OpportunityBillToAccount_Trig','Opportunity',5, 'bi', recTypeId,null,'All'); 
        
        Account accountObj = TestDataFactoryUtils.createAccount();
        accountObj.Legacy_CRM_Instance__c = 'Penton';
        insert accountObj;
        System.assertNotEquals(null, accountObj, 'Account Name and Billing Address cannot be null');
        
        Contact conObj = TestDataFactoryUtils.createContact(accountObj.Id);
        conObj.Legacy_CRM_Instance__c = 'Penton';
        insert conObj;
        
        APXTConga4__Conga_Template__c congaContractTemplObj = TestDataFactoryUtils.createCongaContractTemplate();
        insert congaContractTemplObj;
        
        APXTConga4__Conga_Template__c congaInvoiceTemplObj = TestDataFactoryUtils.createCongaInvoiceTemplate();
        insert congaInvoiceTemplObj;
        
        APXTConga4__Conga_Template__c congaQuoteTemplObj = TestDataFactoryUtils.createCongaQuoteTemplate();
        insert congaQuoteTemplObj;
        
        APXTConga4__Conga_Template__c congaCreditNoteTemplObj = TestDataFactoryUtils.createCongaCreditNoteTemplate();
        insert congaCreditNoteTemplObj;
        
        // setup the Custom Settings
        TestDataFactory.insertBillingCustomSettings();
        
        blng__LegalEntity__c legalEntityObj = TestDataFactoryUtils.createLegalEntity(congaContractTemplObj.Id, congaInvoiceTemplObj.Id, congaQuoteTemplObj.Id, congaCreditNoteTemplObj.Id);
        insert legalEntityObj;

        Series__c seriesObj = TestDataFactoryUtils.createSeries(legalEntityObj.Id);
        insert seriesObj;
        
        Edition__c editionObj = TestDataFactoryUtils.createEdition(seriesObj.Id, congaCreditNoteTemplObj.Id, congaInvoiceTemplObj.Id);
        editionObj.Part_of_Series__c = seriesObj.id;
        insert editionObj;
                
        Payment_Term_Code__c ptC = new Payment_Term_Code__c(Payment_Term_Code__c='PTC-01',Payment_Split_Percentage__c='25-25-25-25',Edition__c=editionObj.Id);
        insert ptC;
        
        Id standardPricebookId = Test.getStandardPricebookId();

        TestDataFactoryUtils.WrapperOpportunity wrpOpp = new TestDataFactoryUtils.WrapperOpportunity();
        wrpOpp.accountId = accountObj.Id;
        wrpOpp.seriesId = seriesObj.Id;
        wrpOpp.editionId = editionObj.Id;
        wrpOpp.contactId = conObj.Id;

        Opportunity opportunityObj = TestDataFactoryUtils.createOpportunity(wrpOpp);
        insert opportunityObj;
        ////opportunityObj.Invoice_to_be_issued_before_in_Days__c = '90';
        update opportunityObj;
                
    }
}