force-app/main/default/objects/Account/fields/One_Invoice_Per_Contract__c.field-meta.xml
<CustomField>
    <fullName>One_Invoice_Per_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It will control the creation of single Invoice created on opportunity.</description>
    <inlineHelpText>It will control the creation of single Invoice created on opportunity.</inlineHelpText>
    <label>One Invoice Per Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <description>Payment term for Account.</description>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Due on Receipt</fullName>
            </value>
            <value>
                <fullName>Net 15</fullName>
            </value>
            <value>
                <fullName>Net 30</fullName>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/API_Synchronization_Item__c.object-meta.xml
<CustomObject>
    <description>object will contain actual information of sync status of account and contact.</description>
    <label>API Synchronization Item</label>
    <nameField>
        <displayFormat>ASI-{0000}</displayFormat>
        <label>API Synchronization Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Synchronization Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>API Synchronization Items</relationshipLabel>
    <relationshipName>API_Synchronization_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Trigger__c/Trigger__c.object-meta.xml
<CustomObject>
    <label>Trigger</label>
    <nameField>
        <label>Trigger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger__c/fields/After_Update__c.field-meta.xml
<CustomField>
    <fullName>After_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Execution_Order__c.field-meta.xml
<CustomField>
    <fullName>Execution_Order__c</fullName>
    <label>Execution Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>This trigger runs against which object?</inlineHelpText>
    <label>Object</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Run_for_Recordypes__c.field-meta.xml
<CustomField>
    <fullName>Run_for_Recordypes__c</fullName>
    <label>Run for Recordypes</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger__c/fields/Trigger_Name_Unique__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Name_Unique__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Trigger Name Unique</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CreateAPISyncItemsforOpp_Trig_Test.cls
/**
* File      	:   CreateAPISyncItemsforOpp_Trig_Test
* Project       : 	Informa Order Management 
* Created By  	:   Girikon(Ansh)
* Created Date  :   25th Feb 2022
******************************************************************************************************
* @description : Test Class to provide code covrage to classes - CreateAPISyncItemsforOpportunity_Trig
******************************************************************************************************
* Last Modified By :
*/
@istest
private class CreateAPISyncItemsforOpp_Trig_Test {
    @testSetup 
    static void setup() 
    {
        //Create Trigger test record 
        Trigger__c trig = new Trigger__c(Name = 'CreateAPISyncItemsforOpportunity_Trig' , Trigger_Name_Unique__c='CreateAPISyncItemsforOpportunity_Trig',Enabled__c=true,Object__c='Opportunity',Run_for_Recordypes__c='All',Description__c='my test',Execution_Order__c=1,After_Update__c=true);
        Insert trig;

        // Create an account
        Account acc = new Account ();
        acc.Name = 'TESTACC';
        acc.currencyisocode='USD';
        acc.BillingStreet ='street2';
        acc.BillingCity='test';
        acc.BillingCity='Alaska';
        acc.BillingState='tamil nadu';
        acc.BillingCountryCode='IN';
        acc.BillingPostalCode='12342';
        acc.One_Invoice_Per_Contract__c = true;
        acc.Payment_Term__c='Net 10';
        insert acc;
        
        //create an opportunity
        opportunity opp = new opportunity(Name='World of Concrete 2017',AccountId = acc.id,Amount=20.00,CloseDate=System.Today(),StageName='Closed Won',Probability = 100.00);
        insert opp;
    }

    @isTest
    private static void  testAccountAPITrasCreation()
    {
        opportunity opp = [Select Id,StageName from opportunity limit 1];
        opp.StageName = 'Closed Lost';
        update opp;
       
		integer itemCount = Database.countQuery('SELECT count() FROM API_Synchronization_Item__c WHERE Opportunity__c  = \''+opp.Id+'\'');
        System.assertNotEquals(0,itemCount,'API Synchronization Item not Created');

    }
}