force-app/main/default/objects/Account/fields/One_Invoice_Per_Contract__c.field-meta.xml
<CustomField>
    <fullName>One_Invoice_Per_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It will control the creation of single Invoice created on opportunity.</description>
    <inlineHelpText>It will control the creation of single Invoice created on opportunity.</inlineHelpText>
    <label>One Invoice Per Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/One_Invoice_Per_Contract__c.field-meta.xml
<CustomField>
    <fullName>One_Invoice_Per_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It will control the creation of single Invoice created on opportunity.</description>
    <inlineHelpText>It will control the creation of single Invoice created on opportunity.</inlineHelpText>
    <label>One Invoice Per Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <description>Payment Schedule</description>
    <label>Payment Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Schedule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>This field stores the Start date of Edition.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Custom_Payment__c.field-meta.xml
<CustomField>
    <fullName>Custom_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Custom Payment of Opportunity</description>
    <label>Custom Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Default_Edition__c.field-meta.xml
<CustomField>
    <fullName>Default_Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Edition of Opportunity</description>
    <label>Default Edition</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Edition__c.Edition_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_10_Amount__c.field-meta.xml
<CustomField>
    <fullName>Milestone_10_Amount__c</fullName>
    <description>Billing 10 Amount of Opportunity</description>
    <label>Billing 10 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_10_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_10_Delivery_Date__c</fullName>
    <description>Billing 10 Date of Opportunity</description>
    <label>Billing 10 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_11_Amount__c.field-meta.xml
<CustomField>
    <fullName>Milestone_11_Amount__c</fullName>
    <description>Billing 11 Amount of Opportunity</description>
    <label>Billing 11 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_11_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_11_Delivery_Date__c</fullName>
    <description>Billing 11 Date of Opportunity</description>
    <label>Billing 11 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_12_Amount__c.field-meta.xml
<CustomField>
    <fullName>Milestone_12_Amount__c</fullName>
    <description>Billing 12 Amount of Opportunity</description>
    <label>Billing 12 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_12_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_12_Delivery_Date__c</fullName>
    <description>Billing 12 Date of Opportunity</description>
    <label>Billing 12 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_1_Amount__c.field-meta.xml
<CustomField>
    <fullName>Milestone_1_Amount__c</fullName>
    <description>Billing 1 Amount of Opportunity</description>
    <label>Billing 1 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_1_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_1_Delivery_Date__c</fullName>
    <description>Billing 1 Date of Opportunity</description>
    <label>Billing 1 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_2_Amount__c.field-meta.xml
<CustomField>
    <fullName>Milestone_2_Amount__c</fullName>
    <description>Billing 2 Amount of Opportunity</description>
    <label>Billing 2 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_2_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_2_Delivery_Date__c</fullName>
    <description>Billing 2 Date of Opportunity</description>
    <label>Billing 2 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_3_Amount__c.field-meta.xml
<CustomField>
    <fullName>Milestone_3_Amount__c</fullName>
    <description>Billing 3 Amount of Opportunity</description>
    <label>Billing 3 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_3_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_3_Delivery_Date__c</fullName>
    <description>Billing 3 Date of Opportunity</description>
    <label>Billing 3 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_4_Amount__c.field-meta.xml
<CustomField>
    <fullName>Milestone_4_Amount__c</fullName>
    <description>Billing 4 Amount of Opportunity</description>
    <label>Billing 4 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_4_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_4_Delivery_Date__c</fullName>
    <description>Billing 4 Date of Opportunity</description>
    <label>Billing 4 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_5_Amount__c.field-meta.xml
<CustomField>
    <fullName>Milestone_5_Amount__c</fullName>
    <description>Billing 5 Amount of Opportunity</description>
    <label>Billing 5 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_5_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_5_Delivery_Date__c</fullName>
    <description>Billing 5 Date of Opportunity</description>
    <label>Billing 5 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_6_Amount__c.field-meta.xml
<CustomField>
    <fullName>Milestone_6_Amount__c</fullName>
    <description>Billing 6 Amount of Opportunity</description>
    <label>Billing 6 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_6_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_6_Delivery_Date__c</fullName>
    <description>Billing 6 Date of Opportunity</description>
    <label>Billing 6 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_7_Amount__c.field-meta.xml
<CustomField>
    <fullName>Milestone_7_Amount__c</fullName>
    <description>Billing 7 Amount of Opportunity</description>
    <label>Billing 7 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_7_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_7_Delivery_Date__c</fullName>
    <description>Billing 7 Date of Opportunity</description>
    <label>Billing 7 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_8_Amount__c.field-meta.xml
<CustomField>
    <fullName>Milestone_8_Amount__c</fullName>
    <description>Billing 8 Amount of Opportunity</description>
    <label>Billing 8 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_8_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_8_Delivery_Date__c</fullName>
    <description>Billing 8 Date of Opportunity</description>
    <label>Billing 8 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_9_Amount__c.field-meta.xml
<CustomField>
    <fullName>Milestone_9_Amount__c</fullName>
    <description>Billing 9 Amount of Opportunity</description>
    <label>Billing 9 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Milestone_9_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_9_Delivery_Date__c</fullName>
    <description>Billing 9 Date of Opportunity</description>
    <label>Billing 9 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <description>This picklist provides options for all payment schedules available</description>
    <inlineHelpText>This picklist provides options for all payment schedules available</inlineHelpText>
    <label>Payment Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Schedule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Term_Code__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term_Code__c</fullName>
    <description>Payment Term Code for ERP[Oracle] ,It is set on the basis of payment Schedule selected from Edition</description>
    <label>Payment Term Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>First Due date</description>
    <inlineHelpText>First Due date</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_No_of_payment__c.field-meta.xml
<CustomField>
    <fullName>Total_No_of_payment__c</fullName>
    <description>Total No of Payment of Opportunity</description>
    <label>Total No of Payment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Payment_Schedule__c/Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This object is used to stores the payment schedule datas into their respective fields.</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Payment Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Term_Code__c/Payment_Term_Code__c.object-meta.xml
<CustomObject>
    <description>The mapping of the Payment Term codes, Description, payment split% based on Edition</description>
    <label>Payment Term Code</label>
    <nameField>
        <displayFormat>PTC-{000000}</displayFormat>
        <label>Payment Term Code ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Term Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Term_Code__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Payment Term Codes</relationshipLabel>
    <relationshipName>Payment_Term_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Term_Code__c/fields/Payment_Split_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Payment_Split_Percentage__c</fullName>
    <description>Payment Split Percentage</description>
    <label>Payment Split Percentage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Schedule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Term_Code__c/fields/Payment_Term_Code__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term_Code__c</fullName>
    <description>Payment Term Code</description>
    <label>Payment Term Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentSchedule_Cls.cls
/**
* Project:      Greenfield
* Date:         11/13/2019
* Created By:   Prashant Choudhary
* Test Class:   UpdateCustomBillingSchedule_Trig_Test (94%)
* *************************************************************************
* @description :  Class for Lightning component "PaymentSchedule" on Opportunity .
* *************************************************************************
* Modification log :
* 1. Girikon (Ashish)  [11 Feb 2022 (IOM-839)] ERP Payment Term Code and additional Tax details to be sent to OrderHub
*/

public with sharing class PaymentSchedule_Cls {
    /**
    * @description   This method is used get Payment Schedule Options
    * @param  oppId Opportunity Id
    * @return  List of Options
    */
    @AuraEnabled 
    public static list<String> getPaymentPicklistValues(String oppId)
    {
       Set<String> options = new Set<String>();
        //    options.add('None');
       
        Schema.DescribeFieldResult fieldResult = Opportunity.Payment_Schedule__c.getDescribe();
        List<Schema.PicklistEntry> pList = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry p: pList) {
            options.add(p.getLabel());
        }
        /*
        for(Payment_Term_Code__c ptc : [SELECT Id,Payment_Split_Percentage__c FROM Payment_Term_Code__c WHERE Edition__c IN (SELECT Default_Edition__c FROM Opportunity WHERE Id =:oppId) WITH SECURITY_ENFORCED])s
        {
            options.add(ptc.Payment_Split_Percentage__c);
        }*/
        return new List<String>(options);
    }
    /**
    * @description   This method is used get All Opportunity Fileds
    * @param  recordIdget Opportunity Id
    * @return  Opportunity Record
    */
    @AuraEnabled
    public static Opportunity getallDataRecord(String recordIdget){
        List<Opportunity> listOpportunity = [SELECT id ,Custom_Payment__c,Start_Date__c,Payment_Schedule__c,Total_No_of_payment__c,Milestone_1_Delivery_Date__c,Milestone_2_Delivery_Date__c,Milestone_3_Delivery_Date__c,Milestone_4_Delivery_Date__c ,Milestone_5_Delivery_Date__c ,Milestone_6_Delivery_Date__c, Milestone_7_Delivery_Date__c ,  Milestone_8_Delivery_Date__c, Milestone_9_Delivery_Date__c,Milestone_10_Delivery_Date__c ,Milestone_11_Delivery_Date__c ,Milestone_12_Delivery_Date__c, Milestone_1_Amount__c,Milestone_2_Amount__c,Milestone_3_Amount__c,Milestone_4_Amount__c, Milestone_5_Amount__c,Milestone_6_Amount__c,Milestone_7_Amount__c,Milestone_8_Amount__c,Milestone_9_Amount__c,Milestone_10_Amount__c,Milestone_11_Amount__c,Milestone_12_Amount__c, Amount,CurrencyIsoCode, AccountId, Account.One_Invoice_Per_Contract__c, Default_Edition__c, Default_Edition__r.One_Invoice_Per_Contract__c FROM Opportunity WHERE Id =:recordIdget WITH SECURITY_ENFORCED LIMIT 1];
        if(listOpportunity.size() > 0){
            return listOpportunity[0];
        } else {
            return null;
        }
    }
    /**
    * @description   This method is used Save Payment Schedules On Opportunity
    * @param  fields Opportunity fields
    */
    @AuraEnabled
    public static void saveData (Opportunity fields){
        if(fields != null){
            Opportunity opp = new Opportunity();
            opp = fields;
            opp.Payment_Schedule__c = (opp.Payment_Schedule__c  == 'None') ? null : opp.Payment_Schedule__c;
            update fields;
        }
    }    
}