force-app/main/default/objects/Account/fields/One_Invoice_Per_Contract__c.field-meta.xml
<CustomField>
    <fullName>One_Invoice_Per_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It will control the creation of single Invoice created on opportunity.</description>
    <inlineHelpText>It will control the creation of single Invoice created on opportunity.</inlineHelpText>
    <label>One Invoice Per Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Tax_Number__c/Account_Tax_Number__c.object-meta.xml
<CustomObject>
    <description>Tax Registration Numbers for a Customer to be used for Tax validation when customer transacts in a Country.</description>
    <label>Account Tax Number</label>
    <nameField>
        <displayFormat>AT-{00000}</displayFormat>
        <label>Account Tax Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Tax Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Tax_Number__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Tax Registration for the Account</description>
    <inlineHelpText>Tax Registration for the Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Tax Numbers</relationshipLabel>
    <relationshipName>Account_Tax_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Tax_Number__c/fields/Account_Tax_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Tax_Number__c</fullName>
    <description>Account Tax Number Auto number</description>
    <displayFormat>AT-{00000}</displayFormat>
    <inlineHelpText>Account Tax Number Auto number</inlineHelpText>
    <label>Account Tax  Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account_Tax_Number__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Updated</description>
    <inlineHelpText>Updated</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Validated</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Valid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Default_Edition__c.field-meta.xml
<CustomField>
    <fullName>Default_Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup of Edition object.</description>
    <label>Default Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Edition_Status__c.field-meta.xml
<CustomField>
    <fullName>Edition_Status__c</fullName>
    <description>This picklist stores the status of Edition.</description>
    <label>Edition Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Tentative</fullName>
            </value>
            <value>
                <fullName>Cancelled by Finance</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Pending Setup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/fields/One_Invoice_Per_Contract__c.field-meta.xml
<CustomField>
    <fullName>One_Invoice_Per_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It will control the creation of single Invoice created on opportunity.</description>
    <inlineHelpText>It will control the creation of single Invoice created on opportunity.</inlineHelpText>
    <label>One Invoice Per Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <description>Payment Schedule</description>
    <label>Payment Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Schedule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account_Tax_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Tax_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tax Number of Number</description>
    <label>Account Tax Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account_Tax_Number__c.Status__c</field>
            <operation>equals</operation>
            <value>Valid</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account_Tax_Number__c</referenceTo>
    <relationshipLabel>Opportunities (Account Tax Number)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Default_Edition__c.field-meta.xml
<CustomField>
    <fullName>Default_Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Edition of Opportunity</description>
    <label>Default Edition</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Edition__c.Edition_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <description>This picklist provides options for all payment schedules available</description>
    <inlineHelpText>This picklist provides options for all payment schedules available</inlineHelpText>
    <label>Payment Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Schedule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of opportunity.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Customer Contacted</fullName>
            </value>
            <value>
                <fullName>Customer Engaged</fullName>
            </value>
            <value>
                <fullName>Proposal Sent</fullName>
            </value>
            <value>
                <fullName>Revised Proposal Sent</fullName>
            </value>
            <value>
                <fullName>Pending Accounting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Payment</fullName>
            </value>
            <value>
                <fullName>Accounting Rejected</fullName>
            </value>
            <value>
                <fullName>AR Cancel / Re-bill</fullName>
            </value>
            <value>
                <fullName>Booth/Sponsorship Cancellation</fullName>
            </value>
            <value>
                <fullName>Digital / Print Cancellation</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
            <value>
                <fullName>Online Booth Form In Review</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Pending Change</fullName>
            </value>
            <value>
                <fullName>Legacy Lost</fullName>
            </value>
            <value>
                <fullName>Legacy Cancelled</fullName>
            </value>
            <value>
                <fullName>Legacy Won</fullName>
            </value>
            <value>
                <fullName>Opportunity Cancelled</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Amended</fullName>
            </value>
            <value>
                <fullName>Customize</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tax_Registration__c.field-meta.xml
<CustomField>
    <fullName>Tax_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Tax Registration to be used on this Contract for the Bill to Account.</description>
    <inlineHelpText>Tax Jurisdiction Auto number.</inlineHelpText>
    <label>Tax Registration Number</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No valid tax registration is available.</errorMessage>
        <filterItems>
            <field>Account_Tax_Number__c.Status__c</field>
            <operation>equals</operation>
            <value>Valid</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account_Tax_Number__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Order/fields/Account_Tax_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Tax_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Billing Account VAT/TAX Registration Number</description>
    <label>Account Tax Number</label>
    <referenceTo>Account_Tax_Number__c</referenceTo>
    <relationshipLabel>Orders (Account Tax Number)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition of order.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This object is used to stores the payment schedule datas into their respective fields.</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Payment Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/OpportunityAccountTaxNumber_Trig.cls
/**
* File:         OpportunityAccountTaxNumber_Trig
* Project:      GAP
* Created Date: 11/15/2019
* Created By:   Yash Gupta
* Test Class:   OpportunityAccountTaxNumber_Trig_Test
* Coverage:     87%
* *******************************************************************************************************
* @description : Sharing Class to update the account tax number on opportunity.
* *******************************************************************************************************
* History:      Modified By Yash Gupta [11/27/2019], Increase code coverage. Modified By Yash Gupta [1/22/2020], Increase code coverage. Modified By Yash Gupta [1/28/2020]
*/

public with sharing class OpportunityAccountTaxNumber_Trig implements TriggerInterface_Opportunity.Runnable {

    /*
    * @description [Variable Declarations]
    */
    Set<String> setAccountId = new Set<String>();
    Set<String> setDeaultEditionId = new Set<String>();
    Set<Boolean> setIsOneInvAcc = new Set<Boolean>();
    Set<Boolean> setIsOneInvEdition = new Set<Boolean>();
    Map<String,Account_Tax_Number__c> mapAccountTaxNumber = new Map<String,Account_Tax_Number__c>();
    
    /*
    * @description [Call Interface Class to fetch the new list and old map of opportunity]
    * @param TriggerInterface_Opportunity [fetch the trigger new list and old map]
    */
    public void run(TriggerInterface_Opportunity.Trig trig) {
        if(trig.isBefore && trig.isInsert){
            if(trig.newList !=null && trig.oldMap !=null){
                accounttaxnumberupdate(trig.newList,trig.oldMap);
            }
        }
    }
    
    /*
    * @description [this method is used to account tax number on the opportunity]
    * @param lstOpportunity [list of opportunity]
    * @param oldMapOpportunity [Map of opportunity id and opportunity]
    */
    public void accounttaxnumberupdate ( List <Opportunity> lstOpportunity , Map<Id , Opportunity> oldMapOpportunity){
        for(Opportunity opp : lstOpportunity){
            if(opp.AccountId!=Null){
                setAccountId.add(opp.AccountId);
                if(opp.Default_Edition__c!=null){
                    setDeaultEditionId.add(opp.Default_Edition__c);
                }
                
            }
        }
        
        if(setAccountId.size() > 0){
            List<Account_Tax_Number__c> lstAccountTaxNumber = [select Id, Status__c from Account_Tax_Number__c where Account__c IN: setAccountId AND Status__c = 'Valid' WITH SECURITY_ENFORCED ORDER BY LASTMODIFIEDDATE DESC];
            List<Account> lstAccount = [select id,One_Invoice_Per_Contract__c from Account Where Id IN : setAccountId WITH SECURITY_ENFORCED];
            if(lstAccount.size() > 0){setIsOneInvAcc.add(lstAccount.get(0).One_Invoice_Per_Contract__c);}
            if(setDeaultEditionId.size() > 0){
                List<Edition__c> lstEdition = [select id,One_Invoice_Per_Contract__c from Edition__c Where Id IN : setDeaultEditionId AND Edition_Status__c = 'Active' WITH SECURITY_ENFORCED];
                if(lstEdition.size() > 0){setIsOneInvEdition.add(lstEdition.get(0).One_Invoice_Per_Contract__c);}
            }
            
            for(Opportunity opp : lstOpportunity){
                if(lstAccountTaxNumber.size() == 1){
                    opp.Tax_Registration__c = lstAccountTaxNumber.get(0).Id;
                } else if(lstAccountTaxNumber.size() > 1){
                    opp.Tax_Registration__c = Null;
                }
                
                /**
                * @Description: Set Payment Schedule field to 100 on the basis of One Invoice Per Contract checkbox of account and defauld edition as per ticket IML2R-502.
                * Modified By:  Yash Gupta [1/22/2020]
                */
                if(setIsOneInvAcc.contains(true)){
                    opp.Payment_Schedule__c = '100';
                } else if(setIsOneInvEdition.contains(true)){
                    opp.Payment_Schedule__c = '100';
                }
            }
            
        }
    }
}