force-app/main/default/objects/Account/fields/Oracle_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Number__c</fullName>
    <description>Oracle Account Number.</description>
    <inlineHelpText>Oracle Account Number.</inlineHelpText>
    <label>Oracle Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Number__c</fullName>
    <description>SAP Unique Number.</description>
    <inlineHelpText>SAP Unique Number.</inlineHelpText>
    <label>SAP Number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/X3rd_Party_ERP_System__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_ERP_System__c</fullName>
    <description>External 3rd Party System Name</description>
    <label>3rd Party ERP System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X3rd_Party_ERP_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition of order.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ship To Account</description>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Ship To Account)</relationshipLabel>
    <relationshipName>ShippingOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>Payment transactions holds information of payment details coming from Payment Portal via Mulesoft integration.</description>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>PT-{000000}</displayFormat>
        <label>Payment Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/ERP_Reference__c.field-meta.xml
<CustomField>
    <fullName>ERP_Reference__c</fullName>
    <description>ERP Reference number of payment  transaction in 3rd party ERP system SAP/Oracle.</description>
    <label>ERP Reference</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/ERP_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>ERP_Sync_Status__c</fullName>
    <description>ERP Sync Status</description>
    <label>ERP Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sync Required</fullName>
                <default>true</default>
                <label>Sync Required</label>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Source_Payment_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_Payment_ID__c</fullName>
    <description>Source Payment ID</description>
    <label>Source Payment ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvoiceRESTService.cls
/**
* File         :   InvoiceRESTService 
* Project      :   Order & Billing Plateform
* Created Date :   16th Nov 2021
* Created By   :   Girikon(Suresh)
* Test Class   :   InvoiceRestService_Test(100%)
*******************************************************************************************************
@description : Apex rest class to update Invoice fields
*******************************************************************************************************
* Modification log : 
* 1. Girikon (Ashish) [IE-410] 10 Oct 2022 : Update ERP Ref in SAP field incase of SAP ERP 
*/
@RestResource(urlMapping='/Invoice/*')
global with sharing class InvoiceRESTService {
    private Static Final String FILTER_FIELD_API_METANAME = 'Invoice_External_No_Field';
    private Static Final String SYNCED='Synced';
    private static final String ERP_SYNC_STATUS = 'Sync Required';
    /**
* @description  This method is used to update Invoice fields
* @return ResponseData 
*/
    @HttpPatch
    global static ResponseData updateERPRefrenceNumOnInv() 
    {
        ResponseData resWrap = new ResponseData();
        resWrap.status = 'Unknown';
        resWrap.message = 'Invalid Request Data';
        RestRequest req = RestContext.request;
        String requestJSONString = req.requestBody.toString();
        try {
            InvoiceWapper invWrap = (InvoiceWapper)JSON.deserialize(requestJSONString,InvoiceWapper.class);
            Map<Id,Account> accMaptoUpdate = new Map<Id,Account>();
            Map<Id,Payment_Transaction__c> paytransMaptoUpdate = new Map<Id,Payment_Transaction__c>();
            if(String.isNotBlank(invWrap.invoiceNumber))
            {                
                String filterFieldAPI = !Test.isRunningTest()?GlobalConstants.getValue(FILTER_FIELD_API_METANAME):'Name';
                filterFieldAPI = String.isNotBlank(filterFieldAPI)?filterFieldAPI:'Name';
                List<blng__Invoice__c> invList = Database.query('Select Id,Name,ERP_Reference__c,blng__InvoiceStatus__c,blng__Account__c,Ship_To_Account__c,ERP_Sync_Status__c,blng__Order__r.Edition__r.X3rd_Party_ERP_System__c from blng__Invoice__c where '+String.escapeSingleQuotes(filterFieldAPI)+' = \''+String.escapeSingleQuotes(invWrap.invoiceNumber)+'\'');
                
                resWrap.status = 'Error';
                resWrap.message = 'No Invoice found with Invoice Number '+invWrap.invoiceNumber;
                if(!invList.isEmpty() && Schema.sObjectType.blng__Invoice__c.isUpdateable())
                {   
                    blng__Invoice__c inv = new blng__Invoice__c(Id=invList.get(0).Id);
                    inv.ERP_Reference__c = invWrap.erpRefrence;
                    inv.ERP_Sync_Status__c = 'Synced';
                    if(invList.get(0).blng__InvoiceStatus__c != 'Cancelled' && invList.get(0).blng__InvoiceStatus__c != 'Rebilled'){
                        inv.blng__InvoiceStatus__c = 'Posted';
                    }
                    
                    
                    update inv;
                    if(invWrap.erpAccountNumber != null)
                    {   // [IE-410]
                        String erpFieldAPI = String.isNotBlank(invList.get(0).blng__Order__r.Edition__r.X3rd_Party_ERP_System__c) && invList.get(0).blng__Order__r.Edition__r.X3rd_Party_ERP_System__c == 'SAP' ?'SAP_Number__c':'Oracle_Number__c';
                        // Update Sold To Account Oracle number
                        /*if(String.isNotBlank(invList.get(0).blng__Account__c) 
                            && isNotNull(invWrap.erpAccountNumber.soldTo))
                        {                           
                            Account soldAcc = new Account(Id = invList.get(0).blng__Account__c);
                            soldAcc.put(erpFieldAPI,invWrap.erpAccountNumber.soldTo);
                            accMaptoUpdate.put(invList.get(0).Ship_To_Account__c,soldAcc);
                        }*/
                        // Update Ship To Account Oracle number
                        if(String.isNotBlank(invList.get(0).Ship_To_Account__c) 
                            && isNotNull(invWrap.erpAccountNumber.shipTo))
                        {
                            Account shipAcc = new Account(Id = invList.get(0).Ship_To_Account__c);
                            shipAcc.put(erpFieldAPI,invWrap.erpAccountNumber.shipTo);
                            accMaptoUpdate.put(invList.get(0).Ship_To_Account__c,shipAcc);
                        }
                        // Update Bill To Account Oracle number
                        if(String.isNotBlank(invList.get(0).blng__Account__c) 
                            && isNotNull(invWrap.erpAccountNumber.billTo))
                        {
                            Account billAcc = new Account(Id = invList.get(0).blng__Account__c);
                            billAcc.put(erpFieldAPI,invWrap.erpAccountNumber.billTo);
                            accMaptoUpdate.put(invList.get(0).blng__Account__c,billAcc);
                        }
                        
                        if(!accMaptoUpdate.isEmpty() && Schema.sObjectType.Account.isUpdateable()){
                            update accMaptoUpdate.values();
                        }
                    }                    
                    resWrap.status = 'Success';
                    resWrap.message = 'ERP Refrence updated successfully';
                }                
            }

            // If payment tras has ERP Ref [IE-234]
            if(invWrap.payments != null && !invWrap.payments.isEmpty())
            {
                Map<String,String> paymentERPIdMap = new Map<String,String>();
                for(ErpPaymentTras erp : invWrap.payments){
                    paymentERPIdMap.put(erp.paymentId,erp.paymentTransERPRefrence);
                }
                for(Payment_Transaction__c pTrans : [SELECT Id,ERP_Reference__c,Source_Payment_ID__c FROM Payment_Transaction__c WHERE ERP_Sync_Status__c =: ERP_SYNC_STATUS AND Source_Payment_ID__c in:paymentERPIdMap.keySet() WITH SECURITY_ENFORCED])
                {
                    pTrans.ERP_Reference__c = paymentERPIdMap.containsKey(pTrans.Source_Payment_ID__c)?paymentERPIdMap.get(pTrans.Source_Payment_ID__c):null;
                    pTrans.ERP_Sync_Status__c = SYNCED;
                    paytransMaptoUpdate.put(pTrans.Id,pTrans);
                }
                if(!paytransMaptoUpdate.isEmpty() && Schema.sObjectType.Payment_Transaction__c.isUpdateable()){
                    update paytransMaptoUpdate.values();
                }
                resWrap.status = 'Success';
                resWrap.message = 'ERP Refrence updated successfully';
            }

        }catch (Exception e) 
        {
            resWrap.status = 'Error';resWrap.message = e.getMessage();
            system.debug(logginglevel.DEBUG,'Error_Message__c --> '+ resWrap.message +' At Line' + e.getLineNumber()); system.debug(logginglevel.DEBUG,' Trace --> '+ e.getStackTraceString());
        }
        return resWrap;
    }
    /**
    * @description  This method is to Check Null or blank values
    * @param val String value
    * @return Boolean Check  
    */
    private static Boolean isNotNull(String val) 
    {
        return String.isNotBlank(val) && !'null'.equalsIgnoreCase(val);
    }
    /**
    * @description  This Class is to Store Invoice Request Data
    */
    public class InvoiceWapper {
        
        public String invoiceNumber;
        public String erpRefrence;
        public ErpAccountNumber erpAccountNumber;
        public List<ErpPaymentTras> payments;
    }
    /**
    * @description  This Class is to Store ErpAccountNumber Data
    */
    public class ErpAccountNumber {
        public String billTo;
        public String shipTo;
        public String soldTo;
    }
    /**
    * @description  This Class is to Store ErpPaymentTras Data
    */
    public class ErpPaymentTras {
        public String paymentId;
        public String paymentTransERPRefrence;        
    }
    
    
    /**
    * @description  This Class is to return Reponse Data
    */
    global class ResponseData 
    {
        public String status;	        // Success / Error /Unknown
        public String message;	        // 006
    }
    /************************END PONT Deatils**********************
        End point - /services/apexrest/Invoice/
        Method - Patch

    /******************** JSON SAMPLE ******************************
     * 
    ------------- Without  payment Trans [Penton]---------------
    // {"invoiceNumber":"TSINV03301024","erpRefrence":"TSTRN03301024","erpAccountNumber":{"billTo":"69525529","shipTo":"69525530","soldTo":"null"}}

    -------- With payment Trans [payment Portal]-----------------
    //{ "invoiceNumber": "TSINV03301024", "erpRefrence": "TSTRN03301024", "erpAccountNumber": { "billTo": "69525529", "shipTo": "69525530", "soldTo": "null" }, "payments": [ { "paymentId": "txn_AzZl8HSSwHz4E25D", "paymentTransERPRefrence": "002365" } ] }
    */
}