force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object use to create form question along with question type and related to Question Group(Section) and Form Questionnaires(junction object)</description>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Is_Allow_Branching__c.field-meta.xml
<CustomField>
    <fullName>Is_Allow_Branching__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Admin can set question branches</description>
    <label>Is Allow Branching</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/is_Delete__c.field-meta.xml
<CustomField>
    <fullName>is_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when question deleted .</description>
    <inlineHelpText>Checked when question deleted .</inlineHelpText>
    <label>is Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Question label</description>
    <label>Question Label</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Group__c/Question_Group__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object used to store information of form sections.</description>
    <label>Question Group</label>
    <nameField>
        <label>Question Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Group__c/fields/is_Delete__c.field-meta.xml
<CustomField>
    <fullName>is_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when section will be deleted by admin.</description>
    <inlineHelpText>Checked when section will be deleted by admin.</inlineHelpText>
    <label>is Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Option__c/Question_Option__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Store all options of picklist, checkbox and radio button type questions.</description>
    <label>Question Option</label>
    <nameField>
        <label>Question Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Set value for question option</description>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Options</relationshipLabel>
    <relationshipName>Question_Options</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/Question_Questionnaire__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - junction object</description>
    <label>Form Questionnaire</label>
    <nameField>
        <label>Question Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Questionnaire__c/fields/Is_Allow_Branching__c.field-meta.xml
<CustomField>
    <fullName>Is_Allow_Branching__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Admin can allowing  branches for  question</description>
    <label>Is Allow Branching</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/is_Delete__c.field-meta.xml
<CustomField>
    <fullName>is_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox will be checked when Question Questionnaire record  will be deleted.</description>
    <inlineHelpText>Checkbox will be checked when Question Questionnaire record  will be deleted.</inlineHelpText>
    <label>is Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question</description>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipName>Question_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Question_Group__c.field-meta.xml
<CustomField>
    <fullName>Question_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question Group</description>
    <label>Question Group</label>
    <referenceTo>Question_Group__c</referenceTo>
    <relationshipName>Question_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Question_Order__c.field-meta.xml
<CustomField>
    <fullName>Question_Order__c</fullName>
    <description>Set order of the question</description>
    <label>Question Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Questionnaire</description>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipName>Question_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Related_To_Column__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Column__c</fullName>
    <description>Define which question is related to particular column.</description>
    <inlineHelpText>Define which question is related to particular column.</inlineHelpText>
    <label>Related To Column</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object store form details like name, description, language, category and header info.</description>
    <label>Form Template</label>
    <nameField>
        <label>Form Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionnaire_Dynamic_Logic__c/Questionnaire_Dynamic_Logic__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Store question branching dynamic logic.</description>
    <label>Question Branching</label>
    <nameField>
        <displayFormat>DL-{0000}</displayFormat>
        <label>Dynamic Logic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Branching</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionnaire_Dynamic_Logic__c/fields/Question_Group__c.field-meta.xml
<CustomField>
    <fullName>Question_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question Group</description>
    <label>Question Group</label>
    <referenceTo>Question_Group__c</referenceTo>
    <relationshipName>Dynamic_Logic</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Questionnaire_Dynamic_Logic__c/fields/Question_Option__c.field-meta.xml
<CustomField>
    <fullName>Question_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question Option</description>
    <label>Question Option</label>
    <referenceTo>Question_Option__c</referenceTo>
    <relationshipName>Dynamic_Logic</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Questionnaire_Dynamic_Logic__c/fields/Question_Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Question_Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question Questionnaire</description>
    <label>Question Questionnaire</label>
    <referenceTo>Question_Questionnaire__c</referenceTo>
    <relationshipName>Dynamic_Logic</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Questionnaire_Dynamic_Logic__c/fields/Show_Question_Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Show_Question_Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question Questionnaire</description>
    <label>Show Question Questionnaire</label>
    <referenceTo>Question_Questionnaire__c</referenceTo>
    <relationshipName>Dynamic_Logic1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuestionBranchingCtrl.cls
/**
* Created/Modified By    : Girikon(Mukesh)
* Created On             : 14 Sept, 2021
* @description           : Use to create branching question 
* Test Class             : QuestionBranchingCtrl_Test 
* Code Coverage          : 90%

* Modification Log----- 
* Modified by            : Girikon(Mukesh)
**/
public with sharing class QuestionBranchingCtrl {
    /**
     * fetching Question_Questionnaire records 
     * @param  qnaireId    :Quenstionnaire id
     * @param  sectionId   : Question group id
     * @param  questnOrder : Question order
     * @param mainQuesQuetnnaireId: Question Questionnaire id
     * @return             : Question_Questionnaire records
     */
    @AuraEnabled
    public static List<Question_Questionnaire__c>  getAllQuestnQuestnnaire(String qnaireId,
        String sectionId,Integer questnOrder, 
        String mainQuesQuetnnaireId,String colnum) {
        
        List<Id> lstQQuestnniareId = new List<Id>();
        
        List<Questionnaire_Dynamic_Logic__c> lstQuestnnaireDynLogic = [SELECT Id,Question_Questionnaire__c,Show_Question_Questionnaire__c FROM Questionnaire_Dynamic_Logic__c WHERE Question_Group__c =:String.escapeSingleQuotes(sectionId) WITH SECURITY_ENFORCED];
        
        lstQQuestnniareId.add(mainQuesQuetnnaireId);
    
        for(Questionnaire_Dynamic_Logic__c objQDLogic : lstQuestnnaireDynLogic){
            if(objQDLogic.Question_Questionnaire__c != mainQuesQuetnnaireId){
                lstQQuestnniareId.add(objQDLogic.Question_Questionnaire__c);
                lstQQuestnniareId.add(objQDLogic.Show_Question_Questionnaire__c);
            }
        }
    
        questnOrder = QuestionBranchingCtrl.getQuestnQuestnniareOrder(mainQuesQuetnnaireId);
        
        List<Question_Questionnaire__c> lstQQuestnnaire = [SELECT id, Name, Question__c,Question__r.Label__c from Question_Questionnaire__c 
            WHERE Questionnaire__c =:String.escapeSingleQuotes(qnaireId) AND Question_Group__c =:String.escapeSingleQuotes(sectionId) AND Question__c != null AND Is_Allow_Branching__c =false
            AND question_order__c >=:questnOrder AND Related_To_Column__c=:String.escapeSingleQuotes(colnum) AND ID NOT IN :lstQQuestnniareId AND is_Delete__c=false WITH SECURITY_ENFORCED ORDER By question_order__c asc];
                
        return lstQQuestnnaire; 
    }
    
    public static Integer getQuestnQuestnniareOrder(String qQnniareID){
        Integer orderVal;
        if(String.isNotBlank(qQnniareID)){
            List<Question_Questionnaire__c> qqList =  [SELECT question_order__c FROM Question_Questionnaire__c WHERE Id=:String.escapeSingleQuotes(qQnniareID) WITH SECURITY_ENFORCED LIMIT 1];
            if(qqList.size()==0){
                orderVal=0;
            }
            else{
                orderVal = Integer.valueOf(qqList[0].question_order__c);
            }
        }
        return orderVal;
    }

    /**
     * fetching already branching questionnaire record
     * @param  sectionId            Question Grorp Id
     * @param  mainQuesQuetnnaireId Question Questionnaire Id
     * @return                      list of Questinniare dynamic logic record
     */
    @AuraEnabled
    public static List<Questionnaire_Dynamic_Logic__c>  getAlraedyBranching(String sectionId, String mainQuesQuetnnaireId) {                         
        return [SELECT Id,Question_Questionnaire__c,Question_Group__c,Question_Option__c,Show_Question_Questionnaire__c FROM
            Questionnaire_Dynamic_Logic__c WHERE Question_Group__c =:String.escapeSingleQuotes(sectionId) and Question_Questionnaire__c =:String.escapeSingleQuotes(mainQuesQuetnnaireId) WITH SECURITY_ENFORCED];                            
    }
    /**
     * Insert new branching record in questinnaire dynamic logic object.
     * Delete old branching record in questionniare dynamic logic object.
     * @param qnaireId               Questionnaire Id
     * @param sectionId              Question Group section
     * @param mainQuesQuetnnaireId   Question Questionnaire Id
     * @param lstQuestnnaireDynLogic List of Questionnaire Dynamic login object record
     * @param questionnaireOrder     Question Order Number.
     */
    @AuraEnabled
    public static void saveQuestnDynLogic(String qnaireId,String sectionId, String mainQuesQuetnnaireId,List<Questionnaire_Dynamic_Logic__c> lstQuestnnaireDynLogic,Integer questionnaireOrder){
        List<Questionnaire_Dynamic_Logic__c>  lstQDLogic = QuestionBranchingCtrl.getAlraedyBranching(sectionId, mainQuesQuetnnaireId);
        if(lstQuestnnaireDynLogic != null && lstQuestnnaireDynLogic.size()>0){            
            if(!lstQDLogic.isEmpty() && Schema.SObjectType.Questionnaire_Dynamic_Logic__c.isDeletable()){
                Delete lstQDLogic;
            }
            SObjectAccessDecision secDec = Security.stripInaccessible(AccessType.CREATABLE, lstQuestnnaireDynLogic);
            Insert secDec.getRecords();            
        }
    }
}