force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object use to create form question along with question type and related to Question Group(Section) and Form Questionnaires(junction object)</description>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Allow_Attachments__c.field-meta.xml
<CustomField>
    <fullName>Allow_Attachments__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For check, Allow for Attachments</description>
    <inlineHelpText>For check, Allow for Attachments</inlineHelpText>
    <label>Allow_Attachments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Allow_Comment__c.field-meta.xml
<CustomField>
    <fullName>Allow_Comment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Admin allows to user add a comment on the question.</description>
    <label>Allow Comment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>select Question Category type</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FB_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Currency_Symbol__c.field-meta.xml
<CustomField>
    <fullName>Currency_Symbol__c</fullName>
    <description>Admin can set currency on Question</description>
    <label>Currency Symbol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Decimal_value__c.field-meta.xml
<CustomField>
    <fullName>Decimal_value__c</fullName>
    <label>Decimal value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <description>Question Help Text</description>
    <label>Help Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Help_Text_Required__c.field-meta.xml
<CustomField>
    <fullName>Help_Text_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allow admin to enter help text of question when checkbox checked.</description>
    <label>Help Text Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Is_Allow_Branching__c.field-meta.xml
<CustomField>
    <fullName>Is_Allow_Branching__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Admin can set question branches</description>
    <label>Is Allow Branching</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Max_Char_Length__c.field-meta.xml
<CustomField>
    <fullName>Max_Char_Length__c</fullName>
    <description>Admin can specify the max char length of the text associated with that question in a questionnaire.</description>
    <label>Max Char Length</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Metadata__c.field-meta.xml
<CustomField>
    <fullName>Metadata__c</fullName>
    <label>Metadata</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Library__c.field-meta.xml
<CustomField>
    <fullName>Question_Library__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question Library</description>
    <label>Question Library</label>
    <referenceTo>Question_Library__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For check, question is required or not.</description>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Set a Question Type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TextPlain</fullName>
                <label>Plain Text</label>
            </value>
            <value>
                <fullName>RichText</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
                <label>Number/Currency</label>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
                <label>Information/Instruction</label>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
            <value>
                <fullName>Slider</fullName>
            </value>
            <value>
                <fullName>GPS Location</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Header/Footer</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
                <label>Time Picklist</label>
            </value>
            <value>
                <fullName>Textarea</fullName>
            </value>
            <value>
                <fullName>GPSLocate</fullName>
                <isActive>false</isActive>
                <label>GPS Locate</label>
            </value>
            <value>
                <fullName>MultiSelect</fullName>
                <isActive>false</isActive>
                <label>MultiSelect</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/Question_Questionnaire__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - junction object</description>
    <label>Form Questionnaire</label>
    <nameField>
        <label>Question Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Questionnaire__c/fields/Allow_Attachments__c.field-meta.xml
<CustomField>
    <fullName>Allow_Attachments__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allow user to upload attachment.</description>
    <inlineHelpText>Allow user to upload attachment.</inlineHelpText>
    <label>Allow_Attachments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Allow_Comment__c.field-meta.xml
<CustomField>
    <fullName>Allow_Comment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allow user to put comment.</description>
    <inlineHelpText>Allow user to put comment.</inlineHelpText>
    <label>Allow Comment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Allow_Currency__c.field-meta.xml
<CustomField>
    <fullName>Allow_Currency__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Admin can define whether its number or a currency, in case of currency, user should be able to choose the currency symbol.</description>
    <label>Allow Currency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/background_Color__c.field-meta.xml
<CustomField>
    <fullName>background_Color__c</fullName>
    <description>Define the background color of information input .</description>
    <inlineHelpText>Define the background color of information input .</inlineHelpText>
    <label>background_Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Set Question Questionnaire Category</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FB_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Currency_Symbol__c.field-meta.xml
<CustomField>
    <fullName>Currency_Symbol__c</fullName>
    <label>Currency Symbol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Decimal_value__c.field-meta.xml
<CustomField>
    <fullName>Decimal_value__c</fullName>
    <description>Admin can define the number of the decimal to be allowed</description>
    <label>Decimal value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <description>Show the help text of questions.</description>
    <inlineHelpText>Show the help text of questions.</inlineHelpText>
    <label>Help Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Help_Text_Required__c.field-meta.xml
<CustomField>
    <fullName>Help_Text_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allow admin to enter help text of question when checkbox checked.</description>
    <inlineHelpText>Allow admin to enter help text of question when checkbox checked.</inlineHelpText>
    <label>Help Text Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Is_Allow_Branching__c.field-meta.xml
<CustomField>
    <fullName>Is_Allow_Branching__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Admin can allowing  branches for  question</description>
    <label>Is Allow Branching</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/lookup_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>lookup_Object_API_Name__c</fullName>
    <description>Keep the object api name related to question.</description>
    <inlineHelpText>Keep the object api name related to question.</inlineHelpText>
    <label>lookup Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Max_Char_Length__c.field-meta.xml
<CustomField>
    <fullName>Max_Char_Length__c</fullName>
    <label>Max Char Length</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Metadata__c.field-meta.xml
<CustomField>
    <fullName>Metadata__c</fullName>
    <description>admin can define the currency format</description>
    <label>Metadata</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question</description>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipName>Question_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Related_To_Column__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Column__c</fullName>
    <description>Define which question is related to particular column.</description>
    <inlineHelpText>Define which question is related to particular column.</inlineHelpText>
    <label>Related To Column</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set true/false for question is required or not</description>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object store form details like name, description, language, category and header info.</description>
    <label>Form Template</label>
    <nameField>
        <label>Form Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionnaire__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Set questionnaire category type</description>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FB_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/InformationInputCtr.cls
/**
* Created/Modified By    : Girikon(Mukesh)
* Created On             : 14 Sept, 2021
* @description           : Use to create information type question 
* Test Class             : InformationInputCtr_Test 
* Code Coverage          : 100%

* Modification Log----- 
* Modified by            : Girikon(Mukesh)
**/
public with sharing class InformationInputCtr{
    /**
     * Create question and question questionnaire.
     * @param  qnaireId: Questionnaire id.
     * @param  qGroupId: Question group id.
     * @param  question: Question object values.
     * @param  qnaireName : Questionnaire name.
     * @param  qOrder: Order of question.
     * @param  colNumber: column number of question.
     */
    @AuraEnabled
    public static void createQuestnAndQuestnQnaire(String qnaireId,String qGroupId,Question__c question,String qnaireName,String qOrder,String colNumber,String colorCode,String textColor){
        String sQLib = NewCreateTemplateCtr.getDefaultQuestnLibraryId();
        if(Schema.SObjectType.Question__c.Fields.Related_To_Column__c.isCreateable()){
            question.Related_To_Column__c = colNumber;
        }
        
        if(String.isNotBlank( sQLib)){
            if(Schema.SObjectType.Question__c.Fields.Question_Library__c.isCreateable()){
                question.Question_Library__c = sQLib;
            }
            if(Schema.SObjectType.Question__c.Fields.Metadata__c.isCreateable()){
                question.Metadata__c=colorCode;
            }
            if(Schema.SObjectType.Question__c.Fields.Background_Color__c.isCreateable()){
                question.Background_Color__c = textColor;
            }
        } 
        
        qOrder = String.valueOf(FieldInputCtr.countQuestnQuestnnaireRecord(qnaireId, qGroupId));
        if(Schema.SObjectType.Question__c.Fields.Name.isCreateable()){
            question.Name = qOrder;
        }
        if(Schema.SObjectType.Question__c.isCreateable()){
            SObjectAccessDecision sd = Security.stripInaccessible(AccessType.CREATABLE, new List<Question__c>{question}); 
            Insert sd.getRecords();
            question = [SELECT Id,Type__c,Currency_Symbol__c,lookup_Object_API_Name__c,Required__c,Allow_Currency__c,Decimal_value__c,Help_Text__c,Help_Text_Required__c,Category__c,Allow_Attachments__c,Allow_Comment__c,Is_Allow_Branching__c,Max_Char_Length__c,Minimum_Value__c,Maximum_value__c,Step_Size__c,Default_Value__c FROM Question__c WHERE Id=:sd.getRecords()[0].Id WITH SECURITY_ENFORCED];
        }

        Question_Questionnaire__c oQQuesnaire   =   new Question_Questionnaire__c();
        if(Schema.SObjectType.Question_Questionnaire__c.Fields.Metadata__c.isCreateable()){
            oQQuesnaire.Metadata__c=colorCode;
        }
        if(Schema.SObjectType.Question_Questionnaire__c.Fields.Required__c.isCreateable()){
            oQQuesnaire.Required__c=question.Required__c;
        }
        if(Schema.SObjectType.Question_Questionnaire__c.Fields.Allow_Currency__c.isCreateable()){
            oQQuesnaire.Allow_Currency__c =question.Allow_Currency__c;
        }
        if(Schema.SObjectType.Question_Questionnaire__c.Fields.Decimal_value__c.isCreateable()){
            oQQuesnaire.Decimal_value__c =question.Decimal_value__c;
        }
        if(Schema.SObjectType.Question_Questionnaire__c.Fields.Related_To_Column__c.isCreateable()){
            oQQuesnaire.Related_To_Column__c=colNumber;
        }
        if(Schema.SObjectType.Question_Questionnaire__c.Fields.Help_Text__c.isCreateable()){
            oQQuesnaire.Help_Text__c=question.Help_Text__c;
        }
        if(Schema.SObjectType.Question_Questionnaire__c.Fields.Help_Text_Required__c.isCreateable()){
            oQQuesnaire.Help_Text_Required__c=question.Help_Text_Required__c;
        }
        if(Schema.SObjectType.Question_Questionnaire__c.Fields.Category__c.isCreateable()){
            oQQuesnaire.Category__c=question.Category__c;
        }
        if(Schema.SObjectType.Question_Questionnaire__c.Fields.Allow_Attachments__c.isCreateable()){
            oQQuesnaire.Allow_Attachments__c=question.Allow_Attachments__c;
        }
        if(Schema.SObjectType.Question_Questionnaire__c.Fields.Allow_Comment__c.isCreateable()){
            oQQuesnaire.Allow_Comment__c=question.Allow_Comment__c;
        }
        if(Schema.SObjectType.Question_Questionnaire__c.Fields.Questionnaire__c.isCreateable()){
            oQQuesnaire.Questionnaire__c = qnaireId;
        }
        if(Schema.SObjectType.Question_Questionnaire__c.Fields.Name.isCreateable()){
            oQQuesnaire.Name=qnaireName;
        }
        if(Schema.SObjectType.Question_Questionnaire__c.Fields.Question_Group__c.isCreateable()){
            oQQuesnaire.Question_Group__c =qGroupId;
        }
        if(Schema.SObjectType.Question_Questionnaire__c.Fields.Question__c.isCreateable()){
            oQQuesnaire.Question__c=question.id;
        }
        if(Schema.SObjectType.Question_Questionnaire__c.Fields.Question_Order__c.isCreateable()){
            oQQuesnaire.Question_Order__c=Integer.valueOf(qOrder);
        }
        if(Schema.SObjectType.Question_Questionnaire__c.Fields.Max_Char_Length__c.isCreateable()){
            oQQuesnaire.Max_Char_Length__c=(question.Max_Char_Length__c != null?question.Max_Char_Length__c:0);
        }

        if(String.isNotBlank(question.Currency_Symbol__c) && Schema.SObjectType.Question_Questionnaire__c.Fields.Currency_Symbol__c.isCreateable()){
            oQQuesnaire.Currency_Symbol__c=question.Currency_Symbol__c;
        }
        if(Schema.SObjectType.Question_Questionnaire__c.isCreateable()){            
            SObjectAccessDecision sd = Security.stripInaccessible(AccessType.CREATABLE, new List<Question_Questionnaire__c>{oQQuesnaire});
            Insert sd.getRecords();
            FieldInputCtr.sortQuestions(sd.getRecords()[0].Id,qnaireId,qGroupId,colNumber,Integer.valueOf(qOrder));
        }
    }
    /**
     * save edited Question and Question Questionniare record
     * @param  oQues: Question object values.
     * @param  qnaireId: Questionnaire id.
     * @param  sectionId: Question group(Section) Id.
     */
    @AuraEnabled
    public static void saveEditQuesRecord(Question__c oQues,String qnaireId,String sectionId) {
        if (oQues != null) 
        {
            if(oQues.Help_Text_Required__c==false && Schema.SObjectType.Question__c.Fields.Help_Text__c.isUpdateable()){
                oQues.Help_Text__c='';
            }
            if(Schema.SObjectType.Question__c.isUpdateable()){
                Update Security.stripInaccessible(AccessType.UPDATABLE, new List<Question__c>{oQues}).getRecords();                
            }
            
            List<Question_Questionnaire__c> lstQQnnaire = [Select Id,Allow_Attachments__c,Allow_Comment__c,Help_Text_Required__c,Help_Text__c,Category__c from Question_Questionnaire__c where Question__c=:oQues.id and Questionnaire__c=:String.escapeSingleQuotes(qnaireId) and Question_Group__c=:String.escapeSingleQuotes(sectionId) WITH SECURITY_ENFORCED];
            
            if(!lstQQnnaire.isEmpty())
            {
                if(Schema.SObjectType.Question_Questionnaire__c.Fields.Allow_Attachments__c.isUpdateable()){
                    lstQQnnaire[0].Allow_Attachments__c=oQues.Allow_Attachments__c;
                }
                if(Schema.SObjectType.Question_Questionnaire__c.Fields.Allow_Comment__c.isUpdateable()){
                    lstQQnnaire[0].Allow_Comment__c=oQues.Allow_Comment__c;
                }
                if(Schema.SObjectType.Question_Questionnaire__c.Fields.Help_Text_Required__c.isUpdateable()){
                    lstQQnnaire[0].Help_Text_Required__c=oQues.Help_Text_Required__c;
                }
                if(Schema.SObjectType.Question_Questionnaire__c.Fields.Help_Text__c.isUpdateable()){
                    lstQQnnaire[0].Help_Text__c='';
                }
                if(Schema.SObjectType.Question_Questionnaire__c.Fields.Required__c.isUpdateable()){
                    lstQQnnaire[0].Required__c=oQues.Required__c;
                }
                
                if(oQues.Help_Text_Required__c==true && Schema.SObjectType.Question_Questionnaire__c.Fields.Help_Text__c.isUpdateable()){lstQQnnaire[0].Help_Text__c=oQues.Help_Text__c;}
                if(String.isNotBlank(oQues.Currency_Symbol__c) && Schema.SObjectType.Question_Questionnaire__c.Fields.Currency_Symbol__c.isUpdateable()){lstQQnnaire[0].Currency_Symbol__c=oQues.Currency_Symbol__c;}
                if(Schema.SObjectType.Question_Questionnaire__c.Fields.Decimal_value__c.isUpdateable()){
                    lstQQnnaire[0].Decimal_value__c =oQues.Decimal_value__c;
                }
                if(Schema.SObjectType.Question_Questionnaire__c.Fields.Allow_Currency__c.isUpdateable()){
                    lstQQnnaire[0].Allow_Currency__c =oQues.Allow_Currency__c;
                }
                if(Schema.SObjectType.Question_Questionnaire__c.Fields.Max_Char_Length__c.isUpdateable()){
                    lstQQnnaire[0].Max_Char_Length__c =(oQues.Max_Char_Length__c != null?oQues.Max_Char_Length__c:0);
                }
                if(Schema.SObjectType.Question_Questionnaire__c.Fields.Category__c.isUpdateable()){
                    lstQQnnaire[0].Category__c=oQues.Category__c;
                }
                if(Schema.SObjectType.Question_Questionnaire__c.isUpdateable()){
                    Update Security.stripInaccessible(AccessType.UPDATABLE, lstQQnnaire).getRecords();
                }
            }
        } 
    }
    
    /**
     * fetch Question Currency Symbols picklist value
     * @return : list of Question Currency sysmbol.
     */
    @AuraEnabled
    public static List<String> getQueCurrencySymbol(){
        List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = Question__c.Currency_Symbol__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }
        return options;
    }
}