force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object use to create form question along with question type and related to Question Group(Section) and Form Questionnaires(junction object)</description>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Allow_Attachments__c.field-meta.xml
<CustomField>
    <fullName>Allow_Attachments__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For check, Allow for Attachments</description>
    <inlineHelpText>For check, Allow for Attachments</inlineHelpText>
    <label>Allow_Attachments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Allow_Comment__c.field-meta.xml
<CustomField>
    <fullName>Allow_Comment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Admin allows to user add a comment on the question.</description>
    <label>Allow Comment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>select Question Category type</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FB_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <description>Question Help Text</description>
    <label>Help Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Help_Text_Required__c.field-meta.xml
<CustomField>
    <fullName>Help_Text_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allow admin to enter help text of question when checkbox checked.</description>
    <label>Help Text Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Question label</description>
    <label>Question Label</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Library__c.field-meta.xml
<CustomField>
    <fullName>Question_Library__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question Library</description>
    <label>Question Library</label>
    <referenceTo>Question_Library__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For check, question is required or not.</description>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Set a Question Type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TextPlain</fullName>
                <label>Plain Text</label>
            </value>
            <value>
                <fullName>RichText</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
                <label>Number/Currency</label>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
                <label>Information/Instruction</label>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
            <value>
                <fullName>Slider</fullName>
            </value>
            <value>
                <fullName>GPS Location</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Header/Footer</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
                <label>Time Picklist</label>
            </value>
            <value>
                <fullName>Textarea</fullName>
            </value>
            <value>
                <fullName>GPSLocate</fullName>
                <isActive>false</isActive>
                <label>GPS Locate</label>
            </value>
            <value>
                <fullName>MultiSelect</fullName>
                <isActive>false</isActive>
                <label>MultiSelect</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Library__c/Question_Library__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It store the questions of forms for cloning</description>
    <label>Question Library</label>
    <nameField>
        <label>Question Lib Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Library__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Question library Description</description>
    <inlineHelpText>Question library Description</inlineHelpText>
    <label>Description</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Library__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Question library name</description>
    <inlineHelpText>Question library name</inlineHelpText>
    <label>Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_Option__c/Question_Option__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Store all options of picklist, checkbox and radio button type questions.</description>
    <label>Question Option</label>
    <nameField>
        <label>Question Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Option__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Lookup with Question</description>
    <label>Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Set value for question option</description>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Options</relationshipLabel>
    <relationshipName>Question_Options</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/Question_Questionnaire__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - junction object</description>
    <label>Form Questionnaire</label>
    <nameField>
        <label>Question Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Questionnaire__c/fields/Allow_Attachments__c.field-meta.xml
<CustomField>
    <fullName>Allow_Attachments__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allow user to upload attachment.</description>
    <inlineHelpText>Allow user to upload attachment.</inlineHelpText>
    <label>Allow_Attachments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Allow_Comment__c.field-meta.xml
<CustomField>
    <fullName>Allow_Comment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allow user to put comment.</description>
    <inlineHelpText>Allow user to put comment.</inlineHelpText>
    <label>Allow Comment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Set Question Questionnaire Category</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FB_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <description>Show the help text of questions.</description>
    <inlineHelpText>Show the help text of questions.</inlineHelpText>
    <label>Help Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Help_Text_Required__c.field-meta.xml
<CustomField>
    <fullName>Help_Text_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allow admin to enter help text of question when checkbox checked.</description>
    <inlineHelpText>Allow admin to enter help text of question when checkbox checked.</inlineHelpText>
    <label>Help Text Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question</description>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipName>Question_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Question_Group__c.field-meta.xml
<CustomField>
    <fullName>Question_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question Group</description>
    <label>Question Group</label>
    <referenceTo>Question_Group__c</referenceTo>
    <relationshipName>Question_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Questionnaire</description>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipName>Question_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set true/false for question is required or not</description>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object store form details like name, description, language, category and header info.</description>
    <label>Form Template</label>
    <nameField>
        <label>Form Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionnaire__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Set questionnaire category type</description>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FB_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Questionnaire__c/fields/Community_URL__c.field-meta.xml
<CustomField>
    <fullName>Community_URL__c</fullName>
    <label>Community URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Questionnaire__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Questionnaire information</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Questionnaire__c/fields/NetworkId__c.field-meta.xml
<CustomField>
    <fullName>NetworkId__c</fullName>
    <label>NetworkId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Questionnaire_Dynamic_Logic__c/Questionnaire_Dynamic_Logic__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Store question branching dynamic logic.</description>
    <label>Question Branching</label>
    <nameField>
        <displayFormat>DL-{0000}</displayFormat>
        <label>Dynamic Logic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Branching</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionnaire_Dynamic_Logic__c/fields/Question_Option__c.field-meta.xml
<CustomField>
    <fullName>Question_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question Option</description>
    <label>Question Option</label>
    <referenceTo>Question_Option__c</referenceTo>
    <relationshipName>Dynamic_Logic</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ListTemplateCtrl_Test.cls
/**
* 
*/
@isTest
public class ListTemplateCtrl_Test {
    static testMethod void createQniareTestMethod(){
        
        ListTemplateCtrl.getCommunities();
        // Create  Questionnaire record        
        Questionnaire__c oQnaireRecord = new Questionnaire__c();
        oQnaireRecord .Name='Test Template 1';
        oQnaireRecord .Category__c='Manual';
        oQnaireRecord .Description__c='Template 1';
        oQnaireRecord.NetworkId__c='testid';
        oQnaireRecord.Community_URL__c=URL.getSalesforceBaseUrl().toExternalForm();
        insert oQnaireRecord;
        ListTemplateCtrl.updateQnaire(new Questionnaire__c[]{oQnaireRecord});
        ListTemplateCtrl.getGenericObjectRecord('Questionnaire__c','Id,Name,Category__c,NetworkId__c,Description__c,Community_URL__c',2,false,false,0,'Healthcare','test','Name','ASC');
        
        System.assertNotEquals(oQnaireRecord,null);
        List<Questionnaire__c> lstQnaire=[Select Id,Name From Questionnaire__c Where Id=:oQnaireRecord.id];
        System.assertEquals(lstQnaire.size(),1); 
        
        //Create Question Library
        Question_Library__c oQL= new Question_Library__c(Name='Global Default',Name__c='Global Default');
        insert oQL;
        
        //Create Question Record 
        Question__c oQue = new Question__c(Name='Test',Help_Text_Required__c=true, Name__c='Test 1', Help_Text__c='Test Help Text', Label__c='Question 1', 
                                           Question_Library__c=oQL.id, Required__c=true, Type__c='TextPlain',Allow_Comment__c=true,Allow_Attachments__c=true);
        insert oQue;
        List<Question__c> lstQutn = [Select id,Type__c from Question__c where id=:oQue.id];
        System.assertEquals(oQue.Type__c,lstQutn[0].Type__c);
        
        // Create Question Option
        Question_Option__c qstnOption=new Question_Option__c();
        qstnOption.Name='A';
        qstnOption.Question__c=oQue.id;
        qstnOption.Name__c='A';
        insert qstnOption;
        List<Question_Option__c> lstQutnOptn = [Select id,Name from Question_Option__c where id=:qstnOption.id];
        System.assertEquals(lstQutnOptn.size(),1);
        //Create Question Group record
        
        Question_Group__c oQG = new Question_Group__c(Name='Test Group');
        insert oQG;
        List<Question_Group__c> lstQuGroup = [Select id,Name from Question_Group__c where id=:oQG.id];
        System.assertEquals(oQG.Name,lstQuGroup[0].Name);
        
        //Create Question Questionnaire Record
        Question_Questionnaire__c oQQuesnaire= new Question_Questionnaire__c(Allow_Attachments__c=oQue.Allow_Attachments__c,Allow_Comment__c=oQue.Allow_Comment__c,
                                                                             Questionnaire__c = oQnaireRecord.id,Is_Allow_Branching__c=true,Name=oQnaireRecord.Name,Question_Group__c =oQG.id,Question__c=oQue.id,Question_Order__c=1);
        insert oQQuesnaire;
        
        List<Question_Questionnaire__c> lstQuestionQnnaire = [Select id,Question__c from Question_Questionnaire__c where id=:oQQuesnaire.id];
        System.assertEquals(oQQuesnaire.Question__c,lstQuestionQnnaire[0].Question__c);
        
        //Create Question Questionnaire Record Without question id
        Question_Questionnaire__c oQQuesnaireWithOutQstn= new Question_Questionnaire__c(Allow_Attachments__c=oQue.Allow_Attachments__c,Allow_Comment__c=oQue.Allow_Comment__c,
                                                                                        Questionnaire__c = oQnaireRecord.id,Name=oQnaireRecord.Name,Question_Group__c =oQG.id,Is_Allow_Branching__c=true,Question_Order__c=1);
        insert oQQuesnaireWithOutQstn;
        
        List<Question_Questionnaire__c> lstQuestionQnnaireWithOutQsrn = [Select id,Question__c from Question_Questionnaire__c where id=:oQQuesnaireWithOutQstn.id];
        System.assertEquals(lstQuestionQnnaireWithOutQsrn[0].Question__c,null);
        System.assertEquals(lstQuestionQnnaireWithOutQsrn.size() ,1);
        
        //Create Questionnaire dynamic logic Record
        Questionnaire_Dynamic_Logic__c QuestnDynLogicInsert = new Questionnaire_Dynamic_Logic__c(Question_Questionnaire__c=oQQuesnaire.id,
                                                                                                 Question_Group__c =oQG.id,
                                                                                                 Question_Option__c=qstnOption.id,
                                                                                                 Show_Question_Questionnaire__c=oQQuesnaireWithOutQstn.id);
        insert QuestnDynLogicInsert;
        Test.startTest();
        ListTemplateCtrl.getQuenaireLanguage();
        List<String> lstCategory = ListTemplateCtrl.getQuenaireCategory();
        System.assert(lstCategory.size()>0,'exist Categories');
        Questionnaire__c oQnaire = new Questionnaire__c(NetworkId__c='testasjdas',Name='Template 1',Community_URL__c=URL.getSalesforceBaseUrl().toExternalForm(),Category__c='Manual',Description__c='Template 1');
        String questnId = ListTemplateCtrl.createQnaire(oQnaire,'sectionName','1');
        System.assert(questnId != null ,'exist id');
        List<Questionnaire__c> lstQQnaire = [SELECT id FROM Questionnaire__c WHERE id=:String.escapeSingleQuotes(questnId) WITH SECURITY_ENFORCED];
        System.assertNotEquals(lstQQnaire,null);
        System.assertEquals(questnId,lstQQnaire[0].id); 
        Questionnaire__c qnaire=ListTemplateCtrl.getQnaireRecord(oQnaireRecord.id);
        System.assertNotEquals(qnaire,null);
        ListTemplateCtrl.saveQnaireCloneRecord(oQnaireRecord);            
        Integer countOfQuestnnaire = [Select count() from Questionnaire__c];
        
        ListTemplateCtrl.getAllApps();
        new ListTemplateCtrl.Wrapper_Class('label','value','networkId');
        System.assertNotEquals(countOfQuestnnaire,0);            
        Test.stopTest();
    }
}