force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object use to create form question along with question type and related to Question Group(Section) and Form Questionnaires(junction object)</description>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Is_Allow_Branching__c.field-meta.xml
<CustomField>
    <fullName>Is_Allow_Branching__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Admin can set question branches</description>
    <label>Is Allow Branching</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/is_Delete__c.field-meta.xml
<CustomField>
    <fullName>is_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when question deleted .</description>
    <inlineHelpText>Checked when question deleted .</inlineHelpText>
    <label>is Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Group__c/Question_Group__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object used to store information of form sections.</description>
    <label>Question Group</label>
    <nameField>
        <label>Question Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Group__c/fields/is_Delete__c.field-meta.xml
<CustomField>
    <fullName>is_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when section will be deleted by admin.</description>
    <inlineHelpText>Checked when section will be deleted by admin.</inlineHelpText>
    <label>is Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Group__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Set Question Group order</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question_Option__c/Question_Option__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Store all options of picklist, checkbox and radio button type questions.</description>
    <label>Question Option</label>
    <nameField>
        <label>Question Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Set value for question option</description>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Options</relationshipLabel>
    <relationshipName>Question_Options</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/Question_Questionnaire__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - junction object</description>
    <label>Form Questionnaire</label>
    <nameField>
        <label>Question Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Questionnaire__c/fields/Is_Allow_Branching__c.field-meta.xml
<CustomField>
    <fullName>Is_Allow_Branching__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Admin can allowing  branches for  question</description>
    <label>Is Allow Branching</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/is_Delete__c.field-meta.xml
<CustomField>
    <fullName>is_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox will be checked when Question Questionnaire record  will be deleted.</description>
    <inlineHelpText>Checkbox will be checked when Question Questionnaire record  will be deleted.</inlineHelpText>
    <label>is Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question</description>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipName>Question_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Question_Group__c.field-meta.xml
<CustomField>
    <fullName>Question_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question Group</description>
    <label>Question Group</label>
    <referenceTo>Question_Group__c</referenceTo>
    <relationshipName>Question_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Question_Order__c.field-meta.xml
<CustomField>
    <fullName>Question_Order__c</fullName>
    <description>Set order of the question</description>
    <label>Question Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Questionnaire</description>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipName>Question_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Questionnaire__c/fields/Related_To_Column__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Column__c</fullName>
    <description>Define which question is related to particular column.</description>
    <inlineHelpText>Define which question is related to particular column.</inlineHelpText>
    <label>Related To Column</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object store form details like name, description, language, category and header info.</description>
    <label>Form Template</label>
    <nameField>
        <label>Form Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionnaire_Dynamic_Logic__c/Questionnaire_Dynamic_Logic__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Store question branching dynamic logic.</description>
    <label>Question Branching</label>
    <nameField>
        <displayFormat>DL-{0000}</displayFormat>
        <label>Dynamic Logic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Branching</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionnaire_Dynamic_Logic__c/fields/Question_Group__c.field-meta.xml
<CustomField>
    <fullName>Question_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question Group</description>
    <label>Question Group</label>
    <referenceTo>Question_Group__c</referenceTo>
    <relationshipName>Dynamic_Logic</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Questionnaire_Dynamic_Logic__c/fields/Question_Option__c.field-meta.xml
<CustomField>
    <fullName>Question_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question Option</description>
    <label>Question Option</label>
    <referenceTo>Question_Option__c</referenceTo>
    <relationshipName>Dynamic_Logic</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Questionnaire_Dynamic_Logic__c/fields/Question_Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Question_Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question Questionnaire</description>
    <label>Question Questionnaire</label>
    <referenceTo>Question_Questionnaire__c</referenceTo>
    <relationshipName>Dynamic_Logic</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Questionnaire_Dynamic_Logic__c/fields/Show_Question_Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Show_Question_Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Question Questionnaire</description>
    <label>Show Question Questionnaire</label>
    <referenceTo>Question_Questionnaire__c</referenceTo>
    <relationshipName>Dynamic_Logic1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddQuestionInSectionCtr.cls
/**
 * TestClass: AddQuestionInSectionCtrTest
 * Code Coverage : 98%
 */
public with sharing class AddQuestionInSectionCtr{
    /*** 
     * Save questions in saction 
	***/
    @AuraEnabled 
    public static boolean saveQstnInSection(String qquaireId,String selectedSectionId,String targetCol){
        boolean isUpdated=false;
        
        //Check isUpdateable for each objects and fields
                
        if(String.isNotBlank(qquaireId) && String.isNotBlank(selectedSectionId)){
            Question_Questionnaire__c qstnQuaire=[SELECT Id,Question__c, Question_Group__c,Is_Allow_Branching__c,Question_Order__c FROM Question_Questionnaire__c WHERE Id=:String.escapeSingleQuotes(qquaireId) WITH SECURITY_ENFORCED LIMIT 1];
            // When no question branching is available            
            Integer order=[SELECT count() from Question_Questionnaire__c WHERE Question_Group__c=:String.escapeSingleQuotes(selectedSectionId) WITH SECURITY_ENFORCED];
            if(qstnQuaire!=null && qstnQuaire.Is_Allow_Branching__c==false && qstnQuaire.Question_Group__c!=selectedSectionId){
                
                if(Schema.SObjectType.Question_Questionnaire__c.fields.Related_To_Column__c.isUpdateable()){
                    qstnQuaire.Related_To_Column__c=targetCol;
                }
                if(Schema.SObjectType.Question_Questionnaire__c.fields.Question_Group__c.isUpdateable()){
                    qstnQuaire.Question_Group__c=selectedSectionId;
                }
                if(Schema.SObjectType.Question_Questionnaire__c.fields.Question_Order__c.isUpdateable()){
                    qstnQuaire.Question_Order__c=order+1;
                }
                if(Schema.SObjectType.Question_Questionnaire__c.isUpdateable()){
                    update qstnQuaire;
                }

                Question__c ques = [SELECT Id FROM Question__C WHERE Id=:String.escapeSingleQuotes(qstnQuaire.Question__c) WITH SECURITY_ENFORCED LIMIT 1];
                
                if(Schema.SObjectType.Question__c.fields.Related_To_Column__c.isUpdateable()){
                    ques.Related_To_Column__c = targetCol;
                }
                if(Schema.SObjectType.Question__c.isUpdateable()){
                    Update ques;
                }
                isUpdated=true;            
            }
            else if(qstnQuaire!=null && qstnQuaire.Question_Group__c!=selectedSectionId){
                // When question branching is available                                  
                List<String> questionIdList = new List<string>();
                List<Question__c> questionToUpdate = new List<Question__c>();

                List<String> lstChildQstnQuariIds=new List<String>();
                List<Questionnaire_Dynamic_Logic__c> lstQuestnnaireDynLogic = [SELECT Id,Question_Questionnaire__c,Question_Group__c,
                Question_Option__c,Show_Question_Questionnaire__c FROM
                Questionnaire_Dynamic_Logic__c WHERE Question_Questionnaire__c =:String.escapeSingleQuotes(qquaireId) WITH SECURITY_ENFORCED];
                for(Questionnaire_Dynamic_Logic__c qstnDynlgc:lstQuestnnaireDynLogic){
                    if(Schema.SObjectType.Questionnaire_Dynamic_Logic__c.fields.Question_Group__c.isUpdateable()){
                        qstnDynlgc.Question_Group__c=selectedSectionId;
                    }                        
                    lstChildQstnQuariIds.add(qstnDynlgc.Show_Question_Questionnaire__c);
                }
                
                List<Question_Questionnaire__c> lstQstnQuaire=[SELECT Id,Question__c,Question_Group__c,
                Is_Allow_Branching__c,Question_Order__c From Question_Questionnaire__c
                WHERE Id IN:lstChildQstnQuariIds WITH SECURITY_ENFORCED];
                Integer i=2;
                for(Question_Questionnaire__c childQstnQuaire:lstQstnQuaire){
                    if(Schema.SObjectType.Question_Questionnaire__c.fields.Question_Group__c.isUpdateable()){
                        childQstnQuaire.Question_Group__c=selectedSectionId;
                    }
                    if(Schema.SObjectType.Question_Questionnaire__c.fields.Question_Order__c.isUpdateable()){
                        childQstnQuaire.Question_Order__c=order+i;
                    }
                    i=i+1;
                    questionIdList.add(childQstnQuaire.Question__c);
                }
                
                if(Schema.SObjectType.Question_Questionnaire__c.fields.Related_To_Column__c.isUpdateable()){
                    qstnQuaire.Related_To_Column__c=targetCol;
                }
                
                if(Schema.SObjectType.Question_Questionnaire__c.fields.Question_Group__c.isUpdateable()){
                    qstnQuaire.Question_Group__c=selectedSectionId;
                }
                if(Schema.SObjectType.Questionnaire_Dynamic_Logic__c.isUpdateable()){
                    update lstQuestnnaireDynLogic;
                }
                
                // Update order in parent
                if(Schema.SObjectType.Question_Questionnaire__c.fields.Question_Order__c.isUpdateable()){
                    qstnQuaire.Question_Order__c=order+1;
                }
                if(Schema.SObjectType.Question_Questionnaire__c.isUpdateable()){
                    update qstnQuaire;
                }
                questionIdList.add(qstnQuaire.Question__c);
                List<Question__c> ques2List = [SELECT Id FROM Question__c WHERE Id IN:questionIdList WITH SECURITY_ENFORCED];
                for(Question__c ques2 : ques2List)
                {
                    if(Schema.SObjectType.Question__c.Fields.Related_To_Column__c.isUpdateable()){
                        ques2.Related_To_Column__c = targetCol;
                    }
                    questionToUpdate.add(ques2);
                }                    
                if(Schema.SObjectType.Question__c.isUpdateable()){
                    update questionToUpdate;
                }
                
                // Update question order in childs                             
                if(Schema.SObjectType.Question_Questionnaire__c.isUpdateable()){
                    update lstQstnQuaire;
                }                           
                isUpdated=true;                    
            
            }        
        }
        return isUpdated;
    }
    
    @AuraEnabled 
    public static List<Question_Group__c> getQuestionGroups(String qnaireId){
        List<String> lstQstnGrpIds=new List<String>();
        List<Question_Group__c> lstQsthGroup = new List<Question_Group__c>();
        List<sobject> lstQQ = Database.query('SELECT Question_Group__c from Question_Questionnaire__c WHERE Questionnaire__c=\''+String.escapeSingleQuotes(qnaireId)+'\' AND is_delete__c=false WITH SECURITY_ENFORCED');
        for(sobject qq:lstQQ){
            lstQstnGrpIds.add(String.valueOf(qq.get('Question_Group__c')));
        }
        return [SELECT Id,Name,Sort_Order__c FROM Question_Group__c WHERE Id IN:lstQstnGrpIds WITH SECURITY_ENFORCED ORDER BY Sort_Order__c ASC];        
    }
    
    @AuraEnabled 
    public static List<Question_Group__c> updateQuestionGroupsSortingOrder(List<Question_Group__c> lstUpdatedQstnGrp){
        if(Schema.SObjectType.Question_Group__c.isUpdateable()){
            update lstUpdatedQstnGrp;
        }        
        return lstUpdatedQstnGrp;
    }
}