force-app/main/default/objects/API_Detail__mdt/API_Detail__mdt.object-meta.xml
<CustomObject>
    <description>API Detail holds information about third party API end points like Onesource, Orderhub etc.</description>
    <label>API Detail</label>
    <pluralLabel>API Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/API_Detail__mdt/fields/API_End_Point__c.field-meta.xml
<CustomField>
    <fullName>API_End_Point__c</fullName>
    <description>API End Point</description>
    <label>API End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Detail__mdt/fields/API_Method__c.field-meta.xml
<CustomField>
    <fullName>API_Method__c</fullName>
    <description>API Method type.</description>
    <label>API Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Detail__mdt/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <description>Callout request header parameter .</description>
    <label>Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/API_Synchronization_Item__c.object-meta.xml
<CustomObject>
    <description>object will contain actual information of sync status of account and contact.</description>
    <label>API Synchronization Item</label>
    <nameField>
        <displayFormat>ASI-{0000}</displayFormat>
        <label>API Synchronization Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Synchronization Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Synchronization_Item__c/fields/API_Call_Type__c.field-meta.xml
<CustomField>
    <fullName>API_Call_Type__c</fullName>
    <description>Type of action which will API callout perform in the external system.</description>
    <label>API Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Credit_Note__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Credit Note</description>
    <label>Credit Note</label>
    <referenceTo>blng__CreditNote__c</referenceTo>
    <relationshipLabel>API Synchronization Items</relationshipLabel>
    <relationshipName>API_Synchronization_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>API Synchronization Items</relationshipLabel>
    <relationshipName>API_Synchronization_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Invoice</description>
    <label>Invoice</label>
    <referenceTo>blng__Invoice__c</referenceTo>
    <relationshipLabel>API Synchronization Items</relationshipLabel>
    <relationshipName>API_Synchronization_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>API Synchronization Items</relationshipLabel>
    <relationshipName>API_Synchronization_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <description>Callout Request Body</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <description>Callout Response Body</description>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>API Synchronization Item Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Re-Queued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>API Synchronization Item Type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tax</fullName>
            </value>
            <value>
                <fullName>Post Documents</fullName>
            </value>
            <value>
                <fullName>Accounting Credit Status</fullName>
            </value>
            <value>
                <fullName>Amendment Request Approved/Rejected</fullName>
            </value>
            <value>
                <fullName>Opportunity Rejected</fullName>
            </value>
            <value>
                <fullName>Opportunity Closed Lost</fullName>
            </value>
            <value>
                <fullName>Amendment Completed</fullName>
            </value>
            <value>
                <fullName>Re-Print for PO number change</fullName>
            </value>
            <value>
                <fullName>Re-Print for Bill To Account Details Change</fullName>
            </value>
            <value>
                <fullName>Re-Print for Contact Details Change</fullName>
            </value>
            <value>
                <fullName>Amended Data Sync</fullName>
                <label>Amended Data Sync - CRM</label>
            </value>
            <value>
                <fullName>Re-Print for Ship To Account Details Change</fullName>
            </value>
            <value>
                <fullName>Re-Print for Account Details Change</fullName>
            </value>
            <value>
                <fullName>Account ERP Number Update</fullName>
            </value>
            <value>
                <fullName>Post Payment Transactions</fullName>
            </value>
            <value>
                <fullName>OLI Start End Amount Update</fullName>
            </value>
            <value>
                <fullName>Amended Data Sync - OH</fullName>
            </value>
            <value>
                <fullName>ERP Ref. Number back update to CRM</fullName>
            </value>
            <value>
                <fullName>Document Pull request from ERP</fullName>
            </value>
            <value>
                <fullName>Account Billing Address Change</fullName>
                <isActive>false</isActive>
                <label>Account Billing Address Change</label>
            </value>
            <value>
                <fullName>Account Credit Status</fullName>
                <isActive>false</isActive>
                <label>Account Credit Status</label>
            </value>
            <value>
                <fullName>Account Name Change</fullName>
                <isActive>false</isActive>
                <label>Account Name Change</label>
            </value>
            <value>
                <fullName>Account Shipping Address Change</fullName>
                <isActive>false</isActive>
                <label>Account Shipping Address Change</label>
            </value>
            <value>
                <fullName>Bill To Account change</fullName>
                <isActive>false</isActive>
                <label>Bill To Account change</label>
            </value>
            <value>
                <fullName>Change Request Completed</fullName>
                <isActive>false</isActive>
                <label>Change Request Completed</label>
            </value>
            <value>
                <fullName>Ship To Account change</fullName>
                <isActive>false</isActive>
                <label>Ship To Account change</label>
            </value>
            <value>
                <fullName>VAT Registration Number Change</fullName>
                <isActive>false</isActive>
                <label>VAT Registration Number Change</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Item__c/fields/X3rd_Party_ERP_System__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_ERP_System__c</fullName>
    <description>External 3rd Party ERP System</description>
    <label>3rd Party ERP System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X3rd_Party_ERP_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Transaction__c/API_Synchronization_Transaction__c.object-meta.xml
<CustomObject>
    <description>Object to track syncing of data &amp; this will help in tracking errors while Sync</description>
    <label>API Synchronization Transaction</label>
    <nameField>
        <displayFormat>AST-{0000}</displayFormat>
        <label>API Synchronization Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Synchronization Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Synchronization_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the transaction. Some status will be dependent on status of related line items. The default value will be Queued.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Completed With Errors</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Requeue for Erroneous records</fullName>
            </value>
            <value>
                <fullName>Requeue All</fullName>
            </value>
            <value>
                <fullName>Requeue for Successful records</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Action at object level which has initiated the transaction.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Get</fullName>
            </value>
            <value>
                <fullName>Post Invoice</fullName>
            </value>
            <value>
                <fullName>Post Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Synchronization_Transaction__c/fields/X3rd_Party_ERP_System__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_ERP_System__c</fullName>
    <description>Name of external system for API sync.</description>
    <label>3rd Party ERP System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X3rd_Party_ERP_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <description>This field is used to fetch the legal entity name from event series as per ticket no IML2R-135.</description>
    <formula>HYPERLINK(&quot;/&quot;&amp;Part_of_Series__r.Legal_Entity__c,Part_of_Series__r.Legal_Entity__r.Name,&quot;_blank&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field is used to fetch the legal entity name from event series.</inlineHelpText>
    <label>Legal Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/X3rd_Party_ERP_System__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_ERP_System__c</fullName>
    <description>External 3rd Party System Name</description>
    <label>3rd Party ERP System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X3rd_Party_ERP_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ViewDocumentController.cls
/**
* File         :   ViewDocumentController 
* Project      :   GECI
* Created Date :   3 July 2023
* Created By   :   IBM (Bharath)
* Test Class   :   ViewDocumentController_Test (96%)
* ***************************************************************************************************
* @description : Controller class for View_Document Visualforce Page (GECI-1922)
* ***************************************************************************************************
*/
public with sharing class ViewDocumentController {
    private static final String USCORE = '_';
    private static final String IOM_INVOICE_PDF_RETRIEVAL = 'IOM_Invoice_PDF_Retrieval';

    public transient Blob blobBody;
    /** @description is show error message */
    public Boolean showErrorMessage{set;get;}
    /** @description is response is success*/
    public Boolean positiveResponse{set;get;}
    /** @description file in base64 format */
    public transient String base64String{get;set;}

    /** 
    * @description : method to call external Call
    * @return PageReference
    */
    public PageReference getDocument(){
        Id recordID = ApexPages.CurrentPage().getparameters().get('RecordID').escapeHtml4();
        String erpRef;
        String sObjName = recordID.getSObjectType().getDescribe().getName();
        blng__Invoice__c invoice;blng__CreditNote__c creditNote;
        String legalEntityCode;
        if(sObjName == 'blng__Invoice__c'){
            invoice = [SELECT Id,Name,blng__Order__r.Edition__r.X3rd_Party_ERP_System__c,OpportunityId__c,Legal_Entity_Code__c,ERP_Reference__c FROM blng__Invoice__c WHERE Id=:recordID WITH SECURITY_ENFORCED limit 1];  
            legalEntityCode = invoice.Legal_Entity_Code__c; 
            erpRef = invoice.ERP_Reference__c;
        }
        if(sObjName == 'blng__CreditNote__c'){
            creditNote = [SELECT Id,Name,blng__RelatedInvoice__r.blng__Order__r.Edition__r.X3rd_Party_ERP_System__c,blng__RelatedInvoice__r.OpportunityId__c,Legal_Entity__r.Legal_Entity_Code__c,ERPReference__c FROM blng__CreditNote__c WHERE Id=:recordID WITH SECURITY_ENFORCED limit 1]; 
            legalEntityCode = creditNote.Legal_Entity__r.Legal_Entity_Code__c;
            erpRef = creditNote.ERPReference__c;
        }
        
        API_Detail__mdt mtAPIDetails = APISynchronizationHelper.getAPIDetails(IOM_INVOICE_PDF_RETRIEVAL, GlobalConstants.ORACLE);

        String urlParameter='/download?legalEntity=' + legalEntityCode;
        String endPointURL = mtAPIDetails.API_End_Point__c + erpRef + urlParameter;
        HttpResponse response = viewDocumentController.calltoExternalSystem(erpRef, legalEntityCode, mtAPIDetails);
        Boolean sizelimit = false;
        if((response.getStatusCode() == 200 || response.getStatusCode() == 202) && String.isNotBlank(response.getBody())){
            blobBody = response.getBodyAsBlob();
            String filetype = response.getHeader('Content-Type');
            Decimal fileSizeInBytes = blobBody.size();
            Decimal fileSizeInKB = fileSizeInBytes/1024;
            Decimal fileSizeInMB = fileSizeInKB/1024;
            if(fileSizeInMB < 4.3 || filetype=='application/pdf'){
                sizelimit=true;
            }
            if(sizelimit){
                positiveResponse = true;
                base64String = EncodingUtil.base64Encode(blobBody);
            }
            if(!sizelimit){
                positiveResponse = false;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Please contact system Admin!'));
            } 
        }
        else{
            positiveResponse = false;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,System.Label.View_Document_Error));
        }
        //create API Records for Tracking
        WrapperListView wrapObj = new WrapperListView(invoice,endPointURL,response.getBody(),sObjName,creditNote,positiveResponse,String.valueOf(response.getStatusCode()));
        viewDocumentController.createAPIrecs(wrapObj);
        return null;
    }

    /**
    * @description : Generic Method for HTTP callout to fetch Invoice/Credit note PDF
    * @param  erpRef ERP Reference
    * @param  legalEntityCode Legal Entity Code
    * @param  mtAPIDetails API_Detail__mdt
    * @return HTTPResponse
    */
    public static HTTPResponse calltoExternalSystem(String erpRef, String legalEntityCode, API_Detail__mdt mtAPIDetails) {
        String endPointURL = '/document/'+erpRef+'/download?legalEntity='+legalEntityCode;
        String method = mtAPIDetails.API_Method__c;
        String headerval = String.ValueOf(mtAPIDetails.Headers__c);  
        HttpRequest request = new HttpRequest();
        request.setHeader('x-api-key', headerval);
        request.setEndpoint('callout:Invoice_PDF_Retrieval'+endPointURL);
        request.setTimeout(60000);
        request.setHeader('Content-Type', 'application/json');        
        request.setMethod(method);
        Http http = new Http();
        HttpResponse response = http.send(request);
        return response;
    }

    /**
    * @description : method to create API Records for History Tracking of callout
    * @param  wrapObj
    * @return String
    */
    public static String createAPIrecs(WrapperListView wrapObj) {
        blng__Invoice__c inv = wrapObj.inv;
        String reqBody = wrapObj.reqBody;
        String responsebody = wrapObj.responsebody;
        String sObjName = wrapObj.sObjName;
        blng__CreditNote__c creditnote = wrapObj.creditnote;
        Boolean positiveResponse = wrapObj.positiveResponse;
        String externalSystem;
        API_Synchronization_Item__c apiSyncItems = new API_Synchronization_Item__c();
        if(sObjName=='blng__Invoice__c'){
            apiSyncItems.Invoice__c = inv.Id;
            apiSyncItems.Response_Body__c = (positiveResponse)?(inv.ERP_Reference__c + USCORE + inv.Legal_Entity_Code__c):responsebody;
            apiSyncItems.Opportunity__c = inv.OpportunityId__c;
            externalSystem = inv.blng__Order__r.Edition__r.X3rd_Party_ERP_System__c;
            apiSyncItems.X3rd_Party_ERP_System__c = externalSystem;
        }

        if(sObjName == 'blng__CreditNote__c'){
            apiSyncItems.Credit_Note__c = creditnote.Id;
            apiSyncItems.Response_Body__c = (positiveResponse)?(creditnote.ERPReference__c+USCORE+ creditnote.Legal_Entity__r.Legal_Entity_Code__c):responsebody;
            apiSyncItems.Opportunity__c = creditnote.blng__RelatedInvoice__r.OpportunityId__c;
            externalSystem = creditNote.blng__RelatedInvoice__r.blng__Order__r.Edition__r.X3rd_Party_ERP_System__c;
            apiSyncItems.X3rd_Party_ERP_System__c = externalSystem;
        }
        apiSyncItems.Status__c = (positiveResponse)?GlobalConstants.COMPLETED:GlobalConstants.ERROR;	
        apiSyncItems.API_Call_Type__c = 'GET';
        apiSyncItems.Type__c = 'Document Pull request from ERP';
        apiSyncItems.Request_Body__c = reqBody;
        apiSyncItems.Response_Code__c = wrapObj.responseCode;

        //create its Transaction record
        API_Synchronization_Transaction__c apiSyncTran = new API_Synchronization_Transaction__c();
        apiSyncTran.Status__c = (positiveResponse)?GlobalConstants.COMPLETED:'Completed With Errors';
        apiSyncTran.X3rd_Party_ERP_System__c = externalSystem;
        apiSyncTran.Started_From__c = (sObjName=='blng__Invoice__c')?'Invoice':'Credit Note';
        apiSyncTran.Type__c = 'GET';
        apiSyncTran.Request_Type__c = GlobalConstants.SYNCHRONOUS;
        if(Schema.sObjectType.API_Synchronization_Transaction__c.isCreateable()){
            insert apiSyncTran;
        }
        apiSyncItems.API_Synchronization_Transaction__c = apiSyncTran.Id;
        
        if(Schema.sObjectType.API_Synchronization_Item__c.isCreateable()){
            insert apiSyncItems;
        }
        return null;
    }

    /**
    * @description  wrapper method for hadling Response data.
    */
    public class WrapperListView {
        public blng__Invoice__c inv;
        public String reqBody;
        public String responsebody;
        public String sObjName;
        public blng__CreditNote__c creditnote;
        public Boolean positiveResponse;
        public String responseCode;

        /** @description to assing variabled on class initiation 
         * @param invtR
         * @param reqBodyR
         * @param responsebodyR
         * @param sObjNameR
         * @param creditnoteR
         * @param posResponse
         * @param responseCodeR
        */
        public wrapperListView(blng__Invoice__c invtR, String reqBodyR,String responsebodyR, String sObjNameR,blng__CreditNote__c creditnoteR,Boolean posResponse, String responseCodeR) {
            inv =  invtR;
            reqBody = reqBodyR;
            responsebody = responsebodyR;
            sObjName = sObjNameR;
            creditnote = creditnoteR;
            positiveResponse = posResponse;
            responseCode = responseCodeR;
        }
    }
}