force-app/main/default/objects/Account_Tax_Number__c/Account_Tax_Number__c.object-meta.xml
<CustomObject>
    <description>Tax Registration Numbers for a Customer to be used for Tax validation when customer transacts in a Country.</description>
    <label>Account Tax Number</label>
    <nameField>
        <displayFormat>AT-{00000}</displayFormat>
        <label>Account Tax Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Tax Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Tax_Number__c/fields/Account_Tax_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Tax_Number__c</fullName>
    <description>Account Tax Number Auto number</description>
    <displayFormat>AT-{00000}</displayFormat>
    <inlineHelpText>Account Tax Number Auto number</inlineHelpText>
    <label>Account Tax  Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account_Tax_Number__c/fields/Tax_Category__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category__c</fullName>
    <description>Category of Account tax number based on Tax Country</description>
    <label>Tax Category</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Tax_Number__c/fields/Tax_Country__c.field-meta.xml
<CustomField>
    <fullName>Tax_Country__c</fullName>
    <description>Country of Tax Registration</description>
    <inlineHelpText>Country of Tax Registration</inlineHelpText>
    <label>Tax Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Registration_Country__mdt/Tax_Registration_Country__mdt.object-meta.xml
<CustomObject>
    <description>Countries that have a 1:1 relationship between the country and the tax category would be stored in a mapping table.</description>
    <label>Tax Registration Country</label>
    <pluralLabel>Tax Registration Countries</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tax_Registration_Country__mdt/fields/SAP_Tax_Type__c.field-meta.xml
<CustomField>
    <fullName>SAP_Tax_Type__c</fullName>
    <description>SAP tax type for Selected country.</description>
    <label>SAP Tax Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TaxCategoryUpdate_Trig.cls
/**
* File         :   TaxCategoryUpdate_Trig
* Project      :   IE ECOM
* Created Date :   2nd Sept 2022
* Created By   :   Girikon(Ansh)
* Test Class   :  TaxCategoryUpdate_Trig_Test
* ******************************************************************************************************
@description : This class is used to update tax category field on Account Tax Number
*******************************************************************************************************
* Modification log :
*/

public with sharing class TaxCategoryUpdate_Trig implements TriggerInterface_AccountTaxNumber.Runnable{

    /** 
*   @description [Call Interface Class to fetch the new list and old map of Account Tax Number]
*   @param trig [fetch the trigger new list and old map]
*/
    public void run(TriggerInterface_AccountTaxNumber.Trig trig){
        if(trig.isBefore){
            updateTaxCategory(trig);
        }
    }
/**
*   @description Update Tax Category on Account Tax Number
*   @param trig
*/
    public void updateTaxCategory(TriggerInterface_AccountTaxNumber.Trig trig){
        for(Account_Tax_Number__c atn : trig.newList){
            String value;
            String key = atn.Tax_Country__c;
            Tax_Registration_Country__mdt tgn = Tax_Registration_Country__mdt.getInstance(key);
            value = tgn != null ? tgn.SAP_Tax_Type__c :'';

            atn.Tax_Category__c = value;
        }
    }

}