force-app/main/default/objects/Account_Tax_Number__c/Account_Tax_Number__c.object-meta.xml
<CustomObject>
    <description>Tax Registration Numbers for a Customer to be used for Tax validation when customer transacts in a Country.</description>
    <label>Account Tax Number</label>
    <nameField>
        <displayFormat>AT-{00000}</displayFormat>
        <label>Account Tax Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Tax Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Tax_Number__c/fields/Account_Tax_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Tax_Number__c</fullName>
    <description>Account Tax Number Auto number</description>
    <displayFormat>AT-{00000}</displayFormat>
    <inlineHelpText>Account Tax Number Auto number</inlineHelpText>
    <label>Account Tax  Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/CC_Emails__c.field-meta.xml
<CustomField>
    <fullName>CC_Emails__c</fullName>
    <description>This field stores all CC Emails.</description>
    <inlineHelpText>Emails to be CC&apos;ed on invoices

Format for multiple emails :

abc@xyz.com,lmn@xyz.com</inlineHelpText>
    <label>CC Emails</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <description>This field is used to fetch the legal entity name from event series as per ticket no IML2R-135.</description>
    <formula>HYPERLINK(&quot;/&quot;&amp;Part_of_Series__r.Legal_Entity__c,Part_of_Series__r.Legal_Entity__r.Name,&quot;_blank&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field is used to fetch the legal entity name from event series.</inlineHelpText>
    <label>Legal Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Tax_Rule__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rule__c</fullName>
    <description>To mark if there needs a check for &quot;UAE VAT Refund&quot;.</description>
    <label>Tax Rule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UAE VAT Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account_Tax_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Tax_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tax Number of Number</description>
    <label>Account Tax Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account_Tax_Number__c.Status__c</field>
            <operation>equals</operation>
            <value>Valid</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account_Tax_Number__c</referenceTo>
    <relationshipLabel>Opportunities (Account Tax Number)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AdditionalCCEmailAddresses__c.field-meta.xml
<CustomField>
    <fullName>AdditionalCCEmailAddresses__c</fullName>
    <label>AdditionalCCEmailAddresses</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Barter_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Is_Barter_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Checkbox is checked then opportunity is a barter deal.</description>
    <label>Is Barter Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the legal entity.</description>
    <inlineHelpText>This legal entity will be the default one for the quote</inlineHelpText>
    <label>Legal Entity</label>
    <referenceTo>blng__LegalEntity__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <description>Purchase Order Number</description>
    <label>PO Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Shipping Account</description>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ship To Account)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tax_Exempt__c.field-meta.xml
<CustomField>
    <fullName>Tax_Exempt__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if Checked then Opportunity will be tax exempt.</description>
    <label>Tax Exempt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tax_Registration__c.field-meta.xml
<CustomField>
    <fullName>Tax_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Tax Registration to be used on this Contract for the Bill to Account.</description>
    <inlineHelpText>Tax Jurisdiction Auto number.</inlineHelpText>
    <label>Tax Registration Number</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No valid tax registration is available.</errorMessage>
        <filterItems>
            <field>Account_Tax_Number__c.Status__c</field>
            <operation>equals</operation>
            <value>Valid</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account_Tax_Number__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tax_Rule__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rule__c</fullName>
    <description>This field is used to update values while upload declaration document.</description>
    <label>VAT_Rule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UAE VAT Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Order/fields/Account_Tax_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Tax_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Billing Account VAT/TAX Registration Number</description>
    <label>Account Tax Number</label>
    <referenceTo>Account_Tax_Number__c</referenceTo>
    <relationshipLabel>Orders (Account Tax Number)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Edition of order.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Is_Barter_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Is_Barter_Opportunity__c</fullName>
    <description>is this a barter deal. If Checked then deal will be barter.</description>
    <formula>Opportunity.Is_Barter_Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Barter Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Legal Entity is set from the Quote</description>
    <label>Legal Entity</label>
    <referenceTo>blng__LegalEntity__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ship To Account</description>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Ship To Account)</relationshipLabel>
    <relationshipName>ShippingOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tax_Exempt1__c.field-meta.xml
<CustomField>
    <fullName>Tax_Exempt1__c</fullName>
    <description>If True, Transaction is Exempt from Tax. This Field is used for Tax Determination</description>
    <formula>Opportunity.Tax_Exempt__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Exempt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tax_Rule__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rule__c</fullName>
    <description>This field is used to update values while upload declaration document.</description>
    <label>Tax Rule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UAE VAT Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Tax_Status__c.field-meta.xml
<CustomField>
    <fullName>Tax_Status__c</fullName>
    <description>Status to indicate Tax Status.</description>
    <label>Tax Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tax Required</fullName>
            </value>
            <value>
                <fullName>Tax Complete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>Payment transactions holds information of payment details coming from Payment Portal via Mulesoft integration.</description>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>PT-{000000}</displayFormat>
        <label>Payment Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Payment Amount</description>
    <label>Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Invoice</description>
    <label>Invoice</label>
    <referenceTo>blng__Invoice__c</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <description>Payment Type</description>
    <label>Payment Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateInvoiceFields_Trig.cls
/***************************************************************************
* File			: 	UpdateInvoiceFields_Trig
* Project       :   Informa Order Management [IOM-772]
* Created By	: 	Girikon(Ashish)
* Created Date	: 	27th Jan 2022
* Test Class   :    UpdateInvoiceFields_Trig_Test(100%)
* ***************************************************************************
* @description : Utility Class for Updating all Fields updates on Invoice
*****************************************************************************
* Modification Log :
* 1. [IML2R-1264]   - Girikon(Ashish)-  11 April 2022   Add Deafult value in Outstanding Balance
* 2. [IE-10]        - Girikon(Ashish)-  09 AUG 2022     update Invoice Id on Payment_Transactions
* 3. [IE-435]       - Girikon(Ashish)-  21 OCT 2022     update Default OutStandig Balance to Invoice Record
******************************************************************************/
public with sharing class UpdateInvoiceFields_Trig implements TriggerInterface_Invoice.Runnable 
{
    /**
    * @description  This method is execute Trigger
    * @param trig Invoice TriggerInterface    
    */
    public void run(TriggerInterface_Invoice.Trig trig)
    {
        if(trig.isBefore && (trig.isInsert || trig.isUpdate)) 
        {   //Update Account Fields From Order
            updateinvFields(trig.newList,trig.oldMap);
            // Set Print Flag Default Value
            updatePDFtoCustomer(trig.newList);
            // Update Fields
            //updateDefaultValues(trig.newList,trig.oldMap);
            //
            updateInvOutStandingVal(trig.newList,trig.oldMap);
        }
        if(trig.isAfter && (trig.isInsert || trig.isUpdate))
        {   // update Invoice Id on Payment_Transactions [IE-10]
            updatePaymentTrans(trig.newList,trig.oldMap);
        }
        
    }
   
    /**
    * @description  This method is used to update Send PDF to Customer on Invoice
    * @param newInvoiceList new Invoice List
    * @param oldInvoiceMap Old Invoice Map
    */
    private static void updateinvFields(list<blng__Invoice__c> newInvoiceList,Map<Id,blng__Invoice__c>oldInvoiceMap)
    {
        set<Id> orderIds = new set<Id>();
        for(blng__Invoice__c inv:newInvoiceList)
        {
            blng__Invoice__c oldInv = !oldInvoiceMap.isEmpty()?oldInvoiceMap.get(inv.Id):new blng__Invoice__c();
            if(string.isNotBlank(inv.blng__Order__c) && inv.blng__Order__c !=  oldInv.blng__Order__c)
            {
                orderIds.add(inv.blng__Order__c);
            }
        }
        Map<Id,Order> orderMap = new Map<Id,Order>([SELECT Id,Ship_To_Account__c,Opportunity.AdditionalCCEmailAddresses__c,Edition__r.CC_Emails__c,BillToContactId,PoNumber,Legal_Entity__c,Account_Tax_Number__c,Tax_Rule__c,Tax_Exempt1__c FROM Order where Id IN:orderIds]);
        for(blng__Invoice__c inv:newInvoiceList)
        {
            if(orderMap.containsKey(inv.blng__Order__c))
            {
                if((String.isNotBlank(orderMap.get(inv.blng__Order__c).Edition__r.CC_Emails__c)) && (String.isNotBlank(orderMap.get(inv.blng__Order__c).Opportunity.AdditionalCCEmailAddresses__c))){
                    inv.Additional_CC_emails__c = orderMap.get(inv.blng__Order__c).Edition__r.CC_Emails__c+','+orderMap.get(inv.blng__Order__c).Opportunity.AdditionalCCEmailAddresses__c;
                }
                else if((String.isBlank(orderMap.get(inv.blng__Order__c).Opportunity.AdditionalCCEmailAddresses__c))){
                    inv.Additional_CC_emails__c = orderMap.get(inv.blng__Order__c).Edition__r.CC_Emails__c;
                }
                else{
                    inv.Additional_CC_emails__c = orderMap.get(inv.blng__Order__c).Opportunity.AdditionalCCEmailAddresses__c;
                }
                inv.Ship_To_Account__c = orderMap.get(inv.blng__Order__c).Ship_To_Account__c;
                
                inv.blng__BillToContact__c = orderMap.get(inv.blng__Order__c).BillToContactId;
                inv.Legal_Entity__c = orderMap.get(inv.blng__Order__c).Legal_Entity__c;
                inv.PO_Number__c = orderMap.get(inv.blng__Order__c).PoNumber;
                inv.Tax_Registration__c = orderMap.get(inv.blng__Order__c).Account_Tax_Number__c;
                inv.Tax_Rule__c = orderMap.get(inv.blng__Order__c).Tax_Rule__c;
                inv.Tax_Exempt__c = orderMap.get(inv.blng__Order__c).Tax_Exempt1__c;
            }
        }
    }
    
    /**
    * @description  This method is used to update Send PDF to Customer on Invoice
    * @param newInvoiceList new Invoice List
    */
    private static void updatePDFtoCustomer(list<blng__Invoice__c> newInvoiceList)
    {
        set<Id> orderIds = new set<Id>();
        set<Id> entityIds = new set<Id>();
        for(blng__Invoice__c inv:newInvoiceList)
        {
            if(string.isNotBlank(inv.blng__Order__c))
            {
                orderIds.add(inv.blng__Order__c);
            }
            if(string.isNotBlank(inv.Legal_Entity__c)){
                entityIds.add(inv.Legal_Entity__c);
            }
        }
        Map<Id,Order> orderMap = new Map<Id,Order>([SELECT Id,Is_Barter_Opportunity__c FROM Order where Id IN:orderIds]);
        Map<Id,blng__LegalEntity__c> entityMap = new Map<Id,blng__LegalEntity__c>([Select Id, Send_PDF_for_Barter_Sell_to_Customer__c from blng__LegalEntity__c where Id IN: entityIds]);
        for(blng__Invoice__c inv:newInvoiceList)
        {
            inv.Send_PDF_to_Customer__c = 'Y';
            if(orderMap.containsKey(inv.blng__Order__c) && orderMap.get(inv.blng__Order__c).Is_Barter_Opportunity__c == true)
            {
                inv.IsBarter__c = 'Y';
                inv.Send_PDF_to_Customer__c = entityMap.containsKey(inv.Legal_Entity__c) && entityMap.get(inv.Legal_Entity__c).Send_PDF_for_Barter_Sell_to_Customer__c == true ? 'Y' : 'N';
            }
        }
    }
    /**
    * @description  This method is used to update Default vaues to Invoice Record
    * @param newInvoiceList new Invoice List
    * @param oldInvoiceMap Old Invoice Map
    */
    /*
    private static void updateDefaultValues(list<blng__Invoice__c> newInvoiceList, Map<Id,blng__Invoice__c> oldInvoiceMap)
    {    
            
        for(blng__Invoice__c inv:newInvoiceList)
        {
            System.debug('IN updateDefaultValues ');
            blng__Invoice__c oldInv = !oldInvoiceMap.isEmpty()?oldInvoiceMap.get(inv.Id):new blng__Invoice__c();            
            if(inv.Outstanding_Balance__c == null && inv.Tax_Status__c !=  oldInv.Tax_Status__c && inv.Tax_Status__c == 'Tax Complete')
            {
                inv.Outstanding_Balance__c = inv.blng__TotalAmount__c; // IOM-1264                
            }
        } 
    }*/
     /** [IE-435]
    * @description  This method is used to update Default OutStandig Balance to Invoice Record -
    * @param newInvoiceList new Invoice List
    * @param oldInvoiceMap Old Invoice Map
    */
    private static void updateInvOutStandingVal(list<blng__Invoice__c> newInvoiceList, Map<Id,blng__Invoice__c> oldInvoiceMap)
    {     
         Map<Id,Decimal> invOutStandbalcMap = new Map<Id,Decimal>();
        for(blng__Invoice__c inv:newInvoiceList)
        {         
            blng__Invoice__c oldInv = !oldInvoiceMap.isEmpty()?oldInvoiceMap.get(inv.Id):new blng__Invoice__c();            
            if(inv.Outstanding_Balance__c == null && inv.Tax_Status__c !=  oldInv.Tax_Status__c && inv.Tax_Status__c == 'Tax Complete')
            {
                //inv.Outstanding_Balance__c = inv.blng__TotalAmount__c; // IOM-1264
                invOutStandbalcMap.put(inv.id,inv.blng__TotalAmount__c);
            }
        }
    
        for(AggregateResult ar : [SELECT Invoice__c,Sum(Amount__c) total From Payment_Transaction__c WHERE Payment_Type__c != 'Refund' AND Invoice__c in:invOutStandbalcMap.keySet() WITH SECURITY_ENFORCED GROUP BY Invoice__c ])
        {
            Id invId = (Id)ar.get('Invoice__c');
            invOutStandbalcMap.put(invId,invOutStandbalcMap.get(invId)-(Decimal)ar.get('total'));
        }
        
        for(blng__Invoice__c inv:newInvoiceList)
        {
            if(invOutStandbalcMap.containsKey(inv.Id))
            {
                inv.Outstanding_Balance__c = invOutStandbalcMap.get(inv.Id);
            }
        }
        
    }
    /** [IE-10]
    * @description  This method is used add Invoice Id on Payment_Transactions
    * @param newInvoiceList new Invoice List
    * @param oldInvoiceMap Old Invoice Map
    */
    private static void updatePaymentTrans(list<blng__Invoice__c> newInvoiceList,Map<Id,blng__Invoice__c>oldInvoiceMap)
    {
        Map<Id,Id> orderInvMap = new Map<Id,Id>();
        for(blng__Invoice__c inv:newInvoiceList)
        {
            blng__Invoice__c oldInv = !oldInvoiceMap.isEmpty()?oldInvoiceMap.get(inv.Id):new blng__Invoice__c();
            // System.debug('Old Odr : '+oldInv.blng__Order__c+' + new Order :'+inv.blng__Order__c);
            if(string.isNotBlank(inv.blng__Order__c) && inv.blng__Order__c !=  oldInv.blng__Order__c)
            {
                orderInvMap.put(inv.blng__Order__c,inv.Id);
            }
            
        }
       
        if(!orderInvMap.isEmpty())
        {
            List<Payment_Transaction__c> listPaymetTxn = new List<Payment_Transaction__c>();
            for(Payment_Transaction__c payTxn : [SELECT Id,Order__c,Invoice__c FROM Payment_Transaction__c WHERE Order__c IN:orderInvMap.keySet() WITH SECURITY_ENFORCED])
            {
                payTxn.Invoice__c = orderInvMap.get(payTxn.Order__c);
                listPaymetTxn.add(payTxn);
                
             }
           
            if(!listPaymetTxn.isEmpty() && Schema.sObjectType.Payment_Transaction__c.isUpdateable())
            {
                update listPaymetTxn;
            }            
        }     
        
    }
    
}