force-app/main/default/objects/Change_Request__c/Change_Request__c.object-meta.xml
<CustomObject>
    <description>To capture details of amendment related to Opportunity/Order/Invoice.</description>
    <label>Amendment</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Salesforce record id</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Amendments (Account)</relationshipLabel>
    <relationshipName>Change_Rquests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Amendment&apos;s Edition.</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Amendments</relationshipLabel>
    <relationshipName>Change_Rquests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>New_Payment_Schedule__c</fullName>
    <description>This picklist contains values of all payment schedules available on Opportunity.</description>
    <label>New Payment Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Schedule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity on which the change is being requested</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Amendments (Opportunity)</relationshipLabel>
    <relationshipName>Change_Rquests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>Amendment Type. Financial/ Non-Financial</description>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Change__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Non-Financial</fullName>
            </value>
            <value>
                <fullName>Booth</fullName>
                <isActive>false</isActive>
                <label>Booth</label>
            </value>
            <value>
                <fullName>Digital</fullName>
                <isActive>false</isActive>
                <label>Digital</label>
            </value>
            <value>
                <fullName>Financial Change</fullName>
                <isActive>false</isActive>
                <label>Financial Change</label>
            </value>
            <value>
                <fullName>Non Product</fullName>
                <isActive>false</isActive>
                <label>Non Product</label>
            </value>
            <value>
                <fullName>Non-Financial Change</fullName>
                <isActive>false</isActive>
                <label>Non-Financial Change</label>
            </value>
            <value>
                <fullName>Opportunity Detail</fullName>
                <isActive>false</isActive>
                <label>Opportunity Detail</label>
            </value>
            <value>
                <fullName>Publishing</fullName>
                <isActive>false</isActive>
                <label>Publishing</label>
            </value>
            <value>
                <fullName>Sponsorship</fullName>
                <isActive>false</isActive>
                <label>Sponsorship</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <description>Email of the user that raised the Amendment in CRM</description>
    <label>Requested By</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Type_of_Change__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Change__c</fullName>
    <description>Type of Amendment.</description>
    <label>ZZ_Type of Change</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bill To Account Change</fullName>
                <label>Account - Bill To Account Change To Different Account</label>
            </value>
            <value>
                <fullName>Billing Address Change</fullName>
                <label>Account - Bill To Address Update Same Account</label>
            </value>
            <value>
                <fullName>Account Name Change</fullName>
                <label>Account - Name Update</label>
            </value>
            <value>
                <fullName>Ship To Account Change</fullName>
                <label>Account - Ship To Account Change To Different Account</label>
            </value>
            <value>
                <fullName>Shipping Address Change</fullName>
                <label>Account - Ship To Address Update Same Account</label>
            </value>
            <value>
                <fullName>Billing Schedule Change</fullName>
                <label>Billing Options Update</label>
            </value>
            <value>
                <fullName>Campaign Run Dates Change</fullName>
                <label>Campaign Run Dates Update</label>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Update Bill To Contact</fullName>
                <label>Contact - Bill To Contact Change To Different Contact</label>
            </value>
            <value>
                <fullName>Bill to Contact Details Change</fullName>
                <label>Contact - Bill To Contact Update Same Contact</label>
            </value>
            <value>
                <fullName>Number of Impressions Amendment</fullName>
            </value>
            <value>
                <fullName>PO number change</fullName>
                <label>PO Number Update</label>
            </value>
            <value>
                <fullName>Tax Exempt Rebill</fullName>
            </value>
            <value>
                <fullName>VAT Registration Number Change</fullName>
                <label>VAT Registration Number Update</label>
            </value>
            <value>
                <fullName>Account Address</fullName>
                <isActive>false</isActive>
                <label>Account Address</label>
            </value>
            <value>
                <fullName>Account Name</fullName>
                <isActive>false</isActive>
                <label>Account Name</label>
            </value>
            <value>
                <fullName>Billing Account</fullName>
                <isActive>false</isActive>
                <label>Billing Account</label>
            </value>
            <value>
                <fullName>Billing Address</fullName>
                <isActive>false</isActive>
                <label>Billing Address</label>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
                <isActive>false</isActive>
                <label>Billing Contact</label>
            </value>
            <value>
                <fullName>Billing Terms</fullName>
                <isActive>false</isActive>
                <label>Billing Terms</label>
            </value>
            <value>
                <fullName>Booth Change</fullName>
                <isActive>false</isActive>
                <label>Booth Change</label>
            </value>
            <value>
                <fullName>Change Sales Rep</fullName>
                <isActive>false</isActive>
                <label>Change Sales Rep</label>
            </value>
            <value>
                <fullName>Content</fullName>
                <isActive>false</isActive>
                <label>Content</label>
            </value>
            <value>
                <fullName>Currency</fullName>
                <isActive>false</isActive>
                <label>Currency</label>
            </value>
            <value>
                <fullName>Date Change</fullName>
                <isActive>false</isActive>
                <label>Date Change</label>
            </value>
            <value>
                <fullName>Downgrade</fullName>
                <isActive>false</isActive>
                <label>Downgrade</label>
            </value>
            <value>
                <fullName>Incorrect Account details with Tax impact Amendment</fullName>
                <isActive>false</isActive>
                <label>Incorrect Account details with Tax impact Amendment</label>
            </value>
            <value>
                <fullName>Incorrect Product Tax amendment</fullName>
                <isActive>false</isActive>
                <label>Incorrect Product Tax amendment</label>
            </value>
            <value>
                <fullName>Ordered Products</fullName>
                <isActive>false</isActive>
                <label>Ordered Products</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Invoice_to_be_issued_before__c.field-meta.xml
<CustomField>
    <fullName>Invoice_to_be_issued_before__c</fullName>
    <description>The field is to be used to drive the invoice start date as per the cut off dates created on the edition. The field will subtract the entered number of days from the Cut off dates and will change the payment plan on contract based on the date on which it gets generated between the Invoicing to Start Date and Cut off Date.</description>
    <inlineHelpText>The field is to be used to drive the invoice start date as per the cut off dates created on the event edition. The field will subtract the entered number of days from the Cut off dates to calculate the Invoicing to Start From Dates.</inlineHelpText>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is an explicit field for Bill To Account.</description>
    <label>Bill To Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Accounting_Credit_Hold__c</field>
            <operation>notEqual</operation>
            <value>Hold</value>
        </filterItems>
        <filterItems>
            <field>Account.Accounting_Credit_Hold__c</field>
            <operation>notEqual</operation>
            <value>Warning</value>
        </filterItems>
        <infoMessage>Account Credit Status is On Hold/Warning.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Bill To Account)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Billing Contact.</description>
    <label>Billing/Invoice Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Default_Edition__c.field-meta.xml
<CustomField>
    <fullName>Default_Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Edition of Opportunity</description>
    <label>Default Edition</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Edition__c.Edition_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <description>Opportunity Owner Email of CRM org</description>
    <label>Sales Person Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Shipping Account</description>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ship To Account)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/SendIOMEmails_Test.cls
/**
* Created By   :   IBM(Bharath)
* Created On   :   9 May 2023
* ******************************************************************************************************************
* @description  : Test Class to give covrage to SendIOMEmails(100%)]
* ******************************************************************************************************************
*/
@isTest
private class SendIOMEmails_Test {
    @TestSetUp
    static void testUserData(){
        UserRole userrole = [Select Id, DeveloperName From UserRole Where DeveloperName = 'Administrator' Limit 1];
        User adminUser = [Select Id, UserRoleId From User Where Profile.Name='System Administrator' and IsActive = true Limit 1];
        adminUser.UserRoleId = userrole.Id;
        update adminUser;
    }
    
    @isTest 
    static void sendiomEmailTest(){
        User adminUser = [Select Id, UserRoleId From User Where Profile.Name='System Administrator' and IsActive = true and UserRole.Name = 'Administrator' Limit 1];
		Contact con = new Contact();
        User userObj;
        Id contactId;
        Id accId;
        string sendEmail='bharath.sharma@informa.com';
        Id standardPricebookId = Test.getStandardPricebookId();
        System.runAs(adminUser){
            List<Account> accObj  = IMCC_TestUtilities.createAccount(1);
            accId = accObj[0].Id;
            List<Contact> contObj = IMCC_TestUtilities.createContact(accId, 1);
            contObj[0].Email=sendEmail;
            update contObj;
            contactId = contObj[0].Id;
            con = contObj[0];
            userObj = IMCC_TestUtilities.createCommunityUser(contactId);
            System.assertEquals(userObj.ContactID,contactId, 'Same contact');
        }

        List<Edition__c> listOfEditions = new List<Edition__c>();
        Edition__c edition = new Edition__c();
        for(Integer i=0;i<2;i++){
            edition =  new Edition__c(Invoice_to_be_issued_before__c='30');
            
            listOfEditions.add(edition);
        }
        insert listOfEditions;

        Opportunity opp = new Opportunity( 
            Pricebook2Id =standardPricebookId,
            CloseDate =Date.newInstance(2019, 11, 5),
            StageName ='Proposal',
            Default_Edition__c=listOfEditions[0].Id,
            Name ='TESTOPP',  
            AccountId=accId,
            Sales_Person__c=sendEmail,
            Bill_To_Account__c = accId,
            Ship_To_Account__c = accId,
            Billing_Contact__c=contactId);
        insert opp;
          
        Change_Request__c cr = new Change_Request__c(Account__c=accId,Opportunity__c=opp.Id,Product_Type__c='Financial'
                                                     ,Type_of_Change__c='Cancellation',New_Payment_Schedule__c='50-50'
                                                     ,Edition__c=listOfEditions[0].id,Requested_By__c=sendEmail);
        List<Change_Request__c> lstCr = new  List<Change_Request__c>();
        lstCr.add(cr);
        insert lstCr;
        Test.startTest();
        SendIOMEmails.sendEmailTemplateWithTemplate(cr.Id,'Amendment_Request_Rejection');
        SendIOMEmails.sendEmailTemplateWithTemplate(opp.Id,'Opportunity_Custom_Billing_Rejection');
        Test.stopTest();
    }
}