force-app/main/default/objects/Change_Request__c/Change_Request__c.object-meta.xml
<CustomObject>
    <description>To capture details of amendment related to Opportunity/Order/Invoice.</description>
    <label>Amendment</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Salesforce record id</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Amendments (Account)</relationshipLabel>
    <relationshipName>Change_Rquests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity on which the change is being requested</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Amendments (Opportunity)</relationshipLabel>
    <relationshipName>Change_Rquests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <description>Email of the user that raised the Amendment in CRM</description>
    <label>Requested By</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Global_Constant__mdt/Global_Constant__mdt.object-meta.xml
<CustomObject>
    <description>Global Constants will hold information of constants that will be used across whole org. Like in Apex or LWC.</description>
    <label>Global Constant</label>
    <pluralLabel>Global Constants</pluralLabel>
</CustomObject>

force-app/main/default/objects/Global_Constant__mdt/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Global Constant Description</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Global_Constant__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Value</description>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Billing Contact.</description>
    <label>Billing/Invoice Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <description>Opportunity Owner Email of CRM org</description>
    <label>Sales Person Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/SendIOMEmails.cls
/**
* Created By       :   IBM(Bharath)
* Created On       :   9 May 2023
* @description     :   [GECI-1528]-Generic class for sending email with custom email tempalte
*                      
* Test Class       :   SendIOMEmails_Test(100%)
***********************************************************************************************
*/
public with sharing class SendIOMEmails {
    /**
    * @description  SendEmailTemplateWithTemplate
    * @param  crrecordId
    * @param  emailTemplate
    */
    @AuraEnabled
	public static void sendEmailTemplateWithTemplate(string crrecordId, string emailTemplate) {
        //system.Debug('recordId==>'+crrecordId);
        Global_Constant__mdt cmeta=[SELECT Id, DeveloperName, Label, Value__c, Description__c, MasterLabel FROM Global_Constant__mdt where DeveloperName='IOM_No_Reply'];

        String orgwideEmail = cmeta.Value__c;
        OrgWideEmailAddress orgEmail = [SELECT Id, Address, DisplayName, IsAllowAllProfiles, Purpose FROM OrgWideEmailAddress WHERE DisplayName=:orgwideEmail];

        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        EmailTemplate emailTemp = [SELECT Id, Subject, Body FROM EmailTemplate WHERE DeveloperName =: emailTemplate WITH SECURITY_ENFORCED];
        Change_Request__c cReq;
        Opportunity opp; 
        String targetEmail;
        Contact con = new Contact();
        if(emailTemplate == 'Amendment_Request_Rejection'){
        	cReq = [SELECT Id, Name, Account__c,Requested_By__c,Opportunity__c,Opportunity__r.Billing_Contact__c FROM Change_Request__c WHERE id=:crrecordId WITH SECURITY_ENFORCED];
            targetEmail = cReq.Requested_By__c;
            con.Id = cReq.Opportunity__r.Billing_Contact__c;
        }

        if(emailTemplate == 'Opportunity_Custom_Billing_Rejection'){
            opp = [SELECT Id,name,Sales_Person__c,Billing_Contact__c FROM Opportunity WHERE id=:crrecordId WITH SECURITY_ENFORCED];
            targetEmail=opp.Sales_Person__c;
            con.Id = opp.Billing_Contact__c;
        }

        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setTargetObjectId(con.Id);
        mail.setTreatTargetObjectAsRecipient(false);
        
        if(emailTemplate=='Amendment_Request_Rejection'){
            mail.setTemplateId(emailTemp.Id);
          	mail.setWhatId(cReq.Id);  
        }
        if(emailTemplate=='Opportunity_Custom_Billing_Rejection'){
            mail.setTemplateId(emailTemp.Id);
          	mail.setWhatId(opp.Id);  
        }
        //mail.setSenderDisplayName(orgEmail.DisplayName);
   		//mail.setReplyTo(orgEmail.Address);
        mail.setOrgWideEmailAddressId(orgEmail.Id);
        
        mail.setSaveAsActivity(false);
        mail.setToAddresses(new List<String>{targetEmail});
        emailList.add(mail);
        
        if(!emailList.isEmpty()){
            Messaging.sendEmail(emailList);
        }    
    }
    
}