force-app/main/default/objects/Opportunity/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <description>This picklist provides options for all payment schedules available</description>
    <inlineHelpText>This picklist provides options for all payment schedules available</inlineHelpText>
    <label>Payment Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Schedule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Stage</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Payment_Schedule__c/Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This object is used to stores the payment schedule datas into their respective fields.</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Payment Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Schedule__c/fields/Amounts__c.field-meta.xml
<CustomField>
    <fullName>Amounts__c</fullName>
    <description>This field will populate the percentage amount from the generated invoice.</description>
    <inlineHelpText>This field will populate the percentage amount from the generated invoice.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Due_Dates__c.field-meta.xml
<CustomField>
    <fullName>Due_Dates__c</fullName>
    <description>This field is used to store the due dates with respect to its parent invoice.</description>
    <inlineHelpText>This field is used to store the due dates with respect to its parent invoice.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <description>This field will populate the invoice id reference.</description>
    <inlineHelpText>This field will populate the invoice id reference.</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>blng__Invoice__c</referenceTo>
    <relationshipLabel>Payment Schedules</relationshipLabel>
    <relationshipName>Payment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <description>This field will populate the amount percentage.</description>
    <inlineHelpText>This field will populate the amount percentage.</inlineHelpText>
    <label>Percentage %</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvoicePaymentScheduleUpdate_Trig.cls
/**
* File:         InvoicePaymentScheduleUpdate_Trig
* Project:      Greenfield
* Created Date: 1/24/2020
* Created By:   Yash Gupta
* Modified By:  Yash Gupta (Girikon) (27 Jan 2020)
* Test Class:   InvoiceLineHandler_TrigTest
* Coverage:     97%
* *******************************************************************************************************
* @description : This class is used to insert payment schedule object based on payment schedule from opportunity on invoice.
* *******************************************************************************************************
* History:      Modified By: Yash Gupta (Girikon) [28 Jan 2020], Increase code coverage.
*               Modified By: Ashish(Girikon) [28 Jan 2020], Automatic Process for PDF genration And Email [IML2R-597]
*				Modified By: Suresh(Girikon) [31 Jan 2022], Payment Schedule Creation [IOM-666]
*/

public with sharing class InvoicePaymentScheduleUpdate_Trig implements TriggerInterface_Invoice.Runnable {
    
    List<String> lstPaymentSch = new List<String>();    
    
    /**
    * @description [Call Interface Class to fetch all the parameters or events from Invoice object]
    * @param trig [fetch the trigger parameters]
    */
    public void run(TriggerInterface_Invoice.Trig trig) 
    {
        if(trig.isAfter && trig.isUpdate){
            for(blng__Invoice__c inv : trig.newList){
                blng__Invoice__c oldInvoice = trig.oldMap.get(inv.Id);
                if(inv.Tax_Status__c == 'Tax Complete' && oldInvoice.Tax_Status__c != inv.Tax_Status__c){
                    insertSinglePaymentSchedule(inv);
                }
            }
        }
    }
    
    /**
    * @description insert Single Payment Schedule For Invoice
    * @param inv invoice record
    */
    public static void insertSinglePaymentSchedule(blng__Invoice__c inv)
    {
        List<Payment_Schedule__c> lstPaymentSchInsert = new List<Payment_Schedule__c>();
        
        Payment_Schedule__c p = new Payment_Schedule__c();
        p.Invoice__c = inv.Id;
        p.Percentage__c = '100';
        p.Amounts__c = inv.blng__TotalAmount__c;
        p.Due_Dates__c = inv.blng__DueDate__c;
        lstPaymentSchInsert.add(p);
        
        if(!lstPaymentSchInsert.isEmpty() && Schema.sObjectType.Payment_Schedule__c.isCreateable()){
            insert lstPaymentSchInsert;
        }  
    }
}