force-app/main/default/objects/Contact/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>user type</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>x_1st Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>Defines the user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Look up to Account record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Edition Mappings (Account)</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/CC_Status__c.field-meta.xml
<CustomField>
    <fullName>CC_Status__c</fullName>
    <description>Formula field, fetches value from Edition Customer Center status</description>
    <formula>TEXT(Edition__r.Customer_Center_Status__c)</formula>
    <label>CC Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Look up to Contact record</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Not a Customer Center Contact.</errorMessage>
        <filterItems>
            <field>Contact.IOM_Contact_Identifier__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/First_Login_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>First_Login_Date_Time__c</fullName>
    <description>To capture first login date time to a particular edition.</description>
    <label>First Login Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <description>Defines status of account contact relationship</description>
    <label>Relationship Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Role of user in selected edition for selected account.</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Center_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Services_Team__c/Customer_Services_Team__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object defines the support information</description>
    <label>Customer Services Team</label>
    <nameField>
        <label>Customer Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Services Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Services_Team__c/fields/Business_Hours__c.field-meta.xml
<CustomField>
    <fullName>Business_Hours__c</fullName>
    <description>Team&apos;s Working Hours</description>
    <inlineHelpText>Team&apos;s Working Hours</inlineHelpText>
    <label>Business Hours</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Services_Team__c/fields/Hotline_Number__c.field-meta.xml
<CustomField>
    <fullName>Hotline_Number__c</fullName>
    <inlineHelpText>Region Hotline Number</inlineHelpText>
    <label>Hotline Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Business_Hours__c.field-meta.xml
<CustomField>
    <fullName>Business_Hours__c</fullName>
    <inlineHelpText>Support Business Hours</inlineHelpText>
    <label>Business Hours</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Customer_Support_Team__c.field-meta.xml
<CustomField>
    <fullName>Customer_Support_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Support Team</label>
    <referenceTo>Customer_Services_Team__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Director__c.field-meta.xml
<CustomField>
    <fullName>Edition_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Lookup Field store the id of the Edition Director.</description>
    <label>Edition Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Edition_Image_URL__c</fullName>
    <description>This Field stores Edition Logo Id.</description>
    <label>Edition Logo Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Website__c.field-meta.xml
<CustomField>
    <fullName>Edition_Website__c</fullName>
    <description>This field store URL of the Edition Website.</description>
    <label>Edition Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Hotline_Number__c.field-meta.xml
<CustomField>
    <fullName>Hotline_Number__c</fullName>
    <label>Hotline Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>This field stores the Start date of Edition.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Support_Email__c.field-meta.xml
<CustomField>
    <fullName>Support_Email__c</fullName>
    <inlineHelpText>Customer Services Email</inlineHelpText>
    <label>Support Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <description>This Field store the venue of Edition.</description>
    <label>Venue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Event_Edition_Email_Template__c/Event_Edition_Email_Template__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Use as email templates specific to an Event Edition</description>
    <label>Event Edition Email Template</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Edition Email Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Edition_Email_Template__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>Display the content of the email</description>
    <inlineHelpText>Display the content of the email</inlineHelpText>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event_Edition_Email_Template__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <description>Define name of the edition</description>
    <inlineHelpText>Define name of the edition</inlineHelpText>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Event Edition Email Templates</relationshipLabel>
    <relationshipName>Event_Edition_Email_Templates</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Edition_Email_Template__c/fields/From_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>From_Email_Address__c</fullName>
    <description>Choose the email address from which email will be sent</description>
    <label>From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Org_Wide_From_Email_Addresses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Edition_Email_Template__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Center_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Edition_Email_Template__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Defines subject on the Template</description>
    <inlineHelpText>Defines subject on the Template</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Edition_Email_Template__c/fields/Template_Code__c.field-meta.xml
<CustomField>
    <fullName>Template_Code__c</fullName>
    <description>Unicode to define template</description>
    <inlineHelpText>Put the Unicode to define template</inlineHelpText>
    <label>Template Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Tabs__c/Event_Tabs__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Event Setting. Defines the different tabs and tab properties for a particular event.</description>
    <label>Event Tab</label>
    <nameField>
        <displayFormat>ET-{0000000}</displayFormat>
        <label>Event Tabs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Tabs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Tabs__c/fields/ExtTabId__c.field-meta.xml
<CustomField>
    <fullName>ExtTabId__c</fullName>
    <label>External Tab Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Tabs__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Standard_Tab_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Customer_Center_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Tabs__c/fields/Tab_Code__c.field-meta.xml
<CustomField>
    <fullName>Tab_Code__c</fullName>
    <displayFormat>T-{0000}</displayFormat>
    <label>Tab Code</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Event_Tabs__c/fields/Tab_Type__c.field-meta.xml
<CustomField>
    <fullName>Tab_Type__c</fullName>
    <description>Defines the different types of tabs like Standard, Custom</description>
    <label>Tab Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IMCC_WelcomeEmailNotification.cls
/**
* Created/Modified By :(Arushi [IMCC-5307])
* Created On:          03/07/2023 
* @description  :      As a primary and/or secondary admin, I want to be able to trigger an email to the relevant 
                       invited team members. So that they are aware they have been invited to the platform.
* Methods:             adminNotification,teamMemberNotification
* Test Class:          IMCC_WelcomeEmailNotificationTest
**/
public class IMCC_WelcomeEmailNotification {
    
    public static void adminNotification(Set<Id> teamMemberIds, Contact_Edition_Mapping__c admin, String templateCode){
        Id sConId;
        set<Id> sEventId = new set<Id>();
        List<User> adminUser = new List<User>();
        boolean bypass = true;
        try
        {
            List<Contact_Edition_Mapping__c> lstContactMapping = [SELECT Id, Role__c, Account__c, Account__r.Name, Contact__c
                                                                  ,Edition__c,Edition__r.Name, CC_Status__c,Edition__r.Edition_Code__c
                                                                  ,Edition__r.Edition_Image_URL__c,Relationship_Status__c
                                                                  ,Access_Type__c,Edition__r.Business_Hours__c,Edition__r.Support_Email__c
                                                                  ,Edition__r.Edition_Website__c,Edition__r.Start_Date__c,Edition__r.Venue__c
                                                                  ,Edition__r.Customer_Support_Team__r.Business_Hours__c
                                                                  ,Edition__r.Customer_Support_Team__r.Hotline_Number__c
                                                                  ,Contact__r.Email,Contact__r.Phone,Contact__r.Name
                                                                  FROM Contact_Edition_Mapping__c where Id IN :teamMemberIds WITH SECURITY_ENFORCED];
            
            for(Contact_Edition_Mapping__c cem : lstContactMapping){
                sEventId.add(cem.Edition__c);
            }
            
            if(admin.Contact__c != null){ sConId = admin.Contact__c; }
            
            List<Messaging.SingleEmailMessage> mails =  new List<Messaging.SingleEmailMessage>();
            //Get existing user of contact with community profile
            if(Schema.sObjectType.User.isAccessible() || bypass){
                adminUser = [SELECT Id,Email,username,firstname,ContactId,Contact.account.name,Contact.name,Contact.email,IsActive,IsPortalEnabled FROM User where ContactId =: sConId AND IsPortalEnabled=true AND Profile.Name='IM Customer Community Login User' AND IsActive=true];  
            }
            
            List<Event_Edition_Email_Template__c> listEEET = [SELECT Role__c,Template_Code__c, Edition__c, Subject__c
                                                              , From_Email_Address__c, Content__c FROM Event_Edition_Email_Template__c
                                                              WHERE Template_Code__c =: templateCode AND Edition__c IN:sEventId WITH SECURITY_ENFORCED];
            
            Map<String,Event_Edition_Email_Template__c> mapEEET = new Map<String,Event_Edition_Email_Template__c>();
            Map<String,String> mapOrgEMailAddr = new Map<String,String>();
            
            for(Event_Edition_Email_Template__c eeet : listEEET){                                
                mapEEET.put(eeet.Edition__c,eeet);
                if(String.isNotBlank(eeet.From_Email_Address__c)){mapOrgEMailAddr.put(eeet.From_Email_Address__c,null);}
            }
            if(Schema.sObjectType.OrgWideEmailAddress.isAccessible() || bypass){
                List<OrgWideEmailAddress> listOrgAddresses = [SELECT Id,Address FROM OrgWideEmailAddress WHERE Address IN:mapOrgEMailAddr.keySet()];
                for(OrgWideEmailAddress orgAdd : listOrgAddresses){
                    mapOrgEMailAddr.put(orgAdd.Address, orgAdd.Id);
                }
            }
            
            for(Contact_Edition_Mapping__c cem : lstContactMapping){
                
                if(mapEEET.containsKey(cem.Edition__c)){
                    Event_Edition_Email_Template__c template = mapEEET.get(cem.Edition__c);
                    String htmlValue = template.Content__c;
                    
                    String teamMember = cem.Contact__r.Name;
                    teamMember = teamMember!=null?teamMember:'';
                    String firstName = admin.Contact__r.Name;
                    firstName = firstName!=null?firstName:'';
                    //String userName = mapConUser.get(cem.Contact__c).userName;
                    //userName = userName!=null?userName:'';
                    String eventName = cem.Edition__r.Name!=null?cem.Edition__r.Name:'';
                    String hotlineNumber = cem.Edition__r.Customer_Support_Team__r.Hotline_Number__c!=null?cem.Edition__r.Customer_Support_Team__r.Hotline_Number__c:''; 
                    String supportEmail = cem.Edition__r.Support_Email__c!=null?cem.Edition__r.Support_Email__c:'';
                    
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    
                    htmlValue = htmlValue!=null?htmlValue:'';
                    htmlValue = htmlValue.replace('{EVENT}',eventName);                    
                    htmlValue = htmlValue.replace('{NAME}',firstName);               
                    //htmlValue = htmlValue.replace('{UserName}',userName);
                    htmlValue = htmlValue.replace('{TEAM MEMBER}',teamMember);
                    htmlValue = htmlValue.replace('{SupportEmail}',supportEmail);
                    htmlValue = htmlValue.replace('{HotlineNumber}',hotlineNumber);
                    
                    String emailSubject = template.Subject__c;
                    emailSubject = emailSubject.replace('{EVENT}', eventName);
                    
                    mail.setSubject(emailSubject);
                    mail.setHtmlBody(htmlValue);
                    mail.setSaveAsActivity(false);
                    mail.setTargetObjectId(adminUser[0].Id);
                    if(String.isNotBlank(template.From_Email_Address__c)){
                        Id oweaId = mapOrgEMailAddr.get(template.From_Email_Address__c);
                        if(oweaId !=null){
                            mail.setOrgWideEmailAddressId(oweaId);
                        }
                    }
                    mails.add(mail);
                }
            }
            
            if(!mails.isEmpty()){
                Messaging.sendEmail(mails,true);
            }
        }
        catch(Exception ex) {
            HandleAllCustomException.logException(ex,'Contact_Edition_Mapping__c', 'Exception in adminNotification');
        }     
    }
    
    public static void teamMemberNotification(Set<Id> teamMemberIds, String templateCode,String tabId, string tabName){
        
        set<Id> sConId = new set<Id>(); 
        set<Id> sEventId = new set<Id>();
        Map<Id,User> mapConUser = new Map<Id,User>();
        List<User> lstUsr = new List<User>();
        boolean bypass = true;
        String commURL = System.Label.CommunityURL;
        String documentURL = System.Label.Document_URL;
        
        try
        {
            List<Contact_Edition_Mapping__c> lstContactMapping = [SELECT Id, Role__c, Account__c, Account__r.Name, Contact__c
                                                                  ,Edition__c,Edition__r.Name, CC_Status__c,Edition__r.Edition_Code__c
                                                                  ,Edition__r.Edition_Image_URL__c,Relationship_Status__c
                                                                  ,Access_Type__c,Edition__r.Business_Hours__c,Edition__r.Support_Email__c
                                                                  ,Edition__r.Edition_Website__c,Edition__r.Start_Date__c,Edition__r.Venue__c
                                                                  ,Edition__r.Customer_Support_Team__r.Business_Hours__c
                                                                  ,Edition__r.Customer_Support_Team__r.Hotline_Number__c
                                                                  ,Contact__r.Email,Contact__r.Phone,First_Login_Date_Time__c
                                                                  FROM Contact_Edition_Mapping__c where Id IN :teamMemberIds WITH SECURITY_ENFORCED];
            
            for(Contact_Edition_Mapping__c cem : lstContactMapping){
                sConId.add(cem.Contact__c);
                sEventId.add(cem.Edition__c);
            }
            
           
            List<Messaging.SingleEmailMessage> mails =  new List<Messaging.SingleEmailMessage>();
            //Get existing user of contact with community profile
            if(Schema.sObjectType.User.isAccessible() || bypass){
                lstUsr = [SELECT Id,Email,username,firstname,ContactId,Contact.account.name,Contact.name,Contact.email,IsActive,IsPortalEnabled FROM User where ContactId IN : sConId AND IsPortalEnabled=true AND Profile.Name='IM Customer Community Login User' AND IsActive=true];  
                for(User oUser : lstUsr){
                    mapConUser.put(oUser.ContactId,oUser);
                }
            }
            
            List<Event_Edition_Email_Template__c> listEEET = [SELECT Role__c,Template_Code__c, Edition__c, Subject__c
                                                              , From_Email_Address__c, Content__c FROM Event_Edition_Email_Template__c
                                                              WHERE Template_Code__c =: templateCode AND Edition__c IN:sEventId WITH SECURITY_ENFORCED];
            
            List<Event_Tabs__c> etl = new List<Event_Tabs__c>();
            if(string.isNotBlank(tabId)){
                 etl = [SELECT ExtTabId__c,Tab_Code__c,Tab_Type__c,Standard_Tab_Type__c 
                        FROM Event_Tabs__c WHERE Tab_Code__c =:tabId WITH SECURITY_ENFORCED];
            }
            Map<String,Event_Edition_Email_Template__c> mapEEET = new Map<String,Event_Edition_Email_Template__c>();
            Map<String,String> mapOrgEMailAddr = new Map<String,String>();
            
            for(Event_Edition_Email_Template__c eeet : listEEET){                                
                mapEEET.put(eeet.Edition__c,eeet);
                if(String.isNotBlank(eeet.From_Email_Address__c)){mapOrgEMailAddr.put(eeet.From_Email_Address__c,null);}
            }
            if(Schema.sObjectType.OrgWideEmailAddress.isAccessible() || bypass){
                List<OrgWideEmailAddress> listOrgAddresses = [SELECT Id,Address FROM OrgWideEmailAddress WHERE Address IN:mapOrgEMailAddr.keySet()];
                for(OrgWideEmailAddress orgAdd : listOrgAddresses){
                    mapOrgEMailAddr.put(orgAdd.Address, orgAdd.Id);
                }
            }
            
            for(Contact_Edition_Mapping__c cem : lstContactMapping){
                
                if(mapEEET.containsKey(cem.Edition__c)){
                    Event_Edition_Email_Template__c template = mapEEET.get(cem.Edition__c);
                    String htmlValue = template.Content__c;
                    
                    String firstName = mapConUser.get(cem.Contact__c).firstName;
                    firstName = firstName!=null?firstName:'';
                    //String userName = mapConUser.get(cem.Contact__c).userName;
                    //userName = userName!=null?userName:'';
                    String eventName = cem.Edition__r.Name!=null?cem.Edition__r.Name:'';
                    String hotlineNumber = cem.Edition__r.Customer_Support_Team__r.Hotline_Number__c!=null?cem.Edition__r.Customer_Support_Team__r.Hotline_Number__c:''; 
                    String supportEmail = cem.Edition__r.Support_Email__c!=null?cem.Edition__r.Support_Email__c:'';
                   
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    
                    htmlValue = htmlValue!=null?htmlValue:'';
                    htmlValue = htmlValue.replace('{EVENT}',eventName);                    
                    htmlValue = htmlValue.replace('{NAME}',firstName);               
                    htmlValue = htmlValue.replace('{SupportEmail}',supportEmail);
                    htmlValue = htmlValue.replace('{HotlineNumber}',hotlineNumber);
                    if(!etl.isEmpty()){
                        htmlValue = htmlValue.replace('{Task Link}','<a href="' + commURL+ tabName +'?accId='+cem.Account__c +'&edcode='+cem.Edition__r.Edition_Code__c+'&tabId='+etl[0].Tab_Code__c+'">here</a>');
                    }
                    system.debug('htmlValue==='+htmlValue);
                    String emailSubject = template.Subject__c;
                    emailSubject = emailSubject.replace('{EVENT}', eventName);
                    
                    mail.setSubject(emailSubject);
                    mail.setHtmlBody(htmlValue);
                    mail.setSaveAsActivity(false);
                    mail.setTargetObjectId(mapConUser.get(cem.Contact__c).Id);
                    if(String.isNotBlank(template.From_Email_Address__c)){
                        Id oweaId = mapOrgEMailAddr.get(template.From_Email_Address__c);
                        if(oweaId !=null){
                            mail.setOrgWideEmailAddressId(oweaId);
                        }
                    }
                    mails.add(mail);
                }
                else{
                     String errorMsg = (!mapConUser.containsKey(cem.Contact__c)?System.Label.IMCC_Welcome_Email_Error_Msg3:System.Label.IMCC_Welcome_Email_Error_Msg4); // Using labels for displaying/populating(error message field on CEM) the error message on screen duirng sending welcome email
                }
            }
            
            if(!mails.isEmpty()){
                Messaging.sendEmail(mails,true);
            }
        }
        catch(Exception ex) {
            HandleAllCustomException.logException(ex,'Contact_Edition_Mapping__c', 'Exception in teamMemberNotification');
        }     
    }
    
}