force-app/main/default/objects/Contact/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>user type</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>x_1st Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>Defines the user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Look up to Account record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Edition Mappings (Account)</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/CC_Status__c.field-meta.xml
<CustomField>
    <fullName>CC_Status__c</fullName>
    <description>Formula field, fetches value from Edition Customer Center status</description>
    <formula>TEXT(Edition__r.Customer_Center_Status__c)</formula>
    <label>CC Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Look up to Contact record</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Not a Customer Center Contact.</errorMessage>
        <filterItems>
            <field>Contact.IOM_Contact_Identifier__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <description>Defines status of account contact relationship</description>
    <label>Relationship Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Services_Team__c/Customer_Services_Team__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This object defines the support information</description>
    <label>Customer Services Team</label>
    <nameField>
        <label>Customer Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Services Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Services_Team__c/fields/Business_Hours__c.field-meta.xml
<CustomField>
    <fullName>Business_Hours__c</fullName>
    <description>Team&apos;s Working Hours</description>
    <inlineHelpText>Team&apos;s Working Hours</inlineHelpText>
    <label>Business Hours</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Services_Team__c/fields/Hotline_Number__c.field-meta.xml
<CustomField>
    <fullName>Hotline_Number__c</fullName>
    <inlineHelpText>Region Hotline Number</inlineHelpText>
    <label>Hotline Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Business_Hours__c.field-meta.xml
<CustomField>
    <fullName>Business_Hours__c</fullName>
    <inlineHelpText>Support Business Hours</inlineHelpText>
    <label>Business Hours</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Customer_Support_Team__c.field-meta.xml
<CustomField>
    <fullName>Customer_Support_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Support Team</label>
    <referenceTo>Customer_Services_Team__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Director__c.field-meta.xml
<CustomField>
    <fullName>Edition_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Lookup Field store the id of the Edition Director.</description>
    <label>Edition Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Edition_Image_URL__c</fullName>
    <description>This Field stores Edition Logo Id.</description>
    <label>Edition Logo Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Website__c.field-meta.xml
<CustomField>
    <fullName>Edition_Website__c</fullName>
    <description>This field store URL of the Edition Website.</description>
    <label>Edition Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Hotline_Number__c.field-meta.xml
<CustomField>
    <fullName>Hotline_Number__c</fullName>
    <label>Hotline Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>This field stores the Start date of Edition.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Support_Email__c.field-meta.xml
<CustomField>
    <fullName>Support_Email__c</fullName>
    <inlineHelpText>Customer Services Email</inlineHelpText>
    <label>Support Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <description>This Field store the venue of Edition.</description>
    <label>Venue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Event_Edition_Email_Template__c/Event_Edition_Email_Template__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Use as email templates specific to an Event Edition</description>
    <label>Event Edition Email Template</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Edition Email Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Edition_Email_Template__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>Display the content of the email</description>
    <inlineHelpText>Display the content of the email</inlineHelpText>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event_Edition_Email_Template__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <description>Define name of the edition</description>
    <inlineHelpText>Define name of the edition</inlineHelpText>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Event Edition Email Templates</relationshipLabel>
    <relationshipName>Event_Edition_Email_Templates</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Edition_Email_Template__c/fields/From_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>From_Email_Address__c</fullName>
    <description>Choose the email address from which email will be sent</description>
    <label>From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Org_Wide_From_Email_Addresses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Edition_Email_Template__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Defines subject on the Template</description>
    <inlineHelpText>Defines subject on the Template</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Edition_Email_Template__c/fields/Template_Code__c.field-meta.xml
<CustomField>
    <fullName>Template_Code__c</fullName>
    <description>Unicode to define template</description>
    <inlineHelpText>Put the Unicode to define template</inlineHelpText>
    <label>Template Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IMCC_WelcomeEmailCtrl.cls
/**
* Created By    :  Girikon(Keertiraj)
* Created on    : 18/10/2021
* @description  : The purpose of this class is to show data on new user welcome email visualforce component.
* Test Class    : IMCC_WelcomeEmailCtrl_Test(100%)
*/

public without sharing class IMCC_WelcomeEmailCtrl {

    /**@description Contact Id */
    public string sContactId {get;set;}
    
    /**@description IMCC_WelcomeEmailCtrl Constructor */
    public IMCC_WelcomeEmailCtrl(){
        system.debug(LoggingLevel.Debug, '@@@@@@@@@@@@');
    }
    
    /**@description to get Welcome Email Content and Subject 
    * @return EmailContent
    */
    public EmailContent getWelcomeEmailContent(){
        return welcomeEmailContentData(sContactId, null);
    }

    /**@description to get Welcome Email Content and Subject 
    * @param contactId
    * @param editionId
    * @return EmailContent
    */
    public EmailContent welcomeEmailContentData(String contactId ,String editionId){
        String body = '';
        /*String commURL = System.Label.CommunityURL;
        String documentURL = System.Label.Document_URL;
        if(String.isNotBlank(contactId) && Schema.sObjectType.Contact.isAccessible()){
            List<Contact> conList = [SELECT Id,FirstName,Account.Name,Contact_Edition_Mapping__c,Contact_Edition_Mapping__r.Edition__c FROM Contact where Id=:contactId LIMIT 1]; 
            List<User> user = [SELECT Id,UserName,FirstName FROM User where ContactId=:contactId LIMIT 1];
            
            if(String.isBlank(editionId) && !conList.isEmpty() && String.isNotBlank(conList.get(0).Contact_Edition_Mapping__c)){
                editionId = conList.get(0).Contact_Edition_Mapping__r.Edition__c;

                List<Event_Edition_Email_Template__c> listEEET = [SELECT Content__c, Subject__c, From_Email_Address__c, Edition__c FROM Event_Edition_Email_Template__c WHERE Edition__c=:editionId AND Template_Code__c='WELNew' WITH SECURITY_ENFORCED];
                if(!listEEET.isEmpty()){
                    Event_Edition_Email_Template__c template = listEEET.get(0);
                    body = template.Content__c;
                    
                    List<Contact_Edition_Mapping__c> listCEM = [SELECT Id, Account__c,Account__r.Name, Contact__c,Edition__c,Edition__r.Name, CC_Status__c,Edition__r.Edition_Code__c,Edition__r.Edition_Image_URL__c,Relationship_Status__c, Access_Type__c,Edition__r.Business_Hours__c,Edition__r.Support_Email__c,Edition__r.Edition_Website__c,Edition__r.Start_Date__c,Edition__r.Venue__c,Edition__r.Customer_Support_Team__r.Business_Hours__c,Edition__r.Customer_Support_Team__r.Hotline_Number__c FROM Contact_Edition_Mapping__c WHERE Id=:conList.get(0).Contact_Edition_Mapping__c WITH SECURITY_ENFORCED];
                    if(!listCEM.isEmpty()){
                        Contact_Edition_Mapping__c conEvntMap = listCEM.get(0);
                        String companyName = conEvntMap.Account__r.Name!=null?conEvntMap.Account__r.Name:'';                
                        String firstName = (!user.isEmpty()?user.get(0).FirstName:'');
                        String userName = (!user.isEmpty()?user.get(0).UserName:'');
                        String eventName = conEvntMap.Edition__r.Name!=null?conEvntMap.Edition__r.Name:'';
                        String businessHours = conEvntMap.Edition__r.Business_Hours__c!=null?conEvntMap.Edition__r.Business_Hours__c:''; 
                        String cSTeamBusinessHours = conEvntMap.Edition__r.Customer_Support_Team__r.Business_Hours__c!=null?conEvntMap.Edition__r.Customer_Support_Team__r.Business_Hours__c:''; 
                        String hotlineNumber = conEvntMap.Edition__r.Customer_Support_Team__r.Hotline_Number__c!=null?conEvntMap.Edition__r.Customer_Support_Team__r.Hotline_Number__c:''; 
                        String eventVenue = conEvntMap.Edition__r.Venue__c!=null?conEvntMap.Edition__r.Venue__c:''; 
                        String eventWebsite = conEvntMap.Edition__r.Edition_Website__c!=null?conEvntMap.Edition__r.Edition_Website__c:'';
                        Datetime eventStartDate = conEvntMap.Edition__r.Start_Date__c!=null?conEvntMap.Edition__r.Start_Date__c:null;           
                        String supportEmail = conEvntMap.Edition__r.Support_Email__c!=null?conEvntMap.Edition__r.Support_Email__c:'';
                        
                        body = body.replace('{Event Name}',eventName);  
                        body = body.replace('{COMPANY NAME}',companyName);
                        body = body.replace('{Firstname}',firstName);
                        body = body.replace('{UserName}',userName);

                        body = body.replace('{Venue}',eventVenue);
                        body = body.replace('{Website}',eventWebsite);
                        body = body.replace('{SupportEmail}',supportEmail);
                        body = body.replace('{HotlineNumber}',hotlineNumber);
                        if(conEvntMap.Edition__r.Business_Hours__c !=null){
                            body = body.replace('{BusinessHours}',businessHours);
                        }
                        else{
                            body = body.replace('{BusinessHours}',cSTeamBusinessHours);
                        }     
                        if(eventStartDate !=null){
                            body = body.replace('{StartDate}',IMCC_UtilityMethod_Handler.getFormattedDateWithSuperScript(eventStartDate));
                        }                    
                        //body = body.replace('{#comm_url#}',commUrl+'?edcode='+conEvntMap.Edition__r.Edition_Code__c);
                        body = body.replaceAll(documentURL, commURL+'/IMCC');
                    }
                }
            }      
        }*/
        EmailContent obj = new EmailContent();
        obj.body = body;
        return obj;
    }
    
    /**@description EmailContent*/
    public class EmailContent{
        /**@description body*/
        public String body{get;set;}
    }
}