force-app/main/default/objects/Contact/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>user type</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>x_1st Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>Defines the user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Look up to Account record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Edition Mappings (Account)</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/CC_Status__c.field-meta.xml
<CustomField>
    <fullName>CC_Status__c</fullName>
    <description>Formula field, fetches value from Edition Customer Center status</description>
    <formula>TEXT(Edition__r.Customer_Center_Status__c)</formula>
    <label>CC Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Completed_Purchase_Summaries__c.field-meta.xml
<CustomField>
    <fullName>Completed_Purchase_Summaries__c</fullName>
    <description>Purchase Summaries Completed by Customer</description>
    <inlineHelpText>Purchase Summaries Completed by Customer</inlineHelpText>
    <label>Completed Purchase Summaries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Purchase_Summary_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Look up to Contact record</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Not a Customer Center Contact.</errorMessage>
        <filterItems>
            <field>Contact.IOM_Contact_Identifier__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Feathr_Unique_Link__c.field-meta.xml
<CustomField>
    <fullName>Feathr_Unique_Link__c</fullName>
    <description>Feathr Unique Link</description>
    <label>Feathr Unique Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/First_Login_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>First_Login_Date_Time__c</fullName>
    <description>To capture first login date time to a particular edition.</description>
    <label>First Login Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/isSecondary__c.field-meta.xml
<CustomField>
    <fullName>isSecondary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag if the contact is assigned to work on selected Edition.</description>
    <label>IS Secondary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Popup_Marked_as_Read__c.field-meta.xml
<CustomField>
    <fullName>Popup_Marked_as_Read__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use to track if greeting pop up message is read by customer</description>
    <label>Popup Marked as Read</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Primary_Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Contact Edition Mappings (Sharer Contact Edition Mapping)</relationshipLabel>
    <relationshipName>Sharer_Contact_Edition_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <description>Defines status of account contact relationship</description>
    <label>Relationship Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Role of user in selected edition for selected account.</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Center_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Company_Profile_Submission_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Company_Profile_Submission_Due_Date__c</fullName>
    <label>Company Profile Submission Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Contractor_Nomination_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Nomination_Due_Date__c</fullName>
    <description>Contractor Nomination Due Date</description>
    <label>Contractor Nomination Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>shows the last date, user can submit the badges</description>
    <label>Badge Submission Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Director__c.field-meta.xml
<CustomField>
    <fullName>Edition_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Lookup Field store the id of the Edition Director.</description>
    <label>Edition Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Event_Setting__c.field-meta.xml
<CustomField>
    <fullName>Event_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Setting</label>
    <referenceTo>Event_Setting__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Expocad_Event_Code__c.field-meta.xml
<CustomField>
    <fullName>Expocad_Event_Code__c</fullName>
    <description>contains expocad event code which will be used in formula Floorplan url</description>
    <label>Expocad Event Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Form_Setting__c.field-meta.xml
<CustomField>
    <fullName>Form_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Setting</label>
    <referenceTo>Form_Setting__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/SizedLogo__c.field-meta.xml
<CustomField>
    <fullName>SizedLogo__c</fullName>
    <formula>IF( ISPICKVAL(Logo_Shape__c, &apos;Rectangle&apos;), IMAGE(PDF_Logo_URL__c, &quot;Rectangle&quot;, 100, 200), If(ISPICKVAL(Logo_Shape__c, &apos;Long Rectangle&apos;), IMAGE(PDF_Logo_URL__c, &quot;Long Rectangle&quot;, 50, 250), If(ISPICKVAL(Logo_Shape__c, &apos;Square&apos;), IMAGE(PDF_Logo_URL__c, &quot;Square&quot;, 200, 200), IMAGE(PDF_Logo_URL__c, &quot;Small Square&quot;, 100, 100))))</formula>
    <label>Edition Logo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Stand_Design_Completion_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Stand_Design_Completion_Due_Date__c</fullName>
    <description>Stand Design Completion Due Date</description>
    <label>Stand Design Completion Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Stand_Setting__c.field-meta.xml
<CustomField>
    <fullName>Stand_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LookUp for Stand Setting</description>
    <label>Stand Setting</label>
    <referenceTo>Stand_Setting__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>This field stores the Start date of Edition.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event_Setting__c/Event_Setting__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child of Edition. This will set the tab visibility on the home page of a particular event.</description>
    <label>Event Setting</label>
    <nameField>
        <label>Event Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Setting__c/Form_Setting__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will show list of forms which will be visible to which user type. It contains different form allocations.</description>
    <label>Form Setting</label>
    <nameField>
        <label>Form Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stand_Setting__c/Stand_Setting__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child of Edition. This will set the stand visibility on the home page of a particular event.</description>
    <label>Stand Setting</label>
    <nameField>
        <label>Stand Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stand Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stand_Setting__c/fields/Allow_Contractor_Nomination__c.field-meta.xml
<CustomField>
    <fullName>Allow_Contractor_Nomination__c</fullName>
    <defaultValue>false</defaultValue>
    <description>allow Contractor Nomination</description>
    <label>Allow Contractor Nomination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Triggers_Configuration__mdt/Triggers_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>IM Customer Center - This setting will be used to manage triggers executions i.e. ON/OFF a trigger.</description>
    <label>Triggers Configuration</label>
    <pluralLabel>Triggers Configurations</pluralLabel>
</CustomObject>

force-app/main/default/classes/IMCC_UtilityMethods.cls
/**
* Created By    :  Girikon(Keertiraj)
* Created on    : 05/10/2021
* @description  : The purpose of this class is to keep common reusable functionalities at single place.
* Modified By     :  Girikon(Arushi[IMCC-763])
* Modified On     :  28/03/2022
* @description   :  On a new customer username creation in Salesforce, currently there are extra characters created along with the email in the username. This will need to be removed for the ease of use from customer's side. 
* Test Class    : (92%), IMCC_UtilityMethods_Test (83%),IMCC_AssetTriggerHandler_Test(58%)
* Modified By : Shiv Raghav (Ticket No - IMCC-2815 ), Garima Gupta(IMCC-4529, 31st Aug 2022),[Aishwarya Kumar IMCC-4936 16 Dec 2022]
* @description : Added null check as part of IMCC-2815 ticket
*/

public without sharing class IMCC_UtilityMethods {
    public static Map<String,Triggers_Configuration__mdt> mapTriggerConfiguration = new Map<String,Triggers_Configuration__mdt>();

    /**
    * @description : Prepare customer community user list
    * @param profileId
    * @param contacts
    * @return : List<User>
    **/
    public static List<User> prepareCommunityUser(Id profileId, List<Contact> contacts){
        //Initialization of community user list
        List<User> commUserLst = new List<User>();
        for(Contact con : contacts){
            String aliasName = (String.isNotBlank(con.FirstName)?String.valueOf(con.FirstName.substring(0,1)):'') + String.valueOf(con.LastName.substring(0,1));

            User commUsr = new User(ContactId = con.Id,
                                    Username = con.Email,
                                    FirstName = con.FirstName,
                                    LastName = con.LastName,
                                    Email = con.Email,
                                    Alias = aliasName,
                                    ProfileId = profileId,
                                    FederationIdentifier = con.Email,
                                    EmailEncodingKey = 'UTF-8',
                                    LanguageLocaleKey = 'en_US',
                                    LocaleSidKey = 'en_US',
                                    TimeZoneSidKey = 'America/Los_Angeles');
            commUserLst.add(commUsr);                     
        }
        return commUserLst;        
    }
    
    /**
    * @description : Get Community URL
    * @return : String
    **/
    public static String getCommunityURL(){
        Network myNetwork = new Network();
        if(Schema.sObjectType.Network.isAccessible()){
            myNetwork = [SELECT Id FROM Network WHERE Name ='IMCustomerCenter'];
        }
        return Network.getLoginUrl(myNetwork.Id);
    }
    
    /**
    * @description : get Comm Profile
    * @return : Id
    **/
    public static Id getCommProfile(){
        String commProfileId; 
        String commUsrProfile = (String.isNotBlank(Label.IMCC_Community_User_Profile)?Label.IMCC_Community_User_Profile:'IM Customer Community Login User');
        //Fetch community user profile        
        List<Profile> communityProfile = [SELECT Id FROM Profile WHERE Name=:commUsrProfile]; 
        if(!communityProfile.isEmpty()){
            commProfileId = communityProfile.get(0).Id;
        } 
        return commProfileId;
    }

    /**
    * @description : get Contact Edition Mappings
    * @param eventCode
    * @param accountId
    * @return : Map<String,Object>
    **/
    public static Map<String,Object> getContactEditionMappings(String eventCode, String accountId){
        User u = [SELECT id,Name,ContactId FROM User WHERE Id =: UserInfo.getUserId() WITH SECURITY_ENFORCED]; 
        List<Contact_Edition_Mapping__c> conEdMapLst = [SELECT Id,
        Name,
        Access_Type__c,
        Account__c,
        Account__r.Name,
        CC_Status__c,
        Contact__c,
        First_Login_Date_Time__c,        //IMCC-4936 adding parameter in query
        Relationship_Status__c,        
        Completed_Purchase_Summaries__c,      
        Primary_Contact_Edition_Mapping__c,
        Primary_Contact_Edition_Mapping__r.Feathr_Unique_Link__c,
        Feathr_Unique_Link__c,   
        Role__c,
        isSecondary__c,
        Edition__c, 
        Edition__r.Name,        
        Edition__r.Edition_Code__c,  
        Edition__r.Form_Setting__c,
        Edition__r.Event_Setting__c,
        Edition__r.Due_Date__c,
        Edition__r.SizedLogo__c,
        Popup_Marked_as_Read__c,
        Edition__r.Company_Profile_Submission_Due_Date__c,
        Edition__r.Contractor_Nomination_Due_Date__c,        
        Edition__r.Event_Type__c,
        Edition__r.Stand_Setting__r.Allow_Contractor_Nomination__c,
        Edition__r.Stand_Design_Completion_Due_Date__c,
        Edition__r.Expocad_Event_Code__c,
        Edition__r.Start_Date__c
        FROM Contact_Edition_Mapping__c 
        WHERE Contact__c =: u.ContactId 
        AND Account__c =: accountId 
        AND Relationship_Status__c = 'Active' 
        AND Edition__r.Edition_Code__c =: eventCode WITH SECURITY_ENFORCED];

        Set<Id> setIds = new Set<Id>();
        Contact_Edition_Mapping__c conRecrod = new Contact_Edition_Mapping__c();
        if(!conEdMapLst.isEmpty()){
            setIds.add(conEdMapLst.get(0).Id);
            if(String.isNotBlank(conEdMapLst.get(0).Primary_Contact_Edition_Mapping__c)){
                setIds.add(conEdMapLst.get(0).Primary_Contact_Edition_Mapping__c);
            }
            conRecrod =  conEdMapLst.get(0);
        }       
        return new Map<String,Object>{
            'cemList' =>conEdMapLst,
            'cem' => conRecrod,
            'cemIds' => setIds
        };       
    }

    /**
    * @description get Custom meta data info
    * @param name
    * @return Triggers_Configuration__mdt
    */
    public static Triggers_Configuration__mdt getTriggerConfiguration(String name){
        Triggers_Configuration__mdt tconfig;
        if(!Test.isRunningTest()){tconfig = [SELECT Before_Insert__c, Before_Update__c, Before_Delete__c, After_Insert__c, After_Update__c, After_Delete__c, After_Undelete__c FROM Triggers_Configuration__mdt WHERE Trigger_Name__c=:name LIMIT 1];}
        else{
            tconfig = mapTriggerConfiguration.get(name);
        }
        return tconfig;
    }
}