force-app/main/default/objects/Contact/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>user type</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>x_1st Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsTestUser__c.field-meta.xml
<CustomField>
    <fullName>IsTestUser__c</fullName>
    <defaultValue>false</defaultValue>
    <description>to check If the contact is test user</description>
    <label>IsTestUser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>Defines the user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Look up to Account record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Edition Mappings (Account)</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Look up to Contact record</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Not a Customer Center Contact.</errorMessage>
        <filterItems>
            <field>Contact.IOM_Contact_Identifier__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <description>contact Email</description>
    <formula>Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Email_Sent__c</fullName>
    <description>To store the value of date time when welcome email is sent</description>
    <label>Welcome Email Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/First_Login_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>First_Login_Date_Time__c</fullName>
    <description>To capture first login date time to a particular edition.</description>
    <label>First Login Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/isSecondary__c.field-meta.xml
<CustomField>
    <fullName>isSecondary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag if the contact is assigned to work on selected Edition.</description>
    <label>IS Secondary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/isTestUser__c.field-meta.xml
<CustomField>
    <fullName>isTestUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isTestUser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Primary_Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Contact Edition Mappings (Sharer Contact Edition Mapping)</relationshipLabel>
    <relationshipName>Sharer_Contact_Edition_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <description>Defines status of account contact relationship</description>
    <label>Relationship Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Role of user in selected edition for selected account.</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Center_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Customer_Center_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Center_Status__c</fullName>
    <label>Customer Center Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Code__c.field-meta.xml
<CustomField>
    <fullName>Edition_Code__c</fullName>
    <label>Edition Code</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Director__c.field-meta.xml
<CustomField>
    <fullName>Edition_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Lookup Field store the id of the Edition Director.</description>
    <label>Edition Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Purchase_Data__c/Purchase_Data__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It is the transactional information regarding the booth/product purchased.</description>
    <label>Purchase Data</label>
    <nameField>
        <displayFormat>PD-{000000000}</displayFormat>
        <label>Purchase Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Account Record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Booth_Number__c.field-meta.xml
<CustomField>
    <fullName>Booth_Number__c</fullName>
    <description>Booth number Purchased by the Exhibitor</description>
    <label>Booth Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Booth_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Booth_Product_Type__c</fullName>
    <description>Booth Product type are picklist values displayed from global picklist value set of Booth Product Type.</description>
    <label>Booth/Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Booth_Product_Type1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Contact Record</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact Edition mapping</description>
    <label>Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Edition Record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Hall_Name__c.field-meta.xml
<CustomField>
    <fullName>Hall_Name__c</fullName>
    <description>Hall name / title of exhibition center</description>
    <inlineHelpText>Hall name / title of exhibition center</inlineHelpText>
    <label>Booth Hall</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Parent_Purchase_Data__c.field-meta.xml
<CustomField>
    <fullName>Parent_Purchase_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will have a lookup to Parent Purchase Data</description>
    <label>Parent Purchase Data</label>
    <referenceTo>Purchase_Data__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Purchase_Status__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Status__c</fullName>
    <description>Lists the purchase status like Active, Inactive</description>
    <label>Purchase Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Quantity_Area__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Area__c</fullName>
    <description>Defines the value of quantity/Area for Product/Booth.</description>
    <label>Quantity/Area</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <description>Defines Transaction status like Active, Inactive</description>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <description>Defines user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/IMCC_CreateViewTestDataCTRL.cls
/**
* Created/Modified By :(Arushi [IMCC-5107])
* Created On:          23/03/2023
* @description  :      As an Ops User, I should be able to easily create Test Accounts to validate In Progress events
* Methods:             getEixstingTestData,testDataCreated,cancelInvitation,sendEmailInvite
* Test Class:          IMCC_CreateViewTestDataCTRLTest
**/
public without sharing class IMCC_CreateViewTestDataCTRL {
    
    @auraEnabled
    public static List<Contact_Edition_Mapping__c> getEixstingTestData(string editionId){
        system.debug('editionId'+editionId);
        List<Contact_Edition_Mapping__c> testCEMList = [SELECT Id,Account__c,Edition__c,Edition__r.Edition_Code__c,Edition__r.Customer_Center_Status__c
                                                        , Contact__c,Contact__r.Name,Role__c, Email_Sent__c,First_Login_Date_Time__c,Name
                                                        ,Access_Type__c,isTestUser__c, Contact_Email__c,Relationship_Status__c,(SELECT Id,Booth_Product_Type__c FROM Purchase_Data__r)
                                                        FROM Contact_Edition_Mapping__c WHERE Relationship_Status__c = 'Active' AND isTestUser__c = True
                                                        AND Edition__c=:editionId AND Role__c =:'Team Member' AND Edition__r.Customer_Center_Status__c = 'In Progress' WITH SECURITY_ENFORCED];
        system.debug('testCEMList'+testCEMList);
        return testCEMList;
    }
    
    @AuraEnabled
    public static Map<string,object> testDataCreated(string editionId, string userType, string boothType){
        
        Map<String,Object> result = new Map<String,Object>();
        
        List<Contact> conList = [SELECT Id,Name,AccountId,Access_Type__c,IsTestUser__c FROM Contact WHERE Access_Type__c=: userType AND 
                                 IsTestUser__c = True WITH SECURITY_ENFORCED];
        string contactId = conList[0].Id;
        string contactName = conList[0].Name;
        
        List<Contact_Edition_Mapping__c> testCEMList = [SELECT Id,Account__c,Relationship_Status__c, Primary_Contact_Edition_Mapping__c
                                                        , isSecondary__c, Contact__c,Role__c,isTestUser__c FROM Contact_Edition_Mapping__c WHERE Contact__c=:contactId AND 
                                                        Access_Type__c =:userType AND Edition__c=:editionId AND isTestUser__c = True WITH SECURITY_ENFORCED LIMIT 1];
        string pdId = '';
        try {
            if(!testCEMList.isEmpty()){
                if(testCEMList[0].Relationship_Status__c == 'Inactive' && Schema.sObjectType.Contact_Edition_Mapping__c.isUpdateable()){
                    testCEMList[0].Relationship_Status__c = 'Active';
                    testCEMList[0].Role__c = 'Team Member';
                    testCEMList[0].isTestUser__c = True;
                    update testCEMList[0];
                }
                string cemId = testCEMList[0].Id;
                string cemAccountId = testCEMList[0].Account__c;
                
                List<Purchase_Data__c> pdList = [SELECT Id,Booth_Product_Type__c,User_Type__c,Contact_Edition_Mapping__c 
                                                 ,Contact__c,Account__c,Edition__c FROM Purchase_Data__c WHERE Booth_Product_Type__c=: boothType AND 
                                                 Contact_Edition_Mapping__c=:cemId AND User_Type__c=: userType AND Contact__c=: contactId AND 
                                                 Account__c=:cemAccountId AND Edition__c=:editionId WITH SECURITY_ENFORCED];
                
                if(pdList.isEmpty()){
                    Purchase_Data__c pd = new Purchase_Data__c();
                    pd.Account__c = testCEMList[0].Account__c;
                    pd.Contact__c = contactId;
                    pd.Contact_Edition_Mapping__c = testCEMList[0].Id;
                    pd.Edition__c = editionId;
                    pd.Purchase_Status__c = 'Active';
                    pd.Transaction_Status__c = 'Active';
                    pd.User_Type__c = userType;
                    pd.Booth_Product_Type__c = boothType;
                    pd.Booth_Number__c = 'booth-1';
                    pd.Hall_Name__c = 'Test';
                    pd.Quantity_Area__c = 1;
                    
                    SObjectAccessDecision securityDecision3 = Security.stripInaccessible(AccessType.CREATABLE, new Purchase_Data__c []{pd});
                    Insert securityDecision3.getRecords();
                    result.put('success',contactId);
                }
                else{
                    result.put('error',contactId+ '_'+contactName);                
                }  
            }
            else{
                Contact_Edition_Mapping__c cEM = new Contact_Edition_Mapping__c();
                cEM.Account__c = conList[0].AccountId;
                cEM.Contact__c = contactId;
                cEM.Access_Type__c = userType;
                cEM.Edition__c = editionId;
                cEM.Role__c = 'Team Member';
                cEM.Relationship_Status__c = 'Active';
                cEM.isTestUser__c = True;
                
                
                SObjectAccessDecision securityDecision1 = Security.stripInaccessible(AccessType.CREATABLE, new Contact_Edition_Mapping__c []{cEM});
                Insert securityDecision1.getRecords();
                Id cEMId = securityDecision1.getRecords()[0].Id;
                
                Purchase_Data__c pd = new Purchase_Data__c();
                pd.Account__c = conList[0].AccountId;
                pd.Contact__c = contactId;
                pd.Contact_Edition_Mapping__c = cEMId;
                pd.Edition__c = editionId;
                pd.Purchase_Status__c = 'Active';
                pd.Transaction_Status__c = 'Active';
                pd.User_Type__c = userType;
                pd.Booth_Product_Type__c = boothType;
                pd.Booth_Number__c = 'booth-1';
                pd.Hall_Name__c = 'Test';
                //pd.Unit_of_Measurement__c = 'Feet';
                pd.Quantity_Area__c = 1;
                
                SObjectAccessDecision securityDecision2 = Security.stripInaccessible(AccessType.CREATABLE, new Purchase_Data__c []{pd});
                Insert securityDecision2.getRecords();
                pdId = securityDecision2.getRecords()[0].Id;
                result.put('success',contactId);
            }
            return result;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void cancelInvitation(String cemId){   
        
        List<Contact_Edition_Mapping__c> teamMemberList = [SELECT Id
                                                           FROM Contact_Edition_Mapping__c WHERE Id =:cemId WITH SECURITY_ENFORCED];
        if(!teamMemberList.isEmpty() && Schema.sObjectType.Contact_Edition_Mapping__c.isUpdateable()){
            teamMemberList[0].Relationship_Status__c = 'Inactive';
            update teamMemberList;
        }
    }
    
    @auraEnabled
    public static void sendEmailInvite(string cemId, string emailAddress){
        
        Map<Id,User> mapConUser = new Map<Id,User>();
        List<User> lstUsr = new List<User>();
        String confluenceURL = System.Label.Confluence_Page_URL_For_Test_Data;
        try{
            Contact_Edition_Mapping__c cem = [SELECT Id, Account__c,Account__r.Name, Contact__c,Edition__c,Edition__r.Name, CC_Status__c,Edition__r.Edition_Code__c,Relationship_Status__c, Access_Type__c FROM Contact_Edition_Mapping__c where Id=:cemId WITH SECURITY_ENFORCED];
            
            Id sConId = cem.Contact__c;
            Id sEventId = cem.Edition__c;   
            
            List<Purchase_Data__c> pdList = [SELECT Id,Booth_Product_Type__c,User_Type__c,Contact_Edition_Mapping__c 
                                             ,Contact__c,Account__c,Edition__c FROM Purchase_Data__c WHERE Contact_Edition_Mapping__c=:cemId WITH SECURITY_ENFORCED];
            
            Set<String> boothTypeSet = new Set<String>();
            String bType = '';

            if(!pdList.isEmpty()){
                for(Purchase_Data__c pd : pdList){
                    boothTypeSet.add(pd.Booth_Product_Type__c);
                }
                bType = String.join( (Iterable<String>)boothTypeSet, ',' );
            }
            
            lstUsr = [SELECT Id,Email,username,firstname,ContactId,Contact.account.name,Contact.name,Contact.email,IsActive,IsPortalEnabled FROM User where ContactId=: sConId AND IsPortalEnabled=true AND Profile.Name='IM Customer Community Login User' AND IsActive=true WITH SECURITY_ENFORCED];  
           
            for(User oUser : lstUsr){
                mapConUser.put(oUser.ContactId,oUser);
            }
            
            List<Email_Templates__c> listET = [SELECT Content__c, Subject__c,Template_Code__c,Name FROM Email_Templates__c WHERE Template_Code__c =:'WELEMAILForTestData' WITH SECURITY_ENFORCED];
            
            if(!listET.isEmpty() && mapConUser.size() > 0){
                if(mapConUser.containsKey(sConId)){
                String htmlValue = listET[0].Content__c;
                
                //String companyName = cem.Account__r.Name!=null?cem.Account__r.Name:'';                
                String accessType = cem.Access_Type__c;
                String boothType = bType != ''?bType:'';
                String userName = mapConUser.get(cem.Contact__c).userName;
                userName = userName!=null?userName:'';
                String eventName = cem.Edition__r.Name!=null?cem.Edition__r.Name:'';
                
                List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                
                htmlValue = htmlValue!=null?htmlValue:'';
                htmlValue = htmlValue.replace('{Event Name}',eventName);                    
                htmlValue = htmlValue.replace('{Access Type}',accessType);     
                htmlValue = htmlValue.replace('{Booth Type}',boothType);               
                htmlValue = htmlValue.replace('{Username}',userName);
                htmlValue = htmlValue.replace('{here}',confluenceURL);
                String emailSubject = listET[0].Subject__c;
                emailSubject = emailSubject.replace('{Event Name}', eventName);
                //emailSubject = emailSubject.replace('{COMPANY NAME}', companyName);
                
                List<string> toAddress = new List<string>();
                toAddress.add(emailAddress);
                
                mail.setToAddresses(toAddress);
                mail.setSubject(emailSubject);
                mail.setHtmlBody(htmlValue);
                mail.setSaveAsActivity(false);
                //mail.setTargetObjectId(mapConUser.get(cem.Contact__c).Id);
                
                system.debug('mail'+ mail);
                //Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage> {mail};
                
                mails.add(mail);
                
                
                
                Messaging.sendEmail(mails,true);
            }
            else{
                String errorMsg = (!mapConUser.containsKey(cem.Contact__c)?System.Label.IMCC_Welcome_Email_Error_Msg3:System.Label.IMCC_Welcome_Email_Error_Msg4); 
            }
            }
            
        }
        catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }  
    }       
}