force-app/main/default/objects/Contact/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>x_1st Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Edition_Director__c.field-meta.xml
<CustomField>
    <fullName>Edition_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Lookup Field store the id of the Edition Director.</description>
    <label>Edition Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>This field stores the Start date of Edition.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/IMCC_PendoAgentController.cls
/**
* Created      : Girikon(Garima)
* Created On   : 31/03/2023
* @description : This class fetch the login user details and its account details to intialize the pendo.
* Methods      : getMetadata
* Test Class   : IMCC_PendoAgentController_Test (91%)
**/
public without sharing class IMCC_PendoAgentController {
    
    /**
    * @description : to fetch the login user details and CEM Details.
    * @param editionCode edition code
    * @param accountId selected account id
    * @return : Map<String, Object>
    **/
    @AuraEnabled
    public static Map<String, Object> getMetadata(String editionCode, String accountId){
        try {
            User u = [SELECT Id, Username, Email, Name, Contact.Account.Name,Contact.AccountId FROM User  WHERE Id = :UserInfo.getUserId()];
            List<Contact_Edition_Mapping__c> listCEM = new List<Contact_Edition_Mapping__c>();
            Integer editionYear = 0;
            if(String.isNotBlank(editionCode) && String.isNotBlank(accountId)){
                Map<String,Object> mapCEMDetails = IMCC_UtilityMethods.getContactEditionMappings(editionCode, accountId);
                listCEM = (List<Contact_Edition_Mapping__c>)mapCEMDetails.get('cemList');
                if(!listCEM.isEmpty()){
                    if(listCEM[0].Edition__r.Start_Date__c !=null){
                        editionYear = listCEM[0].Edition__r.Start_Date__c.year();
                    }
                }
            }
            return new Map<String, Object> {
                'listCEM' => listCEM,
                'editionYear' => editionYear,
                'visitor' => new Map<String, String> {
                    'username' => u.Username,
                	'email' => u.Email,
                    'name' => u.Name,
                    'id' => u.Id
                 },
                 'account' => new Map<String, String> {
                 	'name' => u.Contact.Account.Name,
                    'id' => u.Contact.AccountId
                 }
            };
        } 
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}