force-app/main/default/objects/Contact/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>x_1st Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Look up to Account record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Edition Mappings (Account)</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Look up to Contact record</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Not a Customer Center Contact.</errorMessage>
        <filterItems>
            <field>Contact.IOM_Contact_Identifier__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Unlimited_Badges__c.field-meta.xml
<CustomField>
    <fullName>Unlimited_Badges__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked unlimited badges will be allocated for booth/product.</description>
    <label>Unlimited Badges</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Edition_Director__c.field-meta.xml
<CustomField>
    <fullName>Edition_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Lookup Field store the id of the Edition Director.</description>
    <label>Edition Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Edition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Status__c.field-meta.xml
<CustomField>
    <fullName>Edition_Status__c</fullName>
    <description>This picklist stores the status of Edition.</description>
    <label>Edition Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Tentative</fullName>
            </value>
            <value>
                <fullName>Cancelled by Finance</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Pending Setup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/Purchase_Data__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It is the transactional information regarding the booth/product purchased.</description>
    <label>Purchase Data</label>
    <nameField>
        <displayFormat>PD-{000000000}</displayFormat>
        <label>Purchase Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Account Record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Badge_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Badge_Allocated__c</fullName>
    <defaultValue>0</defaultValue>
    <description>badge allocated for the exhibitor</description>
    <label>Badge Allocated</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Booth_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Booth_Product_Type__c</fullName>
    <description>Booth Product type are picklist values displayed from global picklist value set of Booth Product Type.</description>
    <label>Booth/Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Booth_Product_Type1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Contact Record</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact Edition mapping</description>
    <label>Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Edition Record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Purchase_Status__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Status__c</fullName>
    <description>Lists the purchase status like Active, Inactive</description>
    <label>Purchase Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Quantity_Area__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Area__c</fullName>
    <description>Defines the value of quantity/Area for Product/Booth.</description>
    <label>Quantity/Area</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <description>Defines Transaction status like Active, Inactive</description>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <description>Defines user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Type__c/User_Type__c.object-meta.xml
<CustomObject>
    <label>User Type</label>
    <nameField>
        <label>User Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IMCC_ContactEditionMappingTriggerHandler.cls
/**  
* Created By         : Girikon(Keertiraj)
* Created On         : 06/10/2021
* Modified By        : Girikon(Garima)
* Modified Date      : 16/08/2022 - (IMCC-4188)
* @description       : This class is used to update Contact's Account if Account is blank and also create community user if not already exists                   
* Test Class         : IMCC_ContactEdMapTriggerHandler_Test(100%)
*/

public without sharing class IMCC_ContactEditionMappingTriggerHandler {
    /**
    * @description After Insert Handler for Contact Edition Mapping to update Contact's Account if Account is blank and create community user if not already exists
    * @param lstConEvnMap
    */
    public static void handleAfterInsert(List<Contact_Edition_Mapping__c> lstConEvnMap){
        List<Contact> conList = new List<Contact>();
        Set<Id> contactId = new Set<Id>();
        for(Contact_Edition_Mapping__c cem : lstConEvnMap){
            contactId.add(cem.Contact__c);
        }
        Map<Id,Contact> conMap = New Map<Id,Contact>([Select id,AccountId from Contact where Id IN: contactId WITH SECURITY_ENFORCED]);
        for(Contact_Edition_Mapping__c cem : lstConEvnMap){
            if((String.isBlank(conMap.get(cem.Contact__c).AccountId))){
                Contact con = new Contact();
                con.Id = cem.Contact__c;
                con.AccountId = cem.Account__c;
                conList.add(con);
            }
        }
        if(Schema.sObjectType.Contact.isUpdateable()){
            update conList;
        }
        
        IMCC_EditionWelcomeEmail.processWelcomeEmail(lstConEvnMap, false);
    }
    
    /**
    * @description set/unset Unlimited Badges On Purchase datas
    * @param newMap
    * @param oldMap
    */
    public static void updatePurchaseData(Map<Id, Contact_Edition_Mapping__c> newMap, Map<Id, Contact_Edition_Mapping__c> oldMap){
        Set<Id> cemIds = new Set<Id>();
        for(Contact_Edition_Mapping__c cem : newMap.Values()){
            if((oldMap==null && cem.Unlimited_Badges__c) || (oldMap!=null && cem.Unlimited_Badges__c != oldMap.get(cem.Id).Unlimited_Badges__c)){
                cemIds.add(cem.Id);
            }
        }
        List<Purchase_Data__c> listPData = new List<Purchase_Data__c>();
        if(Schema.sObjectType.Purchase_Data__c.isAccessible() && !cemIds.isEmpty()){
            listPData = new List<Purchase_Data__c>([SELECT Id,Booth_Product_Type__c,Badge_Allocated__c,Contact_Edition_Mapping__c,Purchase_Status__c,Quantity_Area__c,Transaction_Status__c,User_Type__c,Edition__c FROM Purchase_Data__c WHERE Purchase_Status__c = 'Active' AND Transaction_Status__c ='Active' AND Contact_Edition_Mapping__c IN:cemIds AND Edition__r.Edition_Status__c = 'Confirmed']);
            IMCC_PurchaseDataTriggerHandler.recalculateBadge(listPData,false);
        }
    }
}