force-app/main/default/objects/Badge_Setting__c/Badge_Setting__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will define the badge allocations available for a particular event. It will have different badge allocations.</description>
    <label>Badge Setting</label>
    <nameField>
        <label>Badge Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badge Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/Contact_Edition_Mapping__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will contain the account contact mapping along with edition</description>
    <label>Contact Edition Mapping</label>
    <nameField>
        <displayFormat>CEM-{0000000}</displayFormat>
        <label>Contact Edition Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Edition Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>Defines the user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to Edition record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Contact  Edition Mappings</relationshipLabel>
    <relationshipName>Contact_Event_Edition_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Edition_Mapping__c/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <description>Defines status of account contact relationship</description>
    <label>Relationship Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/Edition__c.object-meta.xml
<CustomObject>
    <description>It defines the Event Edition Information. Also contains information of which badge setting, form setting, event setting will be used for the event.</description>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Edition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Edition__c/fields/Additional_Badge_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Additional_Badge_Allocated__c</fullName>
    <label>Additional Badge Allocated</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Badge_Setting__c.field-meta.xml
<CustomField>
    <fullName>Badge_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Badge Setting</label>
    <referenceTo>Badge_Setting__c</referenceTo>
    <relationshipLabel>Edition</relationshipLabel>
    <relationshipName>Edition_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Customer_Center_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Center_Status__c</fullName>
    <label>Customer Center Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Edition__c/fields/Edition_Status__c.field-meta.xml
<CustomField>
    <fullName>Edition_Status__c</fullName>
    <description>This picklist stores the status of Edition.</description>
    <label>Edition Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Tentative</fullName>
            </value>
            <value>
                <fullName>Cancelled by Finance</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Pending Setup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/Purchase_Data__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It is the transactional information regarding the booth/product purchased.</description>
    <label>Purchase Data</label>
    <nameField>
        <displayFormat>PD-{000000000}</displayFormat>
        <label>Purchase Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Data__c/fields/Addition_Badge_Count__c.field-meta.xml
<CustomField>
    <fullName>Addition_Badge_Count__c</fullName>
    <description>adding new badges by the exhibitor</description>
    <label>Addition Badge Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Badge_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Badge_Allocated__c</fullName>
    <defaultValue>0</defaultValue>
    <description>badge allocated for the exhibitor</description>
    <label>Badge Allocated</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Booth_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Booth_Product_Type__c</fullName>
    <description>Booth Product type are picklist values displayed from global picklist value set of Booth Product Type.</description>
    <label>Booth/Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Booth_Product_Type1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Contact_Edition_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Contact_Edition_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact Edition mapping</description>
    <label>Contact Edition Mapping</label>
    <referenceTo>Contact_Edition_Mapping__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Edition Record</description>
    <label>Edition</label>
    <referenceTo>Edition__c</referenceTo>
    <relationshipLabel>Purchase Data</relationshipLabel>
    <relationshipName>Purchase_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Purchase_Status__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Status__c</fullName>
    <description>Lists the purchase status like Active, Inactive</description>
    <label>Purchase Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Quantity_Area__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Area__c</fullName>
    <description>Defines the value of quantity/Area for Product/Booth.</description>
    <label>Quantity/Area</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <description>Defines Transaction status like Active, Inactive</description>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Data__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <description>Defines user type like Exhibitor, Agent, Co-Exhibitor, Contractor, Online</description>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Type__c/User_Type__c.object-meta.xml
<CustomObject>
    <label>User Type</label>
    <nameField>
        <label>User Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IMCC_AdditionBAdgesOnEvent.cls
/**
* Created/Modified By: Girikon(Arushi[IMCC-59])
* Created On    :      23/12/2021
* @description  :      This class is used to allocate the additional badges to the given Edition and to the related purchase data records 
* Methods:             getData
* Apex Class:          IMCC_AdditionBAdgesOnEvent 
* Apex Test Class:     IMCC_AdditionBAdgesOnEvent_Test(85%)
**/

public  without sharing class IMCC_AdditionBAdgesOnEvent {
   @auraEnabled
    public static void getEditionData(Id editionId, Integer additionBadges){
        
        Set<Id> contactEditionMappingSet = new Set<Id>();
        Set<Id> EditionSet = new Set<Id>();
        List<Edition__c> updateEditionList = new List<Edition__c>();
        List<Purchase_Data__c> purchaseDataToUpdateList = new List<Purchase_Data__c>();
        
        try{
            if(editionId != null && (Schema.sObjectType.Edition__c.isAccessible()))
            {
                for(Edition__c editionData : [SELECT Id, Edition_Status__c,Badge_Setting__c, Additional_Badge_Allocated__c FROM Edition__c WHERE Edition_Status__c = 'Confirmed'AND 
                                                         Customer_Center_Status__c='Active' AND Id =: editionId])
                {
                    if(additionBadges != null){
                        editionData.Additional_Badge_Allocated__c = additionBadges;
                        updateEditionList.add(editionData);
                    }
                }
            }
        
            if(!updateEditionList.isEmpty() && (Schema.sObjectType.Contact_Edition_Mapping__c.isAccessible()))
            {
                for(Contact_Edition_Mapping__c cemData : [SELECT Id,Edition__c,Relationship_Status__c,Access_Type__c FROM Contact_Edition_Mapping__c WHERE Relationship_Status__c = 'Active'
                                                                    AND Edition__c =: editionId])
                {
                    contactEditionMappingSet.add(cemData.Id);
                }
            }
            
            if(contactEditionMappingSet.size() > 0 && (Schema.sObjectType.Purchase_Data__c.isAccessible()))
            {
                for(Purchase_Data__c pHData : [SELECT Id,Booth_Product_Type__c,Badge_Allocated__c,Contact_Edition_Mapping__c,Purchase_Status__c,Quantity_Area__c,Transaction_Status__c,User_Type__c,
                                               Addition_Badge_Count__c FROM Purchase_Data__c WHERE Purchase_Status__c = 'Active' AND Transaction_Status__c ='Active' AND Contact_Edition_Mapping__c IN : contactEditionMappingSet])
                {
                    if(pHData.Addition_Badge_Count__c != null){
                        pHData.Addition_Badge_Count__c += additionBadges;
                        purchaseDataToUpdateList.add(pHData);
                    }
                    else{
                        pHData.Addition_Badge_Count__c = additionBadges;
                        purchaseDataToUpdateList.add(pHData);
                    }
                }
            }
            if(!updateEditionList.isEmpty()) update updateEditionList;
            if(!purchaseDataToUpdateList.isEmpty()) update purchaseDataToUpdateList;
        }
        catch(exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }
}