force-app/main/default/objects/Event_Setting__c/Event_Setting__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child of Edition. This will set the tab visibility on the home page of a particular event.</description>
    <label>Event Setting</label>
    <nameField>
        <label>Event Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Tabs__c/Event_Tabs__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Event Setting. Defines the different tabs and tab properties for a particular event.</description>
    <label>Event Tab</label>
    <nameField>
        <displayFormat>ET-{0000000}</displayFormat>
        <label>Event Tabs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Tabs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Tabs__c/fields/Event_Setting__c.field-meta.xml
<CustomField>
    <fullName>Event_Setting__c</fullName>
    <description>Event setting for which this tabs belongs to.</description>
    <inlineHelpText>Event Setting, this Tab Belongs to</inlineHelpText>
    <label>Event Setting</label>
    <referenceTo>Event_Setting__c</referenceTo>
    <relationshipLabel>Event Tabs</relationshipLabel>
    <relationshipName>Event_Tabs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tab_User_Type__c/Tab_User_Type__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - It will give info on tab will be visible to which user type.</description>
    <label>Tab User Type</label>
    <nameField>
        <displayFormat>UT-{00000}</displayFormat>
        <label>Tab User Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tab User Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tab_User_Type__c/fields/Event_Tab__c.field-meta.xml
<CustomField>
    <fullName>Event_Tab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Event Tab</description>
    <label>Event Tab</label>
    <referenceTo>Event_Tabs__c</referenceTo>
    <relationshipLabel>Tab User Types</relationshipLabel>
    <relationshipName>Tab_User_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IMCC_AssignTabs_Test.cls
/*
Created By    : Aishwarya[IMCC-992]
Class         : IMCC_AssignTabs
Created/LastModified Date   : 
*/

@isTest
private class IMCC_AssignTabs_Test{
    
    @isTest
    private static void tabDataInsert()
    {
        List<Event_Setting__c> eveSettingObj = IMCC_TestUtilities.createEventSetting(250);
        Id eveSettingObjId = eveSettingObj[0].Id;
        
        System.assertEquals(eveSettingObjId,eveSettingObj[0].Id, 'both values must be equal');
        List<Event_Tabs__c> evntTabsLst = IMCC_TestUtilities.createEventTabs(eveSettingObjId,5,10,null,'Standard','Forms',null);
        System.assertEquals(evntTabsLst.Size(),5, 'evntTabsLst size should be 5');
        
        List<String> listUserTypes = new List<String>();
        String recordId = evntTabsLst[0].id;
        String fieldName = 'Event_Tab__c';
        List<Tab_User_Type__c> tabUserLst;
        
        tabUserLst = IMCC_TestUtilities.createTabUserType(evntTabsLst[0].id,1,'Exhibitor');
        tabUserLst = IMCC_TestUtilities.createTabUserType(evntTabsLst[0].id,1,'Agent');
        tabUserLst = IMCC_TestUtilities.createTabUserType(evntTabsLst[0].id,1,'Online');
        listUserTypes.add('Exhibitor');
        listUserTypes.add('Online');
        listUserTypes.add('Contractor');
        Test.startTest();
        IMCC_AssignTabs.assignTabToUsers(listUserTypes, recordId, fieldName);
        IMCC_AssignTabs.assignTabToUsers(listUserTypes, recordId, 'Test');
        Test.stopTest();
    }
    
    @isTest
    private static void tabProductTypeInsert()
    {
        List<Event_Setting__c> eveSettingObj = IMCC_TestUtilities.createEventSetting(250);
        Id eveSettingObjId = eveSettingObj[0].Id;
        //Test.startTest();
        System.assertEquals(eveSettingObjId,eveSettingObj[0].Id, 'both values must be equal');
        List<Event_Tabs__c> evntTabsLst = IMCC_TestUtilities.createEventTabs(eveSettingObjId,5,10,null,'Standard','Forms',null);
        System.assertEquals(evntTabsLst.Size(),5, 'evntTabsLst size should be 5');
        //Test.stopTest();
    }
}