force-app/main/default/objects/Event_Setting__c/Event_Setting__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child of Edition. This will set the tab visibility on the home page of a particular event.</description>
    <label>Event Setting</label>
    <nameField>
        <label>Event Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Tabs__c/Event_Tabs__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Event Setting. Defines the different tabs and tab properties for a particular event.</description>
    <label>Event Tab</label>
    <nameField>
        <displayFormat>ET-{0000000}</displayFormat>
        <label>Event Tabs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Tabs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Tabs__c/fields/Event_Setting__c.field-meta.xml
<CustomField>
    <fullName>Event_Setting__c</fullName>
    <description>Event setting for which this tabs belongs to.</description>
    <inlineHelpText>Event Setting, this Tab Belongs to</inlineHelpText>
    <label>Event Setting</label>
    <referenceTo>Event_Setting__c</referenceTo>
    <relationshipLabel>Event Tabs</relationshipLabel>
    <relationshipName>Event_Tabs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Tabs__c/fields/ExtTabId__c.field-meta.xml
<CustomField>
    <fullName>ExtTabId__c</fullName>
    <label>External Tab Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Tabs__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Used to sort the Event tabs</description>
    <inlineHelpText>Sequence of the Tab in Customer Center</inlineHelpText>
    <label>Sequence</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Tabs__c/fields/Tab_Title__c.field-meta.xml
<CustomField>
    <fullName>Tab_Title__c</fullName>
    <description>Tab title defines Home, Badge, Forms, Manual</description>
    <label>Tab Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Trig_EventTabHandler_Test.cls
/**
* Modified By: Girikon(Aishwarya)
* Created On:          22/9/2021
* @description  :      This class covers the code coverage of the class Trig_EventTabHandler and Trigger trig_EventTab
* Methods:             Trig_EventTabHandler_Test
* Apex Class:          Trig_EventTabHandler(90%) 
**/

@isTest
public class Trig_EventTabHandler_Test{
    @isTest static void testdupSeqBeforeInsertHandler()
    {
        List<Event_Tabs__c> objEvtTabList = new List<Event_Tabs__c>();
        List<Event_Setting__c> eveSettingObj = IMCC_TestUtilities.createEventSetting(5);
        Test.StartTest();
            List<Event_Tabs__c> eventTabsObj = IMCC_TestUtilities.createEventTabs(eveSettingObj[0].Id, 10,10,null,null,null,null);
            System.assertEquals(eventTabsObj[0].Sequence__c, 10, 'Sequence should equal to 10');
        	Event_Tabs__c evt=new Event_Tabs__c(Sequence__c=30,ExtTabId__c='TEST19',Tab_Title__c='Test',Event_Setting__c=eveSettingObj[0].Id);
        	insert evt;
            
            /******  Testing addError method of Trigger  ******/
            
            try {
                eventTabsObj[0].Sequence__c = 20;
                eventTabsObj[0].ExtTabId__c='TEST20';
                update eventTabsObj; 
                System.assertNotEquals(eventTabsObj[0].Sequence__c, 10, 'Sequence should equal to 10');
                System.assertEquals(eventTabsObj[2].Sequence__c, 12, 'Sequence should be equal to 12');
            }
            catch(Exception e) {
                System.assert(e.getMessage().contains('You cannot put the same sequence number present in other event tab. Please choose a different sequence number.'), 'Validation Success');
           
            }
        Test.StopTest();
    }
}