force-app/main/default/objects/Event_Setting__c/Event_Setting__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child of Edition. This will set the tab visibility on the home page of a particular event.</description>
    <label>Event Setting</label>
    <nameField>
        <label>Event Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Tabs__c/Event_Tabs__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Child object of Event Setting. Defines the different tabs and tab properties for a particular event.</description>
    <label>Event Tab</label>
    <nameField>
        <displayFormat>ET-{0000000}</displayFormat>
        <label>Event Tabs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Tabs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Tabs__c/fields/Event_Setting__c.field-meta.xml
<CustomField>
    <fullName>Event_Setting__c</fullName>
    <description>Event setting for which this tabs belongs to.</description>
    <inlineHelpText>Event Setting, this Tab Belongs to</inlineHelpText>
    <label>Event Setting</label>
    <referenceTo>Event_Setting__c</referenceTo>
    <relationshipLabel>Event Tabs</relationshipLabel>
    <relationshipName>Event_Tabs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tab_Context__c/Tab_Context__c.object-meta.xml
<CustomObject>
    <description>IM Customer Center - Records to define the Context to be Shown on the Tab, based on the Booth/Product Type</description>
    <label>Tab Context</label>
    <nameField>
        <displayFormat>TC-{0000000}</displayFormat>
        <label>Tab Context Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tab Context</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/IMCC_MarkAsPublishHandler_Test.cls
/**
* Created/Modified By: Girikon(Aishwarya)
* Created On:          07/9/2021
* @description  :      This class covers the code coverage of the class IMCC_MarkAsPublishHandler and Trigger - IMCC_trgUpdateMarkAsPublish
* Apex Class:          IMCC_MarkAsPublishHandler(88%) 
**/

@isTest
private class IMCC_MarkAsPublishHandler_Test{

    public static testMethod void headerDataInsert()
    {
        List<Event_Setting__c> eveSettingObj = IMCC_TestUtilities.createEventSetting(250);
        Id eveSettingObjId = eveSettingObj[0].Id;
        
        Test.startTest();
            
            List<Event_Tabs__c> evntTabsLst = IMCC_TestUtilities.createEventTabs(eveSettingObjId,5,10,'3 Column','Custom',null,null);
            System.assertEquals(evntTabsLst.Size(),5, 'evntTabsLst size should be 5');
            
            List<Tab_Context__c> listTabContext = IMCC_TestUtilities.createTabContext2(evntTabsLst[0].Id, 200);
            
            List<Tab_Context__c> listTabContext2 = IMCC_TestUtilities.createTabContext3(evntTabsLst[0].Id, 200);
        Test.stopTest();
    }
}